"""
This type stub file was generated by pyright.
"""

from typing import List, Tuple
from modin.core.io.text.csv_dispatcher import CSVDispatcher

"""Module houses `ExperimentalCSVGlobDispatcher` class, that is used for reading multiple `.csv` files simultaneously."""
class ExperimentalCSVGlobDispatcher(CSVDispatcher):
    """Class contains utils for reading multiple `.csv` files simultaneously."""
    @classmethod
    def file_exists(cls, file_path: str, storage_options=...) -> bool:
        """
        Check if the `file_path` is valid.

        Parameters
        ----------
        file_path : str
            String representing a path.
        storage_options : dict, optional
            Keyword from `read_*` functions.

        Returns
        -------
        bool
            True if the path is valid.
        """
        ...
    
    @classmethod
    def get_path(cls, file_path: str, storage_options=...) -> list:
        """
        Return the path of the file(s).

        Parameters
        ----------
        file_path : str
            String representing a path.
        storage_options : dict, optional
            Keyword from `read_*` functions.

        Returns
        -------
        list
            List of strings of absolute file paths.
        """
        ...
    
    @classmethod
    def partitioned_file(cls, files, fnames: List[str], num_partitions: int = ..., nrows: int = ..., skiprows: int = ..., skip_header: int = ..., quotechar: bytes = ..., is_quoting: bool = ...) -> List[List[Tuple[str, int, int]]]:
        """
        Compute chunk sizes in bytes for every partition.

        Parameters
        ----------
        files : file or list of files
            File(s) to be partitioned.
        fnames : str or list of str
            File name(s) to be partitioned.
        num_partitions : int, optional
            For what number of partitions split a file.
            If not specified grabs the value from `modin.config.NPartitions.get()`.
        nrows : int, optional
            Number of rows of file to read.
        skiprows : int, optional
            Specifies rows to skip.
        skip_header : int, optional
            Specifies header rows to skip.
        quotechar : bytes, default: b'"'
            Indicate quote in a file.
        is_quoting : bool, default: True
            Whether or not to consider quotes.

        Returns
        -------
        list
            List, where each element of the list is a list of tuples. The inner lists
            of tuples contains the data file name of the chunk, chunk start offset, and
            chunk end offsets for its corresponding file.

        Notes
        -----
        The logic gets really complicated if we try to use the `TextFileDispatcher.partitioned_file`.
        """
        ...
    


