"""
This type stub file was generated by pyright.
"""

from modin.core.execution.unidist.common import UnidistWrapper
from modin.core.execution.unidist.generic.partitioning import GenericUnidistDataframePartitionManager
from .partition import PandasOnUnidistDataframePartition
from .virtual_partition import PandasOnUnidistDataframeColumnPartition, PandasOnUnidistDataframeRowPartition

"""Module houses class that implements ``GenericUnidistDataframePartitionManager`` using Unidist."""
class PandasOnUnidistDataframePartitionManager(GenericUnidistDataframePartitionManager):
    """The class implements the interface in `PandasDataframePartitionManager`."""
    _partition_class = PandasOnUnidistDataframePartition
    _column_partitions_class = PandasOnUnidistDataframeColumnPartition
    _row_partition_class = PandasOnUnidistDataframeRowPartition
    _execution_wrapper = UnidistWrapper
    @classmethod
    def wait_partitions(cls, partitions): # -> None:
        """
        Wait on the objects wrapped by `partitions` in parallel, without materializing them.

        This method will block until all computations in the list have completed.

        Parameters
        ----------
        partitions : np.ndarray
            NumPy array with ``PandasDataframePartition``-s.
        """
        ...
    


