"""
This type stub file was generated by pyright.
"""

from typing import Optional, TYPE_CHECKING, Union
from pandas._typing import Axes
from modin.pandas.dataframe import DataFrame, Series
from modin.core.execution.dask.implementations.pandas_on_dask.partitioning import PandasOnDaskDataframeColumnPartition, PandasOnDaskDataframePartition, PandasOnDaskDataframeRowPartition
from modin.core.execution.ray.implementations.pandas_on_ray.partitioning import PandasOnRayDataframeColumnPartition, PandasOnRayDataframePartition, PandasOnRayDataframeRowPartition
from modin.core.execution.unidist.implementations.pandas_on_unidist.partitioning import PandasOnUnidistDataframeColumnPartition, PandasOnUnidistDataframePartition, PandasOnUnidistDataframeRowPartition

"""Module houses API to operate on Modin DataFrame partitions that are pandas DataFrame(s)."""
if TYPE_CHECKING:
    PartitionUnionType = Union[PandasOnRayDataframePartition, PandasOnDaskDataframePartition, PandasOnUnidistDataframePartition, PandasOnRayDataframeColumnPartition, PandasOnRayDataframeRowPartition, PandasOnDaskDataframeColumnPartition, PandasOnDaskDataframeRowPartition, PandasOnUnidistDataframeColumnPartition, PandasOnUnidistDataframeRowPartition,]
else:
    ...
def unwrap_partitions(api_layer_object: Union[DataFrame, Series], axis: Optional[int] = ..., get_ip: bool = ...) -> list:
    """
    Unwrap partitions of the ``api_layer_object``.

    Parameters
    ----------
    api_layer_object : DataFrame or Series
        The API layer object.
    axis : {None, 0, 1}, default: None
        The axis to unwrap partitions for (0 - row partitions, 1 - column partitions).
        If ``axis is None``, the partitions are unwrapped as they are currently stored.
    get_ip : bool, default: False
        Whether to get node ip address to each partition or not.

    Returns
    -------
    list
        A list of Ray.ObjectRef/Dask.Future to partitions of the ``api_layer_object``
        if Ray/Dask is used as an engine.

    Notes
    -----
    If ``get_ip=True``, a list of tuples of Ray.ObjectRef/Dask.Future to node ip addresses and
    partitions of the ``api_layer_object``, respectively, is returned if Ray/Dask is used as an engine
    (i.e. ``[(Ray.ObjectRef/Dask.Future, Ray.ObjectRef/Dask.Future), ...]``).
    """
    ...

def from_partitions(partitions: list, axis: Optional[int], index: Optional[Axes] = ..., columns: Optional[Axes] = ..., row_lengths: Optional[list] = ..., column_widths: Optional[list] = ...) -> DataFrame:
    """
    Create DataFrame from remote partitions.

    Parameters
    ----------
    partitions : list
        A list of Ray.ObjectRef/Dask.Future to partitions depending on the engine used.
        Or a list of tuples of Ray.ObjectRef/Dask.Future to node ip addresses and partitions
        depending on the engine used (i.e. ``[(Ray.ObjectRef/Dask.Future, Ray.ObjectRef/Dask.Future), ...]``).
    axis : {None, 0 or 1}
        The ``axis`` parameter is used to identify what are the partitions passed.
        You have to set:

        * ``axis=0`` if you want to create DataFrame from row partitions
        * ``axis=1`` if you want to create DataFrame from column partitions
        * ``axis=None`` if you want to create DataFrame from 2D list of partitions
    index : sequence, optional
        The index for the DataFrame. Is computed if not provided.
    columns : sequence, optional
        The columns for the DataFrame. Is computed if not provided.
    row_lengths : list, optional
        The length of each partition in the rows. The "height" of
        each of the block partitions. Is computed if not provided.
    column_widths : list, optional
        The width of each partition in the columns. The "width" of
        each of the block partitions. Is computed if not provided.

    Returns
    -------
    modin.pandas.DataFrame
        DataFrame instance created from remote partitions.

    Notes
    -----
    Pass `index`, `columns`, `row_lengths` and `column_widths` to avoid triggering
    extra computations of the metadata when creating a DataFrame.
    """
    ...

