"""
This type stub file was generated by pyright.
"""

import pandas
from typing import Any
from pandas.util._decorators import doc
from modin.core.storage_formats import BaseQueryCompiler
from modin.utils import _inherit_docstrings

"""
Module houses `BaseIO` class.

`BaseIO` is base class for IO classes, that stores IO functions.
"""
_doc_default_io_method = ...
_doc_returns_qc = ...
_doc_returns_qc_or_parser = ...
class BaseIO:
    """Class for basic utils and default implementation of IO functions."""
    query_compiler_cls: BaseQueryCompiler = ...
    frame_cls = ...
    _should_warn_on_default_to_pandas: bool = ...
    @classmethod
    def from_non_pandas(cls, *args, **kwargs): # -> None:
        """
        Create a Modin `query_compiler` from a non-pandas `object`.

        Parameters
        ----------
        *args : iterable
            Positional arguments to be passed into `func`.
        **kwargs : dict
            Keyword arguments to be passed into `func`.
        """
        ...
    
    @classmethod
    def from_pandas(cls, df) -> BaseQueryCompiler:
        """
        Create a Modin `query_compiler` from a `pandas.DataFrame`.

        Parameters
        ----------
        df : pandas.DataFrame
            The pandas DataFrame to convert from.

        Returns
        -------
        BaseQueryCompiler
            QueryCompiler containing data from the `pandas.DataFrame`.
        """
        ...
    
    @classmethod
    def from_arrow(cls, at): # -> None:
        """
        Create a Modin `query_compiler` from a `pyarrow.Table`.

        Parameters
        ----------
        at : Arrow Table
            The Arrow Table to convert from.

        Returns
        -------
        BaseQueryCompiler
            QueryCompiler containing data from the Arrow Table.
        """
        ...
    
    @classmethod
    def from_interchange_dataframe(cls, df): # -> None:
        """
        Create a Modin QueryCompiler from a DataFrame supporting the DataFrame exchange protocol `__dataframe__()`.

        Parameters
        ----------
        df : DataFrame
            The DataFrame object supporting the DataFrame exchange protocol.

        Returns
        -------
        BaseQueryCompiler
            QueryCompiler containing data from the DataFrame.
        """
        ...
    
    @classmethod
    def from_ray(cls, ray_obj):
        """
        Create a Modin `query_compiler` from a Ray Dataset.

        Parameters
        ----------
        ray_obj : ray.data.Dataset
            The Ray Dataset to convert from.

        Returns
        -------
        BaseQueryCompiler
            QueryCompiler containing data from the Ray Dataset.

        Notes
        -----
        Ray Dataset can only be converted to a Modin Dataframe if Modin uses a Ray engine.
        If another engine is used, the runtime exception will be raised.
        """
        ...
    
    @classmethod
    def from_dask(cls, dask_obj):
        """
        Create a Modin `query_compiler` from a Dask DataFrame.

        Parameters
        ----------
        dask_obj : dask.dataframe.DataFrame
            The Dask DataFrame to convert from.

        Returns
        -------
        BaseQueryCompiler
            QueryCompiler containing data from the Dask DataFrame.

        Notes
        -----
        Dask DataFrame can only be converted to a Modin DataFrame if Modin uses a Dask engine.
        If another engine is used, the runtime exception will be raised.
        """
        ...
    
    @classmethod
    def from_map(cls, func, iterable, *args, **kwargs):
        """
        Create a Modin `query_compiler` from a map function.

        This method will construct a Modin `query_compiler` split by row partitions.
        The number of row partitions matches the number of elements in the iterable object.

        Parameters
        ----------
        func : callable
            Function to map across the iterable object.
        iterable : Iterable
            An iterable object.
        *args : tuple
            Positional arguments to pass in `func`.
        **kwargs : dict
            Keyword arguments to pass in `func`.

        Returns
        -------
        BaseQueryCompiler
            QueryCompiler containing data returned by map function.
        """
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_parquet, apilink="pandas.read_parquet")
    @doc(_doc_default_io_method, summary="Load a parquet object from the file path, returning a query compiler", returns=_doc_returns_qc)
    def read_parquet(cls, **kwargs): # -> BaseQueryCompiler:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_csv, apilink="pandas.read_csv")
    @doc(_doc_default_io_method, summary="Read a comma-separated values (CSV) file into query compiler", returns=_doc_returns_qc_or_parser)
    def read_csv(cls, filepath_or_buffer, **kwargs): # -> BaseQueryCompiler:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_json, apilink="pandas.read_json")
    @doc(_doc_default_io_method, summary="Convert a JSON string to query compiler", returns=_doc_returns_qc)
    def read_json(cls, **kwargs): # -> BaseQueryCompiler:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_gbq, apilink="pandas.read_gbq")
    @doc(_doc_default_io_method, summary="Load data from Google BigQuery into query compiler", returns=_doc_returns_qc)
    def read_gbq(cls, query: str, project_id=..., index_col=..., col_order=..., reauth=..., auth_local_webserver=..., dialect=..., location=..., configuration=..., credentials=..., use_bqstorage_api=..., private_key=..., verbose=..., progress_bar_type=..., max_results=...): # -> BaseQueryCompiler:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_html, apilink="pandas.read_html")
    @doc(_doc_default_io_method, summary="Read HTML tables into query compiler", returns=_doc_returns_qc)
    def read_html(cls, io, *, match=..., flavor=..., header=..., index_col=..., skiprows=..., attrs=..., parse_dates=..., thousands=..., encoding=..., decimal=..., converters=..., na_values=..., keep_default_na=..., displayed_only=..., **kwargs): # -> Generator[BaseQueryCompiler, None, None]:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_clipboard, apilink="pandas.read_clipboard")
    @doc(_doc_default_io_method, summary="Read text from clipboard into query compiler", returns=_doc_returns_qc)
    def read_clipboard(cls, sep=..., **kwargs): # -> BaseQueryCompiler:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_excel, apilink="pandas.read_excel")
    @doc(_doc_default_io_method, summary="Read an Excel file into query compiler", returns="""BaseQueryCompiler or dict :
    QueryCompiler or dict with read data.""")
    def read_excel(cls, **kwargs): # -> dict[Any, Any] | BaseQueryCompiler:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_hdf, apilink="pandas.read_hdf")
    @doc(_doc_default_io_method, summary="Read data from hdf store into query compiler", returns=_doc_returns_qc)
    def read_hdf(cls, path_or_buf, key=..., mode: str = ..., errors: str = ..., where=..., start=..., stop=..., columns=..., iterator=..., chunksize=..., **kwargs): # -> BaseQueryCompiler:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_feather, apilink="pandas.read_feather")
    @doc(_doc_default_io_method, summary="Load a feather-format object from the file path into query compiler", returns=_doc_returns_qc)
    def read_feather(cls, path, **kwargs): # -> BaseQueryCompiler:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_stata, apilink="pandas.read_stata")
    @doc(_doc_default_io_method, summary="Read Stata file into query compiler", returns=_doc_returns_qc)
    def read_stata(cls, filepath_or_buffer, **kwargs): # -> BaseQueryCompiler:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_sas, apilink="pandas.read_sas")
    @doc(_doc_default_io_method, summary="Read SAS files stored as either XPORT or SAS7BDAT format files\ninto query compiler", returns=_doc_returns_qc)
    def read_sas(cls, filepath_or_buffer, *, format=..., index=..., encoding=..., chunksize=..., iterator=..., **kwargs): # -> BaseQueryCompiler:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_pickle, apilink="pandas.read_pickle")
    @doc(_doc_default_io_method, summary="Load pickled pandas object (or any object) from file into query compiler", returns=_doc_returns_qc)
    def read_pickle(cls, filepath_or_buffer, **kwargs): # -> BaseQueryCompiler:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_sql, apilink="pandas.read_sql")
    @doc(_doc_default_io_method, summary="Read SQL query or database table into query compiler", returns=_doc_returns_qc)
    def read_sql(cls, sql, con, index_col=..., coerce_float=..., params=..., parse_dates=..., columns=..., chunksize=..., dtype_backend=..., dtype=...): # -> BaseQueryCompiler | Generator[BaseQueryCompiler, None, None]:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_fwf, apilink="pandas.read_fwf")
    @doc(_doc_default_io_method, summary="Read a table of fixed-width formatted lines into query compiler", returns=_doc_returns_qc_or_parser)
    def read_fwf(cls, filepath_or_buffer, *, colspecs=..., widths=..., infer_nrows=..., dtype_backend=..., iterator=..., chunksize=..., **kwds): # -> BaseQueryCompiler:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_sql_table, apilink="pandas.read_sql_table")
    @doc(_doc_default_io_method, summary="Read SQL database table into query compiler", returns=_doc_returns_qc)
    def read_sql_table(cls, table_name, con, schema=..., index_col=..., coerce_float=..., parse_dates=..., columns=..., chunksize=..., dtype_backend=...): # -> BaseQueryCompiler:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_sql_query, apilink="pandas.read_sql_query")
    @doc(_doc_default_io_method, summary="Read SQL query into query compiler", returns=_doc_returns_qc)
    def read_sql_query(cls, sql, con, **kwargs): # -> BaseQueryCompiler:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.read_spss, apilink="pandas.read_spss")
    @doc(_doc_default_io_method, summary="Load an SPSS file from the file path, returning a query compiler", returns=_doc_returns_qc)
    def read_spss(cls, path, usecols, convert_categoricals, dtype_backend): # -> BaseQueryCompiler:
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.DataFrame.to_sql, apilink="pandas.DataFrame.to_sql")
    def to_sql(cls, qc, name, con, schema=..., if_exists=..., index=..., index_label=..., chunksize=..., dtype=..., method=...): # -> None:
        """
        Write records stored in a DataFrame to a SQL database using pandas.

        For parameters description please refer to pandas API.
        """
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.DataFrame.to_pickle, apilink="pandas.DataFrame.to_pickle")
    def to_pickle(cls, obj: Any, filepath_or_buffer, **kwargs):
        """
        Pickle (serialize) object to file.
        """
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.DataFrame.to_csv, apilink="pandas.DataFrame.to_csv")
    def to_csv(cls, obj, **kwargs):
        """
        Write object to a comma-separated values (CSV) file using pandas.

        For parameters description please refer to pandas API.
        """
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.DataFrame.to_json, apilink="pandas.DataFrame.to_json")
    def to_json(cls, obj, path, **kwargs):
        """
        Convert the object to a JSON string.

        For parameters description please refer to pandas API.
        """
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.Series.to_json, apilink="pandas.Series.to_json")
    def to_json_series(cls, obj, path, **kwargs):
        """
        Convert the object to a JSON string.

        For parameters description please refer to pandas API.
        """
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.DataFrame.to_xml, apilink="pandas.DataFrame.to_xml")
    def to_xml(cls, obj, path_or_buffer, **kwargs):
        """
        Convert the object to a XML string.

        For parameters description please refer to pandas API.
        """
        ...
    
    @classmethod
    @_inherit_docstrings(pandas.DataFrame.to_parquet, apilink="pandas.DataFrame.to_parquet")
    def to_parquet(cls, obj, path, **kwargs):
        """
        Write object to the binary parquet format using pandas.

        For parameters description please refer to pandas API.
        """
        ...
    
    @classmethod
    def to_ray(cls, modin_obj):
        """
        Convert a Modin DataFrame/Series to a Ray Dataset.

        Parameters
        ----------
        modin_obj : modin.pandas.DataFrame, modin.pandas.Series
            The Modin DataFrame/Series to convert.

        Returns
        -------
        ray.data.Dataset
            Converted object with type depending on input.

        Notes
        -----
        Modin DataFrame/Series can only be converted to a Ray Dataset if Modin uses a Ray engine.
        If another engine is used, the runtime exception will be raised.
        """
        ...
    
    @classmethod
    def to_dask(cls, modin_obj):
        """
        Convert a Modin DataFrame to a Dask DataFrame.

        Parameters
        ----------
        modin_obj : modin.pandas.DataFrame, modin.pandas.Series
            The Modin DataFrame/Series to convert.

        Returns
        -------
        dask.dataframe.DataFrame or dask.dataframe.Series
            Converted object with type depending on input.

        Notes
        -----
        Modin DataFrame/Series can only be converted to a Dask DataFrame/Series if Modin uses a Dask engine.
        If another engine is used, the runtime exception will be raised.
        """
        ...
    


