"""
This type stub file was generated by pyright.
"""

import pandas._libs.lib as lib
from typing import Iterator, Literal, Optional, Union
from pandas._typing import CompressionOptions, DtypeArg, DtypeBackend, StorageOptions
from modin.utils import expanduser_path_arg
from . import DataFrame

"""Implement experimental I/O public API."""
def read_sql(sql, con, index_col=..., coerce_float=..., params=..., parse_dates=..., columns=..., chunksize=..., dtype_backend=..., dtype=..., partition_column: Optional[str] = ..., lower_bound: Optional[int] = ..., upper_bound: Optional[int] = ..., max_sessions: Optional[int] = ...) -> Union[DataFrame, Iterator[DataFrame]]:
    """
    General documentation is available in `modin.pandas.read_sql`.

    This experimental feature provides distributed reading from a sql file.
    The function extended with `Spark-like parameters <https://spark.apache.org/docs/2.0.0/api/R/read.jdbc.html>`_
    such as ``partition_column``, ``lower_bound`` and ``upper_bound``. With these
    parameters, the user will be able to specify how to partition the imported data.

    Parameters
    ----------
    sql : str or SQLAlchemy Selectable (select or text object)
        SQL query to be executed or a table name.
    con : SQLAlchemy connectable, str, or sqlite3 connection
        Using SQLAlchemy makes it possible to use any DB supported by that
        library. If a DBAPI2 object, only sqlite3 is supported. The user is responsible
        for engine disposal and connection closure for the SQLAlchemy
        connectable; str connections are closed automatically. See
        `here <https://docs.sqlalchemy.org/en/13/core/connections.html>`_.
    index_col : str or list of str, optional
        Column(s) to set as index(MultiIndex).
    coerce_float : bool, default: True
        Attempts to convert values of non-string, non-numeric objects (like
        decimal.Decimal) to floating point, useful for SQL result sets.
    params : list, tuple or dict, optional
        List of parameters to pass to execute method. The syntax used to pass
        parameters is database driver dependent. Check your database driver
        documentation for which of the five syntax styles, described in PEP 249's
        paramstyle, is supported. Eg. for psycopg2, uses %(name)s so use params=
        {'name' : 'value'}.
    parse_dates : list or dict, optional
        - List of column names to parse as dates.
        - Dict of ``{column_name: format string}`` where format string is
          strftime compatible in case of parsing string times, or is one of
          (D, s, ns, ms, us) in case of parsing integer timestamps.
        - Dict of ``{column_name: arg dict}``, where the arg dict corresponds
          to the keyword arguments of :func:`pandas.to_datetime`
          Especially useful with databases without native Datetime support,
          such as SQLite.
    columns : list, optional
        List of column names to select from SQL table (only used when reading
        a table).
    chunksize : int, optional
        If specified, return an iterator where `chunksize` is the
        number of rows to include in each chunk.
    dtype_backend : {"numpy_nullable", "pyarrow"}, default: NumPy backed DataFrames
        Which dtype_backend to use, e.g. whether a DataFrame should have NumPy arrays,
        nullable dtypes are used for all dtypes that have a nullable implementation when
        "numpy_nullable" is set, PyArrow is used for all dtypes if "pyarrow" is set.
        The dtype_backends are still experimential.
    dtype : Type name or dict of columns, optional
        Data type for data or columns. E.g. np.float64 or {'a': np.float64, 'b': np.int32, 'c': 'Int64'}. The argument is ignored if a table is passed instead of a query.
    partition_column : str, optional
        Column used to share the data between the workers (MUST be a INTEGER column).
    lower_bound : int, optional
        The minimum value to be requested from the partition_column.
    upper_bound : int, optional
        The maximum value to be requested from the partition_column.
    max_sessions : int, optional
        The maximum number of simultaneous connections allowed to use.

    Returns
    -------
    modin.DataFrame or Iterator[modin.DataFrame]
    """
    ...

@expanduser_path_arg("filepath_or_buffer")
def read_custom_text(filepath_or_buffer, columns, custom_parser, compression=..., nrows: Optional[int] = ..., is_quoting=...): # -> DataFrame:
    r"""
    Load custom text data from file.

    Parameters
    ----------
    filepath_or_buffer : str
        File path where the custom text data will be loaded from.
    columns : list or callable(file-like object, \*\*kwargs) -> list
        Column names of list type or callable that create column names from opened file
        and passed `kwargs`.
    custom_parser : callable(file-like object, \*\*kwargs) -> pandas.DataFrame
        Function that takes as input a part of the `filepath_or_buffer` file loaded into
        memory in file-like object form.
    compression : {'infer', 'gzip', 'bz2', 'zip', 'xz', None}, default: 'infer'
        If 'infer' and 'path_or_url' is path-like, then detect compression from
        the following extensions: '.gz', '.bz2', '.zip', or '.xz' (otherwise no
        compression). If 'infer' and 'path_or_url' is not path-like, then use
        None (= no decompression).
    nrows : int, optional
        Amount of rows to read.
    is_quoting : bool, default: True
        Whether or not to consider quotes.

    Returns
    -------
    modin.DataFrame
    """
    ...

read_csv_glob = ...
@expanduser_path_arg("filepath_or_buffer")
def read_pickle_glob(filepath_or_buffer, compression: Optional[str] = ..., storage_options: StorageOptions = ...): # -> DataFrame:
    """
    Load pickled pandas object from files.

    This experimental feature provides parallel reading from multiple pickle files which are
    defined by glob pattern. The files must contain parts of one dataframe, which can be
    obtained, for example, by `DataFrame.modin.to_pickle_glob` function.

    Parameters
    ----------
    filepath_or_buffer : str, path object or file-like object
        File path, URL, or buffer where the pickled object will be loaded from.
        Accept URL. URL is not limited to S3 and GCS.
    compression : {{'infer', 'gzip', 'bz2', 'zip', 'xz', None}}, default: 'infer'
        If 'infer' and 'path_or_url' is path-like, then detect compression from
        the following extensions: '.gz', '.bz2', '.zip', or '.xz' (otherwise no
        compression) If 'infer' and 'path_or_url' is not path-like, then use
        None (= no decompression).
    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc., if using a URL that will be parsed by
        fsspec, e.g., starting "s3://", "gcs://". An error will be raised if providing
        this argument with a non-fsspec URL. See the fsspec and backend storage
        implementation docs for the set of allowed keys and values.

    Returns
    -------
    unpickled : same type as object stored in file

    Notes
    -----
    The number of partitions is equal to the number of input files.
    """
    ...

@expanduser_path_arg("filepath_or_buffer")
def to_pickle_glob(self, filepath_or_buffer, compression: CompressionOptions = ..., protocol: int = ..., storage_options: StorageOptions = ...) -> None:
    """
    Pickle (serialize) object to file.

    This experimental feature provides parallel writing into multiple pickle files which are
    defined by glob pattern, otherwise (without glob pattern) default pandas implementation is used.

    Parameters
    ----------
    filepath_or_buffer : str
        File path where the pickled object will be stored.
    compression : {{'infer', 'gzip', 'bz2', 'zip', 'xz', None}}, default: 'infer'
        A string representing the compression to use in the output file. By
        default, infers from the file extension in specified path.
        Compression mode may be any of the following possible
        values: {{'infer', 'gzip', 'bz2', 'zip', 'xz', None}}. If compression
        mode is 'infer' and path_or_buf is path-like, then detect
        compression mode from the following extensions:
        '.gz', '.bz2', '.zip' or '.xz'. (otherwise no compression).
        If dict given and mode is 'zip' or inferred as 'zip', other entries
        passed as additional compression options.
    protocol : int, default: pickle.HIGHEST_PROTOCOL
        Int which indicates which protocol should be used by the pickler,
        default HIGHEST_PROTOCOL (see `pickle docs <https://docs.python.org/3/library/pickle.html>`_
        paragraph 12.1.2 for details). The possible  values are 0, 1, 2, 3, 4, 5. A negative value
        for the protocol parameter is equivalent to setting its value to HIGHEST_PROTOCOL.
    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc., if using a URL that will be parsed by
        fsspec, e.g., starting "s3://", "gcs://". An error will be raised if providing
        this argument with a non-fsspec URL. See the fsspec and backend storage
        implementation docs for the set of allowed keys and values.
    """
    ...

@expanduser_path_arg("path")
def read_parquet_glob(path, engine: str = ..., columns: list[str] | None = ..., storage_options: StorageOptions = ..., use_nullable_dtypes: bool = ..., dtype_backend=..., filesystem=..., filters=..., **kwargs) -> DataFrame:
    """
    Load a parquet object from the file path, returning a DataFrame.

    This experimental feature provides parallel reading from multiple parquet files which are
    defined by glob pattern. The files must contain parts of one dataframe, which can be
    obtained, for example, by `DataFrame.modin.to_parquet_glob` function.

    Returns
    -------
    DataFrame

    Notes
    -----
    * Only string type supported for `path` argument.
    * The rest of the arguments are the same as for `pandas.read_parquet`.
    """
    ...

@expanduser_path_arg("path")
def to_parquet_glob(self, path, engine=..., compression=..., index=..., partition_cols=..., storage_options: StorageOptions = ..., **kwargs) -> None:
    """
    Write a DataFrame to the binary parquet format.

    This experimental feature provides parallel writing into multiple parquet files which are
    defined by glob pattern, otherwise (without glob pattern) default pandas implementation is used.

    Notes
    -----
    * Only string type supported for `path` argument.
    * The rest of the arguments are the same as for `pandas.to_parquet`.
    """
    ...

@expanduser_path_arg("path_or_buf")
def read_json_glob(path_or_buf, *, orient: str | None = ..., typ: Literal["frame", "series"] = ..., dtype: DtypeArg | None = ..., convert_axes=..., convert_dates: bool | list[str] = ..., keep_default_dates: bool = ..., precise_float: bool = ..., date_unit: str | None = ..., encoding: str | None = ..., encoding_errors: str | None = ..., lines: bool = ..., chunksize: int | None = ..., compression: CompressionOptions = ..., nrows: int | None = ..., storage_options: StorageOptions = ..., dtype_backend: Union[DtypeBackend, lib.NoDefault] = ..., engine=...) -> DataFrame:
    """
    Convert a JSON string to pandas object.

    This experimental feature provides parallel reading from multiple json files which are
    defined by glob pattern. The files must contain parts of one dataframe, which can be
    obtained, for example, by `DataFrame.modin.to_json_glob` function.

    Returns
    -------
    DataFrame

    Notes
    -----
    * Only string type supported for `path_or_buf` argument.
    * The rest of the arguments are the same as for `pandas.read_json`.
    """
    ...

@expanduser_path_arg("path_or_buf")
def to_json_glob(self, path_or_buf=..., orient=..., date_format=..., double_precision=..., force_ascii=..., date_unit=..., default_handler=..., lines=..., compression=..., index=..., indent=..., storage_options: StorageOptions = ..., mode=...) -> None:
    """
    Convert the object to a JSON string.

    Notes
    -----
    * Only string type supported for `path_or_buf` argument.
    * The rest of the arguments are the same as for `pandas.to_json`.
    """
    ...

@expanduser_path_arg("path_or_buffer")
def read_xml_glob(path_or_buffer, *, xpath=..., namespaces=..., elems_only=..., attrs_only=..., names=..., dtype=..., converters=..., parse_dates=..., encoding=..., parser=..., stylesheet=..., iterparse=..., compression=..., storage_options: StorageOptions = ..., dtype_backend=...) -> DataFrame:
    """
    Read XML document into a DataFrame object.

    This experimental feature provides parallel reading from multiple XML files which are
    defined by glob pattern. The files must contain parts of one dataframe, which can be
    obtained, for example, by `DataFrame.modin.to_xml_glob` function.

    Returns
    -------
    DataFrame

    Notes
    -----
    * Only string type supported for `path_or_buffer` argument.
    * The rest of the arguments are the same as for `pandas.read_xml`.
    """
    ...

@expanduser_path_arg("path_or_buffer")
def to_xml_glob(self, path_or_buffer=..., index=..., root_name=..., row_name=..., na_rep=..., attr_cols=..., elem_cols=..., namespaces=..., prefix=..., encoding=..., xml_declaration=..., pretty_print=..., parser=..., stylesheet=..., compression=..., storage_options=...) -> None:
    """
    Render a DataFrame to an XML document.

    Notes
    -----
    * Only string type supported for `path_or_buffer` argument.
    * The rest of the arguments are the same as for `pandas.to_xml`.
    """
    ...

