"""
This type stub file was generated by pyright.
"""

from modin.core.execution.ray.common import RayWrapper
from modin.core.execution.ray.generic.partitioning import GenericRayDataframePartitionManager
from modin.utils import _inherit_docstrings
from .partition import PandasOnRayDataframePartition
from .virtual_partition import PandasOnRayDataframeColumnPartition, PandasOnRayDataframeRowPartition

"""Module houses class that implements ``GenericRayDataframePartitionManager`` using Ray."""
class PandasOnRayDataframePartitionManager(GenericRayDataframePartitionManager):
    """The class implements the interface in `PandasDataframePartitionManager`."""
    _partition_class = PandasOnRayDataframePartition
    _column_partitions_class = PandasOnRayDataframeColumnPartition
    _row_partition_class = PandasOnRayDataframeRowPartition
    _execution_wrapper = RayWrapper
    materialize_futures = ...
    @classmethod
    def wait_partitions(cls, partitions): # -> None:
        """
        Wait on the objects wrapped by `partitions` in parallel, without materializing them.

        This method will block until all computations in the list have completed.

        Parameters
        ----------
        partitions : np.ndarray
            NumPy array with ``PandasDataframePartition``-s.
        """
        ...
    
    @classmethod
    @_inherit_docstrings(GenericRayDataframePartitionManager.split_pandas_df_into_partitions)
    def split_pandas_df_into_partitions(cls, df, row_chunksize, col_chunksize, update_bar): # -> NDArray[Any]:
        ...
    


