"""
This type stub file was generated by pyright.
"""

import pandas
import ray
from typing import Callable, Union
from modin.core.dataframe.pandas.partitioning.partition import PandasDataframePartition
from modin.core.execution.ray.common import MaterializationHook, RayWrapper
from modin.core.execution.ray.common.deferred_execution import DeferredExecution, MetaList
from modin.core.execution.ray.common.utils import ObjectIDType
from modin.logging import disable_logging
from modin.utils import _inherit_docstrings

"""Module houses class that wraps data (block partition) and its metadata."""
class PandasOnRayDataframePartition(PandasDataframePartition):
    """
    The class implements the interface in ``PandasDataframePartition``.

    Parameters
    ----------
    data : ObjectIDType or DeferredExecution
        A reference to ``pandas.DataFrame`` that needs to be wrapped with this class
        or a reference to DeferredExecution that needs to be executed on demand.
    length : ObjectIDType or int, optional
        Length or reference to it of wrapped ``pandas.DataFrame``.
    width : ObjectIDType or int, optional
        Width or reference to it of wrapped ``pandas.DataFrame``.
    ip : ObjectIDType or str, optional
        Node IP address or reference to it that holds wrapped ``pandas.DataFrame``.
    meta : MetaList
        Meta information, containing the lengths and the worker address (the last value).
    meta_offset : int
        The lengths offset in the meta list.
    """
    execution_wrapper = RayWrapper
    def __init__(self, data: Union[ray.ObjectRef, DeferredExecution], length: int = ..., width: int = ..., ip: str = ..., meta: MetaList = ..., meta_offset: int = ...) -> None:
        ...
    
    @disable_logging
    def __del__(self): # -> None:
        """Unsubscribe from DeferredExecution."""
        ...
    
    def apply(self, func: Union[Callable, ray.ObjectRef], *args, **kwargs): # -> PandasDataframePartition:
        """
        Apply a function to the object wrapped by this partition.

        Parameters
        ----------
        func : callable or ray.ObjectRef
            A function to apply.
        *args : iterable
            Additional positional arguments to be passed in `func`.
        **kwargs : dict
            Additional keyword arguments to be passed in `func`.

        Returns
        -------
        PandasOnRayDataframePartition
            A new ``PandasOnRayDataframePartition`` object.

        Notes
        -----
        It does not matter if `func` is callable or an ``ray.ObjectRef``. Ray will
        handle it correctly either way. The keyword arguments are sent as a dictionary.
        """
        ...
    
    @_inherit_docstrings(PandasDataframePartition.add_to_apply_calls)
    def add_to_apply_calls(self, func: Union[Callable, ray.ObjectRef], *args, length=..., width=..., **kwargs): # -> PandasDataframePartition:
        ...
    
    @_inherit_docstrings(PandasDataframePartition.drain_call_queue)
    def drain_call_queue(self): # -> ObjectRefOrListType:
        ...
    
    @_inherit_docstrings(PandasDataframePartition.wait)
    def wait(self): # -> None:
        ...
    
    def __copy__(self): # -> PandasDataframePartition:
        """
        Create a copy of this partition.

        Returns
        -------
        PandasOnRayDataframePartition
            A copy of this partition.
        """
        ...
    
    def mask(self, row_labels, col_labels): # -> Self | PandasDataframePartition:
        """
        Lazily create a mask that extracts the indices provided.

        Parameters
        ----------
        row_labels : list-like, slice or label
            The row labels for the rows to extract.
        col_labels : list-like, slice or label
            The column labels for the columns to extract.

        Returns
        -------
        PandasOnRayDataframePartition
            A new ``PandasOnRayDataframePartition`` object.
        """
        ...
    
    @classmethod
    def put(cls, obj: pandas.DataFrame): # -> Self:
        """
        Put the data frame into Plasma store and wrap it with partition object.

        Parameters
        ----------
        obj : pandas.DataFrame
            A data frame to be put.

        Returns
        -------
        PandasOnRayDataframePartition
            A new ``PandasOnRayDataframePartition`` object.
        """
        ...
    
    @classmethod
    def preprocess_func(cls, func): # -> ObjectRef[FunctionType] | ObjectRef[FunctionType | Any] | None:
        """
        Put a function into the Plasma store to use in ``apply``.

        Parameters
        ----------
        func : callable
            A function to preprocess.

        Returns
        -------
        ray.ObjectRef
            A reference to `func`.
        """
        ...
    
    def length(self, materialize=...): # -> List[Any] | MetaListHook:
        """
        Get the length of the object wrapped by this partition.

        Parameters
        ----------
        materialize : bool, default: True
            Whether to forcibly materialize the result into an integer. If ``False``
            was specified, may return a future of the result if it hasn't been
            materialized yet.

        Returns
        -------
        int or ray.ObjectRef
            The length of the object.
        """
        ...
    
    def width(self, materialize=...): # -> List[Any] | MetaListHook:
        """
        Get the width of the object wrapped by the partition.

        Parameters
        ----------
        materialize : bool, default: True
            Whether to forcibly materialize the result into an integer. If ``False``
            was specified, may return a future of the result if it hasn't been
            materialized yet.

        Returns
        -------
        int or ray.ObjectRef
            The width of the object.
        """
        ...
    
    def ip(self, materialize=...): # -> List[Any] | MetaListHook | None:
        """
        Get the node IP address of the object wrapped by this partition.

        Parameters
        ----------
        materialize : bool, default: True
            Whether to forcibly materialize the result into an integer. If ``False``
            was specified, may return a future of the result if it hasn't been
            materialized yet.

        Returns
        -------
        str
            IP address of the node that holds the data.
        """
        ...
    


class SlicerHook(MaterializationHook):
    """
    Used by mask() for the slilced length computation.

    Parameters
    ----------
    ref : ObjectIDType
        Non-materialized length to be sliced.
    slc : slice
        The slice to be applied.
    """
    def __init__(self, ref: ObjectIDType, slc: slice) -> None:
        ...
    
    def pre_materialize(self): # -> int | ObjectRef[Any]:
        """
        Get the sliced length or object ref if not materialized.

        Returns
        -------
        int or ObjectIDType
        """
        ...
    
    def post_materialize(self, materialized): # -> int:
        """
        Get the sliced length.

        Parameters
        ----------
        materialized : list or int

        Returns
        -------
        int
        """
        ...
    


