"""
This type stub file was generated by pyright.
"""

import pandas
from modin.utils import _inherit_docstrings
from .default import DefaultMethod

"""Module houses default DataFrame functions builder class."""
@_inherit_docstrings(DefaultMethod)
class DataFrameDefault(DefaultMethod):
    DEFAULT_OBJECT_TYPE = pandas.DataFrame


