"""
This type stub file was generated by pyright.
"""

from .series import SeriesDefault

"""Module houses default applied-on-list accessor functions builder class."""
class ListDefault(SeriesDefault):
    """Builder for default-to-pandas methods which is executed under list accessor."""
    @classmethod
    def frame_wrapper(cls, df):
        """
        Get list accessor of the passed frame.

        Parameters
        ----------
        df : pandas.DataFrame

        Returns
        -------
        pandas.core.arrays.arrow.ListAccessor
        """
        ...
    


