"""
This type stub file was generated by pyright.
"""

from .default import DefaultMethod

"""Module houses default Resamle functions builder class."""
class Resampler:
    """Builder class for resampled aggregation functions."""
    @classmethod
    def build_resample(cls, func, squeeze_self): # -> Callable[..., Any]:
        """
        Build function that resamples time-series data and does aggregation.

        Parameters
        ----------
        func : callable
            Aggregation function to execute under resampled frame.
        squeeze_self : bool
            Whether or not to squeeze frame before resampling.

        Returns
        -------
        callable
            Function that takes pandas DataFrame and applies aggregation
            to resampled time-series data.
        """
        ...
    


class ResampleDefault(DefaultMethod):
    """Builder for default-to-pandas resampled aggregation functions."""
    OBJECT_TYPE = ...
    @classmethod
    def register(cls, func, squeeze_self=..., **kwargs): # -> Callable[..., Any]:
        """
        Build function that do fallback to pandas and aggregate resampled data.

        Parameters
        ----------
        func : callable
            Aggregation function to execute under resampled frame.
        squeeze_self : bool, default: False
            Whether or not to squeeze frame before resampling.
        **kwargs : kwargs
            Additional arguments that will be passed to function builder.

        Returns
        -------
        callable
            Function that takes query compiler and does fallback to pandas to resample
            time-series data and apply aggregation on it.
        """
        ...
    


