"""
This type stub file was generated by pyright.
"""

from .default import DefaultMethod

"""Module houses default Rolling functions builder class."""
class RollingDefault(DefaultMethod):
    """Builder for default-to-pandas aggregation on a rolling window functions."""
    OBJECT_TYPE = ...
    @classmethod
    def register(cls, func, **kwargs): # -> Callable[..., Any]:
        """
        Build function that do fallback to pandas to apply `func` on a rolling window.

        Parameters
        ----------
        func : callable
            Function to execute on a rolling window.
        **kwargs : kwargs
            Additional arguments that will be passed to function builder.

        Returns
        -------
        callable
            Function that takes query compiler and defaults to pandas to apply aggregation
            `func` on a rolling window.
        """
        ...
    


class ExpandingDefault(DefaultMethod):
    """Builder for default-to-pandas aggregation on an expanding window functions."""
    OBJECT_TYPE = ...
    @classmethod
    def register(cls, func, squeeze_self=..., **kwargs): # -> Callable[..., Any]:
        """
        Build function that do fallback to pandas to apply `func` on a expanding window.

        Parameters
        ----------
        func : callable
            Function to execute on an expanding window.
        squeeze_self : bool, default: False
            Whether or not to squeeze frame before executing the window function.
        **kwargs : kwargs
            Additional arguments that will be passed to function builder.

        Returns
        -------
        callable
            Function that takes query compiler and defaults to pandas to apply aggregation
            `func` on an expanding window.
        """
        ...
    


