"""
This type stub file was generated by pyright.
"""

from .series import SeriesDefault

"""Module houses default applied-on-str functions builder class."""
class StrDefault(SeriesDefault):
    """Builder for default-to-pandas methods which is executed under `str` accessor."""
    @classmethod
    def frame_wrapper(cls, df):
        """
        Get `str` accessor of the passed frame.

        Parameters
        ----------
        df : pandas.DataFrame

        Returns
        -------
        pandas.core.strings.accessor.StringMethods
        """
        ...
    


