from contextlib import contextmanager

def select_device(dev=...): ...
def is_float16_supported(): ...

class stream:
    @contextmanager
    def auto_synchronize(self): ...
    def synchronize(self): ...

def synchronize(): ...
def close(): ...
def declare_device(*args, **kwargs): ...
def detect(): ...
def list_devices(): ...

class Event:
    def record(self, stream=...): ...
    def wait(self, stream=...): ...
    def synchronize(self): ...
    def elapsed_time(self, event): ...

event = Event

def jit(
    func_or_sig=...,
    device=...,
    debug=...,
    argtypes=...,
    inline=...,
    restype=...,
    fastmath=...,
    link=...,
    boundscheck=...,
    opt=...,
    cache=...,
): ...
@contextmanager
def defer_cleanup(): ...
