from contextlib import contextmanager

class Dim3:
    def __init__(self, x, y, z) -> None: ...
    def __iter__(self): ...

class GridGroup:
    def sync(self): ...

class FakeCUDACg:
    def this_grid(self): ...

class FakeCUDALocal:
    def array(self, shape, dtype): ...

class FakeCUDAConst:
    def array_like(self, ary): ...

class FakeCUDAShared:
    def __init__(self, dynshared_size) -> None: ...
    def array(self, shape, dtype): ...

addlock = ...
sublock = ...
andlock = ...
orlock = ...
xorlock = ...
maxlock = ...
minlock = ...
compare_and_swaplock = ...
caslock = ...
inclock = ...
declock = ...
exchlock = ...

class FakeCUDAAtomic:
    def add(self, array, index, val): ...
    def sub(self, array, index, val): ...
    def and_(self, array, index, val): ...
    def or_(self, array, index, val): ...
    def xor(self, array, index, val): ...
    def inc(self, array, index, val): ...
    def dec(self, array, index, val): ...
    def exch(self, array, index, val): ...
    def max(self, array, index, val): ...
    def min(self, array, index, val): ...
    def nanmax(self, array, index, val): ...
    def nanmin(self, array, index, val): ...
    def compare_and_swap(self, array, old, val): ...
    def cas(self, array, index, old, val): ...

class FakeCUDAFp16:
    def hadd(self, a, b): ...
    def hsub(self, a, b): ...
    def hmul(self, a, b): ...
    def hdiv(self, a, b): ...
    def hfma(self, a, b, c): ...
    def hneg(self, a): ...
    def habs(self, a): ...
    def hsin(self, x): ...
    def hcos(self, x): ...
    def hlog(self, x): ...
    def hlog2(self, x): ...
    def hlog10(self, x): ...
    def hexp(self, x): ...
    def hexp2(self, x): ...
    def hexp10(self, x): ...
    def hsqrt(self, x): ...
    def hrsqrt(self, x): ...
    def hceil(self, x): ...
    def hfloor(self, x): ...
    def hrcp(self, x): ...
    def htrunc(self, x): ...
    def hrint(self, x): ...
    def heq(self, a, b): ...
    def hne(self, a, b): ...
    def hge(self, a, b): ...
    def hgt(self, a, b): ...
    def hle(self, a, b): ...
    def hlt(self, a, b): ...
    def hmax(self, a, b): ...
    def hmin(self, a, b): ...

class FakeCUDAModule:
    def __init__(self, grid_dim, block_dim, dynshared_size) -> None: ...
    @property
    def cg(self): ...
    @property
    def local(self): ...
    @property
    def shared(self): ...
    @property
    def const(self): ...
    @property
    def atomic(self): ...
    @property
    def fp16(self): ...
    @property
    def threadIdx(self): ...
    @property
    def blockIdx(self): ...
    @property
    def warpsize(self): ...
    @property
    def laneid(self): ...
    def syncthreads(self): ...
    def threadfence(self): ...
    def threadfence_block(self): ...
    def threadfence_system(self): ...
    def syncthreads_count(self, val): ...
    def syncthreads_and(self, val): ...
    def syncthreads_or(self, val): ...
    def popc(self, val): ...
    def fma(self, a, b, c): ...
    def cbrt(self, a): ...
    def brev(self, val): ...
    def clz(self, val): ...
    def ffs(self, val): ...
    def selp(self, a, b, c): ...
    def grid(self, n): ...
    def gridsize(self, n): ...

@contextmanager
def swapped_cuda_module(fn, fake_cuda_module): ...
