import threading

_kernel_context = ...

class FakeOverload:
    def max_cooperative_grid_blocks(self, blockdim): ...

class FakeOverloadDict(dict):
    def __getitem__(self, key): ...

class FakeCUDAKernel:
    def __init__(self, fn, device, fastmath=..., extensions=..., debug=...) -> None: ...
    def __call__(self, *args): ...
    def __getitem__(self, configuration): ...
    def bind(self): ...
    def specialize(self, *args): ...
    def forall(self, ntasks, tpb=..., stream=..., sharedmem=...): ...
    @property
    def overloads(self): ...
    @property
    def py_func(self): ...

class BlockThread(threading.Thread):
    def __init__(self, f, manager, blockIdx, threadIdx, debug) -> None: ...
    def run(self): ...
    def syncthreads(self): ...
    def syncthreads_count(self, value): ...
    def syncthreads_and(self, value): ...
    def syncthreads_or(self, value): ...

class BlockManager:
    def __init__(self, f, grid_dim, block_dim, debug) -> None: ...
    def run(self, grid_point, *args): ...
