class SimulatedVectorType:
    attributes = ...
    def __init__(self, *args) -> None: ...
    @property
    def name(self): ...
    @property
    def num_elements(self): ...
    def as_list(self): ...

def make_simulated_vector_type(num_elements, name): ...

vector_types = ...
