import ast

from numba.core import rewrites

@rewrites.register_rewrite("after-inference")
class RewriteArrayExprs(rewrites.Rewrite):
    def __init__(self, state, *args, **kws) -> None: ...
    def match(self, func_ir, block, typemap, calltypes):  # -> bool:

        ...
    def apply(self): ...

_unaryops = ...
_binops = ...
_cmpops = ...

class _EraseInvalidLineRanges(ast.NodeTransformer):
    def generic_visit(self, node: ast.AST) -> ast.AST: ...
