class _BaseVectorize:
    @classmethod
    def get_identity(cls, kwargs): ...
    @classmethod
    def get_cache(cls, kwargs): ...
    @classmethod
    def get_writable_args(cls, kwargs): ...
    @classmethod
    def get_target_implementation(cls, kwargs): ...

class Vectorize(_BaseVectorize):
    target_registry = ...
    def __new__(cls, func, **kws): ...

class GUVectorize(_BaseVectorize):
    target_registry = ...
    def __new__(cls, func, signature, **kws):  # -> GUFunc:
        ...

def vectorize(ftylist_or_function=..., **kws):  # -> DUFunc | Callable[..., Any]:

    ...
def guvectorize(*args, **kwargs):  # -> Callable[..., GUFunc | Any]:

    ...
