from numba.core import serialize
from numba.np.ufunc import _internal
from numba.np.ufunc.ufunc_base import UfuncBase, UfuncLowererBase

class UfuncAtIterator:
    def __init__(self, ufunc, a, a_ty, indices, indices_ty, b=..., b_ty=...) -> None: ...
    def run(self, context, builder):  # -> None:
        ...
    def need_advanced_indexing(self):  # -> bool:
        ...

def make_dufunc_kernel(_dufunc) -> None:  # -> type[DUFuncKernel]:
    ...

class DUFuncLowerer(UfuncLowererBase):
    def __init__(self, dufunc) -> None: ...

class DUFunc(serialize.ReduceMixin, _internal._DUFunc, UfuncBase):
    __base_kwargs = ...
    def __init__(self, py_func, identity=..., cache=..., targetoptions=...) -> None: ...
    def build_ufunc(self):  # -> Self:

        ...
    @property
    def targetoptions(self): ...
    @property
    def nin(self): ...
    @property
    def nout(self): ...
    @property
    def nargs(self): ...
    @property
    def ntypes(self): ...
    @property
    def types(self): ...
    @property
    def identity(self): ...
    @property
    def signature(self): ...
    def disable_compile(self):  # -> None:

        ...
    def add(self, sig): ...
    def __call__(self, *args, **kws): ...
    def match_signature(self, ewise_types, sig): ...
    def at(self, a, indices, b=...): ...
    def find_ewise_function(self, ewise_types):  # -> tuple[None, None] | tuple[Any, Any]:

        ...
