from numba.core import serialize
from numba.np.ufunc.ufunc_base import UfuncBase, UfuncLowererBase

def make_gufunc_kernel(_dufunc) -> None:  # -> type[GUFuncKernel]:
    ...

class GUFuncLowerer(UfuncLowererBase):
    def __init__(self, gufunc) -> None: ...

class GUFunc(serialize.ReduceMixin, UfuncBase):
    def __init__(self, py_func, signature, identity=..., cache=..., is_dynamic=..., targetoptions=..., writable_args=...) -> None: ...
    def add(self, fty):  # -> None:
        ...
    def build_ufunc(self):  # -> Self:
        ...
    def expected_ndims(self):  # -> tuple[tuple[int, ...], tuple[int, ...]]:
        ...
    def match_signature(self, ewise_types, sig):  # -> bool:
        ...
    @property
    def is_dynamic(self):  # -> bool:
        ...
    def __call__(self, *args, **kwargs): ...
