class UfuncLowererBase:
    def __init__(self, ufunc, make_kernel_fn, make_ufunc_kernel_fn) -> None: ...
    def __call__(self, context, builder, sig, args): ...

class UfuncBase:
    @property
    def nin(self): ...
    @property
    def nout(self): ...
    @property
    def nargs(self): ...
    @property
    def ntypes(self): ...
    @property
    def types(self): ...
    @property
    def identity(self): ...
    @property
    def signature(self): ...
    @property
    def accumulate(self): ...
    @property
    def at(self): ...
    @property
    def outer(self): ...
    @property
    def reduce(self): ...
    @property
    def reduceat(self): ...
    def disable_compile(self):  # -> None:

        ...
    def find_ewise_function(self, ewise_types):  # -> tuple[None, None] | tuple[Any, Any]:

        ...
