from numba.core.compiler_lock import global_compiler_lock

_wrapper_info = ...

def build_slow_loop_body(context, func, builder, arrays, out, offsets, store_offset, signature, pyapi, env): ...
def build_obj_loop_body(context, func, builder, arrays, out, offsets, store_offset, signature, pyapi, envptr, env): ...
def build_fast_loop_body(context, func, builder, arrays, out, offsets, store_offset, signature, ind, pyapi, env): ...
def build_ufunc_wrapper(library, context, fname, signature, objmode, cres):  # -> _wrapper_info:

    ...

class UArrayArg:
    def __init__(self, context, builder, args, steps, i, fe_type) -> None: ...
    def load_direct(self, byteoffset): ...
    def load_aligned(self, ind): ...
    def store_direct(self, value, byteoffset):  # -> None:
        ...
    def store_aligned(self, value, ind):  # -> None:
        ...

GufWrapperCache = ...

class _GufuncWrapper:
    def __init__(self, py_func, cres, sin, sout, cache, is_parfors) -> None: ...
    @property
    def library(self): ...
    @property
    def context(self): ...
    @property
    def call_conv(self): ...
    @property
    def signature(self): ...
    @property
    def fndesc(self): ...
    @property
    def env(self): ...
    @global_compiler_lock
    def build(self):  # -> _wrapper_info:
        ...
    def gen_loop_body(self, builder, pyapi, func, args):  # -> tuple[Any, Any]:
        ...
    def gen_prologue(self, builder, pyapi):  # -> None:
        ...
    def gen_epilogue(self, builder, pyapi):  # -> None:
        ...

class _GufuncObjectWrapper(_GufuncWrapper):
    def gen_loop_body(self, builder, pyapi, func, args):  # -> tuple[Any, Any]:
        ...
    def gen_prologue(self, builder, pyapi):  # -> None:
        ...
    def gen_epilogue(self, builder, pyapi):  # -> None:
        ...

def build_gufunc_wrapper(py_func, cres, sin, sout, cache, is_parfors): ...

class GUArrayArg:
    def __init__(self, context, builder, args, steps, i, step_offset, typ, syms, sym_dim) -> None: ...
    def get_array_at_offset(self, ind): ...

class _ScalarArgLoader:
    def __init__(self, dtype, stride) -> None: ...
    def load(self, context, builder, data, ind): ...

class _ArrayArgLoader:
    def __init__(self, dtype, ndim, core_step, as_scalar, shape, strides) -> None: ...
    def load(self, context, builder, data, ind): ...

class _ArrayAsScalarArgLoader(_ArrayArgLoader): ...
