from .table_option import TableOption, TableOptionKey

class IdentifierOption(TableOption):
    def __init__(self, value: str) -> None: ...
    @property
    def priority(self):  # -> Literal[Priority.HIGH]:
        ...
    @staticmethod
    def create(name: TableOptionKey, value: str | IdentifierOption | None) -> TableOption | None: ...
    def template(self) -> str: ...

type IdentifierOptionType = IdentifierOption | str | int
