from .table_option import TableOption, TableOptionKey

class LiteralOption(TableOption):
    def __init__(self, value: int | str) -> None: ...
    @property
    def priority(self):  # -> Literal[Priority.HIGH]:
        ...
    @staticmethod
    def create(name: TableOptionKey, value: str | int | LiteralOption | None) -> TableOption | None: ...
    def template(self) -> str: ...

type LiteralOptionType = LiteralOption | str | int
