from enum import Enum

class Priority(Enum):
    LOWEST = ...
    VERY_LOW = ...
    LOW = ...
    MEDIUM = ...
    HIGH = ...
    VERY_HIGH = ...
    HIGHEST = ...

class TableOption:
    def __init__(self) -> None: ...
    @property
    def option_name(self) -> str: ...
    @property
    def priority(self) -> Priority: ...
    @staticmethod
    def create(**kwargs) -> TableOption: ...
    def template(self) -> str: ...
    def render_option(self, compiler) -> str: ...

class TableOptionKey(Enum):
    AS_QUERY = ...
    BASE_LOCATION = ...
    CATALOG = ...
    CATALOG_SYNC = ...
    CLUSTER_BY = ...
    DATA_RETENTION_TIME_IN_DAYS = ...
    DEFAULT_DDL_COLLATION = ...
    EXTERNAL_VOLUME = ...
    MAX_DATA_EXTENSION_TIME_IN_DAYS = ...
    REFRESH_MODE = ...
    STORAGE_SERIALIZATION_POLICY = ...
    TARGET_LAG = ...
    WAREHOUSE = ...
