from enum import Enum

from .keyword_option import KeywordOptionType
from .table_option import Priority, TableOption

class TimeUnit(Enum):
    SECONDS = ...
    MINUTES = ...
    HOURS = ...
    DAYS = ...

class TargetLagOption(TableOption):
    def __init__(self, time: int | None = ..., unit: TimeUnit | None = ...) -> None: ...
    @staticmethod
    def create(value: TargetLagOption | tuple[int, TimeUnit] | KeywordOptionType) -> TableOption | None: ...
    @property
    def priority(self) -> Priority: ...

type TargetLagOptionType = TargetLagOption | tuple[int, TimeUnit]
