HAS_GOOGLE_AUTH = ...
HAS_OAUTH2CLIENT = ...

def credentials_from_file(filename, scopes=..., quota_project_id=...): ...
def default_credentials(scopes=..., quota_project_id=...): ...
def with_scopes(credentials, scopes): ...
def authorized_http(credentials): ...
def refresh_credentials(credentials): ...
def apply_credentials(credentials, headers): ...
def is_valid(credentials): ...
def get_credentials_from_http(http): ...
