logger = ...
POSITIONAL_WARNING = ...
POSITIONAL_EXCEPTION = ...
POSITIONAL_IGNORE = ...
POSITIONAL_SET = ...
positional_parameters_enforcement = ...
_SYM_LINK_MESSAGE = ...
_IS_DIR_MESSAGE = ...
_MISSING_FILE_MESSAGE = ...

def positional(max_positional_args): ...
def parse_unique_urlencoded(content): ...
def update_query_params(uri, params): ...
