from email.generator import BytesGenerator

from googleapiclient._helpers import positional

__author__ = ...
__all__ = ["build", "build_from_document", "fix_method_name", "key2param"]
HAS_UNIVERSE = ...
logger = ...
URITEMPLATE = ...
VARNAME = ...
DISCOVERY_URI = ...
V1_DISCOVERY_URI = ...
V2_DISCOVERY_URI = ...
DEFAULT_METHOD_DOC = ...
HTTP_PAYLOAD_METHODS = ...
_MEDIA_SIZE_BIT_SHIFTS = ...
BODY_PARAMETER_DEFAULT_VALUE = ...
MEDIA_BODY_PARAMETER_DEFAULT_VALUE = ...
MEDIA_MIME_TYPE_PARAMETER_DEFAULT_VALUE = ...
_PAGE_TOKEN_NAMES = ...
GOOGLE_API_USE_CLIENT_CERTIFICATE = ...
GOOGLE_API_USE_MTLS_ENDPOINT = ...
GOOGLE_CLOUD_UNIVERSE_DOMAIN = ...
DEFAULT_UNIVERSE = ...
STACK_QUERY_PARAMETERS = ...
STACK_QUERY_PARAMETER_DEFAULT_VALUE = ...

class APICoreVersionError(ValueError):
    def __init__(self) -> None: ...

RESERVED_WORDS = ...

class _BytesGenerator(BytesGenerator):
    _write_lines = ...

def fix_method_name(name): ...
def key2param(key): ...
@positional(2)
def build(
    serviceName,
    version,
    http=...,
    discoveryServiceUrl=...,
    developerKey=...,
    model=...,
    requestBuilder=...,
    credentials=...,
    cache_discovery=...,
    cache=...,
    client_options=...,
    adc_cert_path=...,
    adc_key_path=...,
    num_retries=...,
    static_discovery=...,
    always_use_jwt_access=...,
): ...
@positional(1)
def build_from_document(
    service,
    base=...,
    future=...,
    http=...,
    developerKey=...,
    model=...,
    requestBuilder=...,
    credentials=...,
    client_options=...,
    adc_cert_path=...,
    adc_key_path=...,
    always_use_jwt_access=...,
): ...

class ResourceMethodParameters:
    def __init__(self, method_desc) -> None: ...
    def set_parameters(self, method_desc): ...

def createMethod(methodName, methodDesc, rootDesc, schema): ...
def createNextMethod(methodName, pageTokenName=..., nextPageTokenName=..., isPageTokenParameter=...): ...

class Resource:
    def __init__(self, http, baseUrl, model, requestBuilder, developerKey, resourceDesc, rootDesc, schema, universe_domain=...) -> None: ...
    def __getstate__(self): ...
    def __setstate__(self, state): ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc, exc_tb): ...
    def close(self): ...
