from googleapiclient import _helpers as util

__author__ = ...

class Error(Exception): ...

class HttpError(Error):
    @util.positional(3)
    def __init__(self, resp, content, uri=...) -> None: ...
    @property
    def status_code(self): ...

    __str__ = ...

class InvalidJsonError(Error): ...
class UnknownFileType(Error): ...
class UnknownLinkType(Error): ...
class UnknownApiNameOrVersion(Error): ...
class UnacceptableMimeTypeError(Error): ...
class MediaUploadSizeError(Error): ...
class ResumableUploadError(HttpError): ...
class InvalidChunkSizeError(Error): ...
class InvalidNotificationError(Error): ...

class BatchError(HttpError):
    @util.positional(2)
    def __init__(self, reason, resp=..., content=...) -> None: ...

    __str__ = ...

class UnexpectedMethodError(Error):
    @util.positional(1)
    def __init__(self, methodId=...) -> None: ...

class UnexpectedBodyError(Error):
    def __init__(self, expected, provided) -> None: ...
