from googleapiclient import _helpers as util

__author__ = ...
LOGGER = ...
DEFAULT_CHUNK_SIZE = ...
MAX_URI_LENGTH = ...
MAX_BATCH_LIMIT = ...
_TOO_MANY_REQUESTS = ...
DEFAULT_HTTP_TIMEOUT_SEC = ...
_LEGACY_BATCH_URI = ...

class MediaUploadProgress:
    def __init__(self, resumable_progress, total_size) -> None: ...
    def progress(self): ...

class MediaDownloadProgress:
    def __init__(self, resumable_progress, total_size) -> None: ...
    def progress(self): ...

class MediaUpload:
    def chunksize(self): ...
    def mimetype(self): ...
    def size(self): ...
    def resumable(self): ...
    def getbytes(self, begin, end): ...
    def has_stream(self): ...
    def stream(self): ...
    def to_json(self): ...
    @classmethod
    def new_from_json(cls, s): ...

class MediaIoBaseUpload(MediaUpload):
    @util.positional(3)
    def __init__(self, fd, mimetype, chunksize=..., resumable=...) -> None: ...
    def chunksize(self): ...
    def mimetype(self): ...
    def size(self): ...
    def resumable(self): ...
    def getbytes(self, begin, length): ...
    def has_stream(self): ...
    def stream(self): ...
    def to_json(self): ...

class MediaFileUpload(MediaIoBaseUpload):
    @util.positional(2)
    def __init__(self, filename, mimetype=..., chunksize=..., resumable=...) -> None: ...
    def __del__(self) -> None: ...
    def to_json(self): ...
    @staticmethod
    def from_json(s): ...

class MediaInMemoryUpload(MediaIoBaseUpload):
    @util.positional(2)
    def __init__(self, body, mimetype=..., chunksize=..., resumable=...) -> None: ...

class MediaIoBaseDownload:
    @util.positional(3)
    def __init__(self, fd, request, chunksize=...) -> None: ...
    @util.positional(1)
    def next_chunk(self, num_retries=...): ...

class _StreamSlice:
    def __init__(self, stream, begin, chunksize) -> None: ...
    def read(self, n=...): ...

class HttpRequest:
    @util.positional(4)
    def __init__(self, http, postproc, uri, method=..., body=..., headers=..., methodId=..., resumable=...) -> None: ...
    @util.positional(1)
    def execute(self, http=..., num_retries=...): ...
    @util.positional(2)
    def add_response_callback(self, cb): ...
    @util.positional(1)
    def next_chunk(self, http=..., num_retries=...): ...
    def to_json(self): ...
    @staticmethod
    def from_json(s, http, postproc): ...
    @staticmethod
    def null_postproc(resp, contents): ...

class BatchHttpRequest:
    @util.positional(1)
    def __init__(self, callback=..., batch_uri=...) -> None: ...
    @util.positional(2)
    def add(self, request, callback=..., request_id=...): ...
    @util.positional(1)
    def execute(self, http=...): ...

class HttpRequestMock:
    def __init__(self, resp, content, postproc) -> None: ...
    def execute(self, http=...): ...

class RequestMockBuilder:
    def __init__(self, responses, check_unexpected=...) -> None: ...
    def __call__(self, http, postproc, uri, method=..., body=..., headers=..., methodId=..., resumable=...): ...

class HttpMock:
    def __init__(self, filename=..., headers=...) -> None: ...
    def request(self, uri, method=..., body=..., headers=..., redirections=..., connection_type=...): ...
    def close(self): ...

class HttpMockSequence:
    def __init__(self, iterable) -> None: ...
    def request(self, uri, method=..., body=..., headers=..., redirections=..., connection_type=...): ...

def set_user_agent(http, user_agent): ...
def tunnel_patch(http): ...
def build_http(): ...
