from googleapiclient import _helpers as util

__author__ = ...

class Schemas:
    def __init__(self, discovery) -> None: ...
    def prettyPrintByName(self, name): ...
    def prettyPrintSchema(self, schema): ...
    def get(self, name, default=...): ...

class _SchemaToStruct:
    @util.positional(3)
    def __init__(self, schema, seen, dent=...) -> None: ...
    def emit(self, text): ...
    def emitBegin(self, text): ...
    def emitEnd(self, text, comment): ...
    def indent(self): ...
    def undent(self): ...
    def to_str(self, from_cache): ...
