import contextlib

require_context = ...
current_context = ...
gpus = ...

@require_context
def from_cuda_array_interface(desc, owner=..., sync=...): ...
def as_cuda_array(obj, sync=...): ...
def is_cuda_array(obj): ...
def is_float16_supported(): ...
@require_context
def to_device(obj, stream=..., copy=..., to=...): ...
@require_context
def device_array(shape, dtype=..., strides=..., order=..., stream=...): ...
@require_context
def managed_array(shape, dtype=..., strides=..., order=..., stream=..., attach_global=...): ...
@require_context
def pinned_array(shape, dtype=..., strides=..., order=...): ...
@require_context
def mapped_array(shape, dtype=..., strides=..., order=..., stream=..., portable=..., wc=...): ...
@contextlib.contextmanager
@require_context
def open_ipc_array(handle, shape, dtype, strides=..., offset=...): ...
def synchronize(): ...
def device_array_like(ary, stream=...): ...
def mapped_array_like(ary, stream=..., portable=..., wc=...): ...
def pinned_array_like(ary): ...
@require_context
def stream(): ...
@require_context
def default_stream(): ...
@require_context
def legacy_default_stream(): ...
@require_context
def per_thread_default_stream(): ...
@require_context
def external_stream(ptr): ...
@require_context
@contextlib.contextmanager
def pinned(*arylist): ...
@require_context
@contextlib.contextmanager
def mapped(*arylist, **kws): ...
def event(timing=...): ...

event_elapsed_time = ...

def select_device(device_id): ...
def get_current_device(): ...
def list_devices(): ...
def close(): ...
def detect(): ...
@contextlib.contextmanager
def defer_cleanup(): ...

profiling = ...
profile_start = ...
profile_stop = ...
