from numba.core import serialize
from numba.core.codegen import Codegen, CodeLibrary

CUDA_TRIPLE = ...

def run_nvdisasm(cubin, flags):  # -> str:
    ...
def disassemble_cubin(cubin):  # -> str:
    ...
def disassemble_cubin_for_cfg(cubin):  # -> str:
    ...

class CUDACodeLibrary(serialize.ReduceMixin, CodeLibrary):
    def __init__(self, codegen, name, entry_name=..., max_registers=..., nvvm_options=...) -> None: ...
    @property
    def llvm_strs(self):  # -> list[str]:
        ...
    def get_llvm_str(self):  # -> str:
        ...
    def get_asm_str(self, cc=...): ...
    def get_ltoir(self, cc=...):  # -> list[Any]:
        ...
    def get_cubin(self, cc=...):  # -> bytes:
        ...
    def get_cufunc(self):  # -> Any:
        ...
    def get_linkerinfo(self, cc): ...
    def get_sass(self, cc=...):  # -> str:
        ...
    def get_sass_cfg(self, cc=...):  # -> str:
        ...
    def add_ir_module(self, mod):  # -> None:
        ...
    def add_linking_library(self, library):  # -> None:
        ...
    def add_linking_file(self, filepath):  # -> None:
        ...
    def get_function(self, name): ...
    @property
    def modules(self):  # -> list[Any | None]:
        ...
    @property
    def linking_libraries(self):  # -> list[Any]:
        ...
    def finalize(self):  # -> None:
        ...

class JITCUDACodegen(Codegen):
    _library_class = CUDACodeLibrary
    def __init__(self, module_name) -> None: ...
    def magic_tuple(self):  # -> tuple[tuple[int, int], Any]:

        ...
