from numba.core.compiler import CompilerBase, CompileResult, Flags
from numba.core.compiler_lock import global_compiler_lock
from numba.core.compiler_machinery import LoweringPass, register_pass

class CUDAFlags(Flags):
    nvvm_options = ...
    compute_capability = ...

class CUDACompileResult(CompileResult):
    @property
    def entry_point(self):  # -> int:
        ...

def cuda_compile_result(**entries):  # -> CUDACompileResult:
    ...

@register_pass(mutates_CFG=True, analysis_only=False)
class CUDABackend(LoweringPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:

        ...

@register_pass(mutates_CFG=False, analysis_only=False)
class CreateLibrary(LoweringPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:
        ...

class CUDACompiler(CompilerBase):
    def define_pipelines(self):  # -> list[PassManager]:
        ...
    def define_cuda_lowering_pipeline(self, state):  # -> PassManager:
        ...

@global_compiler_lock
def compile_cuda(pyfunc, return_type, args, debug=..., lineinfo=..., inline=..., fastmath=..., nvvm_options=..., cc=...): ...
def cabi_wrap_function(context, lib, fndesc, wrapper_function_name, nvvm_options): ...
@global_compiler_lock
def compile(
    pyfunc, sig, debug=..., lineinfo=..., device=..., fastmath=..., cc=..., opt=..., abi=..., abi_info=..., output=...
):  # -> tuple[Any, Any]:

    ...
def compile_for_current_device(
    pyfunc, sig, debug=..., lineinfo=..., device=..., fastmath=..., opt=..., abi=..., abi_info=..., output=...
): ...
def compile_ptx(pyfunc, sig, debug=..., lineinfo=..., device=..., fastmath=..., cc=..., opt=..., abi=..., abi_info=...): ...
def compile_ptx_for_current_device(pyfunc, sig, debug=..., lineinfo=..., device=..., fastmath=..., opt=..., abi=..., abi_info=...): ...
def declare_device_function(name, restype, argtypes):  # -> ExternFunction:
    ...
def declare_device_function_template(name, restype, argtypes) -> None:  # -> type[device_function_template]:
    ...

class ExternFunction:
    def __init__(self, name, sig) -> None: ...
