_env_path_tuple = ...

def get_system_ctk(*subdirs):  # -> str | None:

    ...
def get_conda_ctk():  # -> None:

    ...
def get_nvidia_nvvm_ctk():  # -> None:

    ...
def get_nvidia_libdevice_ctk():  # -> str | None:

    ...
def get_nvidia_cudalib_ctk():  # -> str | None:

    ...
def get_nvidia_static_cudalib_ctk():  # -> str | None:

    ...
def get_cuda_home(*subdirs):  # -> str | None:

    ...
def get_cuda_paths():  # -> Any | dict[str, _env_path_tuple]:

    ...
def get_debian_pkg_libdevice():  # -> Literal['/usr/lib/nvidia-cuda-toolkit/libdevice'] | None:

    ...
