from abc import ABCMeta, abstractmethod

from numba.np.ufunc.ufuncbuilder import _BaseUFuncBuilder

"""
Implements custom ufunc dispatch mechanism for non-CPU devices.
"""

class UFuncMechanism:
    DEFAULT_STREAM = ...
    SUPPORT_DEVICE_SLICING = ...
    def __init__(self, typemap, args) -> None: ...
    def get_arguments(self):  # -> list[None]:

        ...
    def get_function(self): ...
    def is_device_array(self, obj):  # -> Literal[False]:

        ...
    def as_device_array(self, obj): ...
    def broadcast_device(self, ary, shape): ...
    def force_array_layout(self, ary): ...
    @classmethod
    def call(cls, typemap, args, kws): ...
    def to_device(self, hostary, stream): ...
    def to_host(self, devary, stream): ...
    def allocate_device_array(self, shape, dtype, stream): ...
    def launch(self, func, count, stream, args): ...

def to_dtype(ty):  # -> dtype[Any]:
    ...

class DeviceVectorize(_BaseUFuncBuilder):
    def __init__(self, func, identity=..., cache=..., targetoptions=...) -> None: ...
    @property
    def pyfunc(self):  # -> Any:
        ...
    def add(self, sig=...):  # -> None:
        ...
    def build_ufunc(self): ...

class DeviceGUFuncVectorize(_BaseUFuncBuilder):
    def __init__(self, func, sig, identity=..., cache=..., targetoptions=..., writable_args=...) -> None: ...
    @property
    def pyfunc(self):  # -> Any:
        ...
    def add(self, sig=...):  # -> None:
        ...

def expand_gufunc_template(template, indims, outdims, funcname, argtypes): ...

class GUFuncEngine:
    @classmethod
    def from_signature(cls, signature):  # -> Self:
        ...
    def __init__(self, inputsig, outputsig) -> None: ...
    def schedule(self, ishapes):  # -> GUFuncSchedule:
        ...

class GUFuncSchedule:
    def __init__(self, parent, ishapes, oshapes, loopdims, pinned) -> None: ...

class GeneralizedUFunc:
    def __init__(self, kernelmap, engine) -> None: ...
    def __call__(self, *args, **kws): ...

class GUFuncCallSteps(metaclass=ABCMeta):
    __slots__ = ...
    @abstractmethod
    def launch_kernel(self, kernel, nelem, args):  # -> None:

        ...
    @abstractmethod
    def is_device_array(self, obj):  # -> None:

        ...
    @abstractmethod
    def as_device_array(self, obj):  # -> None:

        ...
    @abstractmethod
    def to_device(self, hostary):  # -> None:

        ...
    @abstractmethod
    def allocate_device_array(self, shape, dtype):  # -> None:

        ...
    def __init__(self, nin, nout, args, kwargs) -> None: ...
    def adjust_input_types(self, indtypes):  # -> None:

        ...
    def prepare_outputs(self, schedule, outdtypes):  # -> list[Any]:

        ...
    def prepare_inputs(self):  # -> list[None]:

        ...
    def post_process_outputs(self, outputs):  # -> NDArray[Any] | tuple[NDArray[Any] | None, ...] | None:

        ...
