import functools

from numba.core import serialize
from numba.core.caching import Cache, CacheImpl
from numba.core.compiler_lock import global_compiler_lock
from numba.core.dispatcher import Dispatcher

cuda_fp16_math_funcs = ...

class _Kernel(serialize.ReduceMixin):
    @global_compiler_lock
    def __init__(
        self,
        py_func,
        argtypes,
        link=...,
        debug=...,
        lineinfo=...,
        inline=...,
        fastmath=...,
        extensions=...,
        max_registers=...,
        opt=...,
        device=...,
    ) -> None: ...
    @property
    def library(self): ...
    @property
    def type_annotation(self): ...
    @property
    def codegen(self): ...
    @property
    def argument_types(self):  # -> tuple[Any, ...]:
        ...
    def bind(self):  # -> None:

        ...
    @property
    def regs_per_thread(self): ...
    @property
    def const_mem_size(self): ...
    @property
    def shared_mem_per_block(self): ...
    @property
    def max_threads_per_block(self): ...
    @property
    def local_mem_per_thread(self): ...
    def inspect_llvm(self): ...
    def inspect_asm(self, cc): ...
    def inspect_sass_cfg(self): ...
    def inspect_sass(self): ...
    def inspect_types(self, file=...):  # -> None:

        ...
    def max_cooperative_grid_blocks(self, blockdim, dynsmemsize=...):  # -> Any:

        ...
    def launch(self, args, griddim, blockdim, stream=..., sharedmem=...):  # -> None:
        ...

class ForAll:
    def __init__(self, dispatcher, ntasks, tpb, stream, sharedmem) -> None: ...
    def __call__(self, *args):  # -> None:
        ...

class _LaunchConfiguration:
    def __init__(self, dispatcher, griddim, blockdim, stream, sharedmem) -> None: ...
    def __call__(self, *args): ...

class CUDACacheImpl(CacheImpl):
    def reduce(self, kernel): ...
    def rebuild(self, target_context, payload):  # -> _Kernel:
        ...
    def check_cachable(self, cres):  # -> Literal[True]:
        ...

class CUDACache(Cache):
    _impl_class = CUDACacheImpl
    def load_overload(self, sig, target_context):  # -> None:
        ...

class CUDADispatcher(Dispatcher, serialize.ReduceMixin):
    _fold_args = ...
    targetdescr = ...
    def __init__(self, py_func, targetoptions, pipeline_class=...) -> None: ...
    def enable_caching(self):  # -> None:
        ...
    @functools.lru_cache(maxsize=128)
    def configure(self, griddim, blockdim, stream=..., sharedmem=...):  # -> _LaunchConfiguration:
        ...
    def __getitem__(self, args):  # -> _LaunchConfiguration:
        ...
    def forall(self, ntasks, tpb=..., stream=..., sharedmem=...):  # -> ForAll:

        ...
    @property
    def extensions(self):  # -> None:

        ...
    def __call__(self, *args, **kwargs): ...
    def call(self, args, griddim, blockdim, stream, sharedmem):  # -> None:

        ...
    def typeof_pyval(self, val):  # -> Buffer | Any | ExternalFunctionPointer | Opaque:
        ...
    def specialize(self, *args):  # -> CUDADispatcher:

        ...
    @property
    def specialized(self):  # -> bool:

        ...
    def get_regs_per_thread(self, signature=...):  # -> dict[Any, Any]:

        ...
    def get_const_mem_size(self, signature=...):  # -> dict[Any, Any]:

        ...
    def get_shared_mem_per_block(self, signature=...):  # -> dict[Any, Any]:

        ...
    def get_max_threads_per_block(self, signature=...):  # -> dict[Any, Any]:

        ...
    def get_local_mem_per_thread(self, signature=...):  # -> dict[Any, Any]:

        ...
    def get_call_template(self, args, kws):  # -> tuple[Any, Signature, Any, Any]:

        ...
    def compile_device(self, args, return_type=...): ...
    def add_overload(self, kernel, argtypes):  # -> None:
        ...
    def compile(self, sig):  # -> _Kernel:

        ...
    def inspect_llvm(self, signature=...):  # -> dict[Any, Any]:

        ...
    def inspect_asm(self, signature=...):  # -> dict[Any, Any]:

        ...
    def inspect_sass_cfg(self, signature=...):  # -> dict[Any, Any]:

        ...
    def inspect_sass(self, signature=...):  # -> dict[Any, Any]:

        ...
    def inspect_types(self, file=...):  # -> None:

        ...
