from numba.core.errors import LoweringError

class KernelRuntimeError(RuntimeError):
    def __init__(self, msg, tid=..., ctaid=...) -> None: ...

class CudaLoweringError(LoweringError): ...

_launch_help_url = ...
missing_launch_config_msg = ...

def normalize_kernel_dimensions(griddim, blockdim):  # -> tuple[tuple[Any, ...], tuple[Any, ...]]:

    ...
