from .decorators import jit

@jit(device=True)
def all_sync(mask, predicate): ...
@jit(device=True)
def any_sync(mask, predicate): ...
@jit(device=True)
def eq_sync(mask, predicate): ...
@jit(device=True)
def ballot_sync(mask, predicate): ...
@jit(device=True)
def shfl_sync(mask, value, src_lane): ...
@jit(device=True)
def shfl_up_sync(mask, value, delta): ...
@jit(device=True)
def shfl_down_sync(mask, value, delta): ...
@jit(device=True)
def shfl_xor_sync(mask, value, lane_mask): ...
