from functools import singledispatch

from numba.core import types

registry = ...
lower = ...
voidptr = ...

@singledispatch
def print_item(ty, context, builder, val): ...
@print_item.register(types.Integer)
@print_item.register(types.IntegerLiteral)
def int_print_impl(ty, context, builder, val):  # -> tuple[Literal['%llu', '%lld'], list[Any]]:
    ...
@print_item.register(types.Float)
def real_print_impl(ty, context, builder, val):  # -> tuple[Literal['%f'], list[Any]]:
    ...
@print_item.register(types.StringLiteral)
def const_print_impl(ty, context, builder, sigval):  # -> tuple[Literal['%s'], list[Any]]:
    ...
@lower(print, types.VarArg(types.Any))
def print_varargs(context, builder, sig, args): ...
