class Stub:
    _description_ = ...
    __slots__ = ...
    def __new__(cls): ...

def stub_function(fn):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], NoReturn]:

    ...

class Dim3(Stub):
    _description_ = ...
    @property
    def x(self):  # -> None:
        ...
    @property
    def y(self):  # -> None:
        ...
    @property
    def z(self):  # -> None:
        ...

class threadIdx(Dim3):
    _description_ = ...

class blockIdx(Dim3):
    _description_ = ...

class blockDim(Dim3):
    _description_ = ...

class gridDim(Dim3):
    _description_ = ...

class warpsize(Stub):
    _description_ = ...

class laneid(Stub):
    _description_ = ...

class shared(Stub):
    _description_ = ...
    @stub_function
    def array(self, dtype):  # -> None:

        ...

class local(Stub):
    _description_ = ...
    @stub_function
    def array(self, dtype):  # -> None:

        ...

class const(Stub):
    @stub_function
    def array_like(self):  # -> None:

        ...

class syncwarp(Stub):
    _description_ = ...

class shfl_sync_intrinsic(Stub):
    _description_ = ...

class vote_sync_intrinsic(Stub):
    _description_ = ...

class match_any_sync(Stub):
    _description_ = ...

class match_all_sync(Stub):
    _description_ = ...

class activemask(Stub):
    _description_ = ...

class lanemask_lt(Stub):
    _description_ = ...

class threadfence_block(Stub):
    _description_ = ...

class threadfence_system(Stub):
    _description_ = ...

class threadfence(Stub):
    _description_ = ...

class popc(Stub): ...
class brev(Stub): ...
class clz(Stub): ...
class ffs(Stub): ...
class selp(Stub): ...
class fma(Stub): ...
class cbrt(Stub): ...

class atomic(Stub):
    _description_ = ...
    class add(Stub): ...
    class sub(Stub): ...
    class and_(Stub): ...
    class or_(Stub): ...
    class xor(Stub): ...
    class inc(Stub): ...
    class dec(Stub): ...
    class exch(Stub): ...
    class max(Stub): ...
    class min(Stub): ...
    class nanmax(Stub): ...
    class nanmin(Stub): ...
    class compare_and_swap(Stub): ...
    class cas(Stub): ...

class nanosleep(Stub):
    _description_ = ...

class fp16(Stub):
    _description_ = ...
    class hadd(Stub): ...
    class hsub(Stub): ...
    class hmul(Stub): ...
    class hdiv(Stub): ...
    class hfma(Stub): ...
    class hneg(Stub): ...
    class habs(Stub): ...
    class hsin(Stub): ...
    class hcos(Stub): ...
    class hlog(Stub): ...
    class hlog10(Stub): ...
    class hlog2(Stub): ...
    class hexp(Stub): ...
    class hexp10(Stub): ...
    class hexp2(Stub): ...
    class hfloor(Stub): ...
    class hceil(Stub): ...
    class hsqrt(Stub): ...
    class hrsqrt(Stub): ...
    class hrcp(Stub): ...
    class hrint(Stub): ...
    class htrunc(Stub): ...
    class heq(Stub): ...
    class hne(Stub): ...
    class hge(Stub): ...
    class hgt(Stub): ...
    class hle(Stub): ...
    class hlt(Stub): ...
    class hmax(Stub): ...
    class hmin(Stub): ...

def make_vector_type_stubs():  # -> list[Any]:

    ...
def map_vector_type_stubs_to_alias(vector_type_stubs):  # -> None:

    ...

_vector_type_stubs = ...
