from functools import cached_property

from numba.core import typing
from numba.core.base import BaseContext
from numba.core.callconv import BaseCallConv, MinimalCallConv

class CUDATypingContext(typing.BaseContext):
    def load_additional_registries(self):  # -> None:
        ...
    def resolve_value_type(self, val):  # -> Buffer | Any | ExternalFunctionPointer | Opaque | ExternalFunction | Module:
        ...

VALID_CHARS = ...

class CUDATargetContext(BaseContext):
    implement_powi_as_math_call = ...
    strict_alignment = ...
    def __init__(self, typingctx, target=...) -> None: ...
    @property
    def DIBuilder(self):  # -> type[DIBuilder]:
        ...
    @property
    def enable_boundscheck(self):  # -> Literal[False]:
        ...
    def create_module(self, name):  # -> Module:
        ...
    def init(self):  # -> None:
        ...
    def load_additional_registries(self):  # -> None:
        ...
    def codegen(self):  # -> JITCUDACodegen:
        ...
    @property
    def target_data(self):  # -> TargetData:
        ...
    @cached_property
    def nonconst_module_attrs(self):  # -> tuple[tuple[Module, str], ...]:

        ...
    @cached_property
    def call_conv(self):  # -> CUDACallConv:
        ...
    def mangler(self, name, argtypes, *, abi_tags=..., uid=...):  # -> str:
        ...
    def prepare_cuda_kernel(
        self, codelib, fndesc, debug, lineinfo, nvvm_options, filename, linenum, max_registers=...
    ):  # -> tuple[Any, Any]:

        ...
    def generate_kernel_wrapper(self, library, fndesc, kernel_name, debug, lineinfo, filename, linenum): ...
    def make_constant_array(self, builder, aryty, arr):  # -> Any:

        ...
    def insert_const_string(self, mod, string):  # -> None:

        ...
    def insert_string_const_addrspace(self, builder, string): ...
    def optimize_function(self, func):  # -> None:

        ...
    def get_ufunc_info(self, ufunc_key): ...

class CUDACallConv(MinimalCallConv): ...

class CUDACABICallConv(BaseCallConv):
    def return_value(self, builder, retval): ...
    def return_user_exc(self, builder, exc, exc_args=..., loc=..., func_name=...): ...
    def return_status_propagate(self, builder, status): ...
    def get_function_type(self, restype, argtypes):  # -> FunctionType:

        ...
    def decorate_function(self, fn, args, fe_argtypes, noalias=...):  # -> None:

        ...
    def get_arguments(self, func): ...
    def call_function(self, builder, callee, resty, argtys, args):  # -> tuple[None, Any]:

        ...
    def get_return_type(self, ty): ...
