from numba.tests.support import SerialMixin, TestCase

numba_cuda_dir = ...
test_data_dir = ...

class CUDATestCase(SerialMixin, TestCase):
    def setUp(self):  # -> None:
        ...
    def tearDown(self):  # -> None:
        ...
    def skip_if_lto(self, reason):  # -> None:
        ...

class ContextResettingTestCase(CUDATestCase):
    def tearDown(self):  # -> None:
        ...

def ensure_supported_ccs_initialized():  # -> None:
    ...
def skip_on_cudasim(reason):  # -> Callable[[_FT], _FT]:

    ...
def skip_unless_cudasim(reason):  # -> Callable[[_FT], _FT]:

    ...
def skip_unless_conda_cudatoolkit(reason):  # -> Callable[[_FT], _FT]:

    ...
def skip_if_external_memmgr(reason):  # -> Callable[[_FT], _FT]:

    ...
def skip_under_cuda_memcheck(reason):  # -> Callable[[_FT], _FT]:
    ...
def skip_without_nvdisasm(reason):  # -> Callable[[_FT], _FT]:
    ...
def skip_with_nvdisasm(reason):  # -> Callable[[_FT], _FT]:
    ...
def skip_on_arm(reason):  # -> Callable[[_FT], _FT]:
    ...
def skip_if_cuda_includes_missing(fn): ...
def skip_if_mvc_enabled(reason):  # -> Callable[[_FT], _FT]:

    ...
def skip_if_mvc_libraries_unavailable(fn): ...
def cc_X_or_above(major, minor):  # -> Any | Literal[True]:
    ...
def skip_unless_cc_50(fn): ...
def skip_unless_cc_53(fn): ...
def skip_unless_cc_60(fn): ...
def skip_unless_cc_75(fn): ...
def xfail_unless_cudasim(fn): ...
def skip_with_cuda_python(reason):  # -> Callable[[_FT], _FT]:
    ...
def cudadevrt_missing():  # -> bool:
    ...
def skip_if_cudadevrt_missing(fn): ...

class ForeignArray:
    def __init__(self, arr) -> None: ...
