from numba.core import types

class Dim3(types.Type):
    def __init__(self) -> None: ...

class GridGroup(types.Type):
    def __init__(self) -> None: ...

dim3 = ...
grid_group = ...

class CUDADispatcher(types.Dispatcher): ...
