from numba.cuda import deviceufunc
from numba.cuda.deviceufunc import GeneralizedUFunc, GUFuncCallSteps, UFuncMechanism

class CUDAUFuncDispatcher:
    def __init__(self, types_to_retty_kernels, pyfunc) -> None: ...
    def __call__(self, *args, **kws): ...
    def reduce(self, arg, stream=...):  # -> Any:
        ...

class _CUDAGUFuncCallSteps(GUFuncCallSteps):
    __slots__ = ...
    def __init__(self, nin, nout, args, kwargs) -> None: ...
    def is_device_array(self, obj):  # -> bool:
        ...
    def as_device_array(self, obj):  # -> DeviceNDArray:
        ...
    def to_device(self, hostary):  # -> DeviceRecord | DeviceNDArray:
        ...
    def to_host(self, devary, hostary): ...
    def allocate_device_array(self, shape, dtype):  # -> DeviceNDArray:
        ...
    def launch_kernel(self, kernel, nelem, args):  # -> None:
        ...

class CUDAGeneralizedUFunc(GeneralizedUFunc):
    def __init__(self, kernelmap, engine, pyfunc) -> None: ...

class CUDAUFuncMechanism(UFuncMechanism):
    DEFAULT_STREAM = ...
    def launch(self, func, count, stream, args):  # -> None:
        ...
    def is_device_array(self, obj):  # -> bool:
        ...
    def as_device_array(self, obj):  # -> DeviceNDArray:
        ...
    def to_device(self, hostary, stream):  # -> DeviceRecord | DeviceNDArray:
        ...
    def to_host(self, devary, stream): ...
    def allocate_device_array(self, shape, dtype, stream):  # -> DeviceNDArray:
        ...
    def broadcast_device(self, ary, shape): ...

vectorizer_stager_source = ...

class CUDAVectorize(deviceufunc.DeviceVectorize):
    def build_ufunc(self):  # -> CUDAUFuncDispatcher:
        ...

_gufunc_stager_source = ...

class CUDAGUFuncVectorize(deviceufunc.DeviceGUFuncVectorize):
    def build_ufunc(self):  # -> CUDAGeneralizedUFunc:
        ...
