from numba import types
from numba.core.extending import models

typing_registry = ...
impl_registry = ...
register = ...
register_attr = ...
register_global = ...
lower = ...

class VectorType(types.Type):
    def __init__(self, name, base_type, attr_names, user_facing_object) -> None: ...
    @property
    def base_type(self):  # -> Any:
        ...
    @property
    def attr_names(self):  # -> Any:
        ...
    @property
    def num_elements(self):  # -> int:
        ...
    @property
    def user_facing_object(self):  # -> Any:
        ...

def make_vector_type(name: str, base_type: types.Type, attr_names: tuple[str, ...], user_facing_object) -> types.Type:

    class _VectorType(VectorType): ...
    class VectorTypeModel(models.StructModel): ...

def enable_vector_type_ctor(vector_type: VectorType, overloads: list[list[types.Type]]) -> None:  # -> None:

    ...

vector_types: dict[str, VectorType] = ...

def build_constructor_overloads(base_type, vty_name, num_elements, arglists, l):  # -> None:

    ...
