"""
This type stub file was generated by pyright.
"""

import pandas
from enum import Enum
from typing import Dict, Tuple
from pandas._typing import IndexLabel

"""
This type stub file was generated by pyright.
"""
class Axis(Enum):
    """
    An enum that represents the `axis` argument provided to the algebra operators.

    The enum has 3 values - ROW_WISE to represent the row axis, COL_WISE to represent the
    column axis, and CELL_WISE to represent no axis. ROW_WISE operations iterate over the rows
    COL_WISE operations over the columns, and CELL_WISE operations over any of the partitioning
    schemes that are supported in Modin (row-wise, column-wise, or block-wise).
    """
    ROW_WISE = ...
    COL_WISE = ...
    CELL_WISE = ...


class JoinType(Enum):
    """
    An enum that represents the `join_type` argument provided to the algebra operators.

    The enum has 4 values - INNER to represent inner joins, LEFT to represent left joins, RIGHT to
    represent right joins, and OUTER to represent outer joins.
    """
    INNER = ...
    LEFT = ...
    RIGHT = ...
    OUTER = ...


def join_columns(left: pandas.Index, right: pandas.Index, left_on: IndexLabel, right_on: IndexLabel, suffixes: Tuple[str, str]) -> Tuple[pandas.Index, Dict[IndexLabel, IndexLabel], Dict[IndexLabel, IndexLabel]]:
    """
    Compute resulting columns for the two dataframes being merged.

    Parameters
    ----------
    left : pandas.Index
        Columns of the left frame to join.
    right : pandas.Index
        Columns of the right frame to join.
    left_on : list-like or scalar
        Column names on which the frames are joined in the left DataFrame.
    right_on : list-like or scalar
        Column names on which the frames are joined in the right DataFrame.
    suffixes : tuple[str, str]
        A 2-length sequence containing suffixes to append to the intersected columns.

    Returns
    -------
    pandas.Index, dict[IndexLabel -> IndexLabel], dict[IndexLabel -> IndexLabel]
        Returns columns for the resulting frame and mappings of old to new column
        names for `left` and `right` accordingly.

    Raises
    ------
    NotImplementedError
        Raised when one of the keys to join is an index level, pandas behaviour is really
        complicated in this case, so we're not supporting this case for now.
    """
    ...

def is_trivial_index(index: pandas.Index) -> bool:
    """
    Check if the index is a trivial index, i.e. a sequence [0..n].

    Parameters
    ----------
    index : pandas.Index
        An index to check.

    Returns
    -------
    bool
    """
    ...

