from typing import Any

from ...auth.default import AuthByDefault as AuthByDefaultSync
from ._by_plugin import AuthByPlugin as AuthByPluginAsync

logger = ...

class AuthByDefault(AuthByPluginAsync, AuthByDefaultSync):
    def __init__(self, password: str, **kwargs) -> None: ...
    async def reset_secrets(self) -> None: ...
    async def prepare(self, **kwargs: Any) -> None: ...
    async def reauthenticate(self, **kwargs: Any) -> dict[str, bool]: ...
    async def update_body(self, body: dict[Any, Any]) -> None: ...
