from typing import TYPE_CHECKING, Any

from ...auth.idtoken import AuthByIdToken as AuthByIdTokenSync
from .._connection import SnowflakeConnection
from ._by_plugin import AuthByPlugin as AuthByPluginAsync

if TYPE_CHECKING: ...

class AuthByIdToken(AuthByPluginAsync, AuthByIdTokenSync):
    def __init__(self, id_token: str, application: str, protocol: str | None, host: str | None, port: str | None, **kwargs) -> None: ...
    async def reset_secrets(self) -> None: ...
    async def prepare(self, **kwargs: Any) -> None: ...
    async def reauthenticate(self, *, conn: SnowflakeConnection, **kwargs: Any) -> dict[str, bool]: ...
    async def update_body(self, body: dict[Any, Any]) -> None: ...
