from typing import Any

from cryptography.hazmat.primitives.asymmetric.rsa import RSAPrivateKey

from ...auth.keypair import AuthByKeyPair as AuthByKeyPairSync
from ._by_plugin import AuthByPlugin as AuthByPluginAsync

logger = ...

class AuthByKeyPair(AuthByPluginAsync, AuthByKeyPairSync):
    def __init__(self, private_key: bytes | str | RSAPrivateKey, lifetime_in_seconds: int = ..., **kwargs) -> None: ...
    async def reset_secrets(self) -> None: ...
    async def prepare(self, **kwargs: Any) -> None: ...
    async def reauthenticate(self, **kwargs: Any) -> dict[str, bool]: ...
    async def update_body(self, body: dict[Any, Any]) -> None: ...
    async def handle_timeout(
        self, *, authenticator: str, service_name: str | None, account: str, user: str, password: str | None, **kwargs: Any
    ) -> None: ...
