from typing import Any

from ...auth.no_auth import AuthNoAuth as AuthNoAuthSync
from ._by_plugin import AuthByPlugin as AuthByPluginAsync

class AuthNoAuth(AuthByPluginAsync, AuthNoAuthSync):
    def __init__(self, **kwargs) -> None: ...
    async def reset_secrets(self) -> None: ...
    async def prepare(self, **kwargs: Any) -> None: ...
    async def reauthenticate(self, **kwargs: Any) -> dict[str, bool]: ...
    async def update_body(self, body: dict[Any, Any]) -> None: ...
