from typing import Any

from ...auth.oauth import AuthByOAuth as AuthByOAuthSync
from ._by_plugin import AuthByPlugin as AuthByPluginAsync

class AuthByOAuth(AuthByPluginAsync, AuthByOAuthSync):
    def __init__(self, oauth_token: str, **kwargs) -> None: ...
    async def reset_secrets(self) -> None: ...
    async def prepare(self, **kwargs: Any) -> None: ...
    async def reauthenticate(self, **kwargs: Any) -> dict[str, bool]: ...
    async def update_body(self, body: dict[Any, Any]) -> None: ...
