from typing import Any

from ...auth.pat import AuthByPAT as AuthByPATSync
from ._by_plugin import AuthByPlugin as AuthByPluginAsync

class AuthByPAT(AuthByPluginAsync, AuthByPATSync):
    def __init__(self, pat_token: str, **kwargs) -> None: ...
    async def reset_secrets(self) -> None: ...
    async def prepare(self, **kwargs: Any) -> None: ...
    async def reauthenticate(self, **kwargs: Any) -> dict[str, bool]: ...
    async def update_body(self, body: dict[Any, Any]) -> None: ...
