from ...auth.usrpwdmfa import AuthByUsrPwdMfa as AuthByUsrPwdMfaSync
from ._by_plugin import AuthByPlugin as AuthByPluginAsync

class AuthByUsrPwdMfa(AuthByPluginAsync, AuthByUsrPwdMfaSync):
    def __init__(self, password: str, mfa_token: str | None = ..., **kwargs) -> None: ...
    async def reset_secrets(self) -> None: ...
    async def prepare(self, **kwargs) -> None: ...
    async def reauthenticate(self, **kwargs) -> dict[str, bool]: ...
    async def update_body(self, body: dict[str, str]) -> None: ...
