"""
This type stub file was generated by pyright.
"""

from typing import NoReturn, Optional, Set

"""
This type stub file was generated by pyright.
"""
class ErrorMessage:
    printed_default_to_pandas = ...
    printed_warnings: Set[int] = ...
    @classmethod
    def not_implemented(cls, message: str = ...) -> NoReturn:
        ...
    
    @classmethod
    def single_warning(cls, message: str, category: Optional[type[Warning]] = ...) -> None:
        ...
    
    @classmethod
    def default_to_pandas(cls, message: str = ..., reason: str = ...) -> None:
        ...
    
    @classmethod
    def catch_bugs_and_request_email(cls, failure_condition: bool, extra_log: str = ...) -> None:
        ...
    
    @classmethod
    def non_verified_udf(cls) -> None:
        ...
    
    @classmethod
    def bad_type_for_numpy_op(cls, function_name: str, operand_type: type) -> None:
        ...
    
    @classmethod
    def mismatch_with_pandas(cls, operation: str, message: str) -> None:
        ...
    
    @classmethod
    def warn(cls, message: str) -> None:
        ...
    
    @classmethod
    def not_initialized(cls, engine: str, code: str) -> None:
        ...
    


