"""
This type stub file was generated by pyright.
"""

import types
from typing import Any, Callable, Iterable, List, Protocol, TypeVar, Union, runtime_checkable

"""
This type stub file was generated by pyright.
"""
sentinel = ...
T = TypeVar("T")
Fn = TypeVar("Fn", bound=Callable)
@runtime_checkable
class SupportsPublicToPandas(Protocol):
    """Structural type for objects with a ``to_pandas`` method (without a leading underscore)."""
    def to_pandas(self) -> Any:
        ...
    


@runtime_checkable
class SupportsPublicToNumPy(Protocol):
    """Structural type for objects with a ``to_numpy`` method (without a leading underscore)."""
    def to_numpy(self) -> Any:
        ...
    


@runtime_checkable
class SupportsPrivateToNumPy(Protocol):
    """Structural type for objects with a ``_to_numpy`` method (note the leading underscore)."""
    ...


MIN_RAY_VERSION = ...
MIN_DASK_VERSION = ...
MIN_UNIDIST_VERSION = ...
PANDAS_API_URL_TEMPLATE = ...
MODIN_UNNAMED_SERIES_LABEL = ...
def format_string(template: str, **kwargs: str) -> str:
    """
    Insert passed values at the corresponding placeholders of the specified template.

    In contrast with the regular ``str.format()`` this function computes proper
    indents for the placeholder values.

    Parameters
    ----------
    template : str
        Template to substitute values in.
    **kwargs : dict
        Dictionary that maps placeholder names with values.

    Returns
    -------
    str
        Formated string.
    """
    ...

def align_indents(source: str, target: str) -> str:
    """
    Align indents of two strings.

    Parameters
    ----------
    source : str
        Source string to align indents with.
    target : str
        Target string to align indents.

    Returns
    -------
    str
        Target string with indents aligned with the source.
    """
    ...

def append_to_docstring(message: str) -> Callable[[Fn], Fn]:
    """
    Create a decorator which appends passed message to the function's docstring.

    Parameters
    ----------
    message : str
        Message to append.

    Returns
    -------
    callable
    """
    ...

_docstring_inheritance_calls: list[Callable[[str], None]] = ...
_attributes_with_docstrings_replaced: set[tuple[type, str]] = ...
def expanduser_path_arg(argname: str) -> Callable[[Fn], Fn]:
    """
    Decorate a function replacing its path argument with "user-expanded" value.

    Parameters
    ----------
    argname : str
        Name of the argument which is containing a path to be expanded.

    Returns
    -------
    callable
        Decorator which performs the replacement.
    """
    ...

def func_from_deprecated_location(func_name: str, module: str, deprecation_message: str) -> Callable:
    """
    Create a function that decorates a function ``module.func_name`` with a ``FutureWarning``.

    Parameters
    ----------
    func_name : str
        Function name to decorate.
    module : str
        Module where the function is located.
    deprecation_message : str
        Message to print in a future warning.

    Returns
    -------
    callable
    """
    ...

def hashable(obj: bool) -> bool:
    """
    Return whether the `obj` is hashable.

    Parameters
    ----------
    obj : object
        The object to check.

    Returns
    -------
    bool
    """
    ...

def try_cast_to_pandas(obj: Any, squeeze: bool = ...) -> Any:
    """
    Convert `obj` and all nested objects from Modin to pandas if it is possible.

    If no convertion possible return `obj`.

    Parameters
    ----------
    obj : object
        Object to convert from Modin to pandas.
    squeeze : bool, default: False
        Squeeze the converted object(s) before returning them.

    Returns
    -------
    object
        Converted object.
    """
    ...

def execute(*objs: Iterable[Any]) -> None:
    """
    Trigger the lazy computations for each obj in `objs`, if any, and wait for them to complete.

    Parameters
    ----------
    *objs : Iterable[Any]
        A collection of objects to trigger lazy computations.
    """
    ...

def wrap_into_list(*args: Any, skipna: bool = ...) -> List[Any]:
    """
    Wrap a sequence of passed values in a flattened list.

    If some value is a list by itself the function appends its values
    to the result one by one instead inserting the whole list object.

    Parameters
    ----------
    *args : tuple
        Objects to wrap into a list.
    skipna : bool, default: True
        Whether or not to skip nan or None values.

    Returns
    -------
    list
        Passed values wrapped in a list.
    """
    ...

def wrap_udf_function(func: Callable) -> Callable:
    """
    Create a decorator that makes `func` return pandas objects instead of Modin.

    Parameters
    ----------
    func : callable
        Function to wrap.

    Returns
    -------
    callable
    """
    ...

def get_current_execution() -> str:
    """
    Return current execution name as a string.

    Returns
    -------
    str
        Returns <StorageFormat>On<Engine>-like string.
    """
    ...

def instancer(_class: Callable[[], T]) -> T:
    """
    Create a dummy instance each time this is imported.

    This serves the purpose of allowing us to use all of pandas plotting methods
    without aliasing and writing each of them ourselves.

    Parameters
    ----------
    _class : object

    Returns
    -------
    object
        Instance of `_class`.
    """
    ...

def import_optional_dependency(name: str, message: str) -> types.ModuleType:
    """
    Import an optional dependecy.

    Parameters
    ----------
    name : str
        The module name.
    message : str
        Additional text to include in the ImportError message.

    Returns
    -------
    module : ModuleType
        The imported module.
    """
    ...

def show_versions(as_json: Union[str, bool] = ...) -> None:
    """
    Provide useful information, important for bug reports.

    It comprises info about hosting operation system, pandas version,
    and versions of other installed relative packages.

    Parameters
    ----------
    as_json : str or bool, default: False
        * If False, outputs info in a human readable form to the console.
        * If str, it will be considered as a path to a file.
          Info will be written to that file in JSON format.
        * If True, outputs info in JSON format to the console.

    Notes
    -----
    This is mostly a copy of pandas.show_versions() but adds separate listing
    of Modin-specific dependencies.
    """
    ...

class ModinAssumptionError(Exception):
    """An exception that allows us defaults to pandas if any assumption fails."""
    ...


class classproperty:
    """
    Decorator that allows creating read-only class properties.

    Parameters
    ----------
    func : method

    Examples
    --------
    >>> class A:
    ...     field = 10
    ...     @classproperty
    ...     def field_x2(cls):
    ...             return cls.field * 2
    ...
    >>> print(A.field_x2)
    20
    """
    def __init__(self, func: Any) -> None:
        ...
    
    def __get__(self, instance: Any, owner: Any) -> Any:
        ...
    


def reload_modin() -> None:
    """
    Reload all previously imported Modin modules.

    The call to this function is required
    if an execution engine has been shut down and
    is going to be started up once again.
    """
    ...

