"""
This type stub file was generated by pyright.
"""

from .extensions import register_base_accessor, register_dataframe_accessor, register_dataframe_groupby_accessor, register_pd_accessor, register_series_accessor, register_series_groupby_accessor

__all__ = ["register_base_accessor", "register_dataframe_accessor", "register_series_accessor", "register_pd_accessor", "register_dataframe_groupby_accessor", "register_series_groupby_accessor"]
