from collections.abc import MutableMapping, MutableSet

from .. import etree
from . import defs
from ._setmixin import SetMixin

__all__ = [
    "Element",
    "defs",
    "document_fromstring",
    "find_class",
    "find_rel_links",
    "fragment_fromstring",
    "fragments_fromstring",
    "fromstring",
    "iterlinks",
    "make_links_absolute",
    "open_in_browser",
    "parse",
    "resolve_base_href",
    "rewrite_links",
    "submit_form",
    "tostring",
]
XHTML_NAMESPACE = ...
_rel_links_xpath = ...
_options_xpath = ...
_forms_xpath = ...
_class_xpath = ...
_id_xpath = ...
_collect_string_content = ...
_iter_css_urls = ...
_iter_css_imports = ...
_label_xpath = ...
_archive_re = ...
_parse_meta_refresh_url = ...

class Classes(MutableSet):
    def __init__(self, attributes) -> None: ...
    def add(self, value): ...
    def discard(self, value): ...
    def remove(self, value): ...
    def __contains__(self, name) -> bool: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def update(self, values): ...
    def toggle(self, value): ...

class HtmlMixin:
    def set(self, key, value=...): ...
    @property
    def classes(self): ...
    @classes.setter
    def classes(self, classes): ...
    @property
    def base_url(self): ...
    @property
    def forms(self): ...
    @property
    def body(self): ...
    @property
    def head(self): ...
    @property
    def label(self): ...
    @label.setter
    def label(self, label): ...
    @label.deleter
    def label(self): ...
    def drop_tree(self): ...
    def drop_tag(self): ...
    def find_rel_links(self, rel): ...
    def find_class(self, class_name): ...
    def get_element_by_id(self, id, *default): ...
    def text_content(self): ...
    def cssselect(self, expr, translator=...): ...
    def make_links_absolute(self, base_url=..., resolve_base_href=..., handle_failures=...): ...
    def resolve_base_href(self, handle_failures=...): ...
    def iterlinks(self): ...
    def rewrite_links(self, link_repl_func, resolve_base_href=..., base_href=...): ...

class _MethodFunc:
    def __init__(self, name, copy=..., source_class=...) -> None: ...
    def __call__(self, doc, *args, **kw): ...

find_rel_links = ...
find_class = ...
make_links_absolute = ...
resolve_base_href = ...
iterlinks = ...
rewrite_links = ...

class HtmlComment(HtmlMixin, etree.CommentBase): ...
class HtmlElement(HtmlMixin, etree.ElementBase): ...
class HtmlProcessingInstruction(HtmlMixin, etree.PIBase): ...
class HtmlEntity(HtmlMixin, etree.EntityBase): ...

class HtmlElementClassLookup(etree.CustomElementClassLookup):
    _default_element_classes = ...
    def __init__(self, classes=..., mixins=...) -> None: ...
    def lookup(self, node_type, document, namespace, name): ...

_looks_like_full_html_unicode = ...
_looks_like_full_html_bytes = ...

def document_fromstring(html, parser=..., ensure_head_body=..., **kw): ...
def fragments_fromstring(html, no_leading_text=..., base_url=..., parser=..., **kw): ...
def fragment_fromstring(html, create_parent=..., base_url=..., parser=..., **kw): ...
def fromstring(html, base_url=..., parser=..., **kw): ...
def parse(filename_or_url, parser=..., base_url=..., **kw): ...

class FormElement(HtmlElement):
    @property
    def inputs(self): ...
    @property
    def fields(self): ...
    @fields.setter
    def fields(self, value): ...
    def form_values(self): ...
    @property
    def action(self): ...
    @action.setter
    def action(self, value): ...
    @action.deleter
    def action(self): ...
    @property
    def method(self): ...
    @method.setter
    def method(self, value): ...

def submit_form(form, extra_values=..., open_http=...): ...
def open_http_urllib(method, url, values): ...

class FieldsDict(MutableMapping):
    def __init__(self, inputs) -> None: ...
    def __getitem__(self, item): ...
    def __setitem__(self, item, value) -> None: ...
    def __delitem__(self, item) -> None: ...
    def keys(self): ...
    def __contains__(self, item) -> bool: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...

class InputGetter:
    def __init__(self, form) -> None: ...
    def __getitem__(self, name): ...
    def __contains__(self, name) -> bool: ...
    def keys(self): ...
    def items(self): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...

class InputMixin:
    @property
    def name(self): ...
    @name.setter
    def name(self, value): ...
    @name.deleter
    def name(self): ...

class TextareaElement(InputMixin, HtmlElement):
    @property
    def value(self): ...
    @value.setter
    def value(self, value): ...
    @value.deleter
    def value(self): ...

class SelectElement(InputMixin, HtmlElement):
    @property
    def value(self): ...
    @value.setter
    def value(self, value): ...
    @value.deleter
    def value(self): ...
    @property
    def value_options(self): ...
    @property
    def multiple(self): ...
    @multiple.setter
    def multiple(self, value): ...

class MultipleSelectOptions(SetMixin):
    def __init__(self, select) -> None: ...
    @property
    def options(self): ...
    def __iter__(self): ...
    def add(self, item): ...
    def remove(self, item): ...

class RadioGroup(list):
    @property
    def value(self): ...
    @value.setter
    def value(self, value): ...
    @value.deleter
    def value(self): ...
    @property
    def value_options(self): ...

class CheckboxGroup(list):
    @property
    def value(self): ...
    @value.setter
    def value(self, value): ...
    @value.deleter
    def value(self): ...
    @property
    def value_options(self): ...

class CheckboxValues(SetMixin):
    def __init__(self, group) -> None: ...
    def __iter__(self): ...
    def add(self, value): ...
    def remove(self, value): ...

class InputElement(InputMixin, HtmlElement):
    @property
    def value(self): ...
    @value.setter
    def value(self, value): ...
    @value.deleter
    def value(self): ...
    @property
    def type(self): ...
    @type.setter
    def type(self, value): ...
    @property
    def checkable(self): ...
    @property
    def checked(self): ...
    @checked.setter
    def checked(self, value): ...

class LabelElement(HtmlElement):
    @property
    def for_element(self): ...
    @for_element.setter
    def for_element(self, other): ...
    @for_element.deleter
    def for_element(self): ...

def html_to_xhtml(html): ...
def xhtml_to_html(xhtml): ...

__str_replace_meta_content_type = ...
__bytes_replace_meta_content_type = ...

def tostring(doc, pretty_print=..., include_meta_content_type=..., encoding=..., method=..., with_tail=..., doctype=...): ...
def open_in_browser(doc, encoding=...): ...

class HTMLParser(etree.HTMLParser):
    def __init__(self, **kwargs) -> None: ...

class XHTMLParser(etree.XMLParser):
    def __init__(self, **kwargs) -> None: ...

def Element(*args, **kw): ...

html_parser = ...
xhtml_parser = ...
