from collections.abc import MutableSet

class SetMixin(MutableSet):
    def __len__(self) -> int: ...
    def __contains__(self, item) -> bool: ...

    issubset = ...
    issuperset = ...
    union = ...
    intersection = ...
    difference = ...
    symmetric_difference = ...
    def copy(self): ...
    def update(self, other): ...
    def intersection_update(self, other): ...
    def difference_update(self, other): ...
    def symmetric_difference_update(self, other): ...
    def discard(self, item): ...
