"""
This type stub file was generated by pyright.
"""

from pathlib import Path
from typing import TYPE_CHECKING, Tuple, Union
from typing_extensions import TypeAlias

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    UrlAndCharset: TypeAlias = Tuple[Union[str, Path], str]
_logger = ...
DEFAULT_PLOTLY = ...
DEFAULT_MATHJAX = ...
KJS_PATH = ...
class PageGenerator:
    """
    A page generator can set the versions of the js libraries used to render.

    It does this by outputting the HTML used to render the plotly figures.
    """
    header = ...
    footer = ...
    def __init__(self, *, plotly: None | Path | str | UrlAndCharset = ..., mathjax: None | Path | str | bool | UrlAndCharset = ..., others: None | list[Path | str | UrlAndCharset] = ..., force_cdn: bool = ...) -> None:
        """
        Create a PageGenerator.

        Args:
            plotly: The url to the plotly.js to use. Defaults to plotly.js
                present in plotly.py, if installed. Otherwise fallback to
                value of DEFAULT_PLOTLY.
            mathjax: The url to the mathjax script. Defaults to values of
                DEFAULT_MATHJAX. Can be set to false to disable mathjax.
            others: A list of other script urls to include. Usually strings, but
                can be (str, str) where it's (url, encoding).
            force_cdn: Set True to force CDN use, defaults to False.

        """
        ...
    
    def generate_index(self):
        """Generate the page."""
        ...
    


