from collections.abc import Coroutine, Generator
from functools import wraps
from typing import Any, Protocol, TypeVar, runtime_checkable

from ._connection import SnowflakeConnection
from ._cursor import DictCursor, SnowflakeCursor

__all__ = [SnowflakeConnection, SnowflakeCursor, DictCursor]
T = TypeVar("T")

@runtime_checkable
class HybridCoroutineContextManager(Protocol[T]):
    def send(self, __arg: Any) -> Any: ...
    def throw(self, __typ: type[BaseException], __val: BaseException | None = ..., __tb: Any = ...) -> Any: ...
    def close(self) -> None: ...
    def __await__(self) -> Generator[Any, None, T]: ...
    def __iter__(self) -> Generator[Any, None, T]: ...
    async def __aenter__(self) -> T: ...
    async def __aexit__(self, __exc_type: type[BaseException] | None, __exc_val: BaseException | None, __exc_tb: Any) -> bool | None: ...

class _AsyncConnectContextManager(HybridCoroutineContextManager[SnowflakeConnection]):
    __slots__ = ...
    def __init__(self, coro: Coroutine[Any, Any, SnowflakeConnection]) -> None: ...
    def send(self, arg: Any) -> Any: ...
    def throw(self, *args: Any, **kwargs: Any) -> Any: ...
    def close(self) -> None: ...
    def __await__(self) -> Generator[Any, None, SnowflakeConnection]: ...
    def __iter__(self) -> Generator[Any, None, SnowflakeConnection]: ...
    async def __aenter__(self) -> SnowflakeConnection: ...
    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...

@wraps(SnowflakeConnection.__init__)
def connect(**kwargs: Any) -> HybridCoroutineContextManager[SnowflakeConnection]: ...
