from typing import TYPE_CHECKING

from snowflake.connector.aio import SnowflakeCursor
from snowflake.connector.bind_upload_agent import BindUploadAgent as BindUploadAgentSync

if TYPE_CHECKING: ...
logger = ...

class BindUploadAgent(BindUploadAgentSync):
    def __init__(self, cursor: SnowflakeCursor, rows: list[bytes], stream_buffer_size: int = ...) -> None: ...
    async def upload(self) -> None: ...
