import pathlib
import sys
import uuid
from collections.abc import AsyncIterator, Iterable
from io import StringIO
from types import TracebackType
from typing import Any, Self, TypeVar

from ..connection import SnowflakeConnection as SnowflakeConnectionSync
from ..constants import QueryStatus
from ._cursor import SnowflakeCursor, SnowflakeCursorBase
from ._network import SnowflakeRestful
from .auth import AuthByPlugin

logger = ...
DEFAULT_CONFIGURATION = ...
if sys.version_info >= (3, 13) or typing.TYPE_CHECKING:
    CursorCls = TypeVar("CursorCls", bound=SnowflakeCursorBase, default=SnowflakeCursor)
else: ...

class SnowflakeConnection(SnowflakeConnectionSync):
    OCSP_ENV_LOCK = ...
    def __init__(self, connection_name: str | None = ..., connections_file_path: pathlib.Path | None = ..., **kwargs) -> None: ...
    @property
    async def snowflake_version(self) -> str: ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None
    ) -> None: ...
    @property
    def auth_class(self) -> AuthByPlugin | None: ...
    @auth_class.setter
    def auth_class(self, value: AuthByPlugin) -> None: ...
    @property
    def client_prefetch_threads(self) -> int: ...
    @client_prefetch_threads.setter
    def client_prefetch_threads(self, value) -> None: ...
    @property
    def errorhandler(self) -> None: ...
    @errorhandler.setter
    def errorhandler(self, value) -> None: ...
    @property
    def rest(self) -> SnowflakeRestful | None: ...
    async def authenticate_with_retry(self, auth_instance) -> None: ...
    async def autocommit(self, mode) -> None: ...
    async def close(self, retry: bool = ...) -> None: ...
    async def cmd_query(
        self,
        sql: str,
        sequence_counter: int,
        request_id: uuid.UUID,
        binding_params: None | tuple | dict[str, dict[str, str]] = ...,
        binding_stage: str | None = ...,
        is_file_transfer: bool = ...,
        statement_params: dict[str, str] | None = ...,
        is_internal: bool = ...,
        describe_only: bool = ...,
        _no_results: bool = ...,
        _update_current_object: bool = ...,
        _no_retry: bool = ...,
        timeout: int | None = ...,
        dataframe_ast: str | None = ...,
    ) -> dict[str, Any]: ...
    async def commit(self) -> None: ...
    async def connect(self, **kwargs) -> None: ...
    def cursor(self, cursor_class: type[CursorCls] = ...) -> CursorCls: ...
    async def execute_stream(
        self, stream: StringIO, remove_comments: bool = ..., cursor_class: type[SnowflakeCursor] = ..., **kwargs
    ) -> AsyncIterator[SnowflakeCursor, None, None]: ...
    async def execute_string(
        self, sql_text: str, remove_comments: bool = ..., return_cursors: bool = ..., cursor_class: type[SnowflakeCursor] = ..., **kwargs
    ) -> Iterable[SnowflakeCursor]: ...
    async def get_query_status(self, sf_qid: str) -> QueryStatus: ...
    async def get_query_status_throw_if_error(self, sf_qid: str) -> QueryStatus: ...
    @staticmethod
    async def setup_ocsp_privatelink(app, hostname) -> None: ...
    async def rollback(self) -> None: ...
    async def is_valid(self) -> bool: ...
