import abc
import typing
from collections.abc import AsyncIterator, Sequence
from types import TracebackType
from typing import IO, TYPE_CHECKING, Any, Literal, Self, overload

from pandas import DataFrame
from pyarrow import Table
from snowflake.connector.aio import SnowflakeConnection
from snowflake.connector.aio._result_batch import ResultBatch
from snowflake.connector.cursor import ResultMetadata, T
from snowflake.connector.cursor import SnowflakeCursorBase as SnowflakeCursorBaseSync
from snowflake.connector.file_transfer_agent import SnowflakeProgressPercentage

if TYPE_CHECKING: ...
logger = ...
FetchRow = typing.TypeVar("FetchRow", bound=tuple[Any, ...] | dict[str, Any])

class SnowflakeCursorBase[FetchRow: tuple[Any, ...] | dict[str, Any]](SnowflakeCursorBaseSync, abc.ABC):
    def __init__(self, connection: SnowflakeConnection) -> None: ...
    def __aiter__(self): ...
    def __iter__(self): ...
    async def __anext__(self): ...
    async def __aenter__(self): ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_tb): ...
    def __del__(self) -> None: ...
    async def __aexit__(
        self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None
    ) -> None: ...
    async def abort_query(self, qid: str) -> bool: ...
    @overload
    async def callproc(self, procname: str) -> tuple: ...
    @overload
    async def callproc(self, procname: str, args: T) -> T: ...
    async def callproc(self, procname: str, args=...): ...
    @property
    def connection(self) -> SnowflakeConnection: ...
    async def close(self): ...
    async def execute(
        self,
        command: str,
        params: Sequence[Any] | dict[Any, Any] | None = ...,
        _bind_stage: str | None = ...,
        timeout: int | None = ...,
        _exec_async: bool = ...,
        _no_retry: bool = ...,
        _do_reset: bool = ...,
        _put_callback: SnowflakeProgressPercentage = ...,
        _put_azure_callback: SnowflakeProgressPercentage = ...,
        _put_callback_output_stream: IO[str] = ...,
        _get_callback: SnowflakeProgressPercentage = ...,
        _get_azure_callback: SnowflakeProgressPercentage = ...,
        _get_callback_output_stream: IO[str] = ...,
        _show_progress_bar: bool = ...,
        _statement_params: dict[str, str] | None = ...,
        _is_internal: bool = ...,
        _describe_only: bool = ...,
        _no_results: bool = ...,
        _is_put_get: bool | None = ...,
        _raise_put_get_error: bool = ...,
        _force_put_overwrite: bool = ...,
        _skip_upload_on_content_match: bool = ...,
        file_stream: IO[bytes] | None = ...,
        num_statements: int | None = ...,
        _force_qmark_paramstyle: bool = ...,
        _dataframe_ast: str | None = ...,
    ) -> Self | dict[str, Any] | None: ...
    async def executemany(self, command: str, seqparams: Sequence[Any] | dict[str, Any], **kwargs: Any) -> SnowflakeCursor: ...
    async def execute_async(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    @property
    def errorhandler(self): ...
    @errorhandler.setter
    def errorhandler(self, value): ...
    async def describe(self, *args: Any, **kwargs: Any) -> list[ResultMetadata]: ...
    @abc.abstractmethod
    async def fetchone(self) -> FetchRow: ...
    async def fetchmany(self, size: int | None = ...) -> list[FetchRow]: ...
    async def fetchall(self) -> list[tuple] | list[dict]: ...
    async def fetch_arrow_batches(self) -> AsyncIterator[Table]: ...
    @overload
    async def fetch_arrow_all(self, force_return_table: Literal[False]) -> Table | None: ...
    @overload
    async def fetch_arrow_all(self, force_return_table: Literal[True]) -> Table: ...
    async def fetch_arrow_all(self, force_return_table: bool = ...) -> Table | None: ...
    async def fetch_pandas_batches(self, **kwargs: Any) -> AsyncIterator[DataFrame]: ...
    async def fetch_pandas_all(self, **kwargs: Any) -> DataFrame: ...
    async def nextset(self) -> SnowflakeCursor | None: ...
    async def get_result_batches(self) -> list[ResultBatch] | None: ...
    async def get_results_from_sfqid(self, sfqid: str) -> None: ...
    async def query_result(self, qid: str) -> SnowflakeCursor: ...

class SnowflakeCursor(SnowflakeCursorBase[tuple[Any, ...]]):
    async def fetchone(self) -> tuple[Any, ...] | None: ...

class DictCursor(SnowflakeCursorBase[dict[str, Any]]):
    async def fetchone(self) -> dict[str, Any] | None: ...
