from abc import ABC, abstractmethod
from typing import TYPE_CHECKING

from ._connection import SnowflakeConnection

if TYPE_CHECKING: ...

class FileOperationParserBase(ABC):
    @abstractmethod
    def __init__(self, connection) -> None: ...
    @abstractmethod
    async def parse_file_operation(
        self, stage_location, local_file_name, target_directory, command_type, options, has_source_from_stream=...
    ):  # -> None:

        ...

class StreamDownloaderBase(ABC):
    @abstractmethod
    def __init__(self, connection) -> None: ...
    @abstractmethod
    async def download_as_stream(self, ret, decompress=...):  # -> None:
        ...

class FileOperationParser(FileOperationParserBase):
    def __init__(self, connection: SnowflakeConnection) -> None: ...
    async def parse_file_operation(
        self, stage_location, local_file_name, target_directory, command_type, options, has_source_from_stream=...
    ):  # -> dict[str, Any]:

        ...

class StreamDownloader(StreamDownloaderBase):
    def __init__(self, connection) -> None: ...
    async def download_as_stream(self, ret, decompress=...): ...
