from abc import abstractmethod
from typing import TYPE_CHECKING, Any

from ..constants import FileHeader
from ..file_transfer_agent import SnowflakeFileMeta, StorageCredential
from ..storage_client import SnowflakeStorageClient as SnowflakeStorageClientSync

if TYPE_CHECKING: ...
logger = ...

class SnowflakeStorageClient(SnowflakeStorageClientSync):
    TRANSIENT_ERRORS = ...
    def __init__(
        self,
        meta: SnowflakeFileMeta,
        stage_info: dict[str, Any],
        chunk_size: int,
        chunked_transfer: bool | None = ...,
        credentials: StorageCredential | None = ...,
        max_retry: int = ...,
        unsafe_file_write: bool = ...,
    ) -> None: ...
    @abstractmethod
    async def get_file_header(self, filename: str) -> FileHeader | None: ...
    async def preprocess(self) -> None: ...
    async def prepare_upload(self) -> None: ...
    async def finish_upload(self) -> None: ...
    async def finish_download(self) -> None: ...
    async def prepare_download(self) -> None: ...
    async def upload_chunk(self, chunk_id: int) -> None: ...
    @abstractmethod
    async def download_chunk(self, chunk_id: int) -> None: ...
