from typing import TYPE_CHECKING

from ..telemetry import TelemetryClient as TelemetryClientSync
from ..telemetry import TelemetryData
from ._network import SnowflakeRestful

if TYPE_CHECKING: ...
logger = ...

class TelemetryClient(TelemetryClientSync):
    def __init__(self, rest: SnowflakeRestful, flush_size=...) -> None: ...
    async def add_log_to_batch(self, telemetry_data: TelemetryData) -> None: ...
    async def send_batch(self, retry: bool = ...) -> None: ...
    async def try_add_log_to_batch(self, telemetry_data: TelemetryData) -> None: ...
    async def close(self, retry: bool = ...) -> None: ...
