from collections.abc import Callable

from ..time_util import TimerContextManager as TimerContextManagerSync

logger = ...

class HeartBeatTimer:
    def __init__(self, client_session_keep_alive_heartbeat_frequency: int, f: Callable) -> None: ...
    async def run(self) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...

class TimerContextManager(TimerContextManagerSync):
    async def __aenter__(self):  # -> TimerContextManager:
        ...
    async def __aexit__(self, exc_type, exc_val, exc_tb):  # -> None:
        ...
