from ..wif_util import AttestationProvider, WorkloadIdentityAttestation
from ._session_manager import SessionManager

logger = ...
GCP_METADATA_SERVICE_ACCOUNT_BASE_URL = ...

async def get_aws_region() -> str: ...
async def get_aws_session(impersonation_path: list[str] | None = ...): ...
async def create_aws_attestation(impersonation_path: list[str] | None = ...) -> WorkloadIdentityAttestation: ...
async def get_gcp_access_token(session_manager: SessionManager) -> str: ...
async def get_gcp_identity_token_via_impersonation(impersonation_path: list[str], session_manager: SessionManager) -> str: ...
async def get_gcp_identity_token(session_manager: SessionManager) -> str: ...
async def create_gcp_attestation(
    session_manager: SessionManager, impersonation_path: list[str] | None = ...
) -> WorkloadIdentityAttestation: ...
async def create_azure_attestation(
    snowflake_entra_resource: str, session_manager: SessionManager | None = ...
) -> WorkloadIdentityAttestation: ...
async def create_attestation(
    provider: AttestationProvider | None,
    entra_resource: str | None = ...,
    token: str | None = ...,
    impersonation_path: list[str] | None = ...,
    session_manager: SessionManager | None = ...,
) -> WorkloadIdentityAttestation: ...
