from contextlib import contextmanager

"""
The Device Array API is not implemented in the simulator. This module provides
stubs to allow tests to import correctly.
"""
DeviceRecord = ...
from_record_like = ...
errmsg_contiguous_buffer = ...

class FakeShape(tuple):
    def __getitem__(self, k): ...

class FakeWithinKernelCUDAArray:
    def __init__(self, item) -> None: ...
    def __getattr__(self, attrname):  # -> FakeWithinKernelCUDAArray | None:
        ...
    def __setattr__(self, nm, val) -> None:  # -> None:
        ...
    def __getitem__(self, idx):  # -> FakeWithinKernelCUDAArray:
        ...
    def __setitem__(self, idx, val) -> None:  # -> None:
        ...
    def __len__(self) -> int:  # -> int:
        ...
    def __array_ufunc__(self, ufunc, method, *args, **kwargs):  # -> Any:
        ...

class FakeCUDAArray:
    __cuda_ndarray__ = ...
    def __init__(self, ary, stream=...) -> None: ...
    @property
    def alloc_size(self): ...
    @property
    def nbytes(self): ...
    def __getattr__(self, attrname):  # -> Any:
        ...
    def bind(self, stream=...):  # -> FakeCUDAArray:
        ...
    @property
    def T(self):  # -> FakeCUDAArray:
        ...
    def transpose(self, axes=...):  # -> FakeCUDAArray:
        ...
    def __getitem__(self, idx):  # -> FakeCUDAArray:
        ...
    def __setitem__(self, idx, val) -> None: ...
    def copy_to_host(self, ary=..., stream=...):  # -> Any:
        ...
    def copy_to_device(self, ary, stream=...):  # -> None:

        ...
    @property
    def shape(self):  # -> FakeShape:
        ...
    def ravel(self, *args, **kwargs):  # -> FakeCUDAArray:
        ...
    def reshape(self, *args, **kwargs):  # -> FakeCUDAArray:
        ...
    def view(self, *args, **kwargs):  # -> FakeCUDAArray:
        ...
    def is_c_contiguous(self): ...
    def is_f_contiguous(self): ...
    def __len__(self) -> int:  # -> int:
        ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __lt__(self, other) -> bool: ...
    def __le__(self, other) -> bool: ...
    def __gt__(self, other) -> bool: ...
    def __ge__(self, other) -> bool: ...
    def __add__(self, other):  # -> FakeCUDAArray:
        ...
    def __sub__(self, other):  # -> FakeCUDAArray:
        ...
    def __mul__(self, other):  # -> FakeCUDAArray:
        ...
    def __floordiv__(self, other):  # -> FakeCUDAArray:
        ...
    def __truediv__(self, other):  # -> FakeCUDAArray:
        ...
    def __mod__(self, other):  # -> FakeCUDAArray:
        ...
    def __pow__(self, other):  # -> FakeCUDAArray:
        ...
    def split(self, section, stream=...):  # -> list[FakeCUDAArray]:
        ...

def array_core(ary): ...
def is_contiguous(ary):  # -> bool:

    ...
def sentry_contiguous(ary):  # -> None:
    ...
def check_array_compatibility(ary1, ary2):  # -> None:
    ...
def to_device(ary, stream=..., copy=..., to=...):  # -> FakeCUDAArray | None:
    ...
@contextmanager
def pinned(arg):  # -> Generator[None, Any, None]:
    ...
def mapped_array(*args, **kwargs):  # -> FakeCUDAArray:
    ...
def pinned_array(shape, dtype=..., strides=..., order=...):  # -> ndarray[_AnyShape, dtype[Any]]:
    ...
def managed_array(shape, dtype=..., strides=..., order=...):  # -> ndarray[_AnyShape, dtype[Any]]:
    ...
def device_array(*args, **kwargs):  # -> FakeCUDAArray:
    ...
def device_array_like(ary, stream=...):  # -> FakeCUDAArray:
    ...
def pinned_array_like(ary):  # -> ndarray[_AnyShape, dtype[Any]]:
    ...
def auto_device(ary, stream=..., copy=...):  # -> tuple[FakeCUDAArray, Literal[False]] | tuple[FakeCUDAArray | None, Literal[True]]:
    ...
def is_cuda_ndarray(obj):  # -> Any | bool:

    ...
def verify_cuda_ndarray_interface(obj):  # -> None:

    ...
def require_cuda_ndarray(obj):  # -> None:

    ...
