_MemoryInfo = ...
_SIMULATOR_CC = ...

class FakeCUDADevice:
    def __init__(self) -> None: ...
    @property
    def compute_capability(self):  # -> tuple[Literal[5], Literal[2]]:
        ...

class FakeCUDAContext:
    def __init__(self, device_id) -> None: ...
    def __enter__(self):  # -> None:
        ...
    def __exit__(self, exc_type, exc_val, exc_tb):  # -> None:
        ...
    @property
    def id(self):  # -> Any:
        ...
    @property
    def device(self):  # -> FakeCUDADevice:
        ...
    @property
    def compute_capability(self):  # -> tuple[Literal[5], Literal[2]]:
        ...
    def reset(self):  # -> None:
        ...
    def get_memory_info(self):  # -> _MemoryInfo:

        ...
    def memalloc(self, sz):  # -> ndarray[_AnyShape, dtype[Any]]:

        ...
    def memhostalloc(self, sz, mapped=..., portable=..., wc=...):  # -> ndarray[_AnyShape, dtype[Any]]:

        ...

class FakeDeviceList:
    def __init__(self) -> None: ...
    def __getitem__(self, devnum): ...
    def __iter__(self):  # -> Iterator[FakeCUDAContext]:
        ...
    def __len__(self) -> int:  # -> int:
        ...
    @property
    def current(self):  # -> FakeCUDAContext | None:
        ...

gpus = ...

def reset():  # -> None:
    ...
def get_context(devnum=...):  # -> FakeCUDAContext:
    ...
def require_context(func): ...
