def device_memset(dst, val, size, stream=...):  # -> None:
    ...
def host_to_device(dst, src, size, stream=...):  # -> None:
    ...
def device_to_host(dst, src, size, stream=...):  # -> None:
    ...
def device_memory_size(obj): ...
def device_to_device(dst, src, size, stream=...):  # -> None:
    ...

class FakeDriver:
    def get_device_count(self):  # -> Literal[1]:
        ...

driver = ...

class Linker:
    @classmethod
    def new(cls, max_registers=..., lineinfo=..., cc=...):  # -> Linker:
        ...
    @property
    def lto(self):  # -> Literal[False]:
        ...

class LinkerError(RuntimeError): ...
class NvrtcError(RuntimeError): ...
class CudaAPIError(RuntimeError): ...

def launch_kernel(*args, **kwargs): ...

USE_NV_BINDING = ...
