class NvvmSupportError(ImportError): ...

class NVVM:
    def __init__(self) -> None: ...

CompilationUnit = ...
compile_ir = ...
set_cuda_kernel = ...
get_arch_option = ...
LibDevice = ...
NvvmError = ...

def is_available():  # -> Literal[False]:
    ...
def get_supported_ccs():  # -> tuple[()]:
    ...
