class FakeRuntime:
    def get_version(self):  # -> tuple[Literal[-1], Literal[-1]]:
        ...
    def is_supported_version(self):  # -> Literal[True]:
        ...
    @property
    def supported_versions(self):  # -> tuple[tuple[int, int]]:
        ...

runtime = ...
