name: "Test"

on:
  push:
    branches: [ "main", "master" ]

  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os:
          - 'ubuntu-latest'
        python-version:
          - '3.12'
          - '3.13'

    runs-on: '{% raw %}${{ matrix.os }}{% endraw %}'

    steps:
      - uses: actions/checkout@v4


      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Lint with ruff
        run: ruff check

      - name: Run tests
        run: uv run pytest
