"""
This type stub file was generated by pyright.
"""

from _typeshed import SupportsItems, SupportsRead, Unused
from collections.abc import Callable, Iterable, Mapping, MutableMapping
from typing import Any, TypedDict, type_check_only
from typing_extensions import Self, TypeAlias
from . import adapters, auth as _auth, cookies, exceptions, hooks, models, status_codes
from .models import Response, _JSON

"""
This type stub file was generated by pyright.
"""
_BaseAdapter: TypeAlias = adapters.BaseAdapter
OrderedDict = ...
cookiejar_from_dict = ...
extract_cookies_to_jar = ...
RequestsCookieJar = cookies.RequestsCookieJar
merge_cookies = ...
Request = models.Request
PreparedRequest = models.PreparedRequest
DEFAULT_REDIRECT_LIMIT = models.DEFAULT_REDIRECT_LIMIT
default_hooks = ...
dispatch_hook = ...
to_key_val_list = ...
default_headers = ...
to_native_string = ...
TooManyRedirects = exceptions.TooManyRedirects
InvalidSchema = exceptions.InvalidSchema
ChunkedEncodingError = exceptions.ChunkedEncodingError
ContentDecodingError = exceptions.ContentDecodingError
HTTPAdapter = adapters.HTTPAdapter
requote_uri = ...
get_environ_proxies = ...
get_netrc_auth = ...
should_bypass_proxies = ...
get_auth_from_url = ...
codes = status_codes.codes
REDIRECT_STATI = models.REDIRECT_STATI
def preferred_clock() -> float:
    ...

def merge_setting(request_setting, session_setting, dict_class=...):
    ...

def merge_hooks(request_hooks, session_hooks, dict_class=...):
    ...

class SessionRedirectMixin:
    def resolve_redirects(self, resp, req, stream: bool = ..., timeout=..., verify: bool = ..., cert=..., proxies=..., yield_requests: bool = ..., **adapter_kwargs):
        ...
    
    def rebuild_auth(self, prepared_request, response):
        ...
    
    def rebuild_proxies(self, prepared_request, proxies):
        ...
    
    def should_strip_auth(self, old_url, new_url):
        ...
    
    def rebuild_method(self, prepared_request: PreparedRequest, response: Response) -> None:
        ...
    
    def get_redirect_target(self, resp: Response) -> str | None:
        ...
    


_Data: TypeAlias = (Iterable[bytes] | str | bytes | SupportsRead[str | bytes] | list[tuple[Any, Any]] | tuple[tuple[Any, Any], ...] | Mapping[Any, Any])
_Auth: TypeAlias = tuple[str, str] | _auth.AuthBase | Callable[[PreparedRequest], PreparedRequest]
_Cert: TypeAlias = str | tuple[str, str]
_FileName: TypeAlias = str | None
_FileContent: TypeAlias = SupportsRead[str | bytes] | str | bytes
_FileContentType: TypeAlias = str
_FileCustomHeaders: TypeAlias = Mapping[str, str]
_FileSpecTuple2: TypeAlias = tuple[_FileName, _FileContent]
_FileSpecTuple3: TypeAlias = tuple[_FileName, _FileContent, _FileContentType]
_FileSpecTuple4: TypeAlias = tuple[_FileName, _FileContent, _FileContentType, _FileCustomHeaders]
_FileSpec: TypeAlias = _FileContent | _FileSpecTuple2 | _FileSpecTuple3 | _FileSpecTuple4
_Files: TypeAlias = Mapping[str, _FileSpec] | Iterable[tuple[str, _FileSpec]]
_Hook: TypeAlias = Callable[[Response], Any]
_HooksInput: TypeAlias = Mapping[str, Iterable[_Hook] | _Hook]
_ParamsMappingKeyType: TypeAlias = str | bytes | int | float
_ParamsMappingValueType: TypeAlias = str | bytes | int | float | Iterable[str | bytes | int | float] | None
_Params: TypeAlias = (SupportsItems[_ParamsMappingKeyType, _ParamsMappingValueType] | tuple[_ParamsMappingKeyType, _ParamsMappingValueType] | Iterable[tuple[_ParamsMappingKeyType, _ParamsMappingValueType]] | str | bytes)
_TextMapping: TypeAlias = MutableMapping[str, str]
_HeadersUpdateMapping: TypeAlias = Mapping[str, str | bytes | None]
_Timeout: TypeAlias = float | tuple[float | None, float | None]
_Verify: TypeAlias = bool | str
@type_check_only
class _Settings(TypedDict):
    verify: _Verify | None
    proxies: _TextMapping
    stream: bool
    cert: _Cert | None
    ...


class Session(SessionRedirectMixin):
    __attrs__: Any
    headers: MutableMapping[str, str | bytes]
    auth: _Auth | None
    proxies: _TextMapping
    hooks: dict[str, list[_Hook] | Any]
    params: _Params
    stream: bool
    verify: _Verify | None
    cert: _Cert | None
    max_redirects: int
    trust_env: bool
    cookies: RequestsCookieJar
    adapters: MutableMapping[str, adapters.BaseAdapter]
    def __init__(self) -> None:
        ...
    
    def __enter__(self) -> Self:
        ...
    
    def __exit__(self, *args: Unused) -> None:
        ...
    
    def prepare_request(self, request: Request) -> PreparedRequest:
        ...
    
    def request(self, method: str | bytes, url: str | bytes, params: _Params | None = ..., data: _Data | None = ..., headers: _HeadersUpdateMapping | None = ..., cookies: None | RequestsCookieJar | _TextMapping = ..., files: _Files | None = ..., auth: _Auth | None = ..., timeout: _Timeout | None = ..., allow_redirects: bool = ..., proxies: _TextMapping | None = ..., hooks: _HooksInput | None = ..., stream: bool | None = ..., verify: _Verify | None = ..., cert: _Cert | None = ..., json: _JSON | None = ...) -> Response:
        ...
    
    def get(self, url: str | bytes, *, params: _Params | None = ..., data: _Data | None = ..., headers: _HeadersUpdateMapping | None = ..., cookies: RequestsCookieJar | _TextMapping | None = ..., files: _Files | None = ..., auth: _Auth | None = ..., timeout: _Timeout | None = ..., allow_redirects: bool = ..., proxies: _TextMapping | None = ..., hooks: _HooksInput | None = ..., stream: bool | None = ..., verify: _Verify | None = ..., cert: _Cert | None = ..., json: _JSON | None = ...) -> Response:
        ...
    
    def options(self, url: str | bytes, *, params: _Params | None = ..., data: _Data | None = ..., headers: _HeadersUpdateMapping | None = ..., cookies: RequestsCookieJar | _TextMapping | None = ..., files: _Files | None = ..., auth: _Auth | None = ..., timeout: _Timeout | None = ..., allow_redirects: bool = ..., proxies: _TextMapping | None = ..., hooks: _HooksInput | None = ..., stream: bool | None = ..., verify: _Verify | None = ..., cert: _Cert | None = ..., json: _JSON | None = ...) -> Response:
        ...
    
    def head(self, url: str | bytes, *, params: _Params | None = ..., data: _Data | None = ..., headers: _HeadersUpdateMapping | None = ..., cookies: RequestsCookieJar | _TextMapping | None = ..., files: _Files | None = ..., auth: _Auth | None = ..., timeout: _Timeout | None = ..., allow_redirects: bool = ..., proxies: _TextMapping | None = ..., hooks: _HooksInput | None = ..., stream: bool | None = ..., verify: _Verify | None = ..., cert: _Cert | None = ..., json: _JSON | None = ...) -> Response:
        ...
    
    def post(self, url: str | bytes, data: _Data | None = ..., json: _JSON | None = ..., *, params: _Params | None = ..., headers: _HeadersUpdateMapping | None = ..., cookies: RequestsCookieJar | _TextMapping | None = ..., files: _Files | None = ..., auth: _Auth | None = ..., timeout: _Timeout | None = ..., allow_redirects: bool = ..., proxies: _TextMapping | None = ..., hooks: _HooksInput | None = ..., stream: bool | None = ..., verify: _Verify | None = ..., cert: _Cert | None = ...) -> Response:
        ...
    
    def put(self, url: str | bytes, data: _Data | None = ..., *, params: _Params | None = ..., headers: _HeadersUpdateMapping | None = ..., cookies: RequestsCookieJar | _TextMapping | None = ..., files: _Files | None = ..., auth: _Auth | None = ..., timeout: _Timeout | None = ..., allow_redirects: bool = ..., proxies: _TextMapping | None = ..., hooks: _HooksInput | None = ..., stream: bool | None = ..., verify: _Verify | None = ..., cert: _Cert | None = ..., json: _JSON | None = ...) -> Response:
        ...
    
    def patch(self, url: str | bytes, data: _Data | None = ..., *, params: _Params | None = ..., headers: _HeadersUpdateMapping | None = ..., cookies: RequestsCookieJar | _TextMapping | None = ..., files: _Files | None = ..., auth: _Auth | None = ..., timeout: _Timeout | None = ..., allow_redirects: bool = ..., proxies: _TextMapping | None = ..., hooks: _HooksInput | None = ..., stream: bool | None = ..., verify: _Verify | None = ..., cert: _Cert | None = ..., json: _JSON | None = ...) -> Response:
        ...
    
    def delete(self, url: str | bytes, *, params: _Params | None = ..., data: _Data | None = ..., headers: _HeadersUpdateMapping | None = ..., cookies: RequestsCookieJar | _TextMapping | None = ..., files: _Files | None = ..., auth: _Auth | None = ..., timeout: _Timeout | None = ..., allow_redirects: bool = ..., proxies: _TextMapping | None = ..., hooks: _HooksInput | None = ..., stream: bool | None = ..., verify: _Verify | None = ..., cert: _Cert | None = ..., json: _JSON | None = ...) -> Response:
        ...
    
    def send(self, request: PreparedRequest, *, stream: bool | None = ..., verify: _Verify | None = ..., proxies: _TextMapping | None = ..., cert: _Cert | None = ..., timeout: _Timeout | None = ..., allow_redirects: bool = ..., **kwargs: Any) -> Response:
        ...
    
    def merge_environment_settings(self, url: str | bytes | None, proxies: _TextMapping | None, stream: bool | None, verify: _Verify | None, cert: _Cert | None) -> _Settings:
        ...
    
    def get_adapter(self, url: str) -> _BaseAdapter:
        ...
    
    def close(self) -> None:
        ...
    
    def mount(self, prefix: str | bytes, adapter: _BaseAdapter) -> None:
        ...
    


def session() -> Session:
    ...

