import wsgiref.simple_server

_LOGGER = ...

class Flow:
    def __init__(
        self, oauth2session, client_type, client_config, redirect_uri=..., code_verifier=..., autogenerate_code_verifier=...
    ) -> None: ...
    @classmethod
    def from_client_config(cls, client_config, scopes, **kwargs): ...
    @classmethod
    def from_client_secrets_file(cls, client_secrets_file, scopes, **kwargs): ...
    @property
    def redirect_uri(self): ...
    @redirect_uri.setter
    def redirect_uri(self, value): ...
    def authorization_url(self, **kwargs): ...
    def fetch_token(self, **kwargs): ...
    @property
    def credentials(self): ...
    def authorized_session(self): ...

class InstalledAppFlow(Flow):
    _DEFAULT_AUTH_PROMPT_MESSAGE = ...
    _DEFAULT_AUTH_CODE_MESSAGE = ...
    _DEFAULT_WEB_SUCCESS_MESSAGE = ...
    def run_local_server(
        self,
        host=...,
        bind_addr=...,
        port=...,
        authorization_prompt_message=...,
        success_message=...,
        open_browser=...,
        redirect_uri_trailing_slash=...,
        timeout_seconds=...,
        token_audience=...,
        browser=...,
        **kwargs,
    ): ...

class _WSGIRequestHandler(wsgiref.simple_server.WSGIRequestHandler):
    def log_message(self, format, *args): ...

class _RedirectWSGIApp:
    def __init__(self, success_message) -> None: ...
    def __call__(self, environ, start_response): ...

class WSGITimeoutError(AttributeError): ...
