LOCALHOST = ...
DEFAULT_PORTS_TO_TRY = ...

def is_port_open(port): ...
def find_open_port(start=..., stop=...): ...
def get_user_credentials(scopes, client_id, client_secret, minimum_port=..., maximum_port=...): ...
