from _typeshed import Incomplete
from mayutils.environment.logging import Logger as Logger
from pathlib import Path
from tomlkit import TOMLDocument as TOMLDocument

logger: Incomplete

def bump_version_string(version: str, bump: str) -> str: ...
def find_pyproject(pyproject_path: Path) -> TOMLDocument: ...
def update_pyproject_version(
    pyproject: TOMLDocument, bump: str
) -> tuple[TOMLDocument, str]: ...
def get_init_file_path(pyproject: TOMLDocument) -> Path: ...
def update_init_version(init_file_path: Path, new_version: str) -> None: ...
def git_update(init_file_path: Path, new_version: str) -> None: ...
def bump() -> None: ...
