from numba.core.compiler_lock import global_compiler_lock
from setuptools.extension import Extension

dir_util = ...
log = ...
extension_libs = ...

class CC:
    _mixin_sources = ...
    _extra_cflags = ...
    _extra_ldflags = ...
    def __init__(self, extension_name, source_module=...) -> None: ...
    @property
    def name(self): ...
    @property
    def output_file(self): ...
    @output_file.setter
    def output_file(self, value):  # -> None:
        ...
    @property
    def output_dir(self):  # -> Any:

        ...
    @output_dir.setter
    def output_dir(self, value):  # -> None:
        ...
    @property
    def use_nrt(self):  # -> bool:
        ...
    @use_nrt.setter
    def use_nrt(self, value):  # -> None:
        ...
    @property
    def target_cpu(self):  # -> str:

        ...
    @target_cpu.setter
    def target_cpu(self, value):  # -> None:
        ...
    @property
    def verbose(self):  # -> bool:

        ...
    @verbose.setter
    def verbose(self, value):  # -> None:
        ...
    def export(self, exported_name, sig):  # -> Callable[..., Any]:

        ...
    @global_compiler_lock
    def compile(self):  # -> None:

        ...
    def distutils_extension(self, **kwargs):  # -> _CCExtension:

        ...

class _CCExtension(Extension):
    _cc = ...
    _distutils_monkey_patched = ...
    @classmethod
    def monkey_patch_distutils(cls) -> None:  # -> None:

        ...
