logger = ...
__all__ = ["ModuleCompiler"]
NULL = ...
ZERO = ...
ONE = ...
METH_VARARGS_AND_KEYWORDS = ...

def get_header():  # -> str:
    ...

class ExportEntry:
    def __init__(self, symbol, signature, function) -> None: ...

class _ModuleCompiler:
    method_def_ty = ...
    method_def_ptr = ...
    env_def_ty = ...
    env_def_ptr = ...
    def __init__(self, export_entries, module_name, use_nrt=..., **aot_options) -> None: ...
    def write_llvm_bitcode(self, output, wrap=..., **kws):  # -> None:
        ...
    def write_native_object(self, output, wrap=..., **kws):  # -> None:
        ...
    def emit_type(self, tyobj):  # -> str:
        ...
    def emit_header(self, output):  # -> None:
        ...

class ModuleCompiler(_ModuleCompiler):
    _ptr_fun = ...
    visitproc_ty = ...
    inquiry_ty = ...
    traverseproc_ty = ...
    freefunc_ty = ...
    m_init_ty = ...
    _char_star = ...
    module_def_base_ty = ...
    module_def_ty = ...
    @property
    def module_create_definition(self):  # -> tuple[FunctionType, Literal['PyModule_Create2TraceRefs', 'PyModule_Create2']]:

        ...
    @property
    def module_init_definition(self):  # -> tuple[FunctionType, LiteralString]:

        ...
