export_registry = ...

def export(prototype):  # -> Callable[..., None]:
    ...
def exportmany(prototypes):  # -> Callable[..., None]:
    ...
def process_input_files(inputs):  # -> None:

    ...
def clear_export_registry():  # -> None:
    ...

re_symbol = ...

def parse_prototype(text):  # -> tuple[Any, Any]:

    ...
