import functools

CCompiler = ...
new_compiler = ...
customize_compiler = ...
log = ...
_configs = ...

def get_configs(arg): ...

find_shared_ending = ...
find_pyext_ending = ...

@functools.lru_cache(maxsize=1)
def external_compiler_works():  # -> bool:

    ...

class _DummyExtension:
    libraries = ...

class Toolchain:
    def __init__(self) -> None: ...
    @property
    def verbose(self):  # -> bool:
        ...
    @verbose.setter
    def verbose(self, value):  # -> None:
        ...
    def compile_objects(self, sources, output_dir, include_dirs=..., depends=..., macros=..., extra_cflags=...): ...
    def link_shared(self, output, objects, libraries=..., library_dirs=..., export_symbols=..., extra_ldflags=...):  # -> None:

        ...
    def get_python_libraries(self):  # -> list[str]:

        ...
    def get_python_library_dirs(self):  # -> list[Incomplete]:

        ...
    def get_python_include_dirs(self):  # -> list[Incomplete]:

        ...
    def get_ext_filename(self, ext_name): ...
