from .browser import CDPBrowser

class ChromeCDP(CDPBrowser):
    def __init__(self, executable=..., flags=..., print_command=..., cdp_port=..., disable_logging=...) -> None: ...
    @property
    def executable(self):  # -> str:
        ...
    @executable.setter
    def executable(self, value):  # -> None:
        ...
    @property
    def disable_logging(self):  # -> bool:
        ...
    @disable_logging.setter
    def disable_logging(self, value):  # -> None:
        ...
    @property
    def ws(self):  # -> WebSocket:
        ...
    def cdp_send(self, method, **params):  # -> int:

        ...
    def screenshot(self, input, output_path, output_file=..., size=...):  # -> None:

        ...
    def get_page_infos(self):  # -> Any:

        ...
    def print_pdf(self):  # -> None:
        ...
    def __enter__(self):  # -> None:

        ...
    def __exit__(self, *exc):  # -> None:

        ...
