from .chromium import ChromiumHeadless

ENV_VAR_LOOKUP_TOGGLE = ...
CHROME_EXECUTABLE_ENV_VAR_CANDIDATES = ...

class ChromeHeadless(ChromiumHeadless):
    def __init__(self, executable=..., flags=..., print_command=..., disable_logging=..., use_new_headless=...) -> None: ...
    @property
    def executable(self):  # -> str:
        ...
    @executable.setter
    def executable(self, value):  # -> None:
        ...
