from .browser import Browser

class ChromiumHeadless(Browser):
    def __init__(self, executable=..., flags=..., print_command=..., disable_logging=..., use_new_headless=...) -> None: ...
    def screenshot(self, input, output_path, output_file=..., size=...):  # -> None:

        ...
    @property
    def disable_logging(self): ...
    @disable_logging.setter
    def disable_logging(self, value):  # -> None:
        ...
    def __enter__(self):  # -> None:
        ...
    def __exit__(self, *exc):  # -> None:
        ...
