ENV_VAR_LOOKUP_TOGGLE = ...
CHROME_EXECUTABLE_ENV_VAR_CANDIDATES = ...
FIREFOX_EXECUTABLE_ENV_VAR_CANDIDATES = ...

def get_command_origin(command):  # -> None:

    ...
def find_first_defined_env_var(env_var_list, toggle):  # -> str | None:

    ...
def find_chrome(user_given_executable=...):  # -> str:

    ...
def find_firefox(user_given_executable=...):  # -> str | None:

    ...
