import math

from numba.core import types

"""
Provide math calls that uses intrinsics or libc math functions.
"""
registry = ...
lower = ...
_NP_FLT_FINFO = ...
FLT_MAX = _NP_FLT_FINFO.max
FLT_MIN = _NP_FLT_FINFO.tiny
_NP_DBL_FINFO = ...
DBL_MAX = ...
DBL_MIN = ...
FLOAT_ABS_MASK = ...
FLOAT_SIGN_MASK = ...
DOUBLE_ABS_MASK = ...
DOUBLE_SIGN_MASK = ...

def is_nan(builder, val): ...
def is_inf(builder, val): ...
def is_finite(builder, val): ...
def f64_as_int64(builder, val): ...
def int64_as_f64(builder, val): ...
def f32_as_int32(builder, val): ...
def int32_as_f32(builder, val): ...
def negate_real(builder, val): ...
def call_fp_intrinsic(builder, name, args): ...
def unary_math_int_impl(fn, float_impl):  # -> None:
    ...
def unary_math_intr(fn, intrcode):  # -> Callable[..., Any]:

    ...
def unary_math_extern(fn, f32extern, f64extern, int_restype=...):  # -> Callable[..., Any]:

    ...

exp_impl = ...
exp2_impl = ...
log_impl = ...
log10_impl = ...
log2_impl = ...
sin_impl = ...
cos_impl = ...
log1p_impl = ...
expm1_impl = ...
erf_impl = ...
erfc_impl = ...
tan_impl = ...
asin_impl = ...
acos_impl = ...
atan_impl = ...
asinh_impl = ...
acosh_impl = ...
atanh_impl = ...
sinh_impl = ...
cosh_impl = ...
tanh_impl = ...
log2_impl = ...
ceil_impl = ...
floor_impl = ...
gamma_impl = ...
sqrt_impl = ...
trunc_impl = ...
lgamma_impl = ...

@lower(math.isnan, types.Float)
def isnan_float_impl(context, builder, sig, args): ...
@lower(math.isnan, types.Integer)
def isnan_int_impl(context, builder, sig, args):  # -> Constant:
    ...
@lower(math.isinf, types.Float)
def isinf_float_impl(context, builder, sig, args): ...
@lower(math.isinf, types.Integer)
def isinf_int_impl(context, builder, sig, args):  # -> Constant:
    ...
@lower(math.isfinite, types.Float)
def isfinite_float_impl(context, builder, sig, args): ...
@lower(math.isfinite, types.Integer)
def isfinite_int_impl(context, builder, sig, args):  # -> Constant:
    ...
@lower(math.copysign, types.Float, types.Float)
def copysign_float_impl(context, builder, sig, args): ...
@lower(math.frexp, types.Float)
def frexp_impl(context, builder, sig, args):  # -> Constant:
    ...
@lower(math.ldexp, types.Float, types.intc)
def ldexp_impl(context, builder, sig, args): ...
@lower(math.atan2, types.int64, types.int64)
def atan2_s64_impl(context, builder, sig, args): ...
@lower(math.atan2, types.uint64, types.uint64)
def atan2_u64_impl(context, builder, sig, args): ...
@lower(math.atan2, types.Float, types.Float)
def atan2_float_impl(context, builder, sig, args): ...
@lower(math.hypot, types.int64, types.int64)
def hypot_s64_impl(context, builder, sig, args): ...
@lower(math.hypot, types.uint64, types.uint64)
def hypot_u64_impl(context, builder, sig, args): ...
@lower(math.hypot, types.Float, types.Float)
def hypot_float_impl(context, builder, sig, args): ...
@lower(math.radians, types.Float)
def radians_float_impl(context, builder, sig, args): ...
@lower(math.degrees, types.Float)
def degrees_float_impl(context, builder, sig, args): ...
@lower(math.pow, types.Float, types.Float)
@lower(math.pow, types.Float, types.Integer)
def pow_impl(context, builder, sig, args): ...
@lower(math.nextafter, types.Float, types.Float)
def nextafter_impl(context, builder, sig, args): ...
def gcd_impl(context, builder, sig, args): ...
