from numba.core import types

"""
This file implements print functionality for the CPU.
"""
registry = ...
lower = ...

@lower("print_item", types.Literal)
def print_item_impl(context, builder, sig, args): ...
@lower("print_item", types.Any)
def print_item_impl(context, builder, sig, args): ...
@lower(print, types.VarArg(types.Any))
def print_varargs_impl(context, builder, sig, args): ...
