from numba.core import types
from numba.core.imputils import lower_builtin, lower_cast, lower_constant, lower_getattr

"""
Implement slices and various slice computations.
"""

def fix_index(builder, idx, size): ...
def fix_slice(builder, slice, size):  # -> None:

    ...
def get_slice_length(builder, slicestruct): ...
def get_slice_bounds(builder, slicestruct):  # -> tuple[Any, Any]:

    ...
def fix_stride(builder, slice, stride): ...
def guard_invalid_slice(context, builder, typ, slicestruct):  # -> None:

    ...
def get_defaults(context):  # -> tuple[Literal[0], Any, Any, Any, Literal[1]]:

    ...
@lower_builtin(slice, types.VarArg(types.Any))
def slice_constructor_impl(context, builder, sig, args): ...
@lower_getattr(types.SliceType, "start")
def slice_start_impl(context, builder, typ, value): ...
@lower_getattr(types.SliceType, "stop")
def slice_stop_impl(context, builder, typ, value): ...
@lower_getattr(types.SliceType, "step")
def slice_step_impl(context, builder, typ, value): ...
@lower_builtin("slice.indices", types.SliceType, types.Integer)
def slice_indices(context, builder, sig, args): ...
def make_slice_from_constant(context, builder, ty, pyval): ...
@lower_constant(types.SliceType)
def constant_slice(context, builder, ty, pyval): ...
@lower_cast(types.misc.SliceLiteral, types.SliceType)
def cast_from_literal(context, builder, fromty, toty, val): ...
