class Rewrite:
    def __init__(self, state=...) -> None: ...
    def match(self, func_ir, block, typemap, calltypes):  # -> Literal[False]:

        ...
    def apply(self): ...

class RewriteRegistry:
    _kinds = ...
    def __init__(self) -> None: ...
    def register(self, kind):  # -> Callable[..., type[Rewrite]]:

        ...
    def apply(self, kind, state):  # -> None:

        ...

rewrite_registry = ...
register_rewrite = ...
