"""
This type stub file was generated by pyright.
"""

from modin.core.execution.python.implementations.pandas_on_python.dataframe.dataframe import PandasOnPythonDataframe
from modin.core.io import BaseIO

"""Module for housing IO classes with pandas storage format and Python engine."""
class PandasOnPythonIO(BaseIO):
    """
    Class for storing IO functions operating on pandas storage format and Python engine.

    Inherits default function implementations from ``BaseIO`` parent class.
    """
    frame_cls = PandasOnPythonDataframe
    query_compiler_cls = ...


