"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._labelfont import Labelfont

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
else:
    ...
