"""
This type stub file was generated by pyright.
"""

import unidist

"""
The module with helper mixin for executing functions remotely.

To be used as a piece of building a unidist-based engine.
"""
class UnidistWrapper:
    """Mixin that provides means of running functions remotely and getting local results."""
    @classmethod
    def deploy(cls, func, f_args=..., f_kwargs=..., return_pandas_df=..., num_returns=...): # -> Any:
        """
        Run local `func` remotely.

        Parameters
        ----------
        func : callable or unidist.ObjectRef
            The function to perform.
        f_args : list or tuple, optional
            Positional arguments to pass to ``func``.
        f_kwargs : dict, optional
            Keyword arguments to pass to ``func``.
        return_pandas_df : bool, optional
            Whether to convert the result of `func` to a pandas DataFrame or not.
        num_returns : int, default: 1
            Amount of return values expected from `func`.

        Returns
        -------
        unidist.ObjectRef or list
            Unidist identifier of the result being put to object store.
        """
        ...
    
    @classmethod
    def is_future(cls, item):
        """
        Check if the item is a Future.

        Parameters
        ----------
        item : unidist.ObjectRef or object
            Future or object to check.

        Returns
        -------
        boolean
            If the value is a future.
        """
        ...
    
    @classmethod
    def materialize(cls, obj_id):
        """
        Get the value of object from the object store.

        Parameters
        ----------
        obj_id : unidist.ObjectRef
            Unidist object identifier to get the value by.

        Returns
        -------
        object
            Whatever was identified by `obj_id`.
        """
        ...
    
    @classmethod
    def put(cls, data, **kwargs):
        """
        Put data into the object store.

        Parameters
        ----------
        data : object
            Data to be put.
        **kwargs : dict
            Additional keyword arguments (mostly for compatibility).

        Returns
        -------
        unidist.ObjectRef
            A reference to `data`.
        """
        ...
    
    @classmethod
    def wait(cls, obj_ids, num_returns=...): # -> None:
        """
        Wait on the objects without materializing them (blocking operation).

        ``unidist.wait`` assumes a list of unique object references: see
        https://github.com/modin-project/modin/issues/5045

        Parameters
        ----------
        obj_ids : list, scalar
        num_returns : int, optional
        """
        ...
    


@unidist.remote
class SignalActor:
    """
    Help synchronize across tasks and actors on cluster.

    Parameters
    ----------
    event_count : int
        Number of events required for synchronization.

    Notes
    -----
    For details see: https://docs.ray.io/en/latest/advanced.html?highlight=signalactor#multi-node-synchronization-using-an-actor.
    """
    def __init__(self, event_count: int) -> None:
        ...
    
    def send(self, event_idx: int): # -> None:
        """
        Indicate that event with `event_idx` has occured.

        Parameters
        ----------
        event_idx : int
        """
        ...
    
    async def wait(self, event_idx: int): # -> None:
        """
        Wait until event with `event_idx` has occured.

        Parameters
        ----------
        event_idx : int
        """
        ...
    


