FROM public.ecr.aws/docker/library/python:3.13.7-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY . .

RUN --mount=type=secret,id=GITHUB_PAT_TOKEN \
	apt-get update && \
    apt-get install -y --no-install-recommends gcc libc6-dev git && \
	export GITHUB_PAT_TOKEN=$(cat /run/secrets/GITHUB_PAT_TOKEN) && \
	git config --global url.https://${GITHUB_PAT_TOKEN}:x-oauth-basic@github.com/.insteadOf ssh://git@github.com/ && \
	uv sync && \
    apt-get purge -y gcc libc6-dev && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

CMD ["uv", "run", "streamlit", "run", "src/{{ cookiecutter.__package_stub }}/app/main.py", "--server.port=8501"]
