class DataModelManager:
    def __init__(self, handlers=...) -> None: ...
    def register(self, fetypecls, handler):  # -> None:

        ...
    def lookup(self, fetype): ...
    def __getitem__(self, fetype): ...
    def copy(self):  # -> DataModelManager:

        ...
    def chain(self, other_manager):  # -> DataModelManager:

        ...
