class DataPacker:
    def __init__(self, dmm, fe_types) -> None: ...
    def as_data(self, builder, values):  # -> Constant:

        ...
    def load(self, builder, ptr):  # -> list[Any]:

        ...
    def load_into(self, builder, ptr, formal_list):  # -> None:

        ...

class ArgPacker:
    def __init__(self, dmm, fe_args) -> None: ...
    def as_arguments(self, builder, values):  # -> tuple[()] | tuple[Any, ...]:

        ...
    def from_arguments(self, builder, args):  # -> list[Any]:

        ...
    def assign_names(self, args, names):  # -> None:

        ...
    @property
    def argument_types(self):  # -> tuple[Any, ...]:

        ...

_PUSH_LIST = ...
_APPEND_NEXT_VALUE = ...
_APPEND_EMPTY_TUPLE = ...
_POP = ...

class _Unflattener:
    def __init__(self, pattern) -> None: ...
    def unflatten(self, flatiter):  # -> list[Any]:

        ...
