"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def show_versions():
    ...

def show_info():
    ...

def get_include():
    ...

def get_libraries():
    ...

def create_library_symlinks():
    ...

def get_library_dirs():
    ...

