"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
_DEPR_MSG = ...
def doc(*docstrings, **params):
    ...

def product(seq):
    ...

def get_contiguous_span(shape, strides, itemsize):
    ...

def find_free_port():
    ...

def guid():
    ...

def download_tzdata_on_windows():
    ...

