from pathlib import Path

class StreamlitManager:
    @staticmethod
    def initialise(**kwargs) -> None: ...
    @staticmethod
    def add_style(css: str) -> None: ...
    @staticmethod
    def add_css(path: Path | str) -> None: ...
    @staticmethod
    def run() -> None: ...
