import socket
from types import TracebackType
from typing import Self

logger = ...

class AuthHttpServer:
    DEFAULT_MAX_ATTEMPTS = ...
    DEFAULT_TIMEOUT = ...
    PORT_BIND_MAX_ATTEMPTS = ...
    PORT_BIND_TIMEOUT = ...
    def __init__(self, uri: str, buf_size: int = ..., redirect_uri: str | None = ...) -> None: ...
    @property
    def redirect_uri(self) -> str | None: ...
    @property
    def url(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def hostname(self) -> str: ...
    def receive_block(self, max_attempts: int = ..., timeout: float | None = ...) -> (list[str] | None, socket.socket | None): ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None: ...
