from abc import ABC, abstractmethod
from collections.abc import Iterator
from enum import Enum, unique
from typing import TYPE_CHECKING, Any

from .. import SnowflakeConnection

if TYPE_CHECKING: ...
logger = ...
DEFAULT_MAX_CON_RETRY_ATTEMPTS = ...
DEFAULT_AUTH_CLASS_TIMEOUT = ...

@unique
class AuthType(Enum):
    DEFAULT = ...
    EXTERNAL_BROWSER = ...
    KEY_PAIR = ...
    OAUTH = ...
    ID_TOKEN = ...
    USR_PWD_MFA = ...
    OKTA = ...
    PAT = ...
    NO_AUTH = ...
    WORKLOAD_IDENTITY = ...
    PAT_WITH_EXTERNAL_SESSION = ...

class AuthByPlugin(ABC):
    def __init__(self, timeout: int | None = ..., backoff_generator: Iterator | None = ..., **kwargs) -> None: ...
    @property
    def timeout(self) -> int: ...
    @timeout.setter
    def timeout(self) -> None: ...
    @property
    @abstractmethod
    def type_(self) -> AuthType: ...
    @property
    @abstractmethod
    def assertion_content(self) -> str: ...
    @abstractmethod
    def prepare(
        self,
        *,
        conn: SnowflakeConnection,
        authenticator: str,
        service_name: str | None,
        account: str,
        user: str,
        password: str | None,
        **kwargs: Any,
    ) -> str | None: ...
    @abstractmethod
    def update_body(self, body: dict[Any, Any]) -> None: ...
    @abstractmethod
    def reset_secrets(self) -> None: ...
    @abstractmethod
    def reauthenticate(self, *, conn: SnowflakeConnection, **kwargs: Any) -> dict[str, Any]: ...
    def handle_timeout(
        self, *, authenticator: str, service_name: str | None, account: str, user: str, password: str, **kwargs: Any
    ) -> None: ...
