from typing import Any

from .by_plugin import AuthByPlugin, AuthType

class AuthByDefault(AuthByPlugin):
    @property
    def type_(self) -> AuthType: ...
    @property
    def assertion_content(self) -> str: ...
    def __init__(self, password: str, **kwargs) -> None: ...
    def reset_secrets(self) -> None: ...
    def prepare(self, **kwargs: Any) -> None: ...
    def reauthenticate(self, **kwargs: Any) -> dict[str, bool]: ...
    def update_body(self, body: dict[Any, Any]) -> None: ...
