from typing import TYPE_CHECKING, Any

from ..connection import SnowflakeConnection
from .by_plugin import AuthByPlugin, AuthType

if TYPE_CHECKING: ...

class AuthByIdToken(AuthByPlugin):
    @property
    def type_(self) -> AuthType: ...
    @property
    def assertion_content(self) -> str: ...
    def __init__(self, id_token: str, application: str, protocol: str | None, host: str | None, port: str | None, **kwargs) -> None: ...
    def reset_secrets(self) -> None: ...
    def prepare(self, **kwargs: Any) -> None: ...
    def reauthenticate(self, *, conn: SnowflakeConnection, **kwargs: Any) -> dict[str, bool]: ...
    def update_body(self, body: dict[Any, Any]) -> None: ...
