from typing import Any

from cryptography.hazmat.primitives.asymmetric.rsa import RSAPrivateKey

from ..errors import OperationalError
from .by_plugin import AuthByPlugin, AuthType

logger = ...

class AuthByKeyPair(AuthByPlugin):
    ALGORITHM = ...
    ISSUER = ...
    SUBJECT = ...
    EXPIRE_TIME = ...
    ISSUE_TIME = ...
    LIFETIME = ...
    DEFAULT_JWT_RETRY_ATTEMPTS = ...
    DEFAULT_JWT_CNXN_WAIT_TIME = ...
    def __init__(
        self, private_key: bytes | str | RSAPrivateKey, private_key_passphrase: bytes | None = ..., lifetime_in_seconds: int = ..., **kwargs
    ) -> None: ...
    def reset_secrets(self) -> None: ...
    @property
    def type_(self) -> AuthType: ...
    def prepare(self, *, account: str, user: str, **kwargs: Any) -> str: ...
    def reauthenticate(self, **kwargs: Any) -> dict[str, bool]: ...
    @staticmethod
    def calculate_public_key_fingerprint(private_key): ...
    def update_body(self, body: dict[Any, Any]) -> None: ...
    def assertion_content(self) -> str: ...
    def should_retry(self, count: int) -> bool: ...
    def handle_timeout(
        self, *, authenticator: str, service_name: str | None, account: str, user: str, password: str | None, **kwargs: Any
    ) -> None: ...
    @staticmethod
    def can_handle_exception(op: OperationalError) -> bool: ...
