from typing import TYPE_CHECKING, Any

from .. import SnowflakeConnection
from .by_plugin import AuthByPlugin, AuthType

if TYPE_CHECKING: ...
logger = ...

class AuthByOkta(AuthByPlugin):
    def __init__(self, application: str, **kwargs) -> None: ...
    def reset_secrets(self) -> None: ...
    @property
    def type_(self) -> AuthType: ...
    @property
    def assertion_content(self) -> str: ...
    def update_body(self, body: dict[Any, Any]) -> None: ...
    def prepare(
        self,
        *,
        conn: SnowflakeConnection,
        authenticator: str,
        service_name: str | None,
        account: str,
        user: str,
        password: str,
        **kwargs: Any,
    ) -> None: ...
    def reauthenticate(self, **kwargs: Any) -> dict[str, bool]: ...
