import typing

from .by_plugin import AuthByPlugin, AuthType

class AuthByPAT(AuthByPlugin):
    def __init__(self, pat_token: str, **kwargs) -> None: ...
    @property
    def type_(self) -> AuthType: ...
    def reset_secrets(self) -> None: ...
    def update_body(self, body: dict[typing.Any, typing.Any]) -> None: ...
    def prepare(self, **kwargs: typing.Any) -> None: ...
    def reauthenticate(self, **kwargs: typing.Any) -> dict[str, bool]: ...
    @property
    def assertion_content(self) -> str | None: ...
