from typing import TYPE_CHECKING, Any

from .. import SnowflakeConnection
from .by_plugin import AuthByPlugin, AuthType

if TYPE_CHECKING: ...
logger = ...
MFA_TOKEN = ...

class AuthByUsrPwdMfa(AuthByPlugin):
    @property
    def assertion_content(self) -> str: ...
    def __init__(self, password: str, mfa_token: str | None = ..., **kwargs) -> None: ...
    def reset_secrets(self) -> None: ...
    @property
    def type_(self) -> AuthType: ...
    def prepare(self, *, conn: SnowflakeConnection, **kwargs: Any) -> None: ...
    def reauthenticate(self, **kwargs) -> dict[str, bool]: ...
    def update_body(self, body: dict[Any, Any]) -> None: ...
