import socket
from types import ModuleType
from typing import TYPE_CHECKING, Any

from .. import SnowflakeConnection
from .by_plugin import AuthByPlugin, AuthType

if TYPE_CHECKING: ...
logger = ...
BUF_SIZE = ...

class AuthByWebBrowser(AuthByPlugin):
    def __init__(
        self,
        application: str,
        webbrowser_pkg: ModuleType | None = ...,
        socket_pkg: type[socket.socket] | None = ...,
        protocol: str | None = ...,
        host: str | None = ...,
        port: str | None = ...,
        **kwargs,
    ) -> None: ...
    def reset_secrets(self) -> None: ...
    @property
    def type_(self) -> AuthType: ...
    @property
    def assertion_content(self) -> str: ...
    def update_body(self, body: dict[Any, Any]) -> None: ...
    def prepare(
        self, *, conn: SnowflakeConnection, authenticator: str, service_name: str | None, account: str, user: str, **kwargs: Any
    ) -> None: ...
    def reauthenticate(self, *, conn: SnowflakeConnection, **kwargs: Any) -> dict[str, bool]: ...
