import typing
from enum import Enum, unique

from snowflake.connector.connection import SnowflakeConnection

from ..wif_util import AttestationProvider, WorkloadIdentityAttestation
from .by_plugin import AuthByPlugin, AuthType

if typing.TYPE_CHECKING: ...

@unique
class ApiFederatedAuthenticationType(Enum):
    AWS = ...
    AZURE = ...
    GCP = ...
    OIDC = ...
    @staticmethod
    def from_attestation(attestation: WorkloadIdentityAttestation) -> ApiFederatedAuthenticationType: ...

class AuthByWorkloadIdentity(AuthByPlugin):
    def __init__(
        self,
        *,
        provider: AttestationProvider,
        token: str | None = ...,
        entra_resource: str | None = ...,
        impersonation_path: list[str] | None = ...,
        **kwargs,
    ) -> None: ...
    def type_(self) -> AuthType: ...
    def reset_secrets(self) -> None: ...
    def update_body(self, body: dict[typing.Any, typing.Any]) -> None: ...
    def prepare(self, *, conn: SnowflakeConnection | None, **kwargs: typing.Any) -> None: ...
    def reauthenticate(self, **kwargs: typing.Any) -> dict[str, bool]: ...
    @property
    def assertion_content(self) -> str: ...
