"""
This type stub file was generated by pyright.
"""

from typing import Any
from plotly.basedatatypes import BaseTraceHierarchyType

"""
This type stub file was generated by pyright.
"""
class Marker(BaseTraceHierarchyType):
    def __init__(self, arg: dict[str, Any] | None = ..., **kwargs: Any) -> None:
        ...
    


