import operator

"""
Overloads for ClassInstanceType for built-in functions that call dunder methods
on an object.
"""

def class_instance_overload(target):  # -> Callable[..., Any]:

    ...
def extract_template(template, name): ...
def register_simple_overload(func, *attrs, n_args=...): ...
def try_call_method(cls_type, method, n_args=...):  # -> None:

    ...
def try_call_complex_method(cls_type, method):  # -> None:

    ...
def take_first(*options):  # -> None:

    ...
@class_instance_overload(bool)
def class_bool(x):  # -> None:
    ...
@class_instance_overload(complex)
def class_complex(real=..., imag=...):  # -> None:
    ...
@class_instance_overload(operator.contains)
def class_contains(x, y):  # -> None:
    ...
@class_instance_overload(float)
def class_float(x):  # -> None:
    ...
@class_instance_overload(int)
def class_int(x):  # -> None:
    ...
@class_instance_overload(str)
def class_str(x):  # -> None:
    ...
@class_instance_overload(operator.ne)
def class_ne(x, y):  # -> None:
    ...
def register_reflected_overload(func, meth_forward, meth_reflected):  # -> None:
    ...
