from nbconvert.exporters import HTMLExporter

async def handler(ws, data, key=...): ...
async def main(file_name, p, debug_port): ...
def get_launch_args(): ...
def launch_chrome(debug_port): ...
def get_free_port(): ...
def get_pdf_data(file_name): ...
def get_pdf_data_chromecontroller(file_name): ...

class BrowserExporter(HTMLExporter):
    def from_notebook_node(self, nb, resources=..., **kw): ...
