"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def convert(model, handler):
    ...

def read_static_file(name):
    ...

def get_js(converter):
    ...

def bundle(handler, model):
    ...

