"""
This type stub file was generated by pyright.
"""

import argparse

"""
This type stub file was generated by pyright.
"""
class CustomFormatter(argparse.RawTextHelpFormatter):
    ...


HELP = ...
parser = ...
def main():
    ...

