_logger = ...

class Converter:
    KINDS = ...
    DISPLAY_DATA_PRIORITY = ...
    def __init__(
        self,
        filename,
        to,
        use,
        center_df,
        max_rows,
        max_cols,
        execute,
        save_notebook,
        limit,
        document_name,
        table_conversion,
        chrome_path,
        latex_command,
        output_dir,
        no_input,
        web_app,
        nbconvert_config=...,
    ) -> None: ...
    def __del__(self) -> None: ...
    def get_to(self, to): ...
    def get_latex_command(self, latex_command): ...
    def get_notebook(self): ...
    def get_document_name(self, document_name): ...
    def get_new_notebook_home(self, output_dir): ...
    def get_resources(self): ...
    def get_code_to_run(self): ...
    def execute_notebook(self): ...
    def no_execute_preprocess(self): ...
    def to_md(self): ...
    def to_pdf_latex(self): ...
    def to_pdf_browser(self): ...
    def save_notebook_to_file(self): ...
    def convert(self): ...

def convert(
    filename,
    to=...,
    use=...,
    center_df=...,
    max_rows=...,
    max_cols=...,
    execute=...,
    save_notebook=...,
    limit=...,
    document_name=...,
    table_conversion=...,
    chrome_path=...,
    latex_command=...,
    output_dir=...,
    no_input=...,
): ...
