from nbconvert.exporters import PDFExporter

def get_latex_command(): ...

class DataFramePDFExporter(PDFExporter):
    export_from_notebook = ...
    latex_command = ...
    preprocessors = ...
    default_preprocessors = ...
