from nbconvert.preprocessors import Preprocessor

def get_image_files(md_source, only_http=...): ...
def replace_md_tables(image_data_dict, md_source, converter, cell_index, to_html=...): ...
def get_image_tags(md_source, only_http=...): ...

class LocalImagePreprocessor(Preprocessor):
    def markdown_preprocess_cell(self, cell, resources, cell_index): ...
    def preprocess_cell(self, cell, resources, cell_index): ...

class MarkdownPreprocessor(LocalImagePreprocessor):
    def markdown_preprocess_cell(self, cell, resources, cell_index): ...

class PdfLatexPreprocessor(LocalImagePreprocessor):
    def markdown_preprocess_cell(self, cell, resources, cell_index): ...

class NoExecuteDataFramePreprocessor(Preprocessor):
    def preprocess_cell(self, cell, resources, index): ...

class ChangeOutputTypePreprocessor(Preprocessor):
    def preprocess_cell(self, cell, resources, cell_index): ...

class MarkdownHTTPPreprocessor(Preprocessor):
    def preprocess_cell(self, cell, resources, cell_index): ...
