from enum import Enum

CHROME_LAST_KNOWN_GOOD_VERSION = ...
CHROME_FOR_TESTING_PUBLIC_BASE_URL = ...

def ensure_directory_exists(directory: str): ...

class BrowserPlatform(Enum):
    LINUX = ...
    MAC_ARM = ...
    MAC = ...
    WIN32 = ...
    WIN64 = ...
    @staticmethod
    def identify_current_os() -> BrowserPlatform: ...
    def get_folder(self) -> str: ...

class ChromeReleaseChannel(Enum):
    STABLE = ...
    BETA = ...
    DEV = ...
    CANARY = ...

def resolve_download_url(platform: BrowserPlatform, build_id: str) -> str: ...
def resolve_download_path(platform: BrowserPlatform, build_id: str) -> list[str]: ...
async def download_file(url: str, download_path: str): ...
def extract_zip(zip_path: str, extract_to: str): ...
async def get_last_known_good_release_for_channel(channel: ChromeReleaseChannel) -> dict: ...
async def resolve_build_id(channel: ChromeReleaseChannel) -> str: ...
def relative_executable_path(platform: BrowserPlatform) -> str: ...
def find_executable_path(extract_to: str, platform: BrowserPlatform) -> str: ...
def main(browser_platform: BrowserPlatform, channel: ChromeReleaseChannel, output_path: str): ...

if __name__ == "__main__":
    parser = ...
    args = ...
