from sqlalchemy.sql.type_api import TypeEngine

ischema_names = ...
NOT_NULL_STR = ...

def tokenize_parameters(text: str, character_for_strip=...) -> list: ...
def parse_index_columns(columns: str) -> list[str]: ...
def parse_type(type_text: str) -> TypeEngine: ...
