from numba.core.extending import intrinsic

UNKNOWN_CLASS = ...
CONST_CLASS = ...
MAP_TYPES = ...
array_analysis_extensions = ...
array_creation = ...
random_int_args = ...
random_1arg_size = ...
random_2arg_sizelast = ...
random_3arg_sizelast = ...
random_calls = ...

@intrinsic
def wrap_index(typingctx, idx, size):  # -> tuple[Signature, Callable[..., Any]]:

    ...
def wrap_index_literal(idx, size):  # -> Literal[0]:
    ...
@intrinsic
def assert_equiv(typingctx, *val):  # -> tuple[Signature, Callable[..., Any]]:

    ...

class EquivSet:
    def __init__(self, obj_to_ind=..., ind_to_obj=..., next_ind=...) -> None: ...
    def empty(self):  # -> EquivSet:

        ...
    def clone(self):  # -> EquivSet:

        ...
    def is_empty(self):  # -> bool:

        ...
    def is_equiv(self, *objs):  # -> bool:

        ...
    def get_equiv_const(self, obj):  # -> int | None:

        ...
    def get_equiv_set(self, obj):  # -> set[Any]:

        ...
    def insert_equiv(self, *objs):  # -> None:

        ...
    def intersect(self, equiv_set):  # -> EquivSet:

        ...

class ShapeEquivSet(EquivSet):
    def __init__(self, typemap, defs=..., ind_to_var=..., obj_to_ind=..., ind_to_obj=..., next_id=..., ind_to_const=...) -> None: ...
    def empty(self):  # -> ShapeEquivSet:

        ...
    def clone(self):  # -> ShapeEquivSet:

        ...
    def is_equiv(self, *objs):  # -> bool:

        ...
    def get_equiv_const(self, obj):  # -> int | None:

        ...
    def get_equiv_var(self, obj):  # -> None:

        ...
    def get_equiv_set(self, obj):  # -> set[Any] | None:

        ...
    def insert_equiv(self, *objs):  # -> Literal[False] | None:

        ...
    def has_shape(self, name):  # -> bool:

        ...
    def get_shape(self, name):  # -> tuple[Any, ...] | None:

        ...
    def get_shape_classes(self, name):  # -> list[Any] | tuple[Any, ...]:

        ...
    def intersect(self, equiv_set):  # -> EquivSet:

        ...
    def define(self, name, redefined):  # -> None:

        ...
    def union_defs(self, defs, redefined):  # -> None:

        ...

class SymbolicEquivSet(ShapeEquivSet):
    def __init__(
        self, typemap, def_by=..., ref_by=..., ext_shapes=..., defs=..., ind_to_var=..., obj_to_ind=..., ind_to_obj=..., next_id=...
    ) -> None: ...
    def empty(self):  # -> SymbolicEquivSet:

        ...
    def clone(self):  # -> SymbolicEquivSet:

        ...
    def get_rel(self, name):  # -> None:

        ...
    def define(self, var, redefined, func_ir=..., typ=...):  # -> Literal[True] | None:

        ...
    def set_shape_setitem(self, obj, shape):  # -> None:

        ...

class WrapIndexMeta:
    def __init__(self, slice_size, dim_size) -> None: ...

class ArrayAnalysis:
    aa_count = ...
    def __init__(self, context, func_ir, typemap, calltypes) -> None: ...
    def get_equiv_set(self, block_label): ...
    def remove_redefineds(self, redefineds):  # -> None:

        ...
    def run(self, blocks=..., equiv_set=...):  # -> None:

        ...
    def dump(self):  # -> None:

        ...

    class AnalyzeResult:
        def __init__(self, **kwargs) -> None: ...

    def gen_literal_slice_part(self, arg_val, loc, scope, stmts, equiv_set, name=...):  # -> tuple[Var, IntegerLiteral]:
        ...
    def gen_static_slice_size(self, lhs_rel, rhs_rel, loc, scope, stmts, equiv_set):  # -> Var:
        ...
    def gen_explicit_neg(self, arg, arg_rel, arg_typ, size_typ, loc, scope, dsize, stmts, equiv_set):  # -> tuple[Var, Integer]:
        ...
    def update_replacement_slice(
        self,
        lhs,
        lhs_typ,
        lhs_rel,
        dsize_rel,
        replacement_slice,
        slice_index,
        need_replacement,
        loc,
        scope,
        stmts,
        equiv_set,
        size_typ,
        dsize,
    ):  # -> tuple[Any | Var, Any | IntegerLiteral | Integer, Any | int, Any, Any | Literal[True], bool]:
        ...
    def slice_size(self, index, dsize, equiv_set, scope, stmts): ...

UNARY_MAP_OP = ...
BINARY_MAP_OP = ...
INPLACE_BINARY_MAP_OP = ...
UFUNC_MAP_OP = ...
