from numba.core import lowering
from numba.core.errors import InternalError

class ParforLower(lowering.Lower):
    def lower_inst(self, inst):  # -> None:
        ...

_ReductionInfo = ...

class ParforsUnexpectedReduceNodeError(InternalError):
    def __init__(self, inst) -> None: ...

def wrap_loop_body(loop_body): ...
def unwrap_loop_body(loop_body):  # -> None:
    ...
def add_to_def_once_sets(a_def, def_once, def_more):  # -> None:

    ...
def compute_def_once_block(block, def_once, def_more, getattr_taken, typemap, module_assigns):  # -> None:

    ...
def wrap_find_topo(loop_body):  # -> list[Any]:
    ...
def compute_def_once_internal(loop_body, def_once, def_more, getattr_taken, typemap, module_assigns):  # -> None:

    ...
def compute_def_once(loop_body, typemap):  # -> tuple[set[Any], set[Any]]:

    ...
def find_vars(var, varset):  # -> Var:
    ...
def find_setitems_block(setitems, itemsset, block, typemap):  # -> None:
    ...
def find_setitems_body(setitems, itemsset, loop_body, typemap):  # -> None:

    ...
def empty_container_allocator_hoist(inst, dep_on_param, call_table, hoisted, not_hoisted, typemap, stored_arrays):  # -> bool:
    ...
def hoist(parfor_params, loop_body, typemap, wrapped_blocks):  # -> tuple[list[Any], list[Any]]:
    ...
def redtyp_is_scalar(redtype):  # -> bool:
    ...
def redtyp_to_redarraytype(redtyp):  # -> Array:

    ...
def redarraytype_to_sig(redarraytyp):  # -> Array:

    ...
def legalize_names_with_typemap(names, typemap):  # -> dict[Any, Any]:

    ...
def to_scalar_from_0d(x):  # -> ArrayCompatible:
    ...
def replace_var_with_array_in_block(vars, block, typemap, calltypes):  # -> list[Any]:
    ...
def replace_var_with_array_internal(vars, loop_body, typemap, calltypes):  # -> None:
    ...
def replace_var_with_array(vars, loop_body, typemap, calltypes):  # -> None:
    ...
def call_parallel_gufunc(
    lowerer,
    cres,
    gu_signature,
    outer_sig,
    expr_args,
    expr_arg_types,
    loop_ranges,
    redvars,
    reddict,
    redarrdict,
    init_block,
    index_var_typ,
    races,
    exp_name_to_tuple_var,
): ...
