from contextlib import contextmanager
from functools import reduce

from numba.core import ir
from numba.core.extending import overload, register_jitable
from numba.core.typing.templates import AbstractTemplate, infer_global

"""
This module transforms data-parallel operations such as Numpy calls into
'Parfor' nodes, which are nested loops that can be parallelized.
It also implements optimizations such as loop fusion, and extends the rest of
compiler analysis and optimizations to support Parfors.
This is similar to ParallelAccelerator package in Julia:
https://github.com/IntelLabs/ParallelAccelerator.jl
'Parallelizing Julia with a Non-invasive DSL', T. Anderson et al., ECOOP'17.
"""
_termwidth = ...
_txtwrapper = ...

def print_wrapped(x):  # -> None:
    ...

sequential_parfor_lowering = ...

def init_prange():  # -> None:
    ...
@overload(init_prange)
def init_prange_overload():  # -> Callable[[], None]:
    ...

class internal_prange:
    def __new__(cls, *args):  # -> range:
        ...

def min_parallel_impl(
    return_type, arg
):  # -> Callable[..., Any] | Callable[..., float | int | Any | None] | Callable[..., float | int | Any]:
    ...
def max_parallel_impl(
    return_type, arg
):  # -> Callable[..., Any] | Callable[..., float | int | Any | None] | Callable[..., float | int | Any]:
    ...
def argmin_parallel_impl(in_arr): ...
def argmax_parallel_impl(in_arr): ...
def dotvv_parallel_impl(a, b):  # -> Literal[0]:
    ...
def dotvm_parallel_impl(a, b):  # -> _Array1D[float64]:
    ...
def dotmv_parallel_impl(a, b):  # -> _Array1D[float64]:
    ...
def dot_parallel_impl(return_type, atyp, btyp):  # -> Callable[..., Any | Literal[0]] | Callable[..., _Array1D[float64]] | None:
    ...
def sum_parallel_impl(return_type, arg):  # -> Callable[..., Any]:
    ...
def prod_parallel_impl(return_type, arg):  # -> Callable[..., Any]:
    ...
def mean_parallel_impl(return_type, arg):  # -> Callable[..., Any]:
    ...
def var_parallel_impl(return_type, arg):  # -> Callable[..., Literal[0]] | Callable[..., Any | float] | Callable[..., Any]:
    ...
def std_parallel_impl(return_type, arg):  # -> Callable[..., Any]:
    ...
def arange_parallel_impl(return_type, *args, dtype=...):  # -> Callable[..., Any] | Callable[..., _Array1D[float64]]:
    ...
def linspace_parallel_impl(return_type, *args):  # -> Callable[..., Any] | Callable[..., ndarray[tuple[int], dtype[object_ | Any]]]:
    ...

swap_functions_map = ...

def fill_parallel_impl(return_type, arr, val):  # -> Callable[..., None]:

    ...

replace_functions_ndarray = ...

@register_jitable
def max_checker(arr_size):  # -> None:
    ...
@register_jitable
def min_checker(arr_size):  # -> None:
    ...
@register_jitable
def argmin_checker(arr_size):  # -> None:
    ...
@register_jitable
def argmax_checker(arr_size):  # -> None:
    ...

checker_impl = ...
replace_functions_checkers_map = ...

class LoopNest:
    def __init__(self, index_variable, start, stop, step) -> None: ...
    def list_vars(self):  # -> list[Any]:
        ...

class Parfor(ir.Expr, ir.Stmt):
    id_counter = ...
    def __init__(
        self, loop_nests, init_block, loop_body, loc, index_var, equiv_set, pattern, flags, *, no_sequential_lowering=..., races=...
    ) -> None: ...
    def get_loop_nest_vars(self):  # -> list[Any]:
        ...
    def list_vars(self):  # -> list[Any]:

        ...
    def get_shape_classes(self, var, typemap=...): ...
    def dump(self, file=...):  # -> None:
        ...
    def validate_params(self, typemap):  # -> None:

        ...

class ParforDiagnostics:
    def __init__(self) -> None: ...
    def setup(self, func_ir, fusion_enabled):  # -> None:
        ...
    @property
    def has_setup(self): ...
    @has_setup.setter
    def has_setup(self, state):  # -> None:
        ...
    def count_parfors(self, blocks=...):  # -> int:
        ...
    def get_parfors(self):  # -> list[Any]:
        ...
    def hoisted_allocations(self):  # -> list[Any]:
        ...
    def compute_graph_info(self, _a):  # -> tuple[list[Any], set[Any]]:

        ...
    def get_stats(self, fadj, nadj, root):  # -> tuple[int, Any]:

        ...
    def reachable_nodes(self, adj, root):  # -> list[Any]:

        ...
    def sort_pf_by_line(self, pf_id, parfors_simple):  # -> int:

        ...
    def get_parfors_simple(self, print_loop_search):  # -> dict[Any, Any]:
        ...
    def get_all_lines(self, parfors_simple):  # -> dict[Any, Any]:
        ...
    def source_listing(self, parfors_simple, purpose_str):  # -> None:
        ...
    def print_unoptimised(self, lines):  # -> None:
        ...
    def print_optimised(self, lines):  # -> None:
        ...
    def allocation_hoist(self):  # -> None:
        ...
    def instruction_hoist(self):  # -> None:
        ...
    def dump(self, level=...): ...

class PreParforPass:
    def __init__(self, func_ir, typemap, calltypes, typingctx, targetctx, options, swapped=..., replace_functions_map=...) -> None: ...
    def run(self):  # -> None:

        ...

def find_template(op):  # -> None:
    ...

class ParforPassStates:
    def __init__(
        self, func_ir, typemap, calltypes, return_type, typingctx, targetctx, options, flags, metadata, diagnostics=...
    ) -> None: ...

class ConvertInplaceBinop:
    def __init__(self, pass_states) -> None: ...
    def run(self, blocks):  # -> None:
        ...

def get_index_var(x):  # -> Var:
    ...

class ConvertSetItemPass:
    def __init__(self, pass_states) -> None: ...
    def run(self, blocks):  # -> None:
        ...

class ConvertNumpyPass:
    def __init__(self, pass_states) -> None: ...
    def run(self, blocks):  # -> None:
        ...

class ConvertReducePass:
    def __init__(self, pass_states) -> None: ...
    def run(self, blocks):  # -> None:
        ...

class ConvertLoopPass:
    def __init__(self, pass_states) -> None: ...
    def run(self, blocks): ...

class ParforPass(ParforPassStates):
    def run(self):  # -> None:

        ...

class ParforFusionPass(ParforPassStates):
    def run(self):  # -> None:

        ...
    def fuse_parfors(self, array_analysis, blocks, func_ir, typemap):  # -> None:
        ...
    def fuse_recursive_parfor(self, parfor, equiv_set, func_ir, typemap):  # -> None:
        ...

class ParforPreLoweringPass(ParforPassStates):
    def run(self):  # -> None:

        ...

def lower_parfor_sequential(typingctx, func_ir, typemap, calltypes, metadata):  # -> None:
    ...
def get_parfor_params(blocks, options_fusion, fusion_info):  # -> tuple[set[Any], list[Any]]:

    ...
def get_parfor_params_inner(parfor, pre_defs, options_fusion, fusion_info): ...
def get_array_indexed_with_parfor_index_internal(loop_body, index, ret_indexed, ret_not_indexed, nest_indices, func_ir):  # -> None:
    ...
def get_array_indexed_with_parfor_index(loop_body, index, nest_indices, func_ir):  # -> tuple[set[Any], set[Any]]:
    ...
def get_parfor_outputs(parfor, parfor_params):  # -> list[Any]:

    ...

_RedVarInfo = ...

def get_parfor_reductions(
    func_ir, parfor, parfor_params, calltypes, reductions=..., reduce_varnames=..., param_uses=..., param_nodes=..., var_to_param=...
):  # -> tuple[Any | list[Any], Any | dict[Any, Any]]:

    ...
def check_conflicting_reduction_operators(param, nodes):  # -> None:

    ...
def get_reduction_init(
    nodes,
):  # -> tuple[Literal[0], Callable[[Any, Any], Any] | Any] | tuple[Literal[1], Callable[[Any, Any], Any] | Any] | tuple[None, None]:

    ...
def supported_reduction(x, func_ir):  # -> bool:
    ...
def get_reduce_nodes(reduction_node, nodes, func_ir):  # -> None:

    ...
def get_expr_args(expr):  # -> list[Any]:

    ...
def visit_parfor_pattern_vars(parfor, callback, cbdata):  # -> None:
    ...
def visit_vars_parfor(parfor, callback, cbdata):  # -> None:
    ...
def parfor_defs(parfor, use_set=..., def_set=...):  # -> use_defs_result:

    ...
def parfor_insert_dels(parfor, curr_dead_set) -> None:  # -> set[Any | str]:

    ...
def maximize_fusion(func_ir, blocks, typemap, up_direction=...):  # -> None:

    ...
def maximize_fusion_inner(func_ir, block, call_table, alias_map, arg_aliases, up_direction=...):  # -> bool:
    ...
def expand_aliases(the_set, alias_map, arg_aliases):  # -> set[Any]:
    ...
def is_assert_equiv(func_ir, expr):  # -> bool:
    ...
def get_parfor_writes(parfor):  # -> set[Any]:
    ...

FusionReport = ...

def try_fuse(equiv_set, parfor1, parfor2, metadata, func_ir, typemap):  # -> tuple[None, FusionReport] | tuple[Any, FusionReport]:

    ...
def fuse_parfors_inner(parfor1, parfor2):  # -> tuple[Any, FusionReport]:
    ...
def remove_duplicate_definitions(blocks, nameset):  # -> None:

    ...
def has_cross_iter_dep(
    parfor, func_ir, typemap, index_positions=..., indexed_arrays=..., non_indexed_arrays=...
):  # -> tuple[Literal[True], Any | dict[Any, Any], set[Any] | Any, set[Any] | Any] | tuple[Literal[False], Any | dict[Any, Any], set[Any] | Any, set[Any] | Any]:
    ...
def dprint(*s):  # -> None:
    ...
def get_parfor_pattern_vars(parfor):  # -> set[Any]:

    ...
def remove_dead_parfor(parfor, lives, lives_n_aliases, arg_aliases, alias_map, func_ir, typemap):  # -> None:

    ...
def remove_dead_parfor_recursive(parfor, lives, arg_aliases, alias_map, func_ir, typemap):  # -> None:

    ...
def find_potential_aliases_parfor(parfor, args, typemap, func_ir, alias_map, arg_aliases):  # -> None:
    ...
def simplify_parfor_body_CFG(blocks):  # -> int:

    ...
def wrap_parfor_blocks(parfor, entry_label=...): ...
def unwrap_parfor_blocks(parfor, blocks=...):  # -> None:

    ...
def get_copies_parfor(parfor, typemap):  # -> tuple[Any, Any]:

    ...
def apply_copies_parfor(parfor, var_dict, name_var_table, typemap, calltypes, save_copies):  # -> None:

    ...
def push_call_vars(blocks, saved_globals, saved_getattrs, typemap, nested=...):  # -> None:

    ...
def repr_arrayexpr(arrayexpr):  # -> str:

    ...
def fix_generator_types(generator_info, return_type, typemap):  # -> None:

    ...
def get_parfor_call_table(parfor, call_table=..., reverse_call_table=...):  # -> tuple[Any | dict[Any, Any], Any | dict[Any, Any]]:
    ...
def get_parfor_tuple_table(parfor, tuple_table=...):  # -> dict[Any, Any]:
    ...
def get_parfor_array_accesses(parfor, accesses=...):  # -> set[Any]:
    ...
def parfor_add_offset_to_labels(parfor, offset):  # -> None:
    ...
def parfor_find_max_label(parfor):  # -> Literal[0]:
    ...
def parfor_typeinfer(parfor, typeinferer):  # -> None:
    ...
def build_parfor_definitions(parfor, definitions=...):  # -> defaultdict[Any, list[Any]]:

    ...
@contextmanager
def dummy_return_in_loop_body(loop_body):  # -> Generator[None, Any, None]:

    ...

@infer_global(reduce)
class ReduceInfer(AbstractTemplate):
    def generic(self, args, kws):  # -> Signature:
        ...

def ensure_parallel_support():  # -> None:

    ...
