from numba.core import ir

_CallableNode = ...

class ParforLoweringBuilder:
    def __init__(self, lowerer, scope, loc) -> None: ...
    def bind_global_function(self, fobj, ftype, args, kws=...):  # -> BoundFunc:

        ...
    def make_const_variable(self, cval, typ, name=...) -> ir.Var: ...
    def make_tuple_variable(self, varlist, name=...) -> ir.Var: ...
    def assign(self, rhs, typ, name=...) -> ir.Var: ...
    def assign_inplace(self, rhs, typ, name) -> ir.Var: ...
    def call(self, callable_node, args, kws=...) -> ir.Expr: ...
    def setitem(self, obj, index, val) -> ir.SetItem: ...
    def getitem(self, obj, index, typ) -> ir.Expr: ...
