"""
This type stub file was generated by pyright.
"""

from .partition import PandasOnDaskDataframePartition
from .partition_manager import PandasOnDaskDataframePartitionManager
from .virtual_partition import PandasOnDaskDataframeColumnPartition, PandasOnDaskDataframeRowPartition, PandasOnDaskDataframeVirtualPartition

"""Base Modin Dataframe classes related to its partitioning and optimized for pandas on Dask execution."""
__all__ = ["PandasOnDaskDataframePartition", "PandasOnDaskDataframePartitionManager", "PandasOnDaskDataframeVirtualPartition", "PandasOnDaskDataframeColumnPartition", "PandasOnDaskDataframeRowPartition"]
