import weakref
from abc import ABCMeta, abstractmethod
from functools import cached_property

_typecodes = ...
_typecache: dict[weakref.ref, weakref.ref] = ...

class _TypeMetaclass(ABCMeta):
    def __init__(cls, name, bases, orig_vars) -> None: ...
    def __call__(cls, *args, **kwargs): ...

class Type(metaclass=_TypeMetaclass):
    mutable = ...
    reflected = ...
    def __init__(self, name) -> None: ...
    @property
    def key(self): ...
    @property
    def mangling_args(self): ...
    def __hash__(self) -> int: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __reduce__(self): ...
    def unify(self, typingctx, other): ...
    def can_convert_to(self, typingctx, other): ...
    def can_convert_from(self, typingctx, other): ...
    def is_precise(self): ...
    def augment(self, other): ...
    def __call__(self, *args): ...
    def __getitem__(self, args): ...
    def cast_python_value(self, args): ...
    @property
    def is_internal(self): ...
    def dump(self, tab=...): ...

class Dummy(Type): ...
class Hashable(Type): ...

class Number(Hashable):
    def unify(self, typingctx, other): ...

class Callable(Type):
    @abstractmethod
    def get_call_type(self, context, args, kws): ...
    @abstractmethod
    def get_call_signatures(self): ...
    @abstractmethod
    def get_impl_key(self, sig): ...

class DTypeSpec(Type):
    @property
    @abstractmethod
    def dtype(self): ...

class IterableType(Type):
    @property
    @abstractmethod
    def iterator_type(self): ...

class Sized(Type): ...

class ConstSized(Sized):
    @abstractmethod
    def __len__(self) -> int: ...

class IteratorType(IterableType):
    def __init__(self, name, **kwargs) -> None: ...
    @property
    @abstractmethod
    def yield_type(self): ...
    @property
    def iterator_type(self): ...

class Container(Sized, IterableType): ...
class Sequence(Container): ...

class MutableSequence(Sequence):
    mutable = ...

class ArrayCompatible(Type):
    array_priority = ...
    @property
    @abstractmethod
    def as_array(self): ...
    @cached_property
    def ndim(self): ...
    @cached_property
    def layout(self): ...
    @cached_property
    def dtype(self): ...

class Literal(Type):
    ctor_map: dict[type, type[Literal]] = ...
    _literal_type_cache = ...
    def __init__(self, value) -> None: ...
    @property
    def literal_value(self): ...
    @property
    def literal_type(self): ...

class TypeRef(Dummy):
    def __init__(self, instance_type) -> None: ...
    @property
    def key(self): ...

class InitialValue:
    def __init__(self, initial_value) -> None: ...
    @property
    def initial_value(self): ...

class Poison(Type):
    def __init__(self, ty) -> None: ...
    def __unliteral__(self): ...
    def unify(self, typingctx, other): ...
