from .abstract import ArrayCompatible, Dummy, IterableType, IteratorType

class Opaque(Dummy): ...

class SimpleIterableType(IterableType):
    def __init__(self, name, iterator_type) -> None: ...
    @property
    def iterator_type(self): ...

class SimpleIteratorType(IteratorType):
    def __init__(self, name, yield_type) -> None: ...
    @property
    def yield_type(self): ...

class Buffer(IterableType, ArrayCompatible):
    mutable = ...
    slice_is_copy = ...
    aligned = ...
    LAYOUTS = ...
    def __init__(self, dtype, ndim, layout, readonly=..., name=...) -> None: ...
    @property
    def iterator_type(self): ...
    @property
    def as_array(self): ...
    def copy(self, dtype=..., ndim=..., layout=...): ...
    @property
    def key(self): ...
    @property
    def is_c_contig(self): ...
    @property
    def is_f_contig(self): ...
    @property
    def is_contig(self): ...
