from collections.abc import Sequence as pySequence

from .abstract import ConstSized, Container, Hashable, InitialValue, Literal, MutableSequence, Sequence, Type
from .common import Buffer, IterableType, SimpleIterableType, SimpleIteratorType

class Pair(Type):
    def __init__(self, first_type, second_type) -> None: ...
    @property
    def key(self): ...
    def unify(self, typingctx, other): ...

class BaseContainerIterator(SimpleIteratorType):
    def __init__(self, container) -> None: ...
    def unify(self, typingctx, other): ...
    @property
    def key(self): ...

class BaseContainerPayload(Type):
    def __init__(self, container) -> None: ...
    @property
    def key(self): ...

class Bytes(Buffer):
    mutable = ...
    slice_is_copy = ...

class ByteArray(Buffer):
    slice_is_copy = ...

class PyArray(Buffer):
    slice_is_copy = ...

class MemoryView(Buffer): ...

def is_homogeneous(*tys): ...

class BaseTuple(ConstSized, Hashable):
    @classmethod
    def from_types(cls, tys, pyclass=...): ...

class BaseAnonymousTuple(BaseTuple):
    def can_convert_to(self, typingctx, other): ...
    def __unliteral__(self): ...

class _HomogeneousTuple(Sequence, BaseTuple):
    @property
    def iterator_type(self): ...
    def __getitem__(self, i): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    @property
    def types(self): ...

class UniTuple(BaseAnonymousTuple, _HomogeneousTuple, Sequence):
    def __init__(self, dtype, count) -> None: ...
    @property
    def mangling_args(self): ...
    @property
    def key(self): ...
    def unify(self, typingctx, other): ...
    def __unliteral__(self): ...

class UniTupleIter(BaseContainerIterator):
    container_class = _HomogeneousTuple

class _HeterogeneousTuple(BaseTuple):
    def __getitem__(self, i): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    @staticmethod
    def is_types_iterable(types): ...

class UnionType(Type):
    def __init__(self, types) -> None: ...
    def get_type_tag(self, typ): ...

class Tuple(BaseAnonymousTuple, _HeterogeneousTuple):
    def __new__(cls, types): ...
    def __init__(self, types) -> None: ...
    @property
    def mangling_args(self): ...
    @property
    def key(self): ...
    def unify(self, typingctx, other): ...

class _StarArgTupleMixin: ...

class StarArgTuple(_StarArgTupleMixin, Tuple):
    def __new__(cls, types): ...

class StarArgUniTuple(_StarArgTupleMixin, UniTuple): ...
class BaseNamedTuple(BaseTuple): ...

class NamedUniTuple(_HomogeneousTuple, BaseNamedTuple):
    def __init__(self, dtype, count, cls) -> None: ...
    @property
    def iterator_type(self): ...
    @property
    def key(self): ...

class NamedTuple(_HeterogeneousTuple, BaseNamedTuple):
    def __init__(self, types, cls) -> None: ...
    @property
    def key(self): ...

class List(MutableSequence, InitialValue):
    def __init__(self, dtype, reflected=..., initial_value=...) -> None: ...
    def copy(self, dtype=..., reflected=...): ...
    def unify(self, typingctx, other): ...
    @property
    def key(self): ...
    @property
    def iterator_type(self): ...
    def is_precise(self): ...
    def __getitem__(self, args): ...
    def __unliteral__(self): ...

class LiteralList(Literal, ConstSized, Hashable):
    mutable = ...
    def __init__(self, literal_value) -> None: ...
    def __getitem__(self, i): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    @classmethod
    def from_types(cls, tys): ...
    @staticmethod
    def is_types_iterable(types): ...
    @property
    def iterator_type(self): ...
    def __unliteral__(self): ...
    def unify(self, typingctx, other): ...

class ListIter(BaseContainerIterator):
    container_class = List

class ListPayload(BaseContainerPayload):
    container_class = List

class Set(Container):
    mutable = ...
    def __init__(self, dtype, reflected=...) -> None: ...
    @property
    def key(self): ...
    @property
    def iterator_type(self): ...
    def is_precise(self): ...
    def copy(self, dtype=..., reflected=...): ...
    def unify(self, typingctx, other): ...

class SetIter(BaseContainerIterator):
    container_class = Set

class SetPayload(BaseContainerPayload):
    container_class = Set

class SetEntry(Type):
    def __init__(self, set_type) -> None: ...
    @property
    def key(self): ...

class ListType(IterableType):
    mutable = ...
    def __init__(self, itemty) -> None: ...
    @property
    def key(self): ...
    def is_precise(self): ...
    @property
    def iterator_type(self): ...
    @classmethod
    def refine(cls, itemty): ...
    def unify(self, typingctx, other): ...

class ListTypeIterableType(SimpleIterableType):
    def __init__(self, parent) -> None: ...

class ListTypeIteratorType(SimpleIteratorType):
    def __init__(self, iterable) -> None: ...

class DictType(IterableType, InitialValue):
    def __init__(self, keyty, valty, initial_value=...) -> None: ...
    def is_precise(self): ...
    @property
    def iterator_type(self): ...
    @classmethod
    def refine(cls, keyty, valty): ...
    def unify(self, typingctx, other): ...
    @property
    def key(self): ...
    def __unliteral__(self): ...

class LiteralStrKeyDict(Literal, ConstSized, Hashable):
    class FakeNamedTuple(pySequence):
        def __init__(self, name, keys) -> None: ...
        def __len__(self) -> int: ...
        def __getitem__(self, key): ...

    mutable = ...
    def __init__(self, literal_value, value_index=...) -> None: ...
    def __unliteral__(self): ...
    def unify(self, typingctx, other): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    @property
    def key(self): ...

class DictItemsIterableType(SimpleIterableType):
    def __init__(self, parent) -> None: ...

class DictKeysIterableType(SimpleIterableType):
    def __init__(self, parent) -> None: ...

class DictValuesIterableType(SimpleIterableType):
    def __init__(self, parent) -> None: ...

class DictIteratorType(SimpleIteratorType):
    def __init__(self, iterable) -> None: ...

class StructRef(Type):
    def __init__(self, fields) -> None: ...
    def preprocess_fields(self, fields): ...
    @property
    def field_dict(self): ...
    def get_data_type(self): ...

class StructRefPayload(Type):
    mutable = ...
    def __init__(self, typename, fields) -> None: ...
    @property
    def field_dict(self): ...
