from .abstract import Callable, DTypeSpec, Dummy, Literal, Type, weakref
from .common import Opaque

_logger = ...
_termcolor = ...
_FAILURE = ...
_termwidth = ...
_header_lead = ...
_header_template = ...
_reason_template = ...
_overload_template = ...
_err_reasons = ...

def argsnkwargs_to_str(args, kwargs): ...

class _ResolutionFailures:
    def __init__(self, context, function_type, args, kwargs, depth=...) -> None: ...
    def __len__(self) -> int: ...
    def add_error(self, calltemplate, matched, error, literal): ...
    def format(self): ...
    def format_error(self, error): ...
    def get_loc(self, classtemplate, error): ...
    def raise_error(self): ...

class BaseFunction(Callable):
    def __init__(self, template) -> None: ...
    @property
    def key(self): ...
    def augment(self, other): ...
    def get_impl_key(self, sig): ...
    def get_call_type(self, context, args, kws): ...
    def get_call_signatures(self): ...

class Function(BaseFunction, Opaque): ...

class BoundFunction(Callable, Opaque):
    def __init__(self, template, this) -> None: ...
    def unify(self, typingctx, other): ...
    def copy(self, this): ...
    @property
    def key(self): ...
    def get_impl_key(self, sig): ...
    def get_call_type(self, context, args, kws): ...
    def get_call_signatures(self): ...

class MakeFunctionLiteral(Literal, Opaque): ...

class _PickleableWeakRef(weakref.ref):
    def __getnewargs__(self): ...

class WeakType(Type):
    @property
    def key(self): ...
    def __eq__(self, other) -> bool: ...
    def __hash__(self) -> int: ...

class Dispatcher(WeakType, Callable, Dummy):
    def __init__(self, dispatcher) -> None: ...
    def dump(self, tab=...): ...
    def get_call_type(self, context, args, kws): ...
    def get_call_signatures(self): ...
    @property
    def dispatcher(self): ...
    def get_overload(self, sig): ...
    def get_impl_key(self, sig): ...
    def unify(self, context, other): ...
    def can_convert_to(self, typingctx, other): ...

class ObjModeDispatcher(Dispatcher): ...

class ExternalFunctionPointer(BaseFunction):
    def __init__(self, sig, get_pointer, cconv=...) -> None: ...
    @property
    def key(self): ...

class ExternalFunction(Function):
    def __init__(self, symbol, sig) -> None: ...
    @property
    def key(self): ...

class NamedTupleClass(Callable, Opaque):
    def __init__(self, instance_class) -> None: ...
    def get_call_type(self, context, args, kws): ...
    def get_call_signatures(self): ...
    def get_impl_key(self, sig): ...
    @property
    def key(self): ...

class NumberClass(Callable, DTypeSpec, Opaque):
    def __init__(self, instance_type) -> None: ...
    def get_call_type(self, context, args, kws): ...
    def get_call_signatures(self): ...
    def get_impl_key(self, sig): ...
    @property
    def key(self): ...
    @property
    def dtype(self): ...

_RecursiveCallOverloads = ...

class RecursiveCall(Opaque):
    _overloads = ...
    def __init__(self, dispatcher_type) -> None: ...
    def add_overloads(self, args, qualname, uid): ...
    def get_overloads(self, args): ...
    @property
    def key(self): ...
