from abc import ABC, abstractmethod

from .abstract import Type

__all__ = ["CompileResultWAP", "FunctionPrototype", "FunctionType", "UndefinedFunctionType", "WrapperAddressProtocol"]

class FunctionType(Type):
    cconv = ...
    def __init__(self, signature) -> None: ...
    @property
    def key(self): ...
    @property
    def name(self): ...
    def is_precise(self): ...
    def get_precise(self): ...
    def dump(self, tab=...): ...
    def get_call_type(self, context, args, kws): ...
    def check_signature(self, other_sig): ...
    def unify(self, context, other): ...

class UndefinedFunctionType(FunctionType):
    _counter = ...
    def __init__(self, nargs, dispatchers) -> None: ...
    def get_precise(self): ...

class FunctionPrototype(Type):
    cconv = ...
    def __init__(self, rtype, atypes) -> None: ...
    @property
    def key(self): ...

class WrapperAddressProtocol(ABC):
    @abstractmethod
    def __wrapper_address__(self): ...
    @abstractmethod
    def signature(self): ...

class CompileResultWAP(WrapperAddressProtocol):
    def __init__(self, cres) -> None: ...
    def dump(self, tab=...): ...
    def __wrapper_address__(self): ...
    def signature(self): ...
    def __call__(self, *args, **kwargs): ...
