from .common import SimpleIterableType, SimpleIteratorType

class RangeType(SimpleIterableType):
    def __init__(self, dtype) -> None: ...
    def unify(self, typingctx, other): ...

class RangeIteratorType(SimpleIteratorType):
    def __init__(self, dtype) -> None: ...
    def unify(self, typingctx, other): ...

class Generator(SimpleIteratorType):
    def __init__(self, gen_func, yield_type, arg_types, state_types, has_finalizer) -> None: ...
    @property
    def key(self): ...

class EnumerateType(SimpleIteratorType):
    def __init__(self, iterable_type) -> None: ...
    @property
    def key(self): ...

class ZipType(SimpleIteratorType):
    def __init__(self, iterable_types) -> None: ...
    @property
    def key(self): ...

class ArrayIterator(SimpleIteratorType):
    def __init__(self, array_type) -> None: ...
