from numba.core.types.abstract import Callable, Hashable, Literal, Type
from numba.core.types.common import Dummy, IterableType, Opaque, SimpleIteratorType

class PyObject(Dummy):
    def is_precise(self): ...

class Phantom(Dummy): ...

class Undefined(Dummy):
    def is_precise(self): ...

class UndefVar(Dummy):
    def can_convert_to(self, typingctx, other): ...

class RawPointer(Opaque): ...

class StringLiteral(Literal, Dummy):
    def can_convert_to(self, typingctx, other): ...

def unliteral(lit_type): ...
def literal(value): ...
def maybe_literal(value): ...

class Omitted(Opaque):
    def __init__(self, value) -> None: ...
    @property
    def key(self): ...
    @property
    def value(self): ...

class VarArg(Type):
    def __init__(self, dtype) -> None: ...
    @property
    def key(self): ...

class Module(Dummy):
    def __init__(self, pymod) -> None: ...
    @property
    def key(self): ...

class MemInfoPointer(Type):
    mutable = ...
    def __init__(self, dtype) -> None: ...
    @property
    def key(self): ...

class CPointer(Type):
    mutable = ...
    def __init__(self, dtype, addrspace=...) -> None: ...
    @property
    def key(self): ...

class EphemeralPointer(CPointer): ...

class EphemeralArray(Type):
    def __init__(self, dtype, count) -> None: ...
    @property
    def key(self): ...

class Object(Type):
    mutable = ...
    def __init__(self, clsobj) -> None: ...
    @property
    def key(self): ...

class Optional(Type):
    def __init__(self, typ) -> None: ...
    @property
    def key(self): ...
    def can_convert_to(self, typingctx, other): ...
    def can_convert_from(self, typingctx, other): ...
    def unify(self, typingctx, other): ...

class NoneType(Opaque):
    def unify(self, typingctx, other): ...

class EllipsisType(Opaque): ...

class ExceptionClass(Callable, Phantom):
    def __init__(self, exc_class) -> None: ...
    def get_call_type(self, context, args, kws): ...
    def get_call_signatures(self): ...
    def get_impl_key(self, sig): ...
    @property
    def key(self): ...

class ExceptionInstance(Phantom):
    def __init__(self, exc_class) -> None: ...
    @property
    def key(self): ...

class SliceType(Type):
    def __init__(self, name, members) -> None: ...
    @property
    def key(self): ...

class SliceLiteral(Literal, SliceType):
    def __init__(self, value) -> None: ...
    @property
    def key(self): ...

class ClassInstanceType(Type):
    mutable = ...
    name_prefix = ...
    def __init__(self, class_type) -> None: ...
    def get_data_type(self): ...
    def get_reference_type(self): ...
    @property
    def key(self): ...
    @property
    def classname(self): ...
    @property
    def jit_props(self): ...
    @property
    def jit_static_methods(self): ...
    @property
    def jit_methods(self): ...
    @property
    def struct(self): ...
    @property
    def methods(self): ...
    @property
    def static_methods(self): ...

class ClassType(Callable, Opaque):
    mutable = ...
    name_prefix = ...
    instance_type_class = ClassInstanceType
    def __init__(self, class_def, ctor_template_cls, struct, jit_methods, jit_props, jit_static_methods) -> None: ...
    def get_call_type(self, context, args, kws): ...
    def get_call_signatures(self): ...
    def get_impl_key(self, sig): ...
    @property
    def methods(self): ...
    @property
    def static_methods(self): ...
    @property
    def instance_type(self): ...
    @property
    def ctor_template(self): ...

class DeferredType(Type):
    def __init__(self) -> None: ...
    def get(self): ...
    def define(self, typ): ...
    def unify(self, typingctx, other): ...

class ClassDataType(Type):
    def __init__(self, classtyp) -> None: ...

class ContextManager(Callable, Phantom):
    def __init__(self, cm) -> None: ...
    def get_call_signatures(self): ...
    def get_call_type(self, context, args, kws): ...
    def get_impl_key(self, sig): ...

class UnicodeType(IterableType, Hashable):
    def __init__(self, name) -> None: ...
    @property
    def iterator_type(self): ...

class UnicodeIteratorType(SimpleIteratorType):
    def __init__(self, dtype) -> None: ...
