from functools import cached_property

from .abstract import DTypeSpec, IteratorType, MutableSequence, Type
from .common import Buffer, Opaque, SimpleIteratorType

class CharSeq(Type):
    mutable = ...
    def __init__(self, count) -> None: ...
    @property
    def key(self): ...
    def can_convert_from(self, typingctx, other): ...

class UnicodeCharSeq(Type):
    mutable = ...
    def __init__(self, count) -> None: ...
    @property
    def key(self): ...
    def can_convert_to(self, typingctx, other): ...
    def can_convert_from(self, typingctx, other): ...

_RecordField = ...

class Record(Type):
    mutable = ...
    @classmethod
    def make_c_struct(cls, name_types): ...
    def __init__(self, fields, size, aligned) -> None: ...
    @property
    def key(self): ...
    @property
    def mangling_args(self): ...
    def __len__(self) -> int: ...
    def offset(self, key): ...
    def typeof(self, key): ...
    def alignof(self, key): ...
    def has_titles(self): ...
    def is_title(self, key): ...
    @property
    def members(self): ...
    @property
    def dtype(self): ...
    def can_convert_to(self, typingctx, other): ...

class DType(DTypeSpec, Opaque):
    def __init__(self, dtype) -> None: ...
    @property
    def key(self): ...
    @property
    def dtype(self): ...
    def __getitem__(self, arg): ...

class NumpyFlatType(SimpleIteratorType, MutableSequence):
    def __init__(self, arrty) -> None: ...
    @property
    def key(self): ...

class NumpyNdEnumerateType(SimpleIteratorType):
    def __init__(self, arrty) -> None: ...
    @property
    def key(self): ...

class NumpyNdIterType(IteratorType):
    def __init__(self, arrays) -> None: ...
    @property
    def key(self): ...
    @property
    def views(self): ...
    @property
    def yield_type(self): ...
    @cached_property
    def indexers(self): ...
    @cached_property
    def need_shaped_indexing(self): ...

class NumpyNdIndexType(SimpleIteratorType):
    def __init__(self, ndim) -> None: ...
    @property
    def key(self): ...

class Array(Buffer):
    def __init__(self, dtype, ndim, layout, readonly=..., name=..., aligned=...) -> None: ...
    @property
    def mangling_args(self): ...
    def copy(self, dtype=..., ndim=..., layout=..., readonly=...): ...
    @property
    def key(self): ...
    def unify(self, typingctx, other): ...
    def can_convert_to(self, typingctx, other): ...
    def is_precise(self): ...
    @property
    def box_type(self): ...

class ArrayCTypes(Type):
    def __init__(self, arytype) -> None: ...
    @property
    def key(self): ...
    def can_convert_to(self, typingctx, other): ...

class ArrayFlags(Type):
    def __init__(self, arytype) -> None: ...
    @property
    def key(self): ...

class NestedArray(Array):
    def __init__(self, dtype, shape) -> None: ...
    @property
    def shape(self): ...
    @property
    def nitems(self): ...
    @property
    def size(self): ...
    @property
    def strides(self): ...
    @property
    def key(self): ...

class NumPyRandomBitGeneratorType(Type):
    def __init__(self, *args, **kwargs) -> None: ...

class NumPyRandomGeneratorType(Type):
    def __init__(self, *args, **kwargs) -> None: ...

class PolynomialType(Type):
    def __init__(self, coef, domain=..., window=..., n_args=...) -> None: ...
