from functools import cached_property, total_ordering

from .abstract import Dummy, Hashable, Literal, Number, Type

class Boolean(Hashable):
    def cast_python_value(self, value): ...

def parse_integer_bitwidth(name): ...
def parse_integer_signed(name): ...

@total_ordering
class Integer(Number):
    def __init__(self, name, bitwidth=..., signed=...) -> None: ...
    @classmethod
    def from_bitwidth(cls, bitwidth, signed=...): ...
    def cast_python_value(self, value): ...
    def __lt__(self, other) -> bool: ...
    @property
    def maxval(self): ...
    @property
    def minval(self): ...

class IntegerLiteral(Literal, Integer):
    def __init__(self, value) -> None: ...
    def can_convert_to(self, typingctx, other): ...

class BooleanLiteral(Literal, Boolean):
    def __init__(self, value) -> None: ...
    def can_convert_to(self, typingctx, other): ...

@total_ordering
class Float(Number):
    def __init__(self, *args, **kws) -> None: ...
    def cast_python_value(self, value): ...
    def __lt__(self, other) -> bool: ...

@total_ordering
class Complex(Number):
    def __init__(self, name, underlying_float, **kwargs) -> None: ...
    def cast_python_value(self, value): ...
    def __lt__(self, other) -> bool: ...

class _NPDatetimeBase(Type):
    def __init__(self, unit, *args, **kws) -> None: ...
    def __lt__(self, other) -> bool: ...
    def cast_python_value(self, value): ...

@total_ordering
class NPTimedelta(_NPDatetimeBase):
    type_name = ...

@total_ordering
class NPDatetime(_NPDatetimeBase):
    type_name = ...

class EnumClass(Dummy):
    basename = ...
    def __init__(self, cls, dtype) -> None: ...
    @property
    def key(self): ...
    @cached_property
    def member_type(self): ...

class IntEnumClass(EnumClass):
    basename = ...
    @cached_property
    def member_type(self): ...

class EnumMember(Type):
    basename = ...
    class_type_class = EnumClass
    def __init__(self, cls, dtype) -> None: ...
    @property
    def key(self): ...
    @property
    def class_type(self): ...

class IntEnumMember(EnumMember):
    basename = ...
    class_type_class = IntEnumClass
    def can_convert_to(self, typingctx, other): ...
