# pyright: reportPropertyTypeMismatch=false
from collections.abc import Hashable, Sequence
from typing import Any

import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.graph_objs.scatter.selected as _selected
import plotly.graph_objs.scatter.unselected as _unselected
from numpy.typing import ArrayLike
from pandas import DataFrame, Series
from plotly.graph_objs.scatter import (
    ErrorX,
    ErrorY,
    Fillgradient,
    Fillpattern,
    Hoverlabel,
    Legendgrouptitle,
    Marker,
    Selected,
    Stream,
    Textfont,
    Unselected,
)
from plotly.graph_objs.scatter import (
    Line as _Line,
)

class Line(go.Scatter):
    def __init__(
        self,
        label_name: bool | str = False,
        *,
        alignmentgroup: str | int | None = ...,
        cliponaxis: bool | None = ...,
        connectgaps: bool | None = ...,
        customdata: Sequence[float] | np.ndarray[tuple[int, ...], np.dtype[np.float64]] | pd.Series[float] | None = ...,
        customdatasrc: str | None = ...,
        dx: float | None = ...,
        dy: float | None = ...,
        error_x: ErrorX | dict[str, Any] | None = ...,
        error_y: ErrorY | dict[str, Any] | None = ...,
        fill: str | None = ...,
        fillcolor: str | None = ...,
        fillgradient: Fillgradient | dict[str, Any] | None = ...,
        fillpattern: Fillpattern | dict[str, Any] | None = ...,
        groupnorm: str | None = ...,
        hoverinfo: str | Sequence[str] | None = ...,
        hoverinfosrc: str | None = ...,
        hoverlabel: Hoverlabel | dict[str, Any] | None = ...,
        hoveron: str | None = ...,
        hovertemplate: str | float | Sequence[str] | Sequence[float] | np.ndarray[tuple[int, ...], np.dtype[np.float64]] | None = ...,
        hovertemplatesrc: str | None = ...,
        hovertext: str | float | Sequence[str] | Sequence[float] | np.ndarray[tuple[int, ...], np.dtype[np.float64]] | None = ...,
        hovertextsrc: str | None = ...,
        ids: Sequence[str] | np.ndarray[tuple[int, ...], np.dtype[np.str_]] | pd.Series[str] | None = ...,
        idssrc: str | None = ...,
        legend: str | None = ...,
        legendgroup: str | int | None = ...,
        legendgrouptitle: Legendgrouptitle | dict[str, Any] | None = ...,
        legendrank: float | None = ...,
        legendwidth: float | None = ...,
        line: _Line | dict[str, str | int | float] | None = ...,
        marker: Marker | dict[str, Any] | None = ...,
        meta: Sequence[Any] | dict[str, Any] | np.ndarray[tuple[int, ...], Any] | None = ...,
        metasrc: str | None = ...,
        mode: str | None = ...,
        name: str | int | None = ...,
        offsetgroup: str | int | None = ...,
        opacity: float | None = ...,
        orientation: str | None = ...,
        selected: Selected | dict[str, _selected.Marker | _selected.Textfont | dict[str, Any]] | None = ...,
        selectedpoints: Sequence[int] | None = ...,
        showlegend: bool | None = ...,
        stackgaps: str | None = ...,
        stackgroup: str | int | None = ...,
        stream: Stream | dict[str, int | str] | None = ...,
        text: str | Sequence[str] | None = ...,
        textfont: Textfont | dict[str, Any] | None = ...,
        textposition: str | Sequence[str] | np.ndarray[tuple[int, ...], np.dtype[np.str_]] | None = ...,
        textpositionsrc: str | None = ...,
        textsrc: str | None = ...,
        texttemplate: str | None = ...,
        texttemplatesrc: str | None = ...,
        uid: str | int | None = ...,
        uirevision: Hashable | None = ...,
        unselected: Unselected | dict[str, _unselected.Marker | _unselected.Textfont | dict[str, Any]] | None = ...,
        visible: bool | str | None = ...,
        x: Sequence[Any] | np.ndarray[tuple[int, ...], np.dtype[Any]] | pd.Series[Any] | None = ...,
        x0: float | None = ...,
        xaxis: str | None = ...,
        xcalendar: str | None = ...,
        xhoverformat: str | None = ...,
        xperiod: float | str | None = ...,
        xperiod0: float | str | None = ...,
        xperiodalignment: str | None = ...,
        xsrc: str | None = ...,
        y: Sequence[int] | Sequence[float] | np.ndarray[tuple[int, ...], np.dtype[np.float64]] | pd.Series[float] | None = ...,
        y0: float | None = ...,
        yaxis: str | None = ...,
        ycalendar: str | None = ...,
        yhoverformat: str | None = ...,
        yperiod: float | str | None = ...,
        yperiod0: float | str | None = ...,
        yperiodalignment: str | None = ...,
        ysrc: str | None = ...,
        zorder: int | None = ...,
        **kwargs: Any,  # noqa: ANN401
    ) -> None: ...
    @classmethod
    def from_series(
        cls,
        series: Series,
        /,
        *,
        alignmentgroup: str | int | None = ...,
        cliponaxis: bool | None = ...,
        connectgaps: bool | None = ...,
        customdata: Sequence[float] | np.ndarray[tuple[int, ...], np.dtype[np.float64]] | pd.Series[float] | None = ...,
        customdatasrc: str | None = ...,
        dx: float | None = ...,
        dy: float | None = ...,
        error_x: ErrorX | dict[str, Any] | None = ...,
        error_y: ErrorY | dict[str, Any] | None = ...,
        fill: str | None = ...,
        fillcolor: str | None = ...,
        fillgradient: Fillgradient | dict[str, Any] | None = ...,
        fillpattern: Fillpattern | dict[str, Any] | None = ...,
        groupnorm: str | None = ...,
        hoverinfo: str | Sequence[str] | None = ...,
        hoverinfosrc: str | None = ...,
        hoverlabel: Hoverlabel | dict[str, Any] | None = ...,
        hoveron: str | None = ...,
        hovertemplate: str | float | Sequence[str] | Sequence[float] | np.ndarray[tuple[int, ...], np.dtype[np.float64]] | None = ...,
        hovertemplatesrc: str | None = ...,
        hovertext: str | float | Sequence[str] | Sequence[float] | np.ndarray[tuple[int, ...], np.dtype[np.float64]] | None = ...,
        hovertextsrc: str | None = ...,
        ids: Sequence[str] | np.ndarray[tuple[int, ...], np.dtype[np.str_]] | pd.Series[str] | None = ...,
        idssrc: str | None = ...,
        legend: str | None = ...,
        legendgroup: str | int | None = ...,
        legendgrouptitle: Legendgrouptitle | dict[str, Any] | None = ...,
        legendrank: float | None = ...,
        legendwidth: float | None = ...,
        line: _Line | dict[str, str | int | float] | None = ...,
        marker: Marker | dict[str, Any] | None = ...,
        meta: Sequence[Any] | dict[str, Any] | np.ndarray[tuple[int, ...], Any] | None = ...,
        metasrc: str | None = ...,
        mode: str | None = ...,
        name: str | int | None = ...,
        offsetgroup: str | int | None = ...,
        opacity: float | None = ...,
        orientation: str | None = ...,
        selected: Selected | dict[str, _selected.Marker | _selected.Textfont | dict[str, Any]] | None = ...,
        selectedpoints: Sequence[int] | None = ...,
        showlegend: bool | None = ...,
        stackgaps: str | None = ...,
        stackgroup: str | int | None = ...,
        stream: Stream | dict[str, int | str] | None = ...,
        text: str | Sequence[str] | None = ...,
        textfont: Textfont | dict[str, Any] | None = ...,
        textposition: str | Sequence[str] | np.ndarray[tuple[int, ...], np.dtype[np.str_]] | None = ...,
        textpositionsrc: str | None = ...,
        textsrc: str | None = ...,
        texttemplate: str | None = ...,
        texttemplatesrc: str | None = ...,
        uid: str | int | None = ...,
        uirevision: Hashable | None = ...,
        unselected: Unselected | dict[str, _unselected.Marker | _unselected.Textfont | dict[str, Any]] | None = ...,
        visible: bool | str | None = ...,
        x: Sequence[Any] | np.ndarray[tuple[int, ...], np.dtype[Any]] | pd.Series[Any] | None = ...,
        x0: float | None = ...,
        xaxis: str | None = ...,
        xcalendar: str | None = ...,
        xhoverformat: str | None = ...,
        xperiod: float | str | None = ...,
        xperiod0: float | str | None = ...,
        xperiodalignment: str | None = ...,
        xsrc: str | None = ...,
        y: Sequence[int] | Sequence[float] | np.ndarray[tuple[int, ...], np.dtype[np.float64]] | pd.Series[float] | None = ...,
        y0: float | None = ...,
        yaxis: str | None = ...,
        ycalendar: str | None = ...,
        yhoverformat: str | None = ...,
        yperiod: float | str | None = ...,
        yperiod0: float | str | None = ...,
        yperiodalignment: str | None = ...,
        ysrc: str | None = ...,
        zorder: int | None = ...,
        **kwargs: Any,  # noqa: ANN401
    ) -> Line: ...
    @classmethod
    def with_bounds(
        cls,
        *,
        x: ArrayLike,
        y: ArrayLike,
        y_upper: Sequence[ArrayLike],
        y_lower: Sequence[ArrayLike],
        max_opacity: float = 0.4,
        alignmentgroup: str | int | None = ...,
        cliponaxis: bool | None = ...,
        connectgaps: bool | None = ...,
        customdata: Sequence[float] | np.ndarray[tuple[int, ...], np.dtype[np.float64]] | pd.Series[float] | None = ...,
        customdatasrc: str | None = ...,
        dx: float | None = ...,
        dy: float | None = ...,
        error_x: ErrorX | dict[str, Any] | None = ...,
        error_y: ErrorY | dict[str, Any] | None = ...,
        fill: str | None = ...,
        fillcolor: str | None = ...,
        fillgradient: Fillgradient | dict[str, Any] | None = ...,
        fillpattern: Fillpattern | dict[str, Any] | None = ...,
        groupnorm: str | None = ...,
        hoverinfo: str | Sequence[str] | None = ...,
        hoverinfosrc: str | None = ...,
        hoverlabel: Hoverlabel | dict[str, Any] | None = ...,
        hoveron: str | None = ...,
        hovertemplate: str | float | Sequence[str] | Sequence[float] | np.ndarray[tuple[int, ...], np.dtype[np.float64]] | None = ...,
        hovertemplatesrc: str | None = ...,
        hovertext: str | float | Sequence[str] | Sequence[float] | np.ndarray[tuple[int, ...], np.dtype[np.float64]] | None = ...,
        hovertextsrc: str | None = ...,
        ids: Sequence[str] | np.ndarray[tuple[int, ...], np.dtype[np.str_]] | pd.Series[str] | None = ...,
        idssrc: str | None = ...,
        legend: str | None = ...,
        legendgroup: str | int | None = ...,
        legendgrouptitle: Legendgrouptitle | dict[str, Any] | None = ...,
        legendrank: float | None = ...,
        legendwidth: float | None = ...,
        line: _Line | dict[str, str | int | float] | None = ...,
        marker: Marker | dict[str, Any] | None = ...,
        meta: Sequence[Any] | dict[str, Any] | np.ndarray[tuple[int, ...], Any] | None = ...,
        metasrc: str | None = ...,
        mode: str | None = ...,
        name: str | int | None = ...,
        offsetgroup: str | int | None = ...,
        opacity: float | None = ...,
        orientation: str | None = ...,
        selected: Selected | dict[str, _selected.Marker | _selected.Textfont | dict[str, Any]] | None = ...,
        selectedpoints: Sequence[int] | None = ...,
        showlegend: bool | None = ...,
        stackgaps: str | None = ...,
        stackgroup: str | int | None = ...,
        stream: Stream | dict[str, int | str] | None = ...,
        text: str | Sequence[str] | None = ...,
        textfont: Textfont | dict[str, Any] | None = ...,
        textposition: str | Sequence[str] | np.ndarray[tuple[int, ...], np.dtype[np.str_]] | None = ...,
        textpositionsrc: str | None = ...,
        textsrc: str | None = ...,
        texttemplate: str | None = ...,
        texttemplatesrc: str | None = ...,
        uid: str | int | None = ...,
        uirevision: Hashable | None = ...,
        unselected: Unselected | dict[str, _unselected.Marker | _unselected.Textfont | dict[str, Any]] | None = ...,
        visible: bool | str | None = ...,
        x0: float | None = ...,
        xaxis: str | None = ...,
        xcalendar: str | None = ...,
        xhoverformat: str | None = ...,
        xperiod: float | str | None = ...,
        xperiod0: float | str | None = ...,
        xperiodalignment: str | None = ...,
        xsrc: str | None = ...,
        y0: float | None = ...,
        yaxis: str | None = ...,
        ycalendar: str | None = ...,
        yhoverformat: str | None = ...,
        yperiod: float | str | None = ...,
        yperiod0: float | str | None = ...,
        yperiodalignment: str | None = ...,
        ysrc: str | None = ...,
        zorder: int | None = ...,
        **kwargs: Any,  # noqa: ANN401
    ) -> tuple[Line, ...]: ...
    @classmethod
    def from_bounds_dataframe(
        cls,
        df: DataFrame,
        /,
        *,
        max_opacity: float = 0.4,
        y_index: int | str = 0,
        y_upper_indices: Sequence[int] | Sequence[str] | None = None,
        y_lower_indices: Sequence[int] | Sequence[str] | None = None,
        alignmentgroup: str | int | None = ...,
        cliponaxis: bool | None = ...,
        connectgaps: bool | None = ...,
        customdata: Sequence[float] | np.ndarray[tuple[int, ...], np.dtype[np.float64]] | pd.Series[float] | None = ...,
        customdatasrc: str | None = ...,
        dx: float | None = ...,
        dy: float | None = ...,
        error_x: ErrorX | dict[str, Any] | None = ...,
        error_y: ErrorY | dict[str, Any] | None = ...,
        fill: str | None = ...,
        fillcolor: str | None = ...,
        fillgradient: Fillgradient | dict[str, Any] | None = ...,
        fillpattern: Fillpattern | dict[str, Any] | None = ...,
        groupnorm: str | None = ...,
        hoverinfo: str | Sequence[str] | None = ...,
        hoverinfosrc: str | None = ...,
        hoverlabel: Hoverlabel | dict[str, Any] | None = ...,
        hoveron: str | None = ...,
        hovertemplate: str | float | Sequence[str] | Sequence[float] | np.ndarray[tuple[int, ...], np.dtype[np.float64]] | None = ...,
        hovertemplatesrc: str | None = ...,
        hovertext: str | float | Sequence[str] | Sequence[float] | np.ndarray[tuple[int, ...], np.dtype[np.float64]] | None = ...,
        hovertextsrc: str | None = ...,
        ids: Sequence[str] | np.ndarray[tuple[int, ...], np.dtype[np.str_]] | pd.Series[str] | None = ...,
        idssrc: str | None = ...,
        legend: str | None = ...,
        legendgroup: str | int | None = ...,
        legendgrouptitle: Legendgrouptitle | dict[str, Any] | None = ...,
        legendrank: float | None = ...,
        legendwidth: float | None = ...,
        line: _Line | dict[str, str | int | float] | None = ...,
        marker: Marker | dict[str, Any] | None = ...,
        meta: Sequence[Any] | dict[str, Any] | np.ndarray[tuple[int, ...], Any] | None = ...,
        metasrc: str | None = ...,
        mode: str | None = ...,
        name: str | int | None = ...,
        offsetgroup: str | int | None = ...,
        opacity: float | None = ...,
        orientation: str | None = ...,
        selected: Selected | dict[str, _selected.Marker | _selected.Textfont | dict[str, Any]] | None = ...,
        selectedpoints: Sequence[int] | None = ...,
        showlegend: bool | None = ...,
        stackgaps: str | None = ...,
        stackgroup: str | int | None = ...,
        stream: Stream | dict[str, int | str] | None = ...,
        text: str | Sequence[str] | None = ...,
        textfont: Textfont | dict[str, Any] | None = ...,
        textposition: str | Sequence[str] | np.ndarray[tuple[int, ...], np.dtype[np.str_]] | None = ...,
        textpositionsrc: str | None = ...,
        textsrc: str | None = ...,
        texttemplate: str | None = ...,
        texttemplatesrc: str | None = ...,
        uid: str | int | None = ...,
        uirevision: Hashable | None = ...,
        unselected: Unselected | dict[str, _unselected.Marker | _unselected.Textfont | dict[str, Any]] | None = ...,
        visible: bool | str | None = ...,
        x: Sequence[Any] | np.ndarray[tuple[int, ...], np.dtype[Any]] | pd.Series[Any] | None = ...,
        x0: float | None = ...,
        xaxis: str | None = ...,
        xcalendar: str | None = ...,
        xhoverformat: str | None = ...,
        xperiod: float | str | None = ...,
        xperiod0: float | str | None = ...,
        xperiodalignment: str | None = ...,
        xsrc: str | None = ...,
        y: Sequence[int] | Sequence[float] | np.ndarray[tuple[int, ...], np.dtype[np.float64]] | pd.Series[float] | None = ...,
        y0: float | None = ...,
        yaxis: str | None = ...,
        ycalendar: str | None = ...,
        yhoverformat: str | None = ...,
        yperiod: float | str | None = ...,
        yperiod0: float | str | None = ...,
        yperiodalignment: str | None = ...,
        ysrc: str | None = ...,
        zorder: int | None = ...,
        **kwargs: Any,  # noqa: ANN401
    ) -> tuple[Line, ...]: ...
