"""
This type stub file was generated by pyright.
"""

import asyncio
import warnings
import logistro
from functools import partial
from importlib.metadata import PackageNotFoundError, version
from typing import Any, AsyncIterator, Callable, Coroutine, TYPE_CHECKING
from packaging.version import Version

"""
This type stub file was generated by pyright.
"""
_logger = ...
if TYPE_CHECKING:
    ...
def event_printer(name: str) -> Callable[[Any], Coroutine[Any, Any, None]]:
    """Return function that prints whatever argument received."""
    ...

def create_task_log_error(coroutine) -> asyncio.Task:
    """Create a task and assign a callback to log its errors."""
    ...

def ensure_async_iter(obj) -> AsyncIterator[Any]:
    """Convert any iterable to an async iterator."""
    class _AIter:
        ...
    
    

async def to_thread(func, *args, **kwargs):
    """Polyfill `asyncio.to_thread()`."""
    ...

def warn_incompatible_plotly():
    """
    Check if installed Plotly version (if any) is compatible with this Kaleido version.

    If not, display a warning.
    """
    ...

