"""
This type stub file was generated by pyright.
"""

from typing import Any, Literal, TYPE_CHECKING, TypedDict
from pathlib import Path
from typing_extensions import TypeGuard

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    Figurish = Any
    FormatString = Literal["png", "jpg", "jpeg", "webp", "svg", "json", "pdf"]
class LayoutOpts(TypedDict, total=False):
    format: FormatString | None
    scale: int | float
    height: int | float
    width: int | float
    ...


class Spec(TypedDict):
    format: FormatString
    width: int | float
    height: int | float
    scale: int | float
    data: Figurish
    ...


_logger = ...
DEFAULT_EXT = ...
DEFAULT_SCALE = ...
DEFAULT_WIDTH = ...
DEFAULT_HEIGHT = ...
SUPPORTED_FORMATS: tuple[FormatString, ...] = ...
def is_figurish(o: Any) -> TypeGuard[Figurish]:
    """Detect if input is a plotly figure or equivalent."""
    ...

def coerce_for_js(fig: Figurish, path: Path | str | None, opts: LayoutOpts | None) -> Spec:
    """
    Package fig, path, and opts into a dictionary that javascript understands.

    This will
        - validate the inputs
        - coerce the inputs if needed (eg. jpeg --> jpg)
        - provide defaults if we can
    """
    ...

