from typing import Any

from sqlalchemy.sql.schema import MetaData, SchemaItem, Table

from .custom_table_prefix import CustomTablePrefix
from .options.table_option import TableOptionKey

class CustomTableBase(Table):
    __table_prefixes__: list[CustomTablePrefix] = ...
    _support_primary_and_foreign_keys: bool = ...
    _enforce_primary_keys: bool = ...
    _required_parameters: list[TableOptionKey] = ...
    _support_structured_types: bool = ...
    @property
    def table_prefixes(self) -> list[str]: ...
    def __init__(self, name: str, metadata: MetaData, *args: SchemaItem, **kw: Any) -> None: ...
    @classmethod
    def is_equal_type(cls, table: Table) -> bool: ...
