from typing import Any

from sqlalchemy.sql.schema import MetaData, SchemaItem

from .custom_table_base import CustomTableBase

class HybridTable(CustomTableBase):
    __table_prefixes__ = ...
    _enforce_primary_keys: bool = ...
    _support_structured_types = ...
    def __init__(self, name: str, metadata: MetaData, *args: SchemaItem, **kw: Any) -> None: ...
