import pickle
import sys

DEFAULT_PROTOCOL = ...
_PICKLE_BY_VALUE_MODULES = ...
_DYNAMIC_CLASS_TRACKER_BY_CLASS = ...
_DYNAMIC_CLASS_TRACKER_BY_ID = ...
_DYNAMIC_CLASS_TRACKER_LOCK = ...
_DYNAMIC_CLASS_TRACKER_REUSING = ...
PYPY = ...
builtin_code_type = ...
if PYPY:
    builtin_code_type = ...
_extract_code_globals_cache = ...

def register_pickle_by_value(module): ...
def unregister_pickle_by_value(module): ...
def list_registry_pickle_by_value(): ...

if sys.version_info >= (3, 14): ...
else: ...
STORE_GLOBAL = ...
DELETE_GLOBAL = ...
LOAD_GLOBAL = ...
GLOBAL_OPS = ...
HAVE_ARGUMENT = ...
EXTENDED_ARG = ...
_BUILTIN_TYPE_NAMES = ...

def is_tornado_coroutine(func): ...
def subimport(name): ...
def dynamic_subimport(name, vars): ...
def instance(cls): ...

@instance
class _empty_cell_value:
    @classmethod
    def __reduce__(cls): ...

_DATACLASSE_FIELD_TYPE_SENTINELS = ...

class Pickler(pickle.Pickler):
    _dispatch_table = ...
    dispatch_table = ...
    def dump(self, obj): ...
    def __init__(self, file, protocol=..., buffer_callback=...) -> None: ...

    if not PYPY:
        dispatch = ...
        def reducer_override(self, obj): ...

    else:
        dispatch = ...
        def save_global(self, obj, name=..., pack=...): ...
        def save_function(self, obj, name=...): ...
        def save_pypy_builtin_func(self, obj): ...

def dump(obj, file, protocol=..., buffer_callback=...): ...
def dumps(obj, protocol=..., buffer_callback=...): ...

CloudPickler = Pickler
