import contextlib

import pyarrow.fs

"""
Utility functions for testing
"""

def randsign():  # -> Literal[-1, 1]:

    ...
@contextlib.contextmanager
def random_seed(seed):  # -> Generator[None, Any, None]:

    ...
def randdecimal(precision, scale):  # -> Decimal:

    ...
def random_ascii(length):  # -> bytes:
    ...
def rands(nchars):  # -> str:

    ...
def memory_leak_check(f, metric=..., threshold=..., iterations=..., check_interval=...):  # -> None:

    ...
def get_modified_env_with_pythonpath():  # -> dict[str, str]:
    ...
def invoke_script(script_name, *args):  # -> None:
    ...
@contextlib.contextmanager
def changed_environ(name, value):  # -> Generator[None, Any, None]:

    ...
@contextlib.contextmanager
def change_cwd(path):  # -> Generator[None, Any, None]:
    ...
@contextlib.contextmanager
def disabled_gc():  # -> Generator[None, Any, None]:
    ...

class FSProtocolClass:
    def __init__(self, path) -> None: ...
    def __fspath__(self):  # -> str:
        ...

class ProxyHandler(pyarrow.fs.FileSystemHandler):
    def __init__(self, fs) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def get_type_name(self): ...
    def normalize_path(self, path): ...
    def get_file_info(self, paths): ...
    def get_file_info_selector(self, selector): ...
    def create_dir(self, path, recursive): ...
    def delete_dir(self, path): ...
    def delete_dir_contents(self, path, missing_dir_ok): ...
    def delete_root_dir_contents(self): ...
    def delete_file(self, path): ...
    def move(self, src, dest): ...
    def copy_file(self, src, dest): ...
    def open_input_stream(self, path): ...
    def open_input_file(self, path): ...
    def open_output_stream(self, path, metadata): ...
    def open_append_stream(self, path, metadata): ...

@contextlib.contextmanager
def signal_wakeup_fd(*, warn_on_full_buffer=...):  # -> Generator[socket, Any, None]:
    ...
def windows_has_tzdata():  # -> bool:

    ...
def running_on_musllinux():  # -> bool:

    ...
