"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def ravel(a, order=...):
    ...

def shape(a):
    ...

def transpose(a, axes=...):
    ...

def split(arr, indices, axis=...):
    ...

def hstack(tup, dtype=..., casting=...):
    ...

def append(arr, values, axis=...):
    ...

