"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def zeros_like(a, dtype=..., order=..., subok=..., shape=...):
    ...

def ones_like(a, dtype=..., order=..., subok=..., shape=...):
    ...

def tri(N, M=..., k=..., dtype=..., like=...):
    ...

