"""
This type stub file was generated by pyright.
"""

import numpy
from packaging import version

"""
This type stub file was generated by pyright.
"""
if version.parse(numpy.__version__) < version.parse("2.0.0b1"):
    ...
__all__ = ["e", "euler_gamma", "inf", "nan", "newaxis", "pi"]
if version.parse(numpy.__version__) < version.parse("2.0.0b1"):
    ...
