from pathlib import Path

def get_root() -> Path: ...
def get_module_root() -> Path: ...
def get_module_path(module: object) -> Path: ...
def read_file(path: Path | str) -> str: ...
def encode_path(path: Path | str) -> str: ...
def decode_path(encoded_path: str) -> Path: ...
