_use_defs_result = ...
ir_extension_usedefs = ...

def compute_use_defs(blocks):  # -> use_defs_result:

    ...
def compute_live_map(cfg, blocks, var_use_map, var_def_map):  # -> dict[Any, Any]:

    ...

_dead_maps_result = ...

def compute_dead_maps(cfg, blocks, live_map, var_def_map):  # -> dead_maps_result:

    ...
def compute_live_variables(cfg, blocks, var_def_map, var_dead_map):  # -> defaultdict[Any, set[Any]]:

    ...
def compute_cfg_from_blocks(blocks):  # -> CFGraph:
    ...
def find_top_level_loops(cfg):  # -> Generator[Any, Any, None]:

    ...

nullified = ...

def dead_branch_prune(func_ir, called_args) -> None: ...
def rewrite_semantic_constants(func_ir, called_args):  # -> None:

    ...
def find_literally_calls(func_ir, argtypes):  # -> None:

    ...

ir_extension_use_alloca = ...

def must_use_alloca(blocks):  # -> set[Any]:

    ...
