from contextlib import contextmanager
from functools import cached_property

from numba.core import debuginfo

GENERIC_POINTER = ...
PYOBJECT = ...
void_ptr = ...

class OverloadSelector:
    def __init__(self) -> None: ...
    def find(self, sig): ...
    def append(self, value, sig):  # -> None:

        ...

class BaseContext:
    strict_alignment = ...
    implement_powi_as_math_call = ...
    implement_pow_as_math_call = ...
    enable_debuginfo = ...
    DIBuilder = debuginfo.DIBuilder
    @property
    def enable_boundscheck(self):  # -> bool:
        ...
    @enable_boundscheck.setter
    def enable_boundscheck(self, value):  # -> None:
        ...

    enable_nrt = ...
    auto_parallel = ...
    aot_mode = ...
    error_model = ...
    allow_dynamic_globals = ...
    fastmath = ...
    environment = ...
    fndesc = ...
    def __init__(self, typing_context, target) -> None: ...
    def init(self):  # -> None:

        ...
    def refresh(self):  # -> None:

        ...
    def load_additional_registries(self):  # -> None:

        ...
    def mangler(self, name, types, *, abi_tags=..., uid=...):  # -> str:

        ...
    def get_env_name(self, fndesc): ...
    def declare_env_global(self, module, envname): ...
    def get_arg_packer(self, fe_args):  # -> ArgPacker:
        ...
    def get_data_packer(self, fe_types):  # -> DataPacker:
        ...
    @property
    def target_data(self): ...
    @cached_property
    def nonconst_module_attrs(self):  # -> tuple[()]:

        ...
    @cached_property
    def nrt(self):  # -> NRTContext:
        ...
    def subtarget(self, **kws):  # -> Self:
        ...
    def install_registry(self, registry):  # -> None:

        ...
    def insert_func_defn(self, defns):  # -> None:
        ...
    def insert_user_function(self, func, fndesc, libs=...):  # -> None:
        ...
    def insert_generator(self, genty, gendesc, libs=...):  # -> None:
        ...
    def remove_user_function(self, func):  # -> None:

        ...
    def get_external_function_type(self, fndesc):  # -> FunctionType:
        ...
    def declare_function(self, module, fndesc):  # -> Function:
        ...
    def apply_target_attributes(self, llvm_func, argtypes=..., restype=...):  # -> None:

        ...
    def declare_external_function(self, module, fndesc):  # -> Function:
        ...
    def insert_const_string(self, mod, string):  # -> None:

        ...
    def insert_const_bytes(self, mod, bytes, name=...):  # -> None:

        ...
    def insert_unique_const(self, mod, name, val):  # -> GlobalVariable:

        ...
    def get_argument_type(self, ty): ...
    def get_return_type(self, ty): ...
    def get_data_type(self, ty): ...
    def get_value_type(self, ty): ...
    def pack_value(self, builder, ty, value, ptr, align=...):  # -> None:

        ...
    def unpack_value(self, builder, ty, ptr, align=...): ...
    def get_constant_generic(self, builder, ty, val): ...
    def get_constant(self, ty, val): ...
    def get_constant_undef(self, ty):  # -> Constant:
        ...
    def get_constant_null(self, ty):  # -> Constant:
        ...
    def get_function(self, fn, sig, _firstcall=...):  # -> _wrap_impl:

        ...
    def get_generator_desc(self, genty): ...
    def get_generator_impl(self, genty): ...
    def get_bound_function(self, builder, obj, ty): ...
    def get_getattr(self, typ, attr):  # -> Callable[..., Any] | None:

        ...
    def get_setattr(self, attr, sig):  # -> Callable[..., Any]:

        ...
    def get_argument_value(self, builder, ty, val): ...
    def get_returned_value(self, builder, ty, val): ...
    def get_return_value(self, builder, ty, val): ...
    def get_value_as_argument(self, builder, ty, val): ...
    def get_value_as_data(self, builder, ty, val): ...
    def get_data_as_value(self, builder, ty, val): ...
    def pair_first(self, builder, val, ty):  # -> Any:

        ...
    def pair_second(self, builder, val, ty):  # -> Any:

        ...
    def cast(self, builder, val, fromty, toty):  # -> Constant:

        ...
    def generic_compare(self, builder, key, argtypes, args): ...
    def make_optional_none(self, builder, valtype):  # -> Any:
        ...
    def make_optional_value(self, builder, valtype, value):  # -> Any:
        ...
    def is_true(self, builder, typ, val): ...
    def get_c_value(self, builder, typ, name, dllimport=...):  # -> GlobalVariable:

        ...
    def call_external_function(self, builder, callee, argtys, args): ...
    def get_function_pointer_type(self, typ): ...
    def call_function_pointer(self, builder, funcptr, args, cconv=...): ...
    def print_string(self, builder, text): ...
    def debug_print(self, builder, text):  # -> None:
        ...
    def printf(self, builder, format_string, *args): ...
    def get_struct_type(self, struct):  # -> LiteralStructType:

        ...
    def get_dummy_value(self):  # -> Constant:
        ...
    def get_dummy_type(self):  # -> PointerType:
        ...
    def compile_subroutine(self, builder, impl, sig, locals=..., flags=..., caching=...): ...
    def compile_internal(self, builder, impl, sig, args, locals=...): ...
    def call_internal(self, builder, fndesc, sig, args): ...
    def call_internal_no_propagate(self, builder, fndesc, sig, args):  # -> tuple[Any, Any]:

        ...
    def call_unresolved(self, builder, name, sig, args): ...
    def get_executable(self, func, fndesc, env): ...
    def get_python_api(self, builder):  # -> PythonAPI:
        ...
    def sentry_record_alignment(self, rectyp, attr):  # -> None:

        ...
    def get_helper_class(self, typ, kind=...):  # -> Any:

        ...
    def make_helper(self, builder, typ, value=..., ref=...):  # -> Any:

        ...
    def make_data_helper(self, builder, typ, ref=...):  # -> Any:

        ...
    def make_array(self, typ):  # -> type[ArrayStruct]:
        ...
    def populate_array(self, arr, **kwargs): ...
    def make_complex(self, builder, typ, value=...):  # -> Any:

        ...
    def make_tuple(self, builder, typ, values):  # -> Constant:

        ...
    def make_constant_array(self, builder, typ, ary):  # -> Any:

        ...
    def add_dynamic_addr(self, builder, intaddr, info): ...
    def get_abi_sizeof(self, ty): ...
    def get_abi_alignment(self, ty): ...
    def get_preferred_array_alignment(self, ty):  # -> Literal[32]:

        ...
    def post_lowering(self, mod, library):  # -> None:

        ...
    def create_module(self, name): ...
    @property
    def active_code_library(self): ...
    @contextmanager
    def push_code_library(self, lib):  # -> Generator[None, Any, None]:

        ...
    def add_linking_libs(self, libs):  # -> None:

        ...
    def get_ufunc_info(self, ufunc_key): ...

class _wrap_impl:
    def __init__(self, imp, context, sig) -> None: ...
    def __call__(self, builder, args, loc=...): ...
    def __getattr__(self, item):  # -> Any:
        ...

class _wrap_missing_loc:
    def __init__(self, fn) -> None: ...
    def __call__(self):  # -> Callable[..., Any] | Any:

        ...
