from numba.core import types
from numba.core.pythonapi import box, reflect, unbox

"""
Boxing and unboxing of native Numba values to / from CPython objects.
"""

@box(types.Boolean)
def box_bool(typ, val, c): ...
@unbox(types.Boolean)
def unbox_boolean(typ, obj, c):  # -> NativeValue:
    ...
@box(types.IntegerLiteral)
@box(types.BooleanLiteral)
def box_literal_integer(typ, val, c): ...
@box(types.Integer)
def box_integer(typ, val, c): ...
@unbox(types.Integer)
def unbox_integer(typ, obj, c):  # -> NativeValue:
    ...
@box(types.Float)
def box_float(typ, val, c): ...
@unbox(types.Float)
def unbox_float(typ, obj, c):  # -> NativeValue:
    ...
@box(types.Complex)
def box_complex(typ, val, c): ...
@unbox(types.Complex)
def unbox_complex(typ, obj, c):  # -> NativeValue:
    ...
@box(types.NoneType)
def box_none(typ, val, c): ...
@unbox(types.NoneType)
@unbox(types.EllipsisType)
def unbox_none(typ, val, c):  # -> NativeValue:
    ...
@box(types.NPDatetime)
def box_npdatetime(typ, val, c): ...
@unbox(types.NPDatetime)
def unbox_npdatetime(typ, obj, c):  # -> NativeValue:
    ...
@box(types.NPTimedelta)
def box_nptimedelta(typ, val, c): ...
@unbox(types.NPTimedelta)
def unbox_nptimedelta(typ, obj, c):  # -> NativeValue:
    ...
@box(types.RawPointer)
def box_raw_pointer(typ, val, c): ...
@box(types.EnumMember)
def box_enum(typ, val, c): ...
@unbox(types.EnumMember)
def unbox_enum(typ, obj, c): ...
@box(types.UndefVar)
def box_undefvar(typ, val, c): ...
@box(types.Record)
def box_record(typ, val, c): ...
@unbox(types.Record)
def unbox_record(typ, obj, c):  # -> NativeValue:
    ...
@box(types.UnicodeCharSeq)
def box_unicodecharseq(typ, val, c): ...
@unbox(types.UnicodeCharSeq)
def unbox_unicodecharseq(typ, obj, c):  # -> NativeValue:
    ...
@box(types.Bytes)
def box_bytes(typ, val, c): ...
@box(types.CharSeq)
def box_charseq(typ, val, c): ...
@unbox(types.CharSeq)
def unbox_charseq(typ, obj, c):  # -> NativeValue:
    ...
@box(types.Optional)
def box_optional(typ, val, c): ...
@unbox(types.Optional)
def unbox_optional(typ, obj, c):  # -> NativeValue:

    ...
@unbox(types.SliceType)
def unbox_slice(typ, obj, c):  # -> NativeValue:

    ...
@box(types.SliceLiteral)
def box_slice_literal(typ, val, c): ...
@unbox(types.StringLiteral)
def unbox_string_literal(typ, obj, c):  # -> NativeValue:
    ...
@box(types.Array)
def box_array(typ, val, c): ...
@unbox(types.Buffer)
def unbox_buffer(typ, obj, c):  # -> NativeValue:

    ...
@unbox(types.Array)
def unbox_array(typ, obj, c):  # -> NativeValue:

    ...
@box(types.Tuple)
@box(types.UniTuple)
def box_tuple(typ, val, c): ...
@box(types.NamedTuple)
@box(types.NamedUniTuple)
def box_namedtuple(typ, val, c): ...
@unbox(types.BaseTuple)
def unbox_tuple(typ, obj, c):  # -> NativeValue:

    ...
@box(types.List)
def box_list(typ, val, c): ...

class _NumbaTypeHelper:
    def __init__(self, c) -> None: ...
    def __enter__(self):  # -> Self:
        ...
    def __exit__(self, *args, **kwargs):  # -> None:
        ...
    def typeof(self, obj): ...

@unbox(types.List)
def unbox_list(typ, obj, c):  # -> NativeValue:

    ...
@reflect(types.List)
def reflect_list(typ, val, c):  # -> None:

    ...
@unbox(types.Set)
def unbox_set(typ, obj, c):  # -> NativeValue:

    ...
@box(types.Set)
def box_set(typ, val, c): ...
@reflect(types.Set)
def reflect_set(typ, val, c):  # -> None:

    ...
@box(types.Generator)
def box_generator(typ, val, c): ...
@unbox(types.Generator)
def unbox_generator(typ, obj, c): ...
@box(types.DType)
def box_dtype(typ, val, c): ...
@unbox(types.DType)
def unbox_dtype(typ, val, c):  # -> NativeValue:
    ...
@box(types.NumberClass)
def box_number_class(typ, val, c): ...
@unbox(types.NumberClass)
def unbox_number_class(typ, val, c):  # -> NativeValue:
    ...
@box(types.PyObject)
@box(types.Object)
def box_pyobject(typ, val, c): ...
@unbox(types.PyObject)
@unbox(types.Object)
def unbox_pyobject(typ, obj, c):  # -> NativeValue:
    ...
@unbox(types.ExternalFunctionPointer)
def unbox_funcptr(typ, obj, c):  # -> NativeValue:
    ...
@box(types.DeferredType)
def box_deferred(typ, val, c): ...
@unbox(types.DeferredType)
def unbox_deferred(typ, obj, c):  # -> NativeValue:
    ...
@unbox(types.Dispatcher)
def unbox_dispatcher(typ, obj, c):  # -> NativeValue:
    ...
@box(types.Dispatcher)
def box_pyobject(typ, val, c): ...
def unbox_unsupported(typ, obj, c):  # -> NativeValue:
    ...
def box_unsupported(typ, val, c): ...
@box(types.Literal)
def box_literal(typ, val, c): ...
@box(types.MemInfoPointer)
def box_meminfo_pointer(typ, val, c): ...
@unbox(types.MemInfoPointer)
def unbox_meminfo_pointer(typ, obj, c):  # -> NativeValue:
    ...
@unbox(types.TypeRef)
def unbox_typeref(typ, val, c):  # -> NativeValue:
    ...
@box(types.LiteralStrKeyDict)
def box_LiteralStrKeyDict(typ, val, c): ...
@unbox(types.NumPyRandomBitGeneratorType)
def unbox_numpy_random_bitgenerator(typ, obj, c):  # -> NativeValue:

    ...

_bit_gen_type = ...

@unbox(types.NumPyRandomGeneratorType)
def unbox_numpy_random_generator(typ, obj, c):  # -> NativeValue:

    ...
@box(types.NumPyRandomGeneratorType)
def box_numpy_random_generator(typ, val, c): ...
