from enum import Enum
from functools import total_ordering

from numba.core.utils import PYVERSION

"""
Implement python 3.8+ bytecode analysis
"""
_logger = ...
_EXCEPT_STACK_OFFSET = ...
_FINALLY_POP = ...
_NO_RAISE_OPS = ...
if PYVERSION in ((3, 12), (3, 13), (3, 14)):
    class CALL_INTRINSIC_1_Operand(Enum):
        INTRINSIC_STOPITERATION_ERROR = ...
        UNARY_POSITIVE = ...
        INTRINSIC_LIST_TO_TUPLE = ...

    ci1op = CALL_INTRINSIC_1_Operand
else: ...

@total_ordering
class BlockKind:
    _members = ...
    def __init__(self, value) -> None: ...
    def __hash__(self) -> int: ...
    def __lt__(self, other) -> bool: ...
    def __eq__(self, other) -> bool: ...

class Flow:
    def __init__(self, bytecode) -> None: ...
    def run(self):  # -> None:

        ...

    if PYVERSION in ((3, 11), (3, 12), (3, 13), (3, 14)): ...
    else: ...
    if PYVERSION == (3, 14): ...
    else: ...

class TraceRunner:
    def __init__(self, debug_filename) -> None: ...
    def get_debug_loc(self, lineno):  # -> Loc:
        ...
    def dispatch(self, state):  # -> None:
        ...
    def op_NOP(self, state, inst):  # -> None:
        ...

    if PYVERSION == (3, 14):
        op_NOT_TAKEN = ...
    else: ...
    def op_RESUME(self, state, inst):  # -> None:
        ...
    def op_CACHE(self, state, inst):  # -> None:
        ...
    def op_PRECALL(self, state, inst):  # -> None:
        ...
    def op_PUSH_NULL(self, state, inst):  # -> None:
        ...
    def op_RETURN_GENERATOR(self, state, inst):  # -> None:
        ...

    if PYVERSION in ((3, 13), (3, 14)):
        def op_FORMAT_SIMPLE(self, state, inst):  # -> None:
            ...

    else: ...
    def op_FORMAT_VALUE(self, state, inst):  # -> None:

        ...
    def op_BUILD_STRING(self, state, inst):  # -> None:

        ...
    def op_POP_TOP(self, state, inst):  # -> None:
        ...

    if PYVERSION == (3, 14):
        op_POP_ITER = ...
    else: ...
    if PYVERSION in ((3, 13), (3, 14)):
        def op_TO_BOOL(self, state, inst):  # -> None:
            ...

    else: ...
    if PYVERSION in ((3, 13), (3, 14)):
        def op_LOAD_GLOBAL(self, state, inst):  # -> None:
            ...

    else:
        def op_LOAD_GLOBAL(self, state, inst):  # -> None:
            ...

    def op_COPY_FREE_VARS(self, state, inst):  # -> None:
        ...
    def op_MAKE_CELL(self, state, inst):  # -> None:
        ...
    def op_LOAD_DEREF(self, state, inst):  # -> None:
        ...
    def op_LOAD_CONST(self, state, inst):  # -> None:
        ...

    if PYVERSION == (3, 14):
        def op_LOAD_SMALL_INT(self, state, inst):  # -> None:
            ...

    else: ...
    def op_LOAD_ATTR(self, state, inst):  # -> None:
        ...
    def op_LOAD_FAST(self, state, inst):  # -> None:
        ...

    if PYVERSION in ((3, 13), (3, 14)):
        def op_LOAD_FAST_LOAD_FAST(self, state, inst):  # -> None:
            ...
        def op_STORE_FAST_LOAD_FAST(self, state, inst):  # -> None:
            ...
        def op_STORE_FAST_STORE_FAST(self, state, inst):  # -> None:
            ...

    else: ...
    if PYVERSION in ((3, 12), (3, 13), (3, 14)):
        op_LOAD_FAST_CHECK = ...
        op_LOAD_FAST_AND_CLEAR = ...
    else: ...
    if PYVERSION == (3, 14):
        op_LOAD_FAST_BORROW = ...
        op_LOAD_FAST_BORROW_LOAD_FAST_BORROW = ...
    else: ...
    def op_DELETE_FAST(self, state, inst):  # -> None:
        ...
    def op_DELETE_ATTR(self, state, inst):  # -> None:
        ...
    def op_STORE_ATTR(self, state, inst):  # -> None:
        ...
    def op_STORE_DEREF(self, state, inst):  # -> None:
        ...
    def op_STORE_FAST(self, state, inst):  # -> None:
        ...
    def op_SLICE_1(self, state, inst):  # -> None:

        ...
    def op_SLICE_2(self, state, inst):  # -> None:

        ...
    def op_SLICE_3(self, state, inst):  # -> None:

        ...
    def op_STORE_SLICE_0(self, state, inst):  # -> None:

        ...
    def op_STORE_SLICE_1(self, state, inst):  # -> None:

        ...
    def op_STORE_SLICE_2(self, state, inst):  # -> None:

        ...
    def op_STORE_SLICE_3(self, state, inst):  # -> None:

        ...
    def op_DELETE_SLICE_0(self, state, inst):  # -> None:

        ...
    def op_DELETE_SLICE_1(self, state, inst):  # -> None:

        ...
    def op_DELETE_SLICE_2(self, state, inst):  # -> None:

        ...
    def op_DELETE_SLICE_3(self, state, inst):  # -> None:

        ...
    def op_BUILD_SLICE(self, state, inst):  # -> None:

        ...

    if PYVERSION in ((3, 12), (3, 13), (3, 14)):
        def op_BINARY_SLICE(self, state, inst):  # -> None:
            ...

    else: ...
    if PYVERSION in ((3, 12), (3, 13), (3, 14)):
        def op_STORE_SLICE(self, state, inst):  # -> None:
            ...

    else: ...
    op_POP_JUMP_IF_TRUE = ...
    op_POP_JUMP_IF_FALSE = ...
    if PYVERSION in ((3, 12), (3, 13), (3, 14)):
        op_POP_JUMP_IF_NONE = ...
        op_POP_JUMP_IF_NOT_NONE = ...
    else: ...
    op_JUMP_IF_FALSE_OR_POP = ...
    op_JUMP_IF_TRUE_OR_POP = ...
    def op_POP_JUMP_FORWARD_IF_NONE(self, state, inst):  # -> None:
        ...
    def op_POP_JUMP_FORWARD_IF_NOT_NONE(self, state, inst):  # -> None:
        ...
    def op_POP_JUMP_BACKWARD_IF_NONE(self, state, inst):  # -> None:
        ...
    def op_POP_JUMP_BACKWARD_IF_NOT_NONE(self, state, inst):  # -> None:
        ...
    def op_POP_JUMP_FORWARD_IF_FALSE(self, state, inst):  # -> None:
        ...
    def op_POP_JUMP_FORWARD_IF_TRUE(self, state, inst):  # -> None:
        ...
    def op_POP_JUMP_BACKWARD_IF_FALSE(self, state, inst):  # -> None:
        ...
    def op_POP_JUMP_BACKWARD_IF_TRUE(self, state, inst):  # -> None:
        ...
    def op_JUMP_FORWARD(self, state, inst):  # -> None:
        ...
    def op_JUMP_BACKWARD(self, state, inst):  # -> None:
        ...

    op_JUMP_BACKWARD_NO_INTERRUPT = ...
    def op_JUMP_ABSOLUTE(self, state, inst):  # -> None:
        ...
    def op_BREAK_LOOP(self, state, inst):  # -> None:
        ...
    def op_RETURN_VALUE(self, state, inst):  # -> None:
        ...

    if PYVERSION in ((3, 12), (3, 13), (3, 14)):
        def op_RETURN_CONST(self, state, inst):  # -> None:
            ...

    else: ...
    def op_YIELD_VALUE(self, state, inst):  # -> None:
        ...

    if PYVERSION in ((3, 11), (3, 12), (3, 13), (3, 14)):
        def op_RAISE_VARARGS(self, state, inst):  # -> None:
            ...

    else:
        def op_RAISE_VARARGS(self, state, inst):  # -> None:
            ...

    def op_BEGIN_FINALLY(self, state, inst):  # -> None:
        ...
    def op_END_FINALLY(self, state, inst):  # -> None:
        ...

    if PYVERSION in ((3, 13), (3, 14)):
        def op_END_FOR(self, state, inst):  # -> None:
            ...

    else:
        def op_END_FOR(self, state, inst):  # -> None:
            ...

    def op_POP_FINALLY(self, state, inst):  # -> None:
        ...
    def op_CALL_FINALLY(self, state, inst):  # -> None:
        ...
    def op_WITH_EXCEPT_START(self, state, inst):  # -> None:
        ...
    def op_WITH_CLEANUP_START(self, state, inst):  # -> None:
        ...
    def op_WITH_CLEANUP_FINISH(self, state, inst):  # -> None:
        ...
    def op_SETUP_LOOP(self, state, inst):  # -> None:
        ...

    if PYVERSION == (3, 14): ...
    else:
        def op_BEFORE_WITH(self, state, inst):  # -> None:
            ...

    def op_SETUP_WITH(self, state, inst):  # -> None:
        ...
    def op_PUSH_EXC_INFO(self, state, inst):  # -> None:
        ...
    def op_SETUP_FINALLY(self, state, inst):  # -> None:
        ...

    if PYVERSION in ((3, 11), (3, 12), (3, 13), (3, 14)):
        def op_POP_EXCEPT(self, state, inst):  # -> None:
            ...

    else:
        def op_POP_EXCEPT(self, state, inst):  # -> None:
            ...

    def op_POP_BLOCK(self, state, inst):  # -> None:
        ...

    if PYVERSION == (3, 14): ...
    else:
        def op_BINARY_SUBSCR(self, state, inst):  # -> None:
            ...

    def op_STORE_SUBSCR(self, state, inst):  # -> None:
        ...
    def op_DELETE_SUBSCR(self, state, inst):  # -> None:
        ...
    def op_CALL(self, state, inst):  # -> None:
        ...
    def op_KW_NAMES(self, state, inst):  # -> None:
        ...
    def op_CALL_FUNCTION(self, state, inst):  # -> None:
        ...
    def op_CALL_FUNCTION_KW(self, state, inst):  # -> None:
        ...

    if PYVERSION in ((3, 13), (3, 14)):
        def op_CALL_KW(self, state, inst):  # -> None:
            ...

    else: ...
    if PYVERSION == (3, 14):
        def op_CALL_FUNCTION_EX(self, state, inst):  # -> None:
            ...

    else:
        def op_CALL_FUNCTION_EX(self, state, inst):  # -> None:
            ...

    if PYVERSION in ((3, 12), (3, 13), (3, 14)):
        def op_CALL_INTRINSIC_1(self, state, inst):  # -> None:
            ...

    else: ...
    def op_DUP_TOPX(self, state, inst):  # -> None:
        ...
    def op_DUP_TOP(self, state, inst):  # -> None:
        ...
    def op_DUP_TOP_TWO(self, state, inst):  # -> None:
        ...
    def op_COPY(self, state, inst):  # -> None:
        ...
    def op_SWAP(self, state, inst):  # -> None:
        ...
    def op_ROT_TWO(self, state, inst):  # -> None:
        ...
    def op_ROT_THREE(self, state, inst):  # -> None:
        ...
    def op_ROT_FOUR(self, state, inst):  # -> None:
        ...
    def op_UNPACK_SEQUENCE(self, state, inst):  # -> None:
        ...
    def op_BUILD_TUPLE(self, state, inst):  # -> None:
        ...
    def op_BUILD_TUPLE_UNPACK_WITH_CALL(self, state, inst):  # -> None:
        ...
    def op_BUILD_TUPLE_UNPACK(self, state, inst):  # -> None:
        ...
    def op_LIST_TO_TUPLE(self, state, inst):  # -> None:
        ...
    def op_BUILD_CONST_KEY_MAP(self, state, inst):  # -> None:
        ...
    def op_BUILD_LIST(self, state, inst):  # -> None:
        ...
    def op_LIST_APPEND(self, state, inst):  # -> None:
        ...
    def op_LIST_EXTEND(self, state, inst):  # -> None:
        ...
    def op_BUILD_MAP(self, state, inst):  # -> None:
        ...
    def op_MAP_ADD(self, state, inst):  # -> None:
        ...
    def op_BUILD_SET(self, state, inst):  # -> None:
        ...
    def op_SET_ADD(self, state, inst):  # -> None:
        ...
    def op_SET_UPDATE(self, state, inst):  # -> None:
        ...
    def op_DICT_UPDATE(self, state, inst):  # -> None:
        ...
    def op_GET_ITER(self, state, inst):  # -> None:
        ...
    def op_FOR_ITER(self, state, inst):  # -> None:
        ...
    def op_GEN_START(self, state, inst):  # -> None:

        ...
    def op_BINARY_OP(self, state, inst):  # -> None:
        ...

    op_UNARY_NEGATIVE = ...
    op_UNARY_POSITIVE = ...
    op_UNARY_NOT = ...
    op_UNARY_INVERT = ...
    op_COMPARE_OP = ...
    op_IS_OP = ...
    op_CONTAINS_OP = ...
    op_INPLACE_ADD = ...
    op_INPLACE_SUBTRACT = ...
    op_INPLACE_MULTIPLY = ...
    op_INPLACE_DIVIDE = ...
    op_INPLACE_TRUE_DIVIDE = ...
    op_INPLACE_FLOOR_DIVIDE = ...
    op_INPLACE_MODULO = ...
    op_INPLACE_POWER = ...
    op_INPLACE_MATRIX_MULTIPLY = ...
    op_INPLACE_LSHIFT = ...
    op_INPLACE_RSHIFT = ...
    op_INPLACE_AND = ...
    op_INPLACE_OR = ...
    op_INPLACE_XOR = ...
    op_BINARY_ADD = ...
    op_BINARY_SUBTRACT = ...
    op_BINARY_MULTIPLY = ...
    op_BINARY_DIVIDE = ...
    op_BINARY_TRUE_DIVIDE = ...
    op_BINARY_FLOOR_DIVIDE = ...
    op_BINARY_MODULO = ...
    op_BINARY_POWER = ...
    op_BINARY_MATRIX_MULTIPLY = ...
    op_BINARY_LSHIFT = ...
    op_BINARY_RSHIFT = ...
    op_BINARY_AND = ...
    op_BINARY_OR = ...
    op_BINARY_XOR = ...
    def op_MAKE_FUNCTION(self, state, inst, MAKE_CLOSURE=...):  # -> None:
        ...
    def op_SET_FUNCTION_ATTRIBUTE(self, state, inst):  # -> None:
        ...
    def op_MAKE_CLOSURE(self, state, inst):  # -> None:
        ...
    def op_LOAD_CLOSURE(self, state, inst):  # -> None:
        ...

    if PYVERSION == (3, 14): ...
    else:
        def op_LOAD_ASSERTION_ERROR(self, state, inst):  # -> None:
            ...

    def op_CHECK_EXC_MATCH(self, state, inst):  # -> None:
        ...
    def op_JUMP_IF_NOT_EXC_MATCH(self, state, inst):  # -> None:
        ...

    if PYVERSION in ((3, 11), (3, 12), (3, 13), (3, 14)):
        def op_RERAISE(self, state, inst):  # -> None:
            ...

    else:
        def op_RERAISE(self, state, inst):  # -> None:
            ...

    if PYVERSION in ((3, 12), (3, 13), (3, 14)): ...
    else:
        def op_LOAD_METHOD(self, state, inst):  # -> None:
            ...

    def op_CALL_METHOD(self, state, inst):  # -> None:
        ...

    if PYVERSION == (3, 14):
        def op_LOAD_SPECIAL(self, state, inst):  # -> None:
            ...

    else: ...
    if PYVERSION == (3, 14):
        def op_LOAD_COMMON_CONSTANT(self, state, inst):  # -> None:
            ...

    else: ...

@total_ordering
class _State:
    def __init__(self, bytecode, pc, nstack, blockstack, nullvals=...) -> None: ...
    def get_identity(self):  # -> tuple[Any, Any]:
        ...
    def __hash__(self) -> int: ...
    def __lt__(self, other) -> bool: ...
    def __eq__(self, other) -> bool: ...
    @property
    def pc_initial(self):  # -> Any:

        ...
    @property
    def instructions(self):  # -> list[Any]:

        ...
    @property
    def outgoing_edges(self):  # -> list[Any]:

        ...
    @property
    def outgoing_phis(self):  # -> UniqueDict:

        ...
    @property
    def blockstack_initial(self):  # -> tuple[Any, ...]:

        ...
    @property
    def stack_depth(self):  # -> int:

        ...
    def find_initial_try_block(self):  # -> None:

        ...
    def has_terminated(self):  # -> bool:
        ...
    def get_inst(self): ...
    def advance_pc(self):  # -> None:
        ...
    def make_temp(self, prefix=...):  # -> str:
        ...
    def append(self, inst, **kwargs):  # -> None:

        ...
    def get_tos(self): ...
    def peek(self, k): ...
    def push(self, item):  # -> None:

        ...
    def pop(self): ...
    def swap(self, idx):  # -> None:

        ...
    def push_block(self, synblk):  # -> None:

        ...
    def reset_stack(self, depth):  # -> list[Any]:

        ...
    def make_block(self, kind, end, reset_stack=..., handler=...):  # -> dict[str, Any]:

        ...
    def pop_block(self): ...
    def pop_block_and_above(self, blk):  # -> None:

        ...
    def get_top_block(self, kind):  # -> None:

        ...
    def get_top_block_either(self, *kinds):  # -> None:

        ...
    def has_active_try(self):  # -> bool:

        ...
    def get_varname(self, inst): ...
    def get_varname_by_arg(self, oparg: int): ...
    def terminate(self):  # -> None:

        ...
    def fork(self, pc, npop=..., npush=..., extra_block=...):  # -> None:

        ...
    def split_new_block(self):  # -> None:

        ...
    def get_outgoing_states(self):  # -> list[Any]:

        ...
    def get_outgoing_edgepushed(self):  # -> dict[Any, tuple[Any, ...]]:

        ...

class StatePy311(_State):
    def __init__(self, *args, **kwargs) -> None: ...
    def pop_kw_names(self):  # -> None:
        ...
    def set_kw_names(self, val):  # -> None:
        ...
    def is_in_exception(self):  # -> bool:
        ...
    def get_exception(self): ...
    def in_with(self):  # -> Literal[True] | None:
        ...
    def make_null(self):  # -> str:
        ...

class StatePy313(StatePy311):
    def __init__(self, *args, **kwargs) -> None: ...
    def set_function_attribute(self, make_func_res, **kwargs):  # -> None:
        ...
    def get_function_attributes(self, make_func_res):  # -> dict[Any, Any]:
        ...

State = ...
Edge = ...

class AdaptDFA:
    def __init__(self, flow) -> None: ...
    @property
    def infos(self): ...

AdaptBlockInfo = ...

def adapt_state_infos(state):  # -> AdaptBlockInfo:
    ...

class AdaptCFA:
    def __init__(self, flow) -> None: ...
    @property
    def graph(self): ...
    @property
    def backbone(self): ...
    @property
    def blocks(self):  # -> dict[Any, Any]:
        ...
    def iterliveblocks(self):  # -> Generator[Any, Any, None]:
        ...
    def dump(self):  # -> None:
        ...

class AdaptCFBlock:
    def __init__(self, blockinfo, offset) -> None: ...
