from numba.core import serialize
from numba.core.utils import PYVERSION

if PYVERSION in ((3, 12), (3, 13), (3, 14)):
    INSTR_LEN = ...
else: ...
opcode_info = ...
_ExceptionTableEntry = ...
_FIXED_OFFSET = ...

def get_function_object(obj):  # -> Any:

    ...
def get_code_object(obj):  # -> Any | None:

    ...

JREL_OPS = ...
JABS_OPS = ...
JUMP_OPS = ...
TERM_OPS = ...
EXTENDED_ARG = ...
HAVE_ARGUMENT = ...

class ByteCodeInst:
    __slots__ = ...
    def __init__(self, offset, opcode, arg, nextoffset) -> None: ...
    @property
    def is_jump(self):  # -> bool:
        ...
    @property
    def is_terminator(self):  # -> bool:
        ...
    def get_jump_target(self): ...
    @property
    def block_effect(self):  # -> Literal[1, -1, 0]:

        ...

CODE_LEN = ...
ARG_LEN = ...
NO_ARG_LEN = ...
OPCODE_NOP = ...
if PYVERSION in ((3, 13), (3, 14)): ...
else: ...

class ByteCodeIter:
    def __init__(self, code) -> None: ...
    def __iter__(self):  # -> Self:
        ...
    def next(self):  # -> tuple[Any | int, ByteCodeInst]:
        ...

    __next__ = ...
    def read_arg(self, size):  # -> int:
        ...

class _ByteCode:
    __slots__ = ...
    def __init__(self, func_id) -> None: ...
    def __iter__(self):  # -> Iterator[ByteCodeInst]:
        ...
    def __getitem__(self, offset):  # -> ByteCodeInst:
        ...
    def __contains__(self, offset) -> bool:  # -> bool:
        ...
    def dump(self):  # -> str:
        ...
    def get_used_globals(self):  # -> dict[Any, Any]:

        ...

class ByteCodePy311(_ByteCode):
    def __init__(self, func_id) -> None: ...
    @staticmethod
    def fixup_eh(ent): ...
    def find_exception_entry(self, offset):  # -> None:

        ...

class ByteCodePy312(ByteCodePy311):
    def __init__(self, func_id) -> None: ...
    @property
    def ordered_offsets(self):  # -> list[Any | int]:
        ...
    def remove_build_list_swap_pattern(self, entries):  # -> list[Any]:

        ...

ByteCode = ...

class FunctionIdentity(serialize.ReduceMixin):
    _unique_ids = ...
    @classmethod
    def from_function(cls, pyfunc):  # -> Self:

        ...
    def derive(self):  # -> Self:

        ...
