from abc import ABCMeta, abstractmethod

"""
Caching mechanism for compiled functions.
"""

class _Cache(metaclass=ABCMeta):
    @property
    @abstractmethod
    def cache_path(self):  # -> None:

        ...
    @abstractmethod
    def load_overload(self, sig, target_context):  # -> None:

        ...
    @abstractmethod
    def save_overload(self, sig, data):  # -> None:

        ...
    @abstractmethod
    def enable(self):  # -> None:

        ...
    @abstractmethod
    def disable(self):  # -> None:

        ...
    @abstractmethod
    def flush(self):  # -> None:

        ...

class NullCache(_Cache):
    @property
    def cache_path(self):  # -> None:
        ...
    def load_overload(self, sig, target_context):  # -> None:
        ...
    def save_overload(self, sig, cres):  # -> None:
        ...
    def enable(self):  # -> None:
        ...
    def disable(self):  # -> None:
        ...
    def flush(self):  # -> None:
        ...

class _CacheLocator(metaclass=ABCMeta):
    def ensure_cache_path(self):  # -> None:
        ...
    @abstractmethod
    def get_cache_path(self):  # -> None:

        ...
    @abstractmethod
    def get_source_stamp(self):  # -> None:

        ...
    @abstractmethod
    def get_disambiguator(self):  # -> None:

        ...
    @classmethod
    def from_function(cls, py_func, py_file): ...
    @classmethod
    def get_suitable_cache_subpath(cls, py_file):  # -> str:

        ...

class _SourceFileBackedLocatorMixin:
    def get_source_stamp(self):  # -> tuple[float, int]:
        ...
    def get_disambiguator(self):  # -> str:
        ...
    @classmethod
    def from_function(cls, py_func, py_file):  # -> Self | None:
        ...

class UserProvidedCacheLocator(_SourceFileBackedLocatorMixin, _CacheLocator):
    def __init__(self, py_func, py_file) -> None: ...
    def get_cache_path(self):  # -> str:
        ...
    @classmethod
    def from_function(cls, py_func, py_file):  # -> _SourceFileBackedLocatorMixin | None:
        ...

class InTreeCacheLocator(_SourceFileBackedLocatorMixin, _CacheLocator):
    def __init__(self, py_func, py_file) -> None: ...
    def get_cache_path(self):  # -> str:
        ...

class InTreeCacheLocatorFsAgnostic(InTreeCacheLocator):
    def get_source_stamp(self):  # -> tuple[int, int]:
        ...

class UserWideCacheLocator(_SourceFileBackedLocatorMixin, _CacheLocator):
    def __init__(self, py_func, py_file) -> None: ...
    def get_cache_path(self):  # -> str:
        ...
    @classmethod
    def from_function(cls, py_func, py_file):  # -> Self | None:
        ...

class IPythonCacheLocator(_CacheLocator):
    def __init__(self, py_func, py_file) -> None: ...
    def get_cache_path(self):  # -> str:
        ...
    def get_source_stamp(self):  # -> str:
        ...
    def get_disambiguator(self):  # -> str:
        ...
    @classmethod
    def from_function(cls, py_func, py_file):  # -> Self | None:
        ...

class ZipCacheLocator(_SourceFileBackedLocatorMixin, _CacheLocator):
    def __init__(self, py_func, py_file) -> None: ...
    def get_cache_path(self):  # -> str:
        ...
    def get_source_stamp(self):  # -> tuple[float, int]:
        ...
    @classmethod
    def from_function(cls, py_func, py_file):  # -> Self | None:
        ...

class CacheImpl(metaclass=ABCMeta):
    _locator_classes = ...
    def __init__(self, py_func) -> None: ...
    def get_filename_base(self, fullname, abiflags):  # -> str:
        ...
    @property
    def filename_base(self):  # -> str:
        ...
    @property
    def locator(self): ...
    @abstractmethod
    def reduce(self, data):  # -> None:

        ...
    @abstractmethod
    def rebuild(self, target_context, reduced_data):  # -> None:

        ...
    @abstractmethod
    def check_cachable(self, data):  # -> None:

        ...

class CompileResultCacheImpl(CacheImpl):
    def reduce(self, cres): ...
    def rebuild(self, target_context, payload):  # -> CompileResult:

        ...
    def check_cachable(self, cres):  # -> bool:

        ...

class CodeLibraryCacheImpl(CacheImpl):
    _filename_prefix = ...
    def reduce(self, codelib): ...
    def rebuild(self, target_context, payload): ...
    def check_cachable(self, codelib):  # -> bool:

        ...
    def get_filename_base(self, fullname, abiflags): ...

class IndexDataCacheFile:
    def __init__(self, cache_path, filename_base, source_stamp) -> None: ...
    def flush(self):  # -> None:
        ...
    def save(self, key, data):  # -> None:

        ...
    def load(self, key):  # -> Any | None:

        ...

class Cache(_Cache):
    _impl_class = ...
    def __init__(self, py_func) -> None: ...
    @property
    def cache_path(self): ...
    def enable(self):  # -> None:
        ...
    def disable(self):  # -> None:
        ...
    def flush(self):  # -> None:
        ...
    def load_overload(self, sig, target_context):  # -> None:

        ...
    def save_overload(self, sig, data):  # -> None:

        ...

class FunctionCache(Cache):
    _impl_class = CompileResultCacheImpl

_lib_cache_prefixes = ...

def make_library_cache(prefix) -> None:  # -> type[LibraryCache]:

    class CustomCodeLibraryCacheImpl(CodeLibraryCacheImpl): ...
    class LibraryCache(Cache): ...
