class _ArgManager:
    def __init__(self, context, builder, api, env_manager, endblk, nargs) -> None: ...
    def add_arg(self, obj, ty): ...
    def emit_cleanup(self):  # -> None:

        ...

class _GilManager:
    def __init__(self, builder, api, argman) -> None: ...
    def emit_cleanup(self):  # -> None:
        ...

class PyCallWrapper:
    def __init__(self, context, module, func, fndesc, env, call_helper, release_gil) -> None: ...
    def build(self):  # -> tuple[Function, Any]:
        ...
    def build_wrapper(self, api, builder, closure, args, kws):  # -> None:
        ...
    def get_env(self, api, builder): ...
    def debug_print(self, builder, msg):  # -> None:
        ...
