TryStatus = ...
Status = ...
int32_t = ...
int64_t = ...
errcode_t = ...
RETCODE_OK = ...
RETCODE_EXC = ...
RETCODE_NONE = ...
RETCODE_STOPIT = ...
FIRST_USEREXC = ...
RETCODE_USEREXC = ...

class BaseCallConv:
    def __init__(self, context) -> None: ...
    def return_optional_value(self, builder, retty, valty, value):  # -> None:
        ...
    def return_native_none(self, builder):  # -> None:
        ...
    def return_exc(self, builder):  # -> None:
        ...
    def return_stop_iteration(self, builder):  # -> None:
        ...
    def get_return_type(self, ty): ...
    def init_call_helper(self, builder): ...
    def unpack_exception(self, builder, pyapi, status): ...
    def raise_error(self, builder, pyapi, status):  # -> None:

        ...
    def decode_arguments(self, builder, argtypes, func): ...

class MinimalCallConv(BaseCallConv):
    def return_value(self, builder, retval):  # -> None:
        ...
    def return_user_exc(self, builder, exc, exc_args=..., loc=..., func_name=...):  # -> None:
        ...
    def return_status_propagate(self, builder, status):  # -> None:
        ...
    def get_function_type(self, restype, argtypes):  # -> FunctionType:

        ...
    def decorate_function(self, fn, args, fe_argtypes, noalias=...):  # -> None:

        ...
    def get_arguments(self, func): ...
    def call_function(self, builder, callee, resty, argtys, args):  # -> tuple[Status, Any]:

        ...

class _MinimalCallHelper:
    def __init__(self) -> None: ...
    def get_exception(self, exc_id):  # -> tuple[type[SystemError], tuple[Any], None]:

        ...

PICKLE_BUF_IDX = ...
PICKLE_BUFSZ_IDX = ...
HASH_BUF_IDX = ...
UNWRAP_FUNC_IDX = ...
ALLOC_FLAG_IDX = ...
excinfo_t = ...
excinfo_ptr_t = ...

class CPUCallConv(BaseCallConv):
    _status_ids = ...
    def return_value(self, builder, retval):  # -> None:
        ...
    def build_excinfo_struct(self, exc, exc_args, loc, func_name):  # -> tuple[Any, Any, tuple[Any, Any, Any] | None]:
        ...
    def set_static_user_exc(self, builder, exc, exc_args=..., loc=..., func_name=...):  # -> None:
        ...
    def return_user_exc(self, builder, exc, exc_args=..., loc=..., func_name=...):  # -> None:
        ...
    def unpack_dynamic_exception(self, builder, pyapi, status): ...
    def unpack_exception(self, builder, pyapi, status): ...
    def emit_unwrap_dynamic_exception_fn(self, module, st_type, nb_types):  # -> Function:
        ...
    def emit_wrap_args_insts(self, builder, pyapi, struct_type, exc_args): ...
    def set_dynamic_user_exc(self, builder, exc, exc_args, nb_types, loc=..., func_name=...):  # -> None:

        ...
    def return_dynamic_user_exc(self, builder, exc, exc_args, nb_types, loc=..., func_name=...):  # -> None:

        ...
    def check_try_status(self, builder):  # -> TryStatus:
        ...
    def set_try_status(self, builder):  # -> None:
        ...
    def unset_try_status(self, builder):  # -> None:
        ...
    def return_status_propagate(self, builder, status):  # -> None:
        ...
    def get_function_type(self, restype, argtypes):  # -> FunctionType:

        ...
    def decorate_function(self, fn, args, fe_argtypes, noalias=...):  # -> None:

        ...
    def get_arguments(self, func): ...
    def call_function(self, builder, callee, resty, argtys, args, attrs=...):  # -> tuple[Status, Any]:

        ...

class ErrorModel:
    def __init__(self, call_conv) -> None: ...
    def fp_zero_division(self, builder, exc_args=..., loc=...):  # -> bool:
        ...

class PythonErrorModel(ErrorModel):
    raise_on_fp_zero_division = ...

class NumpyErrorModel(ErrorModel):
    raise_on_fp_zero_division = ...

error_models = ...

def create_error_model(model_name, context): ...
