from contextlib import ExitStack, contextmanager

"""
Generic helpers for LLVM code generation.
"""
bool_t = ...
int8_t = ...
int32_t = ...
intp_t = ...
voidptr_t = ...
true_bit = ...
false_bit = ...
true_byte = ...
false_byte = ...

def as_bool_bit(builder, value): ...
def make_anonymous_struct(builder, values, struct_type=...):  # -> Constant:

    ...
def make_bytearray(buf):  # -> Constant:

    ...

_struct_proxy_cache = ...

def create_struct_proxy(fe_type, kind=...):  # -> Any:

    ...
def copy_struct(dst, src, repl=...): ...

class _StructProxy:
    _fe_type = ...
    def __init__(self, context, builder, value=..., ref=...) -> None: ...
    def __getattr__(self, field): ...
    def __setattr__(self, field, value) -> None:  # -> None:

        ...
    def __getitem__(self, index): ...
    def __setitem__(self, index, value) -> None:  # -> None:

        ...
    def __len__(self) -> int: ...

class ValueStructProxy(_StructProxy): ...
class DataStructProxy(_StructProxy): ...

class Structure:
    def __init__(self, context, builder, value=..., ref=..., cast_ref=...) -> None: ...
    def __getattr__(self, field): ...
    def __setattr__(self, field, value) -> None:  # -> None:

        ...
    def __getitem__(self, index): ...
    def __setitem__(self, index, value) -> None:  # -> None:

        ...
    def __len__(self) -> int:  # -> int:

        ...

def alloca_once(builder, ty, size=..., name=..., zfill=...): ...
def sizeof(builder, ptr_type): ...
def alloca_once_value(builder, value, name=..., zfill=...): ...
def insert_pure_function(module, fnty, name):  # -> Function:

    ...
def get_or_insert_function(module, fnty, name):  # -> Function:

    ...
def get_or_insert_named_metadata(module, name): ...
def add_global_variable(module, ty, name, addrspace=...):  # -> GlobalVariable:
    ...
def terminate(builder, bbend):  # -> None:
    ...
def get_null_value(ltype): ...
def is_null(builder, val): ...
def is_not_null(builder, val): ...
def if_unlikely(builder, pred): ...
def if_likely(builder, pred): ...
def ifnot(builder, pred): ...
def increment_index(builder, val): ...

Loop = ...

@contextmanager
def for_range(builder, count, start=..., intp=...):  # -> Generator[Loop, Any, None]:

    ...
@contextmanager
def for_range_slice(builder, start, stop, step, intp=..., inc=...):  # -> Generator[tuple[Any, Any], Any, None]:

    ...
@contextmanager
def for_range_slice_generic(
    builder, start, stop, step
):  # -> Generator[tuple[_GeneratorContextManager[Any, None, None], _GeneratorContextManager[Any, None, None]], Any, None]:

    ...
@contextmanager
def loop_nest(builder, shape, intp, order=...):  # -> Generator[tuple[()] | Any, Any, None]:

    ...
def pack_array(builder, values, ty=...):  # -> Constant:

    ...
def pack_struct(builder, values):  # -> Constant:

    ...
def unpack_tuple(builder, tup, count=...):  # -> list[Any]:

    ...
def get_item_pointer(context, builder, aryty, ary, inds, wraparound=..., boundscheck=...): ...
def do_boundscheck(context, builder, ind, dimlen, axis=...):  # -> None:
    ...
def get_item_pointer2(context, builder, data, shape, strides, layout, inds, wraparound=..., boundscheck=...): ...
def is_scalar_zero(builder, value): ...
def is_not_scalar_zero(builder, value): ...
def is_scalar_zero_or_nan(builder, value): ...

is_true = ...
is_false = ...

def is_scalar_neg(builder, value): ...
@contextmanager
def early_exit_if(builder, stack: ExitStack, cond):  # -> Generator[None, Any, None]:

    ...
def early_exit_if_null(builder, stack, obj):  # -> _GeneratorContextManager[None, None, None]:

    ...
def guard_null(context, builder, value, exc_tuple):  # -> None:

    ...
def guard_memory_error(context, builder, pointer, msg=...):  # -> None:

    ...
@contextmanager
def if_zero(builder, value, likely=...):  # -> Generator[None, Any, None]:

    ...

guard_zero = ...

def is_pointer(ltyp):  # -> bool:

    ...
def get_record_member(builder, record, offset, typ): ...
def is_neg_int(builder, val): ...
def gep_inbounds(builder, ptr, *inds, **kws): ...
def gep(builder, ptr, *inds, **kws): ...
def pointer_add(builder, ptr, offset, return_type=...): ...
def memset(builder, ptr, size, value):  # -> None:

    ...
def memset_padding(builder, ptr):  # -> None:

    ...
def global_constant(builder_or_module, name, value, linkage=...):  # -> GlobalVariable:

    ...
def divmod_by_constant(builder, val, divisor):  # -> tuple[Any, Any]:

    ...
def cbranch_or_continue(builder, cond, bbtrue): ...
def memcpy(builder, dst, src, count):  # -> None:

    ...
def raw_memcpy(builder, dst, src, count, itemsize, align=...):  # -> None:

    ...
def raw_memmove(builder, dst, src, count, itemsize, align=...):  # -> None:

    ...
def muladd_with_overflow(builder, a, b, c):  # -> tuple[Any, Any]:

    ...
def printf(builder, format, *args): ...
def snprintf(builder, buffer, bufsz, format, *args): ...
def snprintf_stackbuffer(builder, bufsz, format, *args): ...
def normalize_ir_text(text): ...
def hexdump(builder, ptr, nbytes):  # -> None:

    ...
def is_nonelike(ty):  # -> bool:

    ...
def is_empty_tuple(ty):  # -> bool:

    ...
def create_constant_array(ty, val):  # -> Constant:

    ...
