class _CompilerLock:
    def __init__(self) -> None: ...
    def acquire(self):  # -> None:
        ...
    def release(self):  # -> None:
        ...
    def __enter__(self):  # -> None:
        ...
    def __exit__(self, exc_val, exc_type, traceback):  # -> None:
        ...
    def is_locked(self):  # -> object | bool:
        ...
    def __call__(self, func):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
        ...

global_compiler_lock = ...

def require_global_compiler_lock():  # -> None:

    ...
