from abc import ABCMeta, abstractmethod

_termcolor = ...

class SimpleTimer:
    def __enter__(self):  # -> Self:
        ...
    def __exit__(self, *exc):  # -> None:
        ...

class CompilerPass(metaclass=ABCMeta):
    @abstractmethod
    def __init__(self, *args, **kwargs) -> None: ...
    @classmethod
    def name(cls): ...
    @property
    def pass_id(self):  # -> None:

        ...
    @pass_id.setter
    def pass_id(self, val):  # -> None:

        ...
    @property
    def analysis(self):  # -> None:

        ...
    @analysis.setter
    def analysis(self, val):  # -> None:

        ...
    def run_initialization(self, *args, **kwargs):  # -> Literal[False]:

        ...
    @abstractmethod
    def run_pass(self, *args, **kwargs):  # -> None:

        ...
    def run_finalizer(self, *args, **kwargs):  # -> Literal[False]:

        ...
    def get_analysis_usage(self, AU):  # -> None:

        ...
    def get_analysis(self, pass_name): ...

class SSACompliantMixin: ...
class FunctionPass(CompilerPass): ...
class AnalysisPass(CompilerPass): ...
class LoweringPass(CompilerPass): ...

class AnalysisUsage:
    def __init__(self) -> None: ...
    def get_required_set(self):  # -> set[Any]:
        ...
    def get_preserved_set(self):  # -> set[Any]:
        ...
    def add_required(self, pss):  # -> None:
        ...
    def add_preserved(self, pss):  # -> None:
        ...

_DEBUG = ...

def debug_print(*args, **kwargs):  # -> None:
    ...

pass_timings = ...

class PassManager:
    _ENFORCING = ...
    def __init__(self, pipeline_name) -> None: ...
    def add_pass(self, pss, description=...):  # -> None:

        ...
    def add_pass_after(self, pass_cls, location):  # -> None:

        ...
    def finalize(self):  # -> None:

        ...
    @property
    def finalized(self):  # -> bool:
        ...
    def run(self, state):  # -> None:

        ...
    def dependency_analysis(self):  # -> dict[Any, Any]:

        ...

pass_info = ...

class PassRegistry:
    _id = ...
    _registry = ...
    def register(self, mutates_CFG, analysis_only):  # -> Callable[..., Any]:
        ...
    def is_registered(self, clazz):  # -> bool:
        ...
    def get(self, clazz): ...
    def find_by_name(self, class_name): ...
    def dump(self):  # -> None:
        ...

_pass_registry = ...
register_pass = ...
