from collections import namedtuple

from numba.core.targetconfig import TargetConfig

class Flags(TargetConfig):
    __slots__ = ...
    enable_looplift = ...
    enable_pyobject = ...
    enable_pyobject_looplift = ...
    enable_ssa = ...
    force_pyobject = ...
    release_gil = ...
    no_compile = ...
    debuginfo = ...
    boundscheck = ...
    forceinline = ...
    no_cpython_wrapper = ...
    no_cfunc_wrapper = ...
    auto_parallel = ...
    nrt = ...
    no_rewrites = ...
    error_model = ...
    fastmath = ...
    noalias = ...
    inline = ...
    dbg_extend_lifetimes = ...
    dbg_optnone = ...
    dbg_directives_only = ...

DEFAULT_FLAGS = ...
CR_FIELDS = ...

class CompileResult(namedtuple("_CompileResult", CR_FIELDS)):
    __slots__ = ...
    @property
    def codegen(self):  # -> Any:
        ...
    def dump(self, tab=...):  # -> None:
        ...

_LowerResult = ...

def sanitize_compile_result_entries(entries): ...
def compile_result(**entries):  # -> CompileResult:
    ...
def run_frontend(func, inline_closures=..., emit_dels=...):  # -> FunctionIR:

    ...

class _CompileStatus:
    __slots__ = ...
    def __init__(self, can_fallback) -> None: ...

class _EarlyPipelineCompletion(Exception):
    def __init__(self, result) -> None: ...

class StateDict(dict):
    def __getattr__(self, attr): ...
    def __setattr__(self, attr, value) -> None:  # -> None:
        ...

class CompilerBase:
    def __init__(self, typingctx, targetctx, library, args, return_type, flags, locals) -> None: ...
    def compile_extra(self, func): ...
    def compile_ir(self, func_ir, lifted=..., lifted_from=...): ...
    def define_pipelines(self): ...

class Compiler(CompilerBase):
    def define_pipelines(self):  # -> list[PassManager]:
        ...

class DefaultPassBuilder:
    @staticmethod
    def define_nopython_pipeline(state, name=...):  # -> PassManager:

        ...
    @staticmethod
    def define_nopython_lowering_pipeline(state, name=...):  # -> PassManager:
        ...
    @staticmethod
    def define_parfor_gufunc_nopython_lowering_pipeline(state, name=...):  # -> PassManager:
        ...
    @staticmethod
    def define_typed_pipeline(state, name=...):  # -> PassManager:

        ...
    @staticmethod
    def define_parfor_gufunc_pipeline(state, name=...):  # -> PassManager:

        ...
    @staticmethod
    def define_untyped_pipeline(state, name=...):  # -> PassManager:

        ...
    @staticmethod
    def define_objectmode_pipeline(state, name=...):  # -> PassManager:

        ...

def compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library=..., pipeline_class=...): ...
def compile_ir(
    typingctx,
    targetctx,
    func_ir,
    args,
    return_type,
    flags,
    locals,
    lifted=...,
    lifted_from=...,
    is_lifted_loop=...,
    library=...,
    pipeline_class=...,
): ...
def compile_internal(typingctx, targetctx, library, func, args, return_type, flags, locals): ...
