_HAVE_YAML = ...
IS_WIN32 = ...
IS_OSX = ...
MACHINE_BITS = ...
IS_32BITS = ...
PYVERSION = ...
_config_fname = ...

class _OptLevel(int):
    def __new__(cls, *args, **kwargs): ...
    @property
    def is_opt_max(self): ...

class _EnvReloader:
    def __init__(self) -> None: ...
    def reset(self): ...
    def update(self, force=...): ...
    def validate(self): ...
    def process_environ(self, environ): ...

_env_reloader = ...

def reload_config(): ...
