import collections

from numba.core.utils import PYVERSION

NEW_BLOCKERS = ...

class CFBlock:
    def __init__(self, offset) -> None: ...
    def __iter__(self):  # -> Iterator[Any]:
        ...

class Loop(collections.namedtuple("Loop", ("entries", "exits", "header", "body"))):
    __slots__ = ...
    def __eq__(self, other) -> bool: ...
    def __hash__(self) -> int: ...

class _DictOfContainers(collections.defaultdict):
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...

class CFGraph:
    def __init__(self) -> None: ...
    def add_node(self, node):  # -> None:

        ...
    def add_edge(self, src, dest, data=...):  # -> None:

        ...
    def successors(self, src):  # -> Generator[tuple[Any, Any], Any, None]:

        ...
    def predecessors(self, dest):  # -> Generator[tuple[Any, Any], Any, None]:

        ...
    def set_entry_point(self, node):  # -> None:

        ...
    def process(self):  # -> None:

        ...
    def dominators(self):  # -> dict[Any, Any]:

        ...
    def post_dominators(self):  # -> dict[Any, Any]:

        ...
    def immediate_dominators(self):  # -> dict[Any | None, Any | None]:

        ...
    def dominance_frontier(self):  # -> dict[Any | None, set[Any]]:

        ...
    def dominator_tree(self):  # -> _DictOfContainers:

        ...
    def descendents(self, node): ...
    def entry_point(self): ...
    def exit_points(self):  # -> set[Any]:

        ...
    def backbone(self): ...
    def loops(self):  # -> dict[Any, Any]:

        ...
    def in_loops(self, node):  # -> list[Any]:

        ...
    def dead_nodes(self):  # -> set[Any]:

        ...
    def nodes(self):  # -> set[Any]:

        ...
    def topo_order(self):  # -> list[Any]:

        ...
    def topo_sort(self, nodes, reverse=...):  # -> Generator[Any, Any, None]:

        ...
    def dump(self, file=...):  # -> None:

        ...
    def render_dot(self, filename=...): ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...

class ControlFlowAnalysis:
    def __init__(self, bytecode) -> None: ...
    def iterblocks(self):  # -> Generator[Any, Any, None]:

        ...
    def iterliveblocks(self):  # -> Generator[Any, Any, None]:

        ...
    def incoming_blocks(self, block):  # -> Generator[tuple[Any, Any], Any, None]:

        ...
    def dump(self, file=...):  # -> None:
        ...
    def run(self):  # -> None:
        ...
    def jump(self, target, pops=...):  # -> None:

        ...
    def op_SETUP_LOOP(self, inst):  # -> None:
        ...
    def op_SETUP_WITH(self, inst):  # -> None:
        ...
    def op_POP_BLOCK(self, inst):  # -> None:
        ...
    def op_FOR_ITER(self, inst):  # -> None:
        ...

    op_POP_JUMP_IF_FALSE = ...
    op_POP_JUMP_IF_TRUE = ...
    op_JUMP_IF_FALSE = ...
    op_JUMP_IF_TRUE = ...
    op_POP_JUMP_FORWARD_IF_FALSE = ...
    op_POP_JUMP_BACKWARD_IF_FALSE = ...
    op_POP_JUMP_FORWARD_IF_TRUE = ...
    op_POP_JUMP_BACKWARD_IF_TRUE = ...
    op_JUMP_IF_FALSE_OR_POP = ...
    op_JUMP_IF_TRUE_OR_POP = ...
    def op_JUMP_ABSOLUTE(self, inst):  # -> None:
        ...
    def op_JUMP_FORWARD(self, inst):  # -> None:
        ...

    op_JUMP_BACKWARD = ...
    def op_RETURN_VALUE(self, inst):  # -> None:
        ...

    if PYVERSION in ((3, 12), (3, 13), (3, 14)):
        def op_RETURN_CONST(self, inst):  # -> None:
            ...

    else: ...
    def op_RAISE_VARARGS(self, inst):  # -> None:
        ...
    def op_BREAK_LOOP(self, inst):  # -> None:
        ...
