from abc import ABCMeta, abstractmethod

"""
Defines CPU Options for use in the CPU target
"""

class AbstractOptionValue(metaclass=ABCMeta):
    @abstractmethod
    def encode(self) -> str: ...

class FastMathOptions(AbstractOptionValue):
    def __init__(self, value) -> None: ...
    def __bool__(self) -> bool:  # -> bool:
        ...

    __nonzero__ = ...
    def encode(self) -> str: ...
    def __eq__(self, other) -> bool: ...

class ParallelOptions(AbstractOptionValue):
    __slots__ = ...
    def __init__(self, value) -> None: ...
    def __eq__(self, other) -> bool: ...
    def encode(self) -> str: ...

class InlineOptions(AbstractOptionValue):
    def __init__(self, value) -> None: ...
    @property
    def is_never_inline(self):  # -> bool:

        ...
    @property
    def is_always_inline(self):  # -> bool:

        ...
    @property
    def has_cost_model(self):  # -> bool:

        ...
    @property
    def value(self):  # -> str | Any:

        ...
    def __eq__(self, other) -> bool: ...
    def encode(self) -> str: ...
