import abc
from contextlib import contextmanager

"""
Implements helpers to build LLVM debuginfo.
"""

@contextmanager
def suspend_emission(builder):  # -> Generator[None, Any, None]:

    ...

class AbstractDIBuilder(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def mark_variable(self, builder, allocavalue, name, lltype, size, line, datamodel=..., argidx=...):  # -> None:

        ...
    @abc.abstractmethod
    def mark_location(self, builder, line):  # -> None:

        ...
    @abc.abstractmethod
    def mark_subprogram(self, function, qualname, argnames, argtypes, line):  # -> None:

        ...
    @abc.abstractmethod
    def initialize(self):  # -> None:

        ...
    @abc.abstractmethod
    def finalize(self):  # -> None:

        ...

class DummyDIBuilder(AbstractDIBuilder):
    def __init__(self, module, filepath, cgctx, directives_only) -> None: ...
    def mark_variable(self, builder, allocavalue, name, lltype, size, line, datamodel=..., argidx=...):  # -> None:
        ...
    def mark_location(self, builder, line):  # -> None:
        ...
    def mark_subprogram(self, function, qualname, argnames, argtypes, line):  # -> None:
        ...
    def initialize(self):  # -> None:
        ...
    def finalize(self):  # -> None:
        ...

_BYTE_SIZE = ...

class DIBuilder(AbstractDIBuilder):
    DWARF_VERSION = ...
    DEBUG_INFO_VERSION = ...
    DBG_CU_NAME = ...
    _DEBUG = ...
    def __init__(self, module, filepath, cgctx, directives_only) -> None: ...
    def initialize(self):  # -> None:
        ...
    def mark_variable(self, builder, allocavalue, name, lltype, size, line, datamodel=..., argidx=...): ...
    def mark_location(self, builder, line):  # -> None:
        ...
    def mark_subprogram(self, function, qualname, argnames, argtypes, line):  # -> None:
        ...
    def finalize(self):  # -> None:
        ...
