from abc import abstractmethod

from numba import _dispatcher
from numba.core import config, serialize
from numba.core.compiler_lock import global_compiler_lock

class OmittedArg:
    def __init__(self, value) -> None: ...

class _FunctionCompiler:
    def __init__(self, py_func, targetdescr, targetoptions, locals, pipeline_class) -> None: ...
    def fold_argument_types(self, args, kws):  # -> tuple[Signature, tuple[Any, ...]]:

        ...
    def compile(self, args, return_type):  # -> TypingError:
        ...
    def get_globals_for_reduction(self): ...

class _GeneratedFunctionCompiler(_FunctionCompiler):
    def __init__(self, py_func, targetdescr, targetoptions, locals, pipeline_class) -> None: ...
    def get_globals_for_reduction(self): ...

_CompileStats = ...

class CompilingCounter:
    def __init__(self) -> None: ...
    def __enter__(self):  # -> None:
        ...
    def __exit__(self, *args, **kwargs):  # -> None:
        ...
    def __bool__(self) -> bool:  # -> bool:
        ...

    __nonzero__ = ...

class _DispatcherBase(_dispatcher.Dispatcher):
    __numba__ = ...
    def __init__(self, arg_count, py_func, pysig, can_fallback, exact_match_required) -> None: ...
    @property
    def signatures(self):  # -> list[Any]:

        ...
    @property
    def nopython_signatures(self):  # -> list[Any]:
        ...
    def disable_compile(self, val=...):  # -> None:

        ...
    def add_overload(self, cres):  # -> None:
        ...
    def fold_argument_types(self, args, kws): ...
    def get_call_template(self, args, kws):  # -> tuple[Any, Any, Any, dict[Any, Any]]:

        ...
    def get_overload(self, sig): ...
    @property
    def is_compiling(self):  # -> CompilingCounter:

        ...
    def inspect_llvm(self, signature=...):  # -> dict[Any, Any | dict[Any, Any | dict[Any, Any]]]:

        ...
    def inspect_asm(self, signature=...):  # -> dict[Any, Any | dict[Any, Any | dict[Any, Any]]]:

        ...
    def inspect_types(self, file=..., signature=..., pretty=..., style=..., **kwargs):  # -> Annotate | None:

        ...
    def inspect_cfg(self, signature=..., show_wrapper=..., **kwargs):  # -> dict[Any, Any | dict[Any, Any | dict[Any, Any]]]:

        ...
    def inspect_disasm_cfg(self, signature=...):  # -> dict[Any, Any | dict[Any, Any | dict[Any, Any]]]:

        ...
    def get_annotation_info(self, signature=...):  # -> OrderedDict[Any, Any]:

        ...
    def typeof_pyval(self, val):  # -> PyObject | Buffer | Any | ExternalFunctionPointer | Opaque:

        ...

class _MemoMixin:
    __uuid = ...
    _memo = ...
    _recent = ...

class Dispatcher(serialize.ReduceMixin, _MemoMixin, _DispatcherBase):
    _fold_args = ...
    __numba__ = ...
    def __init__(self, py_func, locals=..., targetoptions=..., pipeline_class=...) -> None: ...
    def dump(self, tab=...):  # -> None:
        ...
    def enable_caching(self):  # -> None:
        ...
    def __get__(self, obj, objtype=...):  # -> Self | MethodType:

        ...
    def compile(self, sig): ...
    def get_compile_result(self, sig): ...
    def recompile(self):  # -> None:

        ...
    @property
    def stats(self):  # -> _CompileStats:
        ...
    def parallel_diagnostics(self, signature=..., level=...):  # -> None:

        ...
    def get_metadata(self, signature=...):  # -> dict[Any, Any]:

        ...
    def get_function_type(self):  # -> FunctionType | None:

        ...

class LiftedCode(serialize.ReduceMixin, _MemoMixin, _DispatcherBase):
    _fold_args = ...
    can_cache = ...
    def __init__(self, func_ir, typingctx, targetctx, flags, locals) -> None: ...
    def get_source_location(self): ...
    @abstractmethod
    def compile(self, sig):  # -> None:

        ...

class LiftedLoop(LiftedCode):
    def compile(self, sig): ...

class LiftedWith(LiftedCode):
    can_cache = ...
    def get_call_template(self, args, kws):  # -> tuple[Any, None, Any, Any]:

        ...
    def compile(self, sig): ...

class ObjModeLiftedWith(LiftedWith):
    def __init__(self, *args, **kwargs) -> None: ...
    def get_call_template(self, args, kws):  # -> tuple[Any, None, list[Opaque], Any]:

        ...
    @global_compiler_lock
    def compile(self, sig): ...

if config.USE_LEGACY_TYPE_SYSTEM: ...
else: ...
