from numba import _dynfunc

class Environment(_dynfunc.Environment):
    __slots__ = ...
    _memo = ...
    @classmethod
    def from_fndesc(cls, fndesc):  # -> Self:
        ...
    def can_cache(self):  # -> bool:
        ...
    def __reduce__(self):  # -> tuple[Callable[..., Any | Environment], tuple[Any, Any, Any]]:
        ...
    def __del__(self) -> None:  # -> None:
        ...

def lookup_environment(env_name):  # -> None:

    ...
