import abc
import contextlib
import os
from abc import abstractmethod

__all__ = []

class NumbaWarning(Warning):
    def __init__(self, msg, loc=..., highlighting=...) -> None: ...

class NumbaPerformanceWarning(NumbaWarning): ...
class NumbaDeprecationWarning(NumbaWarning, DeprecationWarning): ...
class NumbaPendingDeprecationWarning(NumbaWarning, PendingDeprecationWarning): ...
class NumbaParallelSafetyWarning(NumbaWarning): ...
class NumbaTypeSafetyWarning(NumbaWarning): ...
class NumbaExperimentalFeatureWarning(NumbaWarning): ...
class NumbaInvalidConfigWarning(NumbaWarning): ...

class NumbaPedanticWarning(NumbaWarning):
    def __init__(self, msg, **kwargs) -> None: ...

class NumbaIRAssumptionWarning(NumbaPedanticWarning): ...
class NumbaDebugInfoWarning(NumbaWarning): ...
class NumbaSystemWarning(NumbaWarning): ...

class _ColorScheme(metaclass=abc.ABCMeta):
    @abstractmethod
    def code(self, msg): ...
    @abstractmethod
    def errmsg(self, msg): ...
    @abstractmethod
    def filename(self, msg): ...
    @abstractmethod
    def indicate(self, msg): ...
    @abstractmethod
    def highlight(self, msg): ...
    @abstractmethod
    def reset(self, msg): ...

class _DummyColorScheme(_ColorScheme):
    def __init__(self, theme=...) -> None: ...
    def code(self, msg): ...
    def errmsg(self, msg): ...
    def filename(self, msg): ...
    def indicate(self, msg): ...
    def highlight(self, msg): ...
    def reset(self, msg): ...

_termcolor_inst = ...
colorama_version = ...
if tuple([int(x) for x in colorama_version.split(".")]) < (0, 3, 9):
    msg = ...
if os.environ.get("NUMBA_DISABLE_ERROR_MESSAGE_HIGHLIGHTING", None): ...
pedantic_warning_info = ...
feedback_details = ...
unsupported_error_info = ...
interpreter_error_info = ...
constant_inference_info = ...
typing_error_info = ...
reportable_issue_info = ...
error_extras = ...

def deprecated(arg): ...

class WarningsFixer:
    def __init__(self, category) -> None: ...
    @contextlib.contextmanager
    def catch_warnings(self, filename=..., lineno=...): ...
    def flush(self): ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_value, traceback): ...

class NumbaError(Exception):
    def __init__(self, msg, loc=..., highlighting=...) -> None: ...
    @property
    def contexts(self): ...
    def add_context(self, msg): ...
    def patch_message(self, new_message): ...

class UnsupportedError(NumbaError): ...

class UnsupportedBytecodeError(Exception):
    def __init__(self, msg, loc=...) -> None: ...

class UnsupportedRewriteError(UnsupportedError): ...
class IRError(NumbaError): ...
class RedefinedError(IRError): ...

class NotDefinedError(IRError):
    def __init__(self, name, loc=...) -> None: ...

class VerificationError(IRError): ...
class DeprecationError(NumbaError): ...

class LoweringError(NumbaError):
    def __init__(self, msg, loc=...) -> None: ...

class UnsupportedParforsError(NumbaError): ...
class ForbiddenConstruct(LoweringError): ...
class TypingError(NumbaError): ...

class UntypedAttributeError(TypingError):
    def __init__(self, value, attr, loc=...) -> None: ...

class ByteCodeSupportError(NumbaError):
    def __init__(self, msg, loc=...) -> None: ...

class CompilerError(NumbaError): ...

class ConstantInferenceError(NumbaError):
    def __init__(self, value, loc=...) -> None: ...

class InternalError(NumbaError):
    def __init__(self, exception) -> None: ...

class InternalTargetMismatchError(InternalError):
    def __init__(self, kind, target_hw, hw_clazz) -> None: ...

class NonexistentTargetError(InternalError): ...
class RequireLiteralValue(TypingError): ...

class ForceLiteralArg(NumbaError):
    def __init__(self, arg_indices, fold_arguments=..., loc=...) -> None: ...
    def bind_fold_arguments(self, fold_arguments): ...
    def combine(self, other): ...
    def __or__(self, other): ...

class LiteralTypingError(TypingError): ...
class NumbaValueError(TypingError): ...
class NumbaTypeError(TypingError): ...
class NumbaAttributeError(TypingError): ...
class NumbaAssertionError(TypingError): ...
class NumbaNotImplementedError(TypingError): ...
class NumbaKeyError(TypingError): ...
class NumbaIndexError(TypingError): ...
class NumbaRuntimeError(NumbaError): ...

_numba_path = ...
loc_info = ...

@contextlib.contextmanager
def new_error_context(fmt_, *args, **kwargs): ...

__all__ += [
    name
    for (name, value) in globals().items()
    if not name.startswith("_") and isinstance(value, type) and issubclass(value, (Exception, Warning))
]
