def compile_multi3(context): ...

class _Installer:
    _installed = ...
    def install(self, context):  # -> None:

        ...

class _ExternalMathFunctions(_Installer): ...

c_math_functions = ...
