import collections
import weakref
from collections.abc import Callable
from typing import Concatenate, Generic, ParamSpec, TypeVar

from numba.core.serialize import ReduceMixin

def type_callable(func): ...
def overload(func, jit_options=..., strict=..., inline=..., prefer_literal=..., **kwargs): ...
def register_jitable(*args, **kwargs): ...
def overload_attribute(typ, attr, **kwargs): ...
def overload_method(typ, attr, **kwargs): ...
def overload_classmethod(typ, attr, **kwargs): ...
def make_attribute_wrapper(typeclass, struct_attr, python_attr): ...

class _Intrinsic(ReduceMixin, Generic[P, R]):
    _memo: weakref.WeakValueDictionary
    _recent: collections.deque
    def __init__(self, name, defn: Callable[Concatenate[object, P], R], prefer_literal=..., **kwargs) -> None: ...
    def __call__(self, *args: P.args, **kwargs: P.kwargs) -> R: ...
    def __deepcopy__(self, memo): ...

P = ParamSpec("P")
R = TypeVar("R")

def intrinsic(*args, **kwargs) -> Callable[[Callable[Concatenate[object, P], R]], Callable[P, R]]: ...
def get_cython_function_address(module_name, function_name): ...
def include_path(): ...
def sentry_literal_args(pysig, literal_args, args, kwargs): ...

class SentryLiteralArgs(collections.namedtuple("_SentryLiteralArgs", ["literal_args"])):
    def for_function(self, func): ...
    def for_pysig(self, pysig): ...

class BoundLiteralArgs(collections.namedtuple("BoundLiteralArgs", ["pysig", "literal_args"])):
    def bind(self, *args, **kwargs): ...

def is_jitted(function): ...
