from llvmlite.ir.transforms import CallVisitor, Visitor

class FastFloatBinOpVisitor(Visitor):
    float_binops = ...
    def __init__(self, flags) -> None: ...
    def visit_Instruction(self, instr):  # -> None:
        ...

class FastFloatCallVisitor(CallVisitor):
    def __init__(self, flags) -> None: ...
    def visit_Call(self, instr):  # -> None:
        ...

def rewrite_module(mod, options):  # -> None:

    ...
