from numba.core.funcdesc import FunctionDescriptor

"""
Support for lowering generators.
"""

class GeneratorDescriptor(FunctionDescriptor):
    __slots__ = ...
    @classmethod
    def from_generator_fndesc(cls, func_ir, fndesc, gentype, mangler):  # -> Self:

        ...
    @property
    def llvm_finalizer_name(self):  # -> str:

        ...

class BaseGeneratorLower:
    def __init__(self, lower) -> None: ...
    @property
    def call_conv(self): ...
    def get_args_ptr(self, builder, genptr): ...
    def get_resume_index_ptr(self, builder, genptr): ...
    def get_state_ptr(self, builder, genptr): ...
    def lower_init_func(self, lower):  # -> None:

        ...
    def lower_next_func(self, lower):  # -> None:

        ...
    def lower_finalize_func(self, lower):  # -> None:

        ...
    def return_from_generator(self, lower):  # -> None:

        ...
    def create_resumption_block(self, lower, index):  # -> None:
        ...
    def debug_print(self, builder, msg):  # -> None:
        ...

class GeneratorLower(BaseGeneratorLower):
    def get_generator_type(self): ...
    def box_generator_struct(self, lower, gen_struct): ...
    def lower_finalize_func_body(self, builder, genptr):  # -> None:

        ...

class PyGeneratorLower(BaseGeneratorLower):
    def get_generator_type(self):  # -> Generator:

        ...
    def box_generator_struct(self, lower, gen_struct): ...
    def init_generator_state(self, lower):  # -> None:

        ...
    def lower_finalize_func_body(self, builder, genptr):  # -> None:

        ...

class LowerYield:
    def __init__(self, lower, yield_point, live_vars) -> None: ...
    def lower_yield_suspend(self):  # -> None:
        ...
    def lower_yield_resume(self):  # -> None:
        ...
