import contextlib
from enum import Enum

from numba.core.typing.templates import BaseRegistryLoader

"""
Utilities to simplify the boilerplate for native lowering.
"""

class Registry:
    def __init__(self, name=...) -> None: ...
    def lower(self, func, *argtys):  # -> Callable[..., Any]:

        ...
    def lower_getattr(self, ty, attr):  # -> Callable[..., Any]:

        ...
    def lower_getattr_generic(self, ty):  # -> Callable[..., Any]:

        ...
    def lower_setattr(self, ty, attr):  # -> Callable[..., Any]:

        ...
    def lower_setattr_generic(self, ty):  # -> Callable[..., Any]:

        ...
    def lower_cast(self, fromty, toty):  # -> Callable[..., Any]:

        ...
    def lower_constant(self, ty):  # -> Callable[..., Any]:

        ...

class RegistryLoader(BaseRegistryLoader):
    registry_items = ...

builtin_registry = ...
lower_builtin = ...
lower_getattr = ...
lower_getattr_generic = ...
lower_setattr = ...
lower_setattr_generic = ...
lower_cast = ...
lower_constant = ...

def fix_returning_optional(context, builder, sig, status, retval): ...
def user_function(fndesc, libs):  # -> Callable[..., Any]:

    ...
def user_generator(gendesc, libs):  # -> Callable[..., tuple[Any, Any]]:

    ...
def iterator_impl(iterable_type, iterator_type):  # -> Callable[..., Any]:

    ...

class _IternextResult:
    __slots__ = ...
    def __init__(self, context, builder, pairobj) -> None: ...
    def set_exhausted(self):  # -> None:

        ...
    def set_valid(self, is_valid=...):  # -> None:

        ...
    def yield_(self, value):  # -> None:

        ...
    def is_valid(self): ...
    def yielded_value(self): ...

class RefType(Enum):
    NEW = ...
    BORROWED = ...
    UNTRACKED = ...

def iternext_impl(ref_type=...):  # -> Callable[..., Callable[..., Any]]:

    ...
def call_getiter(context, builder, iterable_type, val): ...
def call_iternext(context, builder, iterator_type, val):  # -> _IternextResult:

    ...
def call_len(context, builder, ty, val):  # -> None:

    ...

_ForIterLoop = ...

@contextlib.contextmanager
def for_iter(context, builder, iterable_type, val):  # -> Generator[_ForIterLoop, Any, None]:

    ...
def impl_ret_new_ref(ctx, builder, retty, ret): ...
def impl_ret_borrowed(ctx, builder, retty, ret): ...
def impl_ret_untracked(ctx, builder, retty, ret): ...
@contextlib.contextmanager
def force_error_model(context, model_name=...):  # -> Generator[None, Any, None]:

    ...
def numba_typeref_ctor(*args, **kwargs): ...
