from numba.core.utils import PYVERSION

if PYVERSION in ((3, 12), (3, 13), (3, 14)): ...
else: ...

class _UNKNOWN_VALUE:
    def __init__(self, varname) -> None: ...

_logger = ...

class Assigner:
    def __init__(self) -> None: ...
    def assign(self, srcvar, destvar): ...
    def get_assignment_source(self, destname):  # -> None:

        ...

def peep_hole_call_function_ex_to_call_function_kw(func_ir): ...
def peep_hole_list_to_tuple(func_ir): ...
def peep_hole_delete_with_exit(func_ir): ...
def peep_hole_fuse_dict_add_updates(func_ir): ...
def peep_hole_split_at_pop_block(func_ir): ...

class Interpreter:
    _DEBUG_PRINT = ...
    def __init__(self, func_id) -> None: ...
    def interpret(self, bytecode):  # -> FunctionIR:

        ...
    def post_process(self, peepholes, func_ir): ...
    def init_first_block(self):  # -> None:
        ...
    def get_global_value(self, name):  # -> Any | UndefinedType:

        ...
    def get_closure_value(self, index):  # -> UndefinedType:

        ...
    @property
    def current_scope(self): ...
    @property
    def code_consts(self): ...
    @property
    def code_locals(self): ...
    @property
    def code_names(self): ...
    @property
    def code_cellvars(self): ...
    @property
    def code_freevars(self): ...
    def store(self, value, name, redefine=...): ...
    def get(self, name): ...
    def insert_block(self, offset, scope=..., loc=...):  # -> Block:
        ...
    def op_NOP(self, inst):  # -> None:
        ...

    if PYVERSION == (3, 14):
        op_NOT_TAKEN = ...
    else: ...
    def op_RESUME(self, inst):  # -> None:
        ...
    def op_CACHE(self, inst):  # -> None:
        ...
    def op_PRECALL(self, inst):  # -> None:
        ...
    def op_PUSH_NULL(self, inst):  # -> None:
        ...
    def op_RETURN_GENERATOR(self, inst):  # -> None:
        ...
    def op_PRINT_ITEM(self, inst, item, printvar, res):  # -> None:
        ...
    def op_PRINT_NEWLINE(self, inst, printvar, res):  # -> None:
        ...
    def op_UNPACK_SEQUENCE(self, inst, iterable, stores, tupleobj):  # -> None:
        ...
    def op_FORMAT_SIMPLE(self, inst, value, res, strvar):  # -> None:
        ...
    def op_FORMAT_VALUE(self, inst, value, res, strvar):  # -> None:

        ...
    def op_BUILD_STRING(self, inst, strings, tmps):  # -> None:

        ...
    def op_BUILD_SLICE(self, inst, start, stop, step, res, slicevar):  # -> None:
        ...

    if PYVERSION in ((3, 12), (3, 13), (3, 14)):
        def op_BINARY_SLICE(self, inst, start, end, container, res, slicevar, temp_res):  # -> None:
            ...

    else: ...
    if PYVERSION in ((3, 12), (3, 13), (3, 14)):
        def op_STORE_SLICE(self, inst, start, end, container, value, res, slicevar):  # -> None:
            ...

    else: ...
    def op_SLICE_0(self, inst, base, res, slicevar, indexvar, nonevar):  # -> None:
        ...
    def op_SLICE_1(self, inst, base, start, nonevar, res, slicevar, indexvar):  # -> None:
        ...
    def op_SLICE_2(self, inst, base, nonevar, stop, res, slicevar, indexvar):  # -> None:
        ...
    def op_SLICE_3(self, inst, base, start, stop, res, slicevar, indexvar):  # -> None:
        ...
    def op_STORE_SLICE_0(self, inst, base, value, slicevar, indexvar, nonevar):  # -> None:
        ...
    def op_STORE_SLICE_1(self, inst, base, start, nonevar, value, slicevar, indexvar):  # -> None:
        ...
    def op_STORE_SLICE_2(self, inst, base, nonevar, stop, value, slicevar, indexvar):  # -> None:
        ...
    def op_STORE_SLICE_3(self, inst, base, start, stop, value, slicevar, indexvar):  # -> None:
        ...
    def op_DELETE_SLICE_0(self, inst, base, slicevar, indexvar, nonevar):  # -> None:
        ...
    def op_DELETE_SLICE_1(self, inst, base, start, nonevar, slicevar, indexvar):  # -> None:
        ...
    def op_DELETE_SLICE_2(self, inst, base, nonevar, stop, slicevar, indexvar):  # -> None:
        ...
    def op_DELETE_SLICE_3(self, inst, base, start, stop, slicevar, indexvar):  # -> None:
        ...

    if PYVERSION in ((3, 13), (3, 14)):
        def op_LOAD_FAST(self, inst, res, as_load_deref=...):  # -> None:
            ...

    else:
        op_LOAD_FAST = ...
    if PYVERSION in ((3, 13), (3, 14)):
        def op_LOAD_FAST_LOAD_FAST(self, inst, res1, res2):  # -> None:
            ...
        def op_STORE_FAST_LOAD_FAST(self, inst, store_value, load_res):  # -> None:
            ...
        def op_STORE_FAST_STORE_FAST(self, inst, value1, value2):  # -> None:
            ...

    else: ...
    if PYVERSION in ((3, 12), (3, 13), (3, 14)):
        op_LOAD_FAST_CHECK = ...
        def op_LOAD_FAST_AND_CLEAR(self, inst, res):  # -> None:
            ...

    else: ...
    if PYVERSION == (3, 14):
        op_LOAD_FAST_BORROW = ...
        op_LOAD_FAST_BORROW_LOAD_FAST_BORROW = ...
    else: ...
    def op_STORE_FAST(self, inst, value):  # -> None:
        ...
    def op_DELETE_FAST(self, inst):  # -> None:
        ...
    def op_DUP_TOPX(self, inst, orig, duped):  # -> None:
        ...

    op_DUP_TOP = ...
    op_DUP_TOP_TWO = ...
    def op_STORE_ATTR(self, inst, target, value):  # -> None:
        ...
    def op_DELETE_ATTR(self, inst, target):  # -> None:
        ...
    def op_LOAD_ATTR(self, inst, item, res):  # -> None:
        ...
    def op_LOAD_CONST(self, inst, res):  # -> None:
        ...

    if PYVERSION == (3, 14):
        def op_LOAD_SMALL_INT(self, inst, res):  # -> None:
            ...

    else: ...
    if PYVERSION in ((3, 11), (3, 12), (3, 13), (3, 14)):
        def op_LOAD_GLOBAL(self, inst, idx, res):  # -> None:
            ...

    else:
        def op_LOAD_GLOBAL(self, inst, res):  # -> None:
            ...

    def op_COPY_FREE_VARS(self, inst):  # -> None:
        ...

    if PYVERSION in ((3, 11), (3, 12), (3, 13), (3, 14)):
        def op_LOAD_DEREF(self, inst, res):  # -> None:
            ...

    else:
        def op_LOAD_DEREF(self, inst, res):  # -> None:
            ...

    if PYVERSION in ((3, 11), (3, 12), (3, 13), (3, 14)):
        def op_MAKE_CELL(self, inst):  # -> None:
            ...

    if PYVERSION in ((3, 11), (3, 12), (3, 13), (3, 14)):
        def op_STORE_DEREF(self, inst, value):  # -> None:
            ...

    else:
        def op_STORE_DEREF(self, inst, value):  # -> None:
            ...

    def op_SETUP_LOOP(self, inst):  # -> None:
        ...
    def op_SETUP_WITH(self, inst, contextmanager, exitfn=...):  # -> None:
        ...

    if PYVERSION == (3, 14): ...
    else:
        def op_BEFORE_WITH(self, inst, contextmanager, exitfn, end):  # -> None:
            ...

    def op_SETUP_FINALLY(self, inst):  # -> None:
        ...
    def op_WITH_CLEANUP(self, inst):  # -> None:

        ...
    def op_WITH_CLEANUP_START(self, inst):  # -> None:

        ...
    def op_WITH_CLEANUP_FINISH(self, inst):  # -> None:

        ...
    def op_END_FINALLY(self, inst):  # -> None:

        ...
    def op_BEGIN_FINALLY(self, inst, temps):  # -> None:
        ...
    def op_CALL(self, inst, func, args, kw_names, res):  # -> None:
        ...

    if PYVERSION in ((3, 13), (3, 14)):
        def op_CALL_KW(self, inst, func, args, kw_names, res):  # -> None:
            ...

    else: ...
    def op_CALL_FUNCTION(self, inst, func, args, res):  # -> None:
        ...
    def op_CALL_FUNCTION_KW(self, inst, func, args, names, res):  # -> None:
        ...
    def op_CALL_FUNCTION_EX(self, inst, func, vararg, varkwarg, res):  # -> None:
        ...
    def op_BUILD_TUPLE_UNPACK_WITH_CALL(self, inst, tuples, temps, is_assign):  # -> None:
        ...
    def op_BUILD_TUPLE_UNPACK(self, inst, tuples, temps, is_assign):  # -> None:
        ...
    def op_LIST_TO_TUPLE(self, inst, const_list, res):  # -> None:
        ...
    def op_BUILD_CONST_KEY_MAP(self, inst, keys, keytmps, values, res):  # -> None:
        ...
    def op_GET_ITER(self, inst, value, res):  # -> None:
        ...
    def op_FOR_ITER(self, inst, iterator, pair, indval, pred):  # -> None:

        ...

    if PYVERSION == (3, 14): ...
    else:
        def op_BINARY_SUBSCR(self, inst, target, index, res):  # -> None:
            ...

    def op_STORE_SUBSCR(self, inst, target, index, value):  # -> None:
        ...
    def op_DELETE_SUBSCR(self, inst, target, index):  # -> None:
        ...
    def op_BUILD_TUPLE(self, inst, items, res):  # -> None:
        ...
    def op_BUILD_LIST(self, inst, items, res):  # -> None:
        ...
    def op_BUILD_SET(self, inst, items, res):  # -> None:
        ...
    def op_SET_ADD(self, inst, value, target, addvar, res):  # -> None:
        ...
    def op_SET_UPDATE(self, inst, target, value, updatevar, res):  # -> None:
        ...
    def op_DICT_UPDATE(self, inst, target, value, updatevar, res):  # -> None:
        ...
    def op_BUILD_MAP(self, inst, items, size, res):  # -> None:
        ...
    def op_STORE_MAP(self, inst, dct, key, value):  # -> None:
        ...
    def op_UNARY_NEGATIVE(self, inst, value, res): ...
    def op_UNARY_POSITIVE(self, inst, value, res): ...
    def op_UNARY_INVERT(self, inst, value, res): ...
    def op_UNARY_NOT(self, inst, value, res): ...
    def op_BINARY_OP(self, inst, op, lhs, rhs, res):  # -> None:
        ...
    def op_BINARY_ADD(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_BINARY_SUBTRACT(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_BINARY_MULTIPLY(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_BINARY_DIVIDE(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_BINARY_TRUE_DIVIDE(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_BINARY_FLOOR_DIVIDE(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_BINARY_MODULO(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_BINARY_POWER(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_BINARY_MATRIX_MULTIPLY(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_BINARY_LSHIFT(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_BINARY_RSHIFT(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_BINARY_AND(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_BINARY_OR(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_BINARY_XOR(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_INPLACE_ADD(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_INPLACE_SUBTRACT(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_INPLACE_MULTIPLY(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_INPLACE_DIVIDE(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_INPLACE_TRUE_DIVIDE(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_INPLACE_FLOOR_DIVIDE(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_INPLACE_MODULO(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_INPLACE_POWER(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_INPLACE_MATRIX_MULTIPLY(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_INPLACE_LSHIFT(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_INPLACE_RSHIFT(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_INPLACE_AND(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_INPLACE_OR(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_INPLACE_XOR(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_JUMP_ABSOLUTE(self, inst):  # -> None:
        ...
    def op_JUMP_FORWARD(self, inst):  # -> None:
        ...
    def op_JUMP_BACKWARD(self, inst):  # -> None:
        ...

    op_JUMP_BACKWARD_NO_INTERRUPT = ...
    def op_POP_BLOCK(self, inst, kind=...):  # -> None:
        ...
    def op_RETURN_VALUE(self, inst, retval, castval):  # -> None:
        ...

    if PYVERSION in ((3, 12), (3, 13), (3, 14)):
        def op_RETURN_CONST(self, inst, retval, castval):  # -> None:
            ...

    else: ...
    if PYVERSION in ((3, 13), (3, 14)):
        def op_TO_BOOL(self, inst, val, res):  # -> None:
            ...

    else: ...
    def op_COMPARE_OP(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_IS_OP(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_CONTAINS_OP(self, inst, lhs, rhs, res):  # -> None:
        ...
    def op_BREAK_LOOP(self, inst, end=...):  # -> None:
        ...
    def op_JUMP_IF_FALSE(self, inst, pred):  # -> None:
        ...
    def op_JUMP_IF_TRUE(self, inst, pred):  # -> None:
        ...
    def op_POP_JUMP_FORWARD_IF_NONE(self, inst, pred):  # -> None:
        ...
    def op_POP_JUMP_FORWARD_IF_NOT_NONE(self, inst, pred):  # -> None:
        ...

    if PYVERSION in ((3, 12), (3, 13), (3, 14)):
        def op_POP_JUMP_IF_NONE(self, inst, pred):  # -> None:
            ...
        def op_POP_JUMP_IF_NOT_NONE(self, inst, pred):  # -> None:
            ...

    else: ...
    def op_POP_JUMP_BACKWARD_IF_NONE(self, inst, pred):  # -> None:
        ...
    def op_POP_JUMP_BACKWARD_IF_NOT_NONE(self, inst, pred):  # -> None:
        ...
    def op_POP_JUMP_FORWARD_IF_FALSE(self, inst, pred):  # -> None:
        ...
    def op_POP_JUMP_FORWARD_IF_TRUE(self, inst, pred):  # -> None:
        ...
    def op_POP_JUMP_BACKWARD_IF_FALSE(self, inst, pred):  # -> None:
        ...
    def op_POP_JUMP_BACKWARD_IF_TRUE(self, inst, pred):  # -> None:
        ...
    def op_POP_JUMP_IF_FALSE(self, inst, pred):  # -> None:
        ...
    def op_POP_JUMP_IF_TRUE(self, inst, pred):  # -> None:
        ...
    def op_JUMP_IF_FALSE_OR_POP(self, inst, pred):  # -> None:
        ...
    def op_JUMP_IF_TRUE_OR_POP(self, inst, pred):  # -> None:
        ...
    def op_CHECK_EXC_MATCH(self, inst, pred, tos, tos1):  # -> None:
        ...
    def op_JUMP_IF_NOT_EXC_MATCH(self, inst, pred, tos, tos1):  # -> None:
        ...
    def op_RERAISE(self, inst, exc):  # -> None:
        ...
    def op_RAISE_VARARGS(self, inst, exc):  # -> None:
        ...
    def op_YIELD_VALUE(self, inst, value, res): ...
    def op_MAKE_FUNCTION(self, inst, name, code, closure, annotations, annotate, kwdefaults, defaults, res):  # -> None:
        ...
    def op_MAKE_CLOSURE(self, inst, name, code, closure, annotations, kwdefaults, defaults, res):  # -> None:
        ...

    if PYVERSION in ((3, 11), (3, 12), (3, 13), (3, 14)):
        def op_LOAD_CLOSURE(self, inst, res):  # -> None:
            ...

    else:
        def op_LOAD_CLOSURE(self, inst, res):  # -> None:
            ...

    def op_LIST_APPEND(self, inst, target, value, appendvar, res):  # -> None:
        ...
    def op_LIST_EXTEND(self, inst, target, value, extendvar, res):  # -> None:
        ...
    def op_MAP_ADD(self, inst, target, key, value, setitemvar, res):  # -> None:
        ...

    if PYVERSION == (3, 14): ...
    else:
        def op_LOAD_ASSERTION_ERROR(self, inst, res):  # -> None:
            ...

    def op_LOAD_METHOD(self, *args, **kws):  # -> None:
        ...
    def op_CALL_METHOD(self, *args, **kws):  # -> None:
        ...

    if PYVERSION in ((3, 12), (3, 13), (3, 14)):
        def op_CALL_INTRINSIC_1(self, inst, operand, **kwargs):  # -> None:
            ...

    else: ...
    if PYVERSION == (3, 14):
        def op_LOAD_SPECIAL(self, inst, contextmanager, exit_method, block_end):  # -> None:
            ...

    else: ...
    if PYVERSION == (3, 14):
        def op_LOAD_COMMON_CONSTANT(self, inst, res, idx):  # -> None:
            ...

    else: ...

if PYVERSION in ((3, 12), (3, 13), (3, 14)):
    class INTRINSIC_STOPITERATION_ERROR(AssertionError): ...

else: ...
