from functools import total_ordering

_termcolor = ...

class Loc:
    _defmatcher = ...
    def __init__(self, filename, line, col=..., maybe_decorator=...) -> None: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    @classmethod
    def from_function_id(cls, func_id):  # -> Self:
        ...
    def get_lines(self):  # -> list[str]:
        ...
    def strformat(self, nlines_up=...):  # -> str:
        ...
    def with_lineno(self, line, col=...):  # -> Self:

        ...
    def short(self):  # -> LiteralString:

        ...

unknown_loc = ...

@total_ordering
class SlotEqualityCheckMixin:
    __slots__ = ...
    def __eq__(self, other) -> bool: ...
    def __le__(self, other) -> bool: ...
    def __hash__(self) -> int: ...

@total_ordering
class EqualityCheckMixin:
    def __eq__(self, other) -> bool: ...
    def __le__(self, other) -> bool: ...
    def __hash__(self) -> int: ...

class VarMap:
    def __init__(self) -> None: ...
    def define(self, name, var):  # -> None:
        ...
    def get(self, name): ...
    def __contains__(self, name) -> bool:  # -> bool:
        ...
    def __len__(self) -> int:  # -> int:
        ...
    def __hash__(self) -> int: ...
    def __iter__(self): ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...

class AbstractRHS: ...

class Inst(EqualityCheckMixin, AbstractRHS):
    def list_vars(self): ...

class Stmt(Inst):
    is_terminator = ...
    is_exit = ...
    def list_vars(self):  # -> list[Var] | list[Any]:
        ...

class Terminator(Stmt):
    is_terminator = ...
    def get_targets(self): ...

class Expr(Inst):
    def __init__(self, op, loc, **kws) -> None: ...
    def __getattr__(self, name): ...
    def __setattr__(self, name, value) -> None:  # -> None:
        ...
    @classmethod
    def binop(cls, fn, lhs, rhs, loc):  # -> Self:
        ...
    @classmethod
    def inplace_binop(cls, fn, immutable_fn, lhs, rhs, loc):  # -> Self:
        ...
    @classmethod
    def unary(cls, fn, value, loc):  # -> Self:
        ...
    @classmethod
    def call(cls, func, args, kws, loc, vararg=..., varkwarg=..., target=...):  # -> Self:
        ...
    @classmethod
    def build_tuple(cls, items, loc):  # -> Self:
        ...
    @classmethod
    def build_list(cls, items, loc):  # -> Self:
        ...
    @classmethod
    def build_set(cls, items, loc):  # -> Self:
        ...
    @classmethod
    def build_map(cls, items, size, literal_value, value_indexes, loc):  # -> Self:
        ...
    @classmethod
    def pair_first(cls, value, loc):  # -> Self:
        ...
    @classmethod
    def pair_second(cls, value, loc):  # -> Self:
        ...
    @classmethod
    def getiter(cls, value, loc):  # -> Self:
        ...
    @classmethod
    def iternext(cls, value, loc):  # -> Self:
        ...
    @classmethod
    def exhaust_iter(cls, value, count, loc):  # -> Self:
        ...
    @classmethod
    def getattr(cls, value, attr, loc):  # -> Self:
        ...
    @classmethod
    def getitem(cls, value, index, loc):  # -> Self:
        ...
    @classmethod
    def typed_getitem(cls, value, dtype, index, loc):  # -> Self:
        ...
    @classmethod
    def static_getitem(cls, value, index, index_var, loc):  # -> Self:
        ...
    @classmethod
    def cast(cls, value, loc):  # -> Self:

        ...
    @classmethod
    def phi(cls, loc):  # -> Self:

        ...
    @classmethod
    def make_function(cls, name, code, closure, defaults, loc):  # -> Self:

        ...
    @classmethod
    def null(cls, loc):  # -> Self:

        ...
    @classmethod
    def undef(cls, loc):  # -> Self:

        ...
    @classmethod
    def dummy(cls, op, info, loc):  # -> Self:

        ...
    def list_vars(self):  # -> list[Var] | list[Any]:
        ...
    def infer_constant(self): ...

class SetItem(Stmt):
    def __init__(self, target, index, value, loc) -> None: ...

class StaticSetItem(Stmt):
    def __init__(self, target, index, index_var, value, loc) -> None: ...

class DelItem(Stmt):
    def __init__(self, target, index, loc) -> None: ...

class SetAttr(Stmt):
    def __init__(self, target, attr, value, loc) -> None: ...

class DelAttr(Stmt):
    def __init__(self, target, attr, loc) -> None: ...

class StoreMap(Stmt):
    def __init__(self, dct, key, value, loc) -> None: ...

class Del(Stmt):
    def __init__(self, value, loc) -> None: ...

class Raise(Terminator):
    is_exit = ...
    def __init__(self, exception, loc) -> None: ...
    def get_targets(self):  # -> list[Any]:
        ...

class StaticRaise(Terminator):
    is_exit = ...
    def __init__(self, exc_class, exc_args, loc) -> None: ...
    def get_targets(self):  # -> list[Any]:
        ...

class DynamicRaise(Terminator):
    is_exit = ...
    def __init__(self, exc_class, exc_args, loc) -> None: ...
    def get_targets(self):  # -> list[Any]:
        ...

class TryRaise(Stmt):
    def __init__(self, exception, loc) -> None: ...

class StaticTryRaise(Stmt):
    def __init__(self, exc_class, exc_args, loc) -> None: ...

class DynamicTryRaise(Stmt):
    def __init__(self, exc_class, exc_args, loc) -> None: ...

class Return(Terminator):
    is_exit = ...
    def __init__(self, value, loc) -> None: ...
    def get_targets(self):  # -> list[Any]:
        ...

class Jump(Terminator):
    def __init__(self, target, loc) -> None: ...
    def get_targets(self):  # -> list[Any]:
        ...

class Branch(Terminator):
    def __init__(self, cond, truebr, falsebr, loc) -> None: ...
    def get_targets(self):  # -> list[Any]:
        ...

class Assign(Stmt):
    def __init__(self, value, target, loc) -> None: ...

class Print(Stmt):
    def __init__(self, args, vararg, loc) -> None: ...

class Yield(Inst):
    def __init__(self, value, loc, index) -> None: ...
    def list_vars(self):  # -> list[Var]:
        ...

class EnterWith(Stmt):
    def __init__(self, contextmanager, begin, end, loc) -> None: ...
    def list_vars(self):  # -> list[Var]:
        ...

class PopBlock(Stmt):
    def __init__(self, loc) -> None: ...

class Arg(EqualityCheckMixin, AbstractRHS):
    def __init__(self, name, index, loc) -> None: ...
    def infer_constant(self): ...

class Const(EqualityCheckMixin, AbstractRHS):
    def __init__(self, value, loc, use_literal_type=...) -> None: ...
    def infer_constant(self):  # -> Any:
        ...
    def __deepcopy__(self, memo):  # -> Const:
        ...

class Global(EqualityCheckMixin, AbstractRHS):
    def __init__(self, name, value, loc) -> None: ...
    def infer_constant(self):  # -> Any:
        ...
    def __deepcopy__(self, memo):  # -> Global:
        ...

class FreeVar(EqualityCheckMixin, AbstractRHS):
    def __init__(self, index, name, value, loc) -> None: ...
    def infer_constant(self):  # -> Any:
        ...
    def __deepcopy__(self, memo):  # -> FreeVar:
        ...

class Var(EqualityCheckMixin, AbstractRHS):
    def __init__(self, scope, name, loc) -> None: ...
    @property
    def is_temp(self):  # -> bool:
        ...
    @property
    def unversioned_name(self):  # -> str:

        ...
    @property
    def versioned_names(self):  # -> set[Any]:

        ...
    @property
    def all_names(self):  # -> set[Any | str]:

        ...
    def __deepcopy__(self, memo):  # -> Var:
        ...

class Scope(EqualityCheckMixin):
    def __init__(self, parent, loc) -> None: ...
    def define(self, name, loc):  # -> Var:

        ...
    def get(self, name): ...
    def get_exact(self, name): ...
    def get_or_define(self, name, loc):  # -> Var:
        ...
    def redefine(self, name, loc, rename=...):  # -> Var:

        ...
    def get_versions_of(self, name):  # -> set[Any]:

        ...
    def make_temp(self, loc):  # -> Var:
        ...
    @property
    def has_parent(self):  # -> bool:
        ...

class Block(EqualityCheckMixin):
    def __init__(self, scope, loc) -> None: ...
    def copy(self):  # -> Block:
        ...
    def find_exprs(self, op=...):  # -> Generator[Expr, Any, None]:

        ...
    def find_insts(self, cls=...):  # -> Generator[Any, Any, None]:

        ...
    def find_variable_assignment(self, name):  # -> None:

        ...
    def prepend(self, inst):  # -> None:
        ...
    def append(self, inst):  # -> None:
        ...
    def remove(self, inst):  # -> None:
        ...
    def clear(self):  # -> None:
        ...
    def dump(self, file=...):  # -> None:
        ...
    @property
    def terminator(self): ...
    @property
    def is_terminated(self):  # -> list[Any]:
        ...
    def verify(self):  # -> None:
        ...
    def insert_after(self, stmt, other):  # -> None:

        ...
    def insert_before_terminator(self, stmt):  # -> None:
        ...

class Loop(SlotEqualityCheckMixin):
    __slots__ = ...
    def __init__(self, entry, exit) -> None: ...

class With(SlotEqualityCheckMixin):
    __slots__ = ...
    def __init__(self, entry, exit) -> None: ...

class FunctionIR:
    def __init__(self, blocks, is_generator, func_id, loc, definitions, arg_count, arg_names) -> None: ...
    def equal_ir(self, other):  # -> Literal[False]:

        ...
    def diff_str(self, other):  # -> LiteralString:

        ...
    def derive(self, blocks, arg_count=..., arg_names=..., force_non_generator=..., loc=...):  # -> Self:

        ...
    def copy(self):  # -> Self:
        ...
    def get_block_entry_vars(self, block): ...
    def infer_constant(self, name): ...
    def get_definition(self, value, lhs_only=...):  # -> Var | str:

        ...
    def get_assignee(self, rhs_value, in_blocks=...): ...
    def dump(self, file=...):  # -> None:
        ...
    def dump_to_string(self):  # -> str:
        ...
    def dump_generator_info(self, file=...):  # -> None:
        ...
    def render_dot(self, filename_prefix=..., include_ir=...): ...

class UndefinedType(EqualityCheckMixin):
    _singleton = ...
    def __new__(cls):  # -> Self:
        ...

UNDEFINED = ...
