import numba

_unique_var_count = ...

def mk_unique_var(prefix): ...

class _MaxLabel:
    def __init__(self, value=...) -> None: ...
    def next(self):  # -> int:
        ...
    def update(self, newval):  # -> None:
        ...

_the_max_label = ...

def get_unused_var_name(prefix, var_table): ...
def next_label():  # -> int:
    ...
def mk_alloc(typingctx, typemap, calltypes, lhs, size_var, dtype, scope, loc, lhs_typ):  # -> list[Any]:

    ...
def convert_size_to_var(size_var, typemap, scope, loc, nodes):  # -> Var:
    ...
def get_np_ufunc_typ(func, typingctx): ...
def mk_range_block(typemap, start, stop, step, calltypes, scope, loc):  # -> Block:

    ...
def get_global_func_typ(func): ...
def mk_loop_header(typemap, phi_var, calltypes, scope, loc):  # -> Block:

    ...
def legalize_names(varnames):  # -> dict[Any, Any]:

    ...
def get_name_var_table(blocks):  # -> dict[Any, Any]:

    ...
def replace_var_names(blocks, namedict):  # -> None:

    ...
def replace_var_callback(var, vardict):  # -> Var:
    ...
def replace_vars(blocks, vardict):  # -> None:

    ...
def replace_vars_stmt(stmt, vardict):  # -> None:
    ...
def replace_vars_inner(
    node, vardict
):  # -> Var | list[Var | list[Any] | tuple[Var | list[Any] | tuple[Any, ...] | Expr | Yield | Any, ...] | Expr | Yield | Any] | tuple[Var | list[Any] | tuple[Any, ...] | Expr | Yield | Any, ...] | Expr | Yield:
    ...

visit_vars_extensions = ...

def visit_vars(blocks, callback, cbdata):  # -> None:

    ...
def visit_vars_stmt(stmt, callback, cbdata):  # -> None:
    ...
def visit_vars_inner(
    node, callback, cbdata
):  # -> list[Any | list[Any | list[Any] | tuple[Any | list[Any] | tuple[Any, ...] | Expr | Yield, ...] | Expr | Yield] | tuple[Any | list[Any] | tuple[Any, ...] | Expr | Yield, ...] | Expr | Yield] | tuple[Any | list[Any] | tuple[Any, ...] | Expr | Yield, ...] | Expr | Yield:
    ...

add_offset_to_labels_extensions = ...

def add_offset_to_labels(blocks, offset):  # -> dict[Any, Any]:

    ...

find_max_label_extensions = ...

def find_max_label(blocks):  # -> Literal[0]:
    ...
def flatten_labels(blocks):  # -> dict[Any, Any]:

    ...
def remove_dels(blocks):  # -> None:

    ...
def remove_args(blocks):  # -> None:

    ...
def dead_code_elimination(func_ir, typemap=..., alias_map=..., arg_aliases=...):  # -> None:

    ...
def remove_dead(blocks, args, func_ir, typemap=..., alias_map=..., arg_aliases=...):  # -> bool:

    ...

remove_dead_extensions = ...

def remove_dead_block(block, lives, call_table, arg_aliases, alias_map, alias_set, func_ir, typemap):  # -> bool:

    ...

remove_call_handlers = ...

def remove_dead_random_call(rhs, lives, call_list):  # -> bool:
    ...
def has_no_side_effect(rhs, lives, call_table): ...

is_pure_extensions = ...

def is_pure(rhs, lives, call_table):  # -> bool:

    ...
def is_const_call(module_name, func_name):  # -> bool:
    ...

alias_analysis_extensions = ...
alias_func_extensions = ...

def get_canonical_alias(v, alias_map): ...
def find_potential_aliases(blocks, args, typemap, func_ir, alias_map=..., arg_aliases=...): ...
def is_immutable_type(var, typemap):  # -> bool:
    ...
def copy_propagate(blocks, typemap):  # -> tuple[dict[Any, set[Any] | Any], dict[Any, Any]]:

    ...
def init_copy_propagate_data(
    blocks, entry, typemap
):  # -> tuple[dict[Any, Any], set[Any] | Any, dict[Any, Any], dict[Any, set[Any] | Any], dict[Any, Any]]:

    ...

copy_propagate_extensions = ...

def get_block_copies(blocks, typemap):  # -> tuple[dict[Any, Any], dict[Any, Any]]:

    ...

apply_copy_propagate_extensions = ...

def apply_copy_propagate(blocks, in_copies, name_var_table, typemap, calltypes, save_copies=...):  # -> list[Any]:

    ...
def fix_setitem_type(stmt, typemap, calltypes):  # -> None:

    ...
def dprint_func_ir(func_ir, title, blocks=...):  # -> None:

    ...
def find_topo_order(blocks, cfg=...):  # -> list[Any]:

    ...

call_table_extensions = ...

def get_call_table(
    blocks, call_table=..., reverse_call_table=..., topological_ordering=...
):  # -> tuple[Any | dict[Any, Any], Any | dict[Any, Any]]:

    ...

tuple_table_extensions = ...

def get_tuple_table(blocks, tuple_table=...):  # -> dict[Any, Any]:

    ...
def get_stmt_writes(stmt):  # -> set[Any]:
    ...
def rename_labels(blocks):  # -> dict[Any, Any]:

    ...
def simplify_CFG(blocks):  # -> dict[Any, Any]:

    ...

arr_math = ...

def canonicalize_array_math(func_ir, typemap, calltypes, typingctx):  # -> None:
    ...

array_accesses_extensions = ...

def get_array_accesses(blocks, accesses=...):  # -> set[Any]:

    ...
def is_slice_index(index):  # -> bool:

    ...
def merge_adjacent_blocks(blocks):  # -> None:
    ...
def restore_copy_var_names(blocks, save_copies, typemap):  # -> dict[Any, Any]:

    ...
def simplify(func_ir, typemap, calltypes, metadata):  # -> None:
    ...

class GuardException(Exception): ...

def require(cond):  # -> None:

    ...
def guard(func, *args, **kwargs):  # -> None:

    ...
def get_definition(func_ir, name, **kwargs): ...
def build_definitions(blocks, definitions=...):  # -> defaultdict[Any, list[Any]]:

    ...

build_defs_extensions = ...

def find_callname(
    func_ir, expr, typemap=..., definition_finder=...
):  # -> tuple[Any, Any] | tuple[LiteralString, Any] | tuple[Any, LiteralString]:

    ...
def find_build_sequence(func_ir, var):  # -> tuple[Any, Any]:

    ...
def find_const(func_ir, var): ...
def compile_to_numba_ir(mk_func, glbls, typingctx=..., targetctx=..., arg_typs=..., typemap=..., calltypes=...):  # -> FunctionIR:

    ...
def get_ir_of_code(glbls, fcode) -> None:  # -> FunctionIR:

    ...
def replace_arg_nodes(block, args):  # -> None:

    ...
def replace_returns(blocks, target, return_label):  # -> None:

    ...
def gen_np_call(func_as_str, func, lhs, args, typingctx, typemap, calltypes):  # -> list[Assign]:
    ...
def dump_block(label, block):  # -> None:
    ...
def dump_blocks(blocks):  # -> None:
    ...
def is_operator_or_getitem(expr):  # -> Any | bool:

    ...
def is_get_setitem(stmt):  # -> bool:

    ...
def is_getitem(stmt):  # -> bool:

    ...
def is_setitem(stmt):  # -> bool:

    ...
def index_var_of_get_setitem(stmt):  # -> Var | None:

    ...
def set_index_var_of_get_setitem(stmt, new_index):  # -> None:
    ...
def is_namedtuple_class(c):  # -> bool:

    ...
def fill_block_with_call(newblock, callee, label_next, inputs, outputs): ...
def fill_callee_prologue(block, inputs, label_next): ...
def fill_callee_epilogue(block, outputs): ...
def find_outer_value(func_ir, var):  # -> Any:

    ...
def raise_on_unsupported_feature(func_ir, typemap):  # -> None:

    ...
def warn_deprecated(func_ir, typemap):  # -> None:
    ...
def resolve_func_from_module(func_ir, node):  # -> Any | Literal[True] | None:

    ...
def enforce_no_dels(func_ir):  # -> None:

    ...
def enforce_no_phis(func_ir):  # -> None:

    ...
def legalize_single_scope(blocks):  # -> bool:

    ...
def check_and_legalize_ir(func_ir, flags: numba.core.compiler.Flags):  # -> None:

    ...
def convert_code_obj_to_function(code_obj, caller_ir): ...
def fixup_var_define_in_scope(blocks):  # -> None:

    ...
def transfer_scope(block, scope): ...
def is_setup_with(stmt):  # -> bool:
    ...
def is_terminator(stmt):  # -> bool:
    ...
def is_raise(stmt):  # -> bool:
    ...
def is_return(stmt):  # -> bool:
    ...
def is_pop_block(stmt):  # -> bool:
    ...
