_re_invalid_char = ...
PREFIX = ...
N2CODE = ...

def mangle_abi_tag(abi_tag: str) -> str: ...
def mangle_identifier(ident, template_params=..., *, abi_tags=..., uid=...):  # -> str:

    ...
def mangle_type_or_value(typ):  # -> str:

    ...

mangle_type = ...
mangle_value = ...

def mangle_templated_ident(identifier, parameters):  # -> str:

    ...
def mangle_args(argtys):  # -> str:

    ...
def mangle(ident, argtys, *, abi_tags=..., uid=...):  # -> str:

    ...
def prepend_namespace(mangled, ns): ...
