from numba.core import generators, ir

_VarArgItem = ...

class BaseLower:
    def __init__(self, context, library, fndesc, func_ir, metadata=...) -> None: ...
    @property
    def call_conv(self): ...
    def init(self):  # -> None:
        ...
    def init_pyapi(self):  # -> None:

        ...
    def pre_lower(self):  # -> None:

        ...
    def post_lower(self):  # -> None:

        ...
    def pre_block(self, block):  # -> None:

        ...
    def post_block(self, block):  # -> None:

        ...
    def return_dynamic_exception(self, exc_class, exc_args, nb_types, loc=...):  # -> None:
        ...
    def return_exception(self, exc_class, exc_args=..., loc=...):  # -> None:

        ...
    def set_exception(self, exc_class, exc_args=..., loc=...):  # -> None:

        ...
    def emit_environment_object(self):  # -> None:

        ...
    def lower(self):  # -> None:
        ...
    def extract_function_arguments(self): ...
    def lower_normal_function(self, fndesc):  # -> None:

        ...
    def lower_function_body(self):  # -> None:

        ...
    def lower_block(self, block):  # -> None:

        ...
    def create_cpython_wrapper(self, release_gil=...):  # -> None:

        ...
    def create_cfunc_wrapper(self):  # -> None:

        ...
    def setup_function(self, fndesc):  # -> None:
        ...
    def typeof(self, varname): ...
    def notify_loc(self, loc: ir.Loc) -> None: ...
    def debug_print(self, msg):  # -> None:
        ...
    def print_variable(self, msg, varname):  # -> None:

        ...

class Lower(BaseLower):
    GeneratorLower = generators.GeneratorLower
    def init(self):  # -> None:
        ...
    def pre_block(self, block):  # -> None:
        ...
    def post_block(self, block):  # -> None:
        ...
    def lower_inst(self, inst):  # -> None:
        ...
    def lower_setitem(self, target_var, index_var, value_var, signature): ...
    def lower_try_dynamic_raise(self, inst):  # -> None:
        ...
    def lower_dynamic_raise(self, inst):  # -> None:
        ...
    def lower_static_raise(self, inst):  # -> None:
        ...
    def lower_static_try_raise(self, inst):  # -> None:
        ...
    def lower_assign(self, ty, inst): ...
    def lower_yield(self, retty, inst): ...
    def lower_binop(self, resty, expr, op): ...
    def lower_getitem(self, resty, expr, value, index, signature): ...
    def fold_call_args(self, fnty, signature, pos_args, vararg, kw_args):  # -> list[Any] | tuple[Any, ...]:
        ...
    def lower_print(self, inst):  # -> None:

        ...
    def lower_call(self, resty, expr): ...
    def lower_expr(self, resty, expr): ...
    def getvar(self, name): ...
    def loadvar(self, name):  # -> LoadInstr:

        ...
    def storevar(self, value, name, argidx=...):  # -> None:

        ...
    def delvar(self, name):  # -> None:

        ...
    def alloca(self, name, type):  # -> AllocaInstr:
        ...
    def alloca_lltype(self, name, lltype, datamodel=...):  # -> AllocaInstr:
        ...
    def incref(self, typ, val):  # -> None:
        ...
    def decref(self, typ, val):  # -> None:
        ...
