from numba.core import types
from numba.core.imputils import lower_cast, lower_getattr_generic, lower_setattr_generic

def always_return_true_impl(context, builder, sig, args):  # -> Constant:
    ...
def always_return_false_impl(context, builder, sig, args):  # -> Constant:
    ...
def optional_is_none(context, builder, sig, args): ...
@lower_getattr_generic(types.Optional)
def optional_getattr(context, builder, typ, value, attr): ...
@lower_setattr_generic(types.Optional)
def optional_setattr(context, builder, sig, args, attr): ...
@lower_cast(types.Optional, types.Optional)
def optional_to_optional(context, builder, fromty, toty, val): ...
@lower_cast(types.Any, types.Optional)
def any_to_optional(context, builder, fromty, toty, val): ...
@lower_cast(types.Optional, types.Any)
@lower_cast(types.Optional, types.Boolean)
def optional_to_any(context, builder, fromty, toty, val): ...
