from numba.core import generators
from numba.core.lowering import BaseLower

"""
Lowering implementation for object mode.
"""
_unsupported_builtins = ...

class _Undefined: ...

_UNDEFINED = ...
PYTHON_BINOPMAP = ...
PYTHON_COMPAREOPMAP = ...

class PyLower(BaseLower):
    GeneratorLower = generators.PyGeneratorLower
    def init(self):  # -> None:
        ...
    def pre_lower(self):  # -> None:
        ...
    def post_lower(self):  # -> None:
        ...
    def pre_block(self, block):  # -> None:
        ...
    def lower_inst(self, inst):  # -> None:
        ...
    def lower_assign(self, inst):  # -> LoadInstr | PhiInstr:

        ...
    def lower_yield(self, inst): ...
    def lower_binop(self, expr, op, inplace=...):  # -> Any:
        ...
    def lower_expr(self, expr): ...
    def lower_const(self, const): ...
    def lower_global(self, name, value):  # -> PhiInstr:

        ...
    def get_module_dict(self): ...
    def get_builtin_obj(self, name):  # -> PhiInstr:
        ...
    def builtin_lookup(self, mod, name):  # -> PhiInstr:

        ...
    def check_occurred(self):  # -> None:

        ...
    def check_error(self, obj): ...
    def check_int_status(self, num, ok_value=...):  # -> None:

        ...
    def is_null(self, obj):  # -> ICMPInstr:
        ...
    def return_exception_raised(self):  # -> None:

        ...
    def init_vars(self, block):  # -> None:

        ...
    def loadvar(self, name):  # -> LoadInstr:

        ...
    def delvar(self, name):  # -> None:

        ...
    def storevar(self, value, name, clobber=...):  # -> None:

        ...
    def cleanup_vars(self):  # -> None:

        ...
    def alloca(self, name, ltype=...):  # -> AllocaInstr:

        ...
    def incref(self, value):  # -> None:
        ...
    def decref(self, value):  # -> None:

        ...
