import contextlib
from collections import namedtuple

from numba.core.utils import PYVERSION

PY_UNICODE_1BYTE_KIND = ...
PY_UNICODE_2BYTE_KIND = ...
PY_UNICODE_4BYTE_KIND = ...
if PYVERSION in ((3, 10), (3, 11)):
    PY_UNICODE_WCHAR_KIND = ...

class _Registry:
    def __init__(self) -> None: ...
    def register(self, typeclass):  # -> Callable[..., Any]:
        ...
    def lookup(self, typeclass, default=...):  # -> None:
        ...

_boxers = ...
_unboxers = ...
_reflectors = ...
box = ...
unbox = ...
reflect = ...

class _BoxContext(namedtuple("_BoxContext", ("context", "builder", "pyapi", "env_manager"))):
    __slots__ = ...
    def box(self, typ, val): ...

class _UnboxContext(namedtuple("_UnboxContext", ("context", "builder", "pyapi"))):
    __slots__ = ...
    def unbox(self, typ, obj): ...

class _ReflectContext(namedtuple("_ReflectContext", ("context", "builder", "pyapi", "env_manager", "is_error"))):
    __slots__ = ...
    def set_error(self):  # -> None:
        ...
    def box(self, typ, val): ...
    def reflect(self, typ, val): ...

class NativeValue:
    def __init__(self, value, is_error=..., cleanup=...) -> None: ...

class EnvironmentManager:
    def __init__(self, pyapi, env, env_body, env_ptr) -> None: ...
    def add_const(self, const):  # -> int:

        ...
    def read_const(self, index): ...

_IteratorLoop = ...

class PythonAPI:
    def __init__(self, context, builder) -> None: ...
    def get_env_manager(self, env, env_body, env_ptr):  # -> EnvironmentManager:
        ...
    def emit_environment_sentry(self, envptr, return_pyobject=..., debug_msg=...):  # -> None:

        ...
    def incref(self, obj):  # -> None:
        ...
    def decref(self, obj):  # -> None:
        ...
    def get_type(self, obj): ...
    def parse_tuple_and_keywords(self, args, kws, fmt, keywords, *objs): ...
    def parse_tuple(self, args, fmt, *objs): ...
    def unpack_tuple(self, args, name, n_min, n_max, *objs): ...
    def err_occurred(self): ...
    def err_clear(self): ...
    def err_set_string(self, exctype, msg): ...
    def err_format(self, exctype, msg, *format_args): ...
    def raise_object(self, exc=...): ...
    def err_set_object(self, exctype, excval): ...
    def err_set_none(self, exctype): ...
    def err_write_unraisable(self, obj): ...
    def err_fetch(self, pty, pval, ptb): ...
    def err_restore(self, ty, val, tb): ...
    @contextlib.contextmanager
    def err_push(self, keep_new=...):  # -> Generator[None, Any, None]:

        ...
    def get_c_object(self, name): ...
    def raise_missing_global_error(self, name):  # -> None:
        ...
    def raise_missing_name_error(self, name):  # -> None:
        ...
    def fatal_error(self, msg):  # -> None:
        ...
    def dict_getitem_string(self, dic, name): ...
    def dict_getitem(self, dic, name): ...
    def dict_new(self, presize=...): ...
    def dict_setitem(self, dictobj, nameobj, valobj): ...
    def dict_setitem_string(self, dictobj, name, valobj): ...
    def dict_pack(self, keyvalues): ...
    def float_from_double(self, fval): ...
    def number_as_ssize_t(self, numobj): ...
    def number_long(self, numobj): ...
    def long_as_ulonglong(self, numobj): ...
    def long_as_longlong(self, numobj): ...
    def long_as_voidptr(self, numobj): ...
    def long_from_long(self, ival): ...
    def long_from_ulong(self, ival): ...
    def long_from_ssize_t(self, ival): ...
    def long_from_longlong(self, ival): ...
    def long_from_ulonglong(self, ival): ...
    def long_from_signed_int(self, ival): ...
    def long_from_unsigned_int(self, ival): ...
    def number_add(self, lhs, rhs, inplace=...): ...
    def number_subtract(self, lhs, rhs, inplace=...): ...
    def number_multiply(self, lhs, rhs, inplace=...): ...
    def number_truedivide(self, lhs, rhs, inplace=...): ...
    def number_floordivide(self, lhs, rhs, inplace=...): ...
    def number_remainder(self, lhs, rhs, inplace=...): ...
    def number_matrix_multiply(self, lhs, rhs, inplace=...): ...
    def number_lshift(self, lhs, rhs, inplace=...): ...
    def number_rshift(self, lhs, rhs, inplace=...): ...
    def number_and(self, lhs, rhs, inplace=...): ...
    def number_or(self, lhs, rhs, inplace=...): ...
    def number_xor(self, lhs, rhs, inplace=...): ...
    def number_power(self, lhs, rhs, inplace=...): ...
    def number_negative(self, obj): ...
    def number_positive(self, obj): ...
    def number_float(self, val): ...
    def number_invert(self, obj): ...
    def float_as_double(self, fobj): ...
    def bool_from_bool(self, bval): ...
    def bool_from_long(self, ival): ...
    def complex_from_doubles(self, realval, imagval): ...
    def complex_real_as_double(self, cobj): ...
    def complex_imag_as_double(self, cobj): ...
    def slice_as_ints(self, obj):  # -> tuple[Any, Any, Any, Any]:

        ...
    def sequence_getslice(self, obj, start, stop): ...
    def sequence_tuple(self, obj): ...
    def sequence_concat(self, obj1, obj2): ...
    def list_new(self, szval): ...
    def list_size(self, lst): ...
    def list_append(self, lst, val): ...
    def list_setitem(self, lst, idx, val): ...
    def list_getitem(self, lst, idx): ...
    def list_setslice(self, lst, start, stop, obj): ...
    def tuple_getitem(self, tup, idx): ...
    def tuple_pack(self, items): ...
    def tuple_size(self, tup): ...
    def tuple_new(self, count): ...
    def tuple_setitem(self, tuple_val, index, item):  # -> None:

        ...
    def set_new(self, iterable=...): ...
    def set_add(self, set, value): ...
    def set_clear(self, set): ...
    def set_size(self, set): ...
    def set_update(self, set, iterable): ...
    def set_next_entry(self, set, posptr, keyptr, hashptr): ...
    @contextlib.contextmanager
    def set_iterate(self, set):  # -> Generator[_IteratorLoop, Any, None]:
        ...
    def gil_ensure(self): ...
    def gil_release(self, gil): ...
    def save_thread(self): ...
    def restore_thread(self, thread_state):  # -> None:

        ...
    def object_get_private_data(self, obj): ...
    def object_set_private_data(self, obj, ptr): ...
    def object_reset_private_data(self, obj): ...
    def import_module(self, modname): ...
    def call_function_objargs(self, callee, objargs): ...
    def call_method(self, callee, method, objargs=...): ...
    def call(self, callee, args=..., kws=...): ...
    def object_type(self, obj): ...
    def object_istrue(self, obj): ...
    def object_not(self, obj): ...
    def object_richcompare(self, lhs, rhs, opstr): ...
    def iter_next(self, iterobj): ...
    def object_getiter(self, obj): ...
    def object_getattr_string(self, obj, attr): ...
    def object_getattr(self, obj, attr): ...
    def object_setattr_string(self, obj, attr, val): ...
    def object_setattr(self, obj, attr, val): ...
    def object_delattr_string(self, obj, attr): ...
    def object_delattr(self, obj, attr): ...
    def object_getitem(self, obj, key): ...
    def object_setitem(self, obj, key, val): ...
    def object_delitem(self, obj, key): ...
    def string_as_string(self, strobj): ...
    def string_as_string_and_size(self, strobj):  # -> tuple[Any, Any, Any]:

        ...
    def string_as_string_size_and_kind(self, strobj):  # -> tuple[Any, Any, Any, Any, Any, Any]:

        ...
    def string_from_string_and_size(self, string, size): ...
    def string_from_string(self, string): ...
    def string_from_kind_and_data(self, kind, string, size): ...
    def bytes_as_string(self, obj): ...
    def bytes_as_string_and_size(self, obj, p_buffer, p_length): ...
    def bytes_from_string_and_size(self, string, size): ...
    def object_hash(self, obj): ...
    def object_str(self, obj): ...
    def make_none(self): ...
    def borrow_none(self): ...
    def sys_write_stdout(self, fmt, *args): ...
    def object_dump(self, obj): ...
    def nrt_adapt_ndarray_to_python(self, aryty, ary, dtypeptr): ...
    def nrt_meminfo_new_from_pyobject(self, data, pyobj): ...
    def nrt_meminfo_as_pyobject(self, miptr): ...
    def nrt_meminfo_from_pyobject(self, miobj): ...
    def nrt_adapt_ndarray_from_python(self, ary, ptr): ...
    def nrt_adapt_buffer_from_python(self, buf, ptr): ...
    def alloca_obj(self): ...
    def alloca_buffer(self): ...
    @contextlib.contextmanager
    def if_object_ok(self, obj):  # -> Generator[None, Any, None]:
        ...
    def print_object(self, obj):  # -> None:
        ...
    def print_string(self, text):  # -> None:
        ...
    def get_null_object(self):  # -> Constant:
        ...
    def return_none(self):  # -> None:
        ...
    def list_pack(self, items): ...
    def unserialize(self, structptr): ...
    def build_dynamic_excinfo_struct(self, struct_gv, exc_args): ...
    def serialize_uncached(self, obj):  # -> Constant:

        ...
    def serialize_object(self, obj): ...
    def c_api_error(self): ...
    def to_native_value(self, typ, obj): ...
    def from_native_return(self, typ, val, env_manager): ...
    def from_native_value(self, typ, val, env_manager=...): ...
    def reflect_native_value(self, typ, val, env_manager=...):  # -> Constant:

        ...
    def to_native_generator(self, obj, typ):  # -> NativeValue:

        ...
    def from_native_generator(self, val, typ, env=...): ...
    def numba_array_adaptor(self, ary, ptr): ...
    def numba_buffer_adaptor(self, buf, ptr): ...
    def complex_adaptor(self, cobj, cmplx): ...
    def extract_record_data(self, obj, pbuf): ...
    def get_buffer(self, obj, pbuf): ...
    def release_buffer(self, pbuf): ...
    def extract_np_datetime(self, obj): ...
    def extract_np_timedelta(self, obj): ...
    def create_np_datetime(self, val, unit_code): ...
    def create_np_timedelta(self, val, unit_code): ...
    def recreate_record(self, pdata, size, dtype, env_manager): ...
    def string_from_constant_string(self, string): ...
    def call_jit_code(self, func, sig, args):  # -> tuple[Any, Any]:

        ...

class ObjModeUtils:
    def __init__(self, pyapi) -> None: ...
    def load_dispatcher(self, fnty, argtypes): ...
