_logger = ...

def reconstruct_ssa(func_ir): ...

class _CacheListVars:
    def __init__(self) -> None: ...
    def get(self, inst): ...

class _BaseHandler:
    def on_assign(self, states, assign):  # -> None:

        ...
    def on_other(self, states, stmt):  # -> None:

        ...

class _GatherDefsHandler(_BaseHandler):
    def on_assign(self, states, assign):  # -> None:
        ...
    def on_other(self, states, stmt):  # -> None:
        ...

class UndefinedVariable:
    def __init__(self) -> None: ...

    target = ...

class _FreshVarHandler(_BaseHandler):
    def on_assign(self, states, assign):  # -> Assign:
        ...
    def on_other(self, states, stmt): ...

class _FixSSAVars(_BaseHandler):
    def __init__(self, cache_list_vars) -> None: ...
    def on_assign(self, states, assign):  # -> Assign:
        ...
    def on_other(self, states, stmt): ...
