from numba.core import utils

"""
This module contains utils for manipulating target configurations such as
compiler flags.
"""

class Option:
    __slots__ = ...
    def __init__(self, type, *, default, doc) -> None: ...
    @property
    def type(self):  # -> Any:
        ...
    @property
    def default(self):  # -> Any:
        ...
    @property
    def doc(self):  # -> Any:
        ...

class _FlagsStack(utils.ThreadLocalStack, stack_name="flags"): ...

class ConfigStack:
    @classmethod
    def top_or_none(cls):  # -> Any | None:

        ...
    def __init__(self) -> None: ...
    def top(self):  # -> Any:
        ...
    def __len__(self) -> int:  # -> int:
        ...
    def enter(self, flags):  # -> _GeneratorContextManager[None, None, None]:

        ...

class _MetaTargetConfig(type):
    def __init__(cls, name, bases, dct) -> None: ...
    def find_options(cls, dct):  # -> dict[Any, Option]:

        ...

class _NotSetType: ...

_NotSet = ...

class TargetConfig(metaclass=_MetaTargetConfig):
    __slots__ = ...
    _ZLIB_CONFIG = ...
    def __init__(self, copy_from=...) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other) -> bool: ...
    def values(self):  # -> dict[Any, Any]:

        ...
    def is_set(self, name):  # -> bool:

        ...
    def discard(self, name):  # -> None:

        ...
    def inherit_if_not_set(self, name, default=...):  # -> None:

        ...
    def copy(self):  # -> Self:

        ...
    def summary(self) -> str: ...
    def get_mangle_string(self) -> str: ...
    @classmethod
    def demangle(cls, mangled: str) -> str: ...
