from abc import ABC, abstractmethod

from numba.core.registry import DelayedRegistry

_active_context = ...
_active_context_default = ...

class _TargetRegistry(DelayedRegistry):
    def __getitem__(self, item): ...

target_registry = ...
jit_registry = ...

class target_override:
    def __init__(self, name) -> None: ...
    def __enter__(self):  # -> None:
        ...
    def __exit__(self, ty, val, tb):  # -> None:
        ...

def current_target():  # -> Any | str:

    ...
def get_local_target(context): ...
def resolve_target_str(target_str): ...
def resolve_dispatcher_from_str(target_str): ...

class JitDecorator(ABC):
    @abstractmethod
    def __call__(self):  # -> NotImplementedType:
        ...

class Target(ABC):
    @classmethod
    def inherits_from(cls, other):  # -> bool:

        ...

class Generic(Target): ...
class CPU(Generic): ...
class GPU(Generic): ...
class CUDA(GPU): ...
class NPyUfunc(Target): ...

dispatcher_registry = ...
cpu_target = ...
