import threading

from numba.core import config

class TLS(threading.local):
    def __init__(self) -> None: ...

tls = ...

def find_function_info(func, spec, args):  # -> tuple[LiteralString | Any | None, None]:

    ...
def chop(value):  # -> str:
    ...
def create_events(fname, spec, args, kwds):  # -> tuple[list[Any], list[Any]]:
    ...
def dotrace(
    *args, **kwds
):  # -> classmethod[Any, Callable[..., Any], Any] | staticmethod[Callable[..., Any], Any] | property | Callable[..., classmethod[Any, Callable[..., Any], Any] | staticmethod[Callable[..., Any], Any] | Any]:

    ...
def notrace(*args, **kwds):  # -> Callable[..., object] | Callable[..., Any] | None:

    ...
def doevent(msg):  # -> None:
    ...
def noevent(msg):  # -> None:
    ...

if config.TRACE:
    logger = ...
    trace = ...
    event = ...
else:
    trace = ...
    event = ...
