_logger = ...

def find_region_inout_vars(blocks, livemap, callfrom, returnto, body_block_ids):  # -> tuple[list[Any], list[Any]]:

    ...

_loop_lift_info = ...

def loop_lifting(func_ir, typingctx, targetctx, flags, locals):  # -> tuple[Any, list[Any]]:

    ...
def canonicalize_cfg_single_backedge(blocks): ...
def canonicalize_cfg(blocks): ...
def with_lifting(func_ir, typingctx, targetctx, flags, locals):  # -> tuple[Any, list[Any]]:

    ...
def find_setupwiths(func_ir):  # -> tuple[list[Any], Any]:

    ...
def consolidate_multi_exit_withs(withs: dict, blocks, func_ir): ...
