import abc
from contextlib import contextmanager

from numba.core.compiler_machinery import AnalysisPass, FunctionPass, LoweringPass, register_pass

_TypingResults = ...

@contextmanager
def fallback_context(state, msg):  # -> Generator[None, Any, None]:

    ...
def type_inference_stage(typingctx, targetctx, interp, args, return_type, locals=..., raise_errors=...):  # -> _TypingResults:
    ...

class BaseTypeInference(FunctionPass):
    _raise_errors = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:

        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class NopythonTypeInference(BaseTypeInference):
    _name = ...

@register_pass(mutates_CFG=True, analysis_only=False)
class PartialTypeInference(BaseTypeInference):
    _name = ...
    _raise_errors = ...

@register_pass(mutates_CFG=False, analysis_only=False)
class AnnotateTypes(AnalysisPass):
    _name = ...
    def __init__(self) -> None: ...
    def get_analysis_usage(self, AU):  # -> None:
        ...
    def run_pass(self, state):  # -> Literal[False]:

        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class NopythonRewrites(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:

        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class PreParforPass(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:

        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class ParforPass(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:

        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class ParforFusionPass(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:

        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class ParforPreLoweringPass(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:

        ...

@register_pass(mutates_CFG=False, analysis_only=True)
class DumpParforDiagnostics(AnalysisPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:
        ...

class BaseNativeLowering(abc.ABC, LoweringPass):
    _name = ...
    def __init__(self) -> None: ...
    @property
    @abc.abstractmethod
    def lowering_class(self):  # -> None:

        ...
    def run_pass(self, state):  # -> Literal[True]:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class NativeLowering(BaseNativeLowering):
    _name = ...
    @property
    def lowering_class(self):  # -> type[Lower]:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class NativeParforLowering(BaseNativeLowering):
    _name = ...
    @property
    def lowering_class(self):  # -> type[ParforLower]:
        ...

@register_pass(mutates_CFG=False, analysis_only=True)
class NoPythonSupportedFeatureValidation(AnalysisPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[False]:
        ...

@register_pass(mutates_CFG=False, analysis_only=True)
class IRLegalization(AnalysisPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class NoPythonBackend(LoweringPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:

        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class InlineOverloads(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...

    _DEBUG = ...
    def run_pass(self, state):  # -> Literal[True]:

        ...

@register_pass(mutates_CFG=False, analysis_only=False)
class DeadCodeElimination(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:
        ...

@register_pass(mutates_CFG=False, analysis_only=False)
class PreLowerStripPhis(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:
        ...
