from contextlib import contextmanager

from numba.core.compiler_machinery import AnalysisPass, FunctionPass, SSACompliantMixin, register_pass

@contextmanager
def fallback_context(state, msg):  # -> Generator[None, Any, None]:

    ...

@register_pass(mutates_CFG=True, analysis_only=False)
class ExtractByteCode(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:

        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class TranslateByteCode(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:

        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class FixupArgs(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class IRProcessing(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class RewriteSemanticConstants(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:

        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class DeadBranchPrune(SSACompliantMixin, FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:

        ...
    def get_analysis_usage(self, AU):  # -> None:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class InlineClosureLikes(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class GenericRewrites(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:

        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class WithLifting(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:

        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class InlineInlinables(FunctionPass):
    _name = ...
    _DEBUG = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:

        ...

@register_pass(mutates_CFG=False, analysis_only=False)
class PreserveIR(AnalysisPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[False]:
        ...

@register_pass(mutates_CFG=False, analysis_only=True)
class FindLiterallyCalls(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[False]:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class CanonicalizeLoopExit(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> bool:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class CanonicalizeLoopEntry(FunctionPass):
    _name = ...
    _supported_globals = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> bool:
        ...

@register_pass(mutates_CFG=False, analysis_only=True)
class PrintIRCFG(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[False]:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class MakeFunctionToJitFunction(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> bool:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class TransformLiteralUnrollConstListToTuple(FunctionPass):
    _name = ...
    _accepted_types = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> bool:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class MixedContainerUnroller(FunctionPass):
    _name = ...
    _DEBUG = ...
    _accepted_types = ...
    def __init__(self) -> None: ...
    def analyse_tuple(self, tup):  # -> defaultdict[Any, list[Any]]:

        ...
    def add_offset_to_labels_w_ignore(self, blocks, offset, ignore=...):  # -> dict[Any, Any]:

        ...
    def inject_loop_body(self, switch_ir, loop_ir, caller_max_label, dont_replace, switch_data): ...
    def gen_switch(self, data, index):  # -> FunctionIR:

        ...
    def apply_transform(self, state):  # -> bool:
        ...
    def unroll_loop(self, state, loop_info):  # -> None:
        ...
    def run_pass(self, state):  # -> bool:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class IterLoopCanonicalization(FunctionPass):
    _name = ...
    _DEBUG = ...
    _accepted_types = ...
    _accepted_calls = ...
    def __init__(self) -> None: ...
    def assess_loop(self, loop, func_ir, partial_typemap=...):  # -> bool | None:
        ...
    def transform(self, loop, func_ir, cfg):  # -> None:
        ...
    def run_pass(self, state):  # -> bool:
        ...

@register_pass(mutates_CFG=False, analysis_only=False)
class PropagateLiterals(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def get_analysis_usage(self, AU):  # -> None:
        ...
    def run_pass(self, state):  # -> bool:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class LiteralPropagationSubPipelinePass(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> bool:
        ...
    def get_analysis_usage(self, AU):  # -> None:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class LiteralUnroll(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> bool:
        ...

@register_pass(mutates_CFG=True, analysis_only=False)
class SimplifyCFG(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state): ...

@register_pass(mutates_CFG=False, analysis_only=False)
class ReconstructSSA(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> Literal[True]:
        ...

@register_pass(mutates_CFG=False, analysis_only=False)
class RewriteDynamicRaises(FunctionPass):
    _name = ...
    def __init__(self) -> None: ...
    def run_pass(self, state):  # -> bool:
        ...
