import contextlib
import functools
import json
import typing as _tp
from collections.abc import Mapping, MutableMapping, MutableSet
from types import ModuleType

def erase_traceback(exc_value): ...
def safe_relpath(path, start=...):  # -> str:

    ...

BINOPS_TO_OPERATORS = ...
INPLACE_BINOPS_TO_OPERATORS = ...
ALL_BINOPS_TO_OPERATORS = ...
UNARY_BUITINS_TO_OPERATORS = ...
OPERATORS_TO_BUILTINS = ...
_shutting_down = ...

def shutting_down(globals=...):  # -> bool:

    ...

class ThreadLocalStack:
    _tls = ...
    stack_name: str
    _registered = ...
    def __init_subclass__(cls, *, stack_name, **kwargs):  # -> None:
        ...
    def __init__(self) -> None: ...
    def push(self, state):  # -> None:

        ...
    def pop(self):  # -> Any:

        ...
    def top(self):  # -> Any:

        ...
    def __len__(self) -> int:  # -> int:
        ...
    @contextlib.contextmanager
    def enter(self, state):  # -> Generator[None, Any, None]:

        ...

class ConfigOptions:
    OPTIONS = ...
    def __init__(self) -> None: ...
    def set(self, name, value=...):  # -> None:
        ...
    def unset(self, name):  # -> None:
        ...
    def __getattr__(self, name): ...
    def __setattr__(self, name, value) -> None:  # -> None:
        ...
    def copy(self):  # -> Self:
        ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __hash__(self) -> int: ...

def order_by_target_specificity(target, templates, fnkey=...):  # -> list[Any]:

    ...

T = _tp.TypeVar("T")

class OrderedSet(MutableSet[T]):
    def __init__(self, iterable: _tp.Iterable[T] = ...) -> None: ...
    def __contains__(self, key) -> bool:  # -> bool:
        ...
    def __iter__(self):  # -> Iterator[T]:
        ...
    def __len__(self) -> int:  # -> int:
        ...
    def add(self, item):  # -> None:
        ...
    def discard(self, item):  # -> None:
        ...

class MutableSortedSet[T](MutableSet[T]):
    def __init__(self, values: _tp.Iterable[T] = ...) -> None: ...
    def __len__(self) -> int:  # -> int:
        ...
    def __iter__(self):  # -> Generator[Any, None, None]:
        ...
    def __contains__(self, x: T) -> bool: ...
    def add(self, x: T):  # -> None:
        ...
    def discard(self, value: T):  # -> None:
        ...
    def update(self, values):  # -> None:
        ...

Tk = _tp.TypeVar("Tk")
Tv = _tp.TypeVar("Tv")

class SortedMap[Tk, Tv](Mapping[Tk, Tv]):
    def __init__(self, seq) -> None: ...
    def __getitem__(self, k): ...
    def __len__(self) -> int:  # -> int:
        ...
    def __iter__(self):  # -> Generator[Any, None, None]:
        ...

class MutableSortedMap[Tk, Tv](MutableMapping[Tk, Tv]):
    def __init__(self, dct=...) -> None: ...
    def __getitem__(self, k: Tk) -> Tv: ...
    def __setitem__(self, k: Tk, v: Tv) -> None:  # -> None:
        ...
    def __delitem__(self, k: Tk) -> None:  # -> None:
        ...
    def __len__(self) -> int: ...
    def __iter__(self) -> int: ...

class UniqueDict(dict):
    def __setitem__(self, key, value) -> None:  # -> None:
        ...

def runonce(fn):  # -> _Wrapped[Callable[..., Any], Any, Callable[[], Any], Any]:
    ...
def bit_length(intval):  # -> int:

    ...
def stream_list(lst):  # -> Generator[Any, Any, NoReturn]:

    ...

class BenchmarkResult:
    def __init__(self, func, records, loop) -> None: ...

def format_time(tm):  # -> LiteralString:
    ...
def benchmark(func, maxsec=...):  # -> BenchmarkResult:
    ...

_dynamic_modname = ...
_dynamic_module = ...

def chain_exception(new_exc, old_exc): ...
def get_nargs_range(pyfunc):  # -> tuple[int, int]:

    ...
def unify_function_types(numba_types):  # -> tuple[UndefinedFunctionType | FunctionType, ...]:

    ...
def unified_function_type(numba_types, require_precise=...):  # -> UndefinedFunctionType | FunctionType | None:

    ...

class _RedirectSubpackage(ModuleType):
    def __init__(self, old_module_locals, new_module) -> None: ...
    def __reduce__(self):  # -> tuple[type[_RedirectSubpackage], tuple[dict[Any, Any], Any]]:
        ...

def get_hashable_key(value):  # -> int:

    ...

class threadsafe_cached_property(functools.cached_property):
    def __init__(self, *args, **kwargs) -> None: ...
    def __get__(self, *args, **kwargs):  # -> Self:
        ...

def dump_llvm(fndesc, module):  # -> None:
    ...

class _lazy_pformat:
    def __init__(self, *args, **kwargs) -> None: ...

class _LazyJSONEncoder(json.JSONEncoder):
    def default(self, obj):  # -> str | Any:
        ...
