from numba.core.typing.typeof import typeof_impl

class WithContext:
    is_callable = ...
    def __enter__(self):  # -> None:
        ...
    def __exit__(self, typ, val, tb):  # -> None:
        ...
    def mutate_with_body(self, func_ir, blocks, blk_start, blk_end, body_blocks, dispatcher_factory, extra): ...

@typeof_impl.register(WithContext)
def typeof_contextmanager(val, c):  # -> ContextManager:
    ...

class _ByPassContextType(WithContext):
    def mutate_with_body(self, func_ir, blocks, blk_start, blk_end, body_blocks, dispatcher_factory, extra):  # -> None:
        ...

bypass_context = ...

class _CallContextType(WithContext):
    def mutate_with_body(self, func_ir, blocks, blk_start, blk_end, body_blocks, dispatcher_factory, extra): ...

call_context = ...

class _ObjModeContextType(WithContext):
    is_callable = ...
    def mutate_with_body(self, func_ir, blocks, blk_start, blk_end, body_blocks, dispatcher_factory, extra): ...
    def __call__(self, *args, **kwargs):  # -> Self:
        ...

objmode_context = ...

class _ParallelChunksize(WithContext):
    is_callable = ...
    def mutate_with_body(self, func_ir, blocks, blk_start, blk_end, body_blocks, dispatcher_factory, extra):  # -> None:
        ...
    def __call__(self, *args, **kwargs):  # -> Self:

        ...
    def __enter__(self):  # -> None:
        ...
    def __exit__(self, typ, val, tb):  # -> None:
        ...

parallel_chunksize = ...
