"""
This type stub file was generated by pyright.
"""

import warnings
import pandas
import os
from packaging import version
from modin.config import Parameter
from modin.pandas import arrays, errors
from modin.pandas.api.extensions.extensions import __getattr___impl
from modin.utils import show_versions
from .. import __version__
from .dataframe import DataFrame
from .general import concat, crosstab, cut, get_dummies, isna, isnull, lreshape, melt, merge, merge_asof, merge_ordered, notna, notnull, pivot, pivot_table, qcut, to_datetime, to_numeric, to_timedelta, unique, value_counts, wide_to_long
from .io import ExcelFile, HDFStore, json_normalize, read_clipboard, read_csv, read_excel, read_feather, read_fwf, read_gbq, read_hdf, read_html, read_json, read_orc, read_parquet, read_pickle, read_sas, read_spss, read_sql, read_sql_query, read_sql_table, read_stata, read_table, read_xml, to_pickle
from .plotting import Plotting as plotting
from .series import Series

"""
This type stub file was generated by pyright.
"""
__min_pandas_version__ = ...
__max_pandas_version__ = ...
pandas_version = ...
if pandas_version < version.parse(__min_pandas_version__) or pandas_version >= version.parse(__max_pandas_version__):
    ...
_engine_initialized = ...
__getattr__ = ...
__all__ = ["DataFrame", "Series", "read_csv", "read_parquet", "read_json", "read_html", "read_clipboard", "read_excel", "read_hdf", "read_feather", "read_stata", "read_sas", "read_pickle", "read_sql", "read_gbq", "read_table", "read_spss", "read_orc", "json_normalize", "concat", "eval", "cut", "factorize", "test", "qcut", "to_datetime", "get_dummies", "isna", "isnull", "merge", "pivot_table", "date_range", "Index", "MultiIndex", "Series", "bdate_range", "period_range", "DatetimeIndex", "to_timedelta", "set_eng_float_format", "options", "describe_option", "set_option", "get_option", "reset_option", "option_context", "CategoricalIndex", "Timedelta", "Timestamp", "NaT", "PeriodIndex", "Categorical", "__version__", "melt", "crosstab", "plotting", "Interval", "UInt8Dtype", "UInt16Dtype", "UInt32Dtype", "UInt64Dtype", "SparseDtype", "Int8Dtype", "Int16Dtype", "Int32Dtype", "Int64Dtype", "CategoricalDtype", "DatetimeTZDtype", "IntervalDtype", "PeriodDtype", "BooleanDtype", "StringDtype", "NA", "RangeIndex", "TimedeltaIndex", "IntervalIndex", "IndexSlice", "Grouper", "array", "Period", "show_versions", "DateOffset", "timedelta_range", "infer_freq", "interval_range", "ExcelWriter", "read_fwf", "read_sql_table", "read_sql_query", "ExcelFile", "to_pickle", "HDFStore", "lreshape", "wide_to_long", "merge_asof", "merge_ordered", "notnull", "notna", "pivot", "to_numeric", "unique", "value_counts", "NamedAgg", "api", "read_xml", "ArrowDtype", "Flags", "Float32Dtype", "Float64Dtype", "from_dummies", "errors"]
