"""
This type stub file was generated by pyright.
"""

import numpy as np
import pandas
import pandas.core.generic
from functools import cached_property
from typing import Any, Callable, Hashable, Literal, Optional, Sequence, TYPE_CHECKING
from pandas._libs import lib
from pandas._typing import Axis, CompressionOptions, DtypeBackend, IndexKeyFunc, IndexLabel, Level, RandomState, Scalar, StorageOptions, T, TimedeltaConvertibleTypes, TimestampConvertibleTypes, npt
from pandas.util._decorators import doc
from modin.core.storage_formats.pandas.query_compiler_caster import QueryCompilerCaster
from modin.logging import ClassLogger, disable_logging
from modin.pandas.accessor import ModinAPI
from modin.pandas.api.extensions.extensions import EXTENSION_DICT_TYPE
from modin.pandas.utils import GET_BACKEND_DOC, SET_BACKEND_DOC
from modin.utils import _inherit_docstrings, expanduser_path_arg
from .utils import _doc_binary_op
from typing_extensions import Self
from modin.core.storage_formats import BaseQueryCompiler
from .dataframe import DataFrame
from .indexing import _LocIndexer, _iLocIndexer
from .resample import Resampler
from .series import Series
from .window import Expanding, Rolling, Window

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
_ATTRS_NO_LOOKUP = ...
_DEFAULT_BEHAVIOUR = ...
_doc_binary_op_kwargs = ...
@_inherit_docstrings(pandas.DataFrame, apilink=["pandas.DataFrame", "pandas.Series"])
class BasePandasDataset(QueryCompilerCaster, ClassLogger):
    """
    Implement most of the common code that exists in DataFrame/Series.

    Since both objects share the same underlying representation, and the algorithms
    are the same, we use this object to define the general behavior of those objects
    and then use those objects to define the output type.
    """
    _pandas_class = pandas.core.generic.NDFrame
    _query_compiler: BaseQueryCompiler
    _siblings: list[BasePandasDataset]
    _extensions: EXTENSION_DICT_TYPE = ...
    _pinned: bool = ...
    @cached_property
    def __constructor__(self) -> type[Self]:
        """
        Construct DataFrame or Series object depending on self type.

        Returns
        -------
        modin.pandas.BasePandasDataset
            Constructed object.
        """
        ...
    
    def abs(self) -> Self:
        """
        Return a `BasePandasDataset` with absolute numeric value of each element.
        """
        ...
    
    index: pandas.Index = ...
    def add(self, other, axis=..., level=..., fill_value=...) -> Self:
        """
        Return addition of `BasePandasDataset` and `other`, element-wise (binary operator `add`).
        """
        ...
    
    def aggregate(self, func=..., axis=..., *args, **kwargs) -> DataFrame | Series | Scalar:
        """
        Aggregate using one or more operations over the specified axis.
        """
        ...
    
    agg: DataFrame | Series | Scalar = ...
    def align(self, other, join=..., axis=..., level=..., copy=..., fill_value=..., method=..., limit=..., fill_axis=..., broadcast_axis=...) -> tuple[Self, Self]:
        """
        Align two objects on their axes with the specified join method.
        """
        ...
    
    def all(self, axis=..., bool_only=..., skipna=..., **kwargs) -> Self:
        """
        Return whether all elements are True, potentially over an axis.
        """
        ...
    
    def any(self, *, axis=..., bool_only=..., skipna=..., **kwargs) -> Self:
        """
        Return whether any element is True, potentially over an axis.
        """
        ...
    
    def apply(self, func, axis, raw, result_type, args, **kwds) -> BaseQueryCompiler:
        """
        Apply a function along an axis of the `BasePandasDataset`.
        """
        ...
    
    def asfreq(self, freq, method=..., how=..., normalize=..., fill_value=...) -> Self:
        """
        Convert time series to specified frequency.
        """
        ...
    
    def asof(self, where, subset=...) -> Self:
        """
        Return the last row(s) without any NaNs before `where`.
        """
        ...
    
    def astype(self, dtype, copy=..., errors=...) -> Self:
        """
        Cast a Modin object to a specified dtype `dtype`.
        """
        ...
    
    @property
    def at(self, axis=...) -> _LocIndexer:
        """
        Get a single value for a row/column label pair.
        """
        ...
    
    def at_time(self, time, asof=..., axis=...) -> Self:
        """
        Select values at particular time of day (e.g., 9:30AM).
        """
        ...
    
    @_inherit_docstrings(pandas.DataFrame.between_time, apilink="pandas.DataFrame.between_time")
    def between_time(self, start_time, end_time, inclusive=..., axis=...) -> Self:
        ...
    
    def bfill(self, *, axis=..., inplace=..., limit=..., limit_area=..., downcast=...) -> Self:
        """
        Synonym for `DataFrame.fillna` with ``method='bfill'``.
        """
        ...
    
    def backfill(self, *, axis=..., inplace=..., limit=..., downcast=...) -> Self:
        """
        Synonym for `DataFrame.bfill`.
        """
        ...
    
    def bool(self) -> bool:
        """
        Return the bool of a single element `BasePandasDataset`.
        """
        ...
    
    def clip(self, lower=..., upper=..., *, axis=..., inplace=..., **kwargs) -> Self:
        """
        Trim values at input threshold(s).
        """
        ...
    
    def combine(self, other, func, fill_value=..., **kwargs) -> Self:
        """
        Perform combination of `BasePandasDataset`-s according to `func`.
        """
        ...
    
    def combine_first(self, other) -> Self:
        """
        Update null elements with value in the same location in `other`.
        """
        ...
    
    def copy(self, deep=...) -> Self:
        """
        Make a copy of the object's metadata.
        """
        ...
    
    def count(self, axis=..., numeric_only=...) -> Series | Scalar:
        """
        Count non-NA cells for `BasePandasDataset`.
        """
        ...
    
    def cummax(self, axis=..., skipna=..., *args, **kwargs) -> Self:
        """
        Return cumulative maximum over a `BasePandasDataset` axis.
        """
        ...
    
    def cummin(self, axis=..., skipna=..., *args, **kwargs) -> Self:
        """
        Return cumulative minimum over a `BasePandasDataset` axis.
        """
        ...
    
    def cumprod(self, axis=..., skipna=..., *args, **kwargs) -> Self:
        """
        Return cumulative product over a `BasePandasDataset` axis.
        """
        ...
    
    def cumsum(self, axis=..., skipna=..., *args, **kwargs) -> Self:
        """
        Return cumulative sum over a `BasePandasDataset` axis.
        """
        ...
    
    def describe(self, percentiles=..., include=..., exclude=...) -> Self:
        """
        Generate descriptive statistics.
        """
        ...
    
    def diff(self, periods=..., axis=...) -> Self:
        """
        First discrete difference of element.
        """
        ...
    
    def drop(self, labels=..., *, axis=..., index=..., columns=..., level=..., inplace=..., errors=...) -> Self:
        """
        Drop specified labels from `BasePandasDataset`.
        """
        ...
    
    def dropna(self, *, axis: Axis = ..., how: str | lib.NoDefault = ..., thresh: int | lib.NoDefault = ..., subset: IndexLabel = ..., inplace: bool = ..., ignore_index: bool = ...) -> Self:
        """
        Remove missing values.
        """
        ...
    
    def droplevel(self, level, axis=...) -> Self:
        """
        Return `BasePandasDataset` with requested index / column level(s) removed.
        """
        ...
    
    def drop_duplicates(self, keep=..., inplace=..., **kwargs) -> Self:
        """
        Return `BasePandasDataset` with duplicate rows removed.
        """
        ...
    
    def eq(self, other, axis=..., level=...) -> Self:
        """
        Get equality of `BasePandasDataset` and `other`, element-wise (binary operator `eq`).
        """
        ...
    
    def explode(self, column, ignore_index: bool = ...) -> Self:
        """
        Transform each element of a list-like to a row.
        """
        ...
    
    def ewm(self, com: float | None = ..., span: float | None = ..., halflife: float | TimedeltaConvertibleTypes | None = ..., alpha: float | None = ..., min_periods: int | None = ..., adjust: bool = ..., ignore_na: bool = ..., axis: Axis = ..., times: str | np.ndarray | BasePandasDataset | None = ..., method: str = ...) -> pandas.core.window.ewm.ExponentialMovingWindow:
        """
        Provide exponentially weighted (EW) calculations.
        """
        ...
    
    def expanding(self, min_periods=..., axis=..., method=...) -> Expanding:
        """
        Provide expanding window calculations.
        """
        ...
    
    def ffill(self, *, axis=..., inplace=..., limit=..., limit_area=..., downcast=...) -> Self | None:
        """
        Synonym for `DataFrame.fillna` with ``method='ffill'``.
        """
        ...
    
    def pad(self, *, axis=..., inplace=..., limit=..., downcast=...) -> Self | None:
        """
        Synonym for `DataFrame.ffill`.
        """
        ...
    
    def fillna(self, squeeze_self, squeeze_value, value=..., method=..., axis=..., inplace=..., limit=..., downcast=...) -> Self | None:
        """
        Fill NA/NaN values using the specified method.

        Parameters
        ----------
        squeeze_self : bool
            If True then self contains a Series object, if False then self contains
            a DataFrame object.
        squeeze_value : bool
            If True then value contains a Series object, if False then value contains
            a DataFrame object.
        value : scalar, dict, Series, or DataFrame, default: None
            Value to use to fill holes (e.g. 0), alternately a
            dict/Series/DataFrame of values specifying which value to use for
            each index (for a Series) or column (for a DataFrame).  Values not
            in the dict/Series/DataFrame will not be filled. This value cannot
            be a list.
        method : {'backfill', 'bfill', 'pad', 'ffill', None}, default: None
            Method to use for filling holes in reindexed Series
            pad / ffill: propagate last valid observation forward to next valid
            backfill / bfill: use next valid observation to fill gap.
        axis : {None, 0, 1}, default: None
            Axis along which to fill missing values.
        inplace : bool, default: False
            If True, fill in-place. Note: this will modify any
            other views on this object (e.g., a no-copy slice for a column in a
            DataFrame).
        limit : int, default: None
            If method is specified, this is the maximum number of consecutive
            NaN values to forward/backward fill. In other words, if there is
            a gap with more than this number of consecutive NaNs, it will only
            be partially filled. If method is not specified, this is the
            maximum number of entries along the entire axis where NaNs will be
            filled. Must be greater than 0 if not None.
        downcast : dict, default: None
            A dict of item->dtype of what to downcast if possible,
            or the string 'infer' which will try to downcast to an appropriate
            equal type (e.g. float64 to int64 if possible).

        Returns
        -------
        Series, DataFrame or None
            Object with missing values filled or None if ``inplace=True``.
        """
        ...
    
    def filter(self, items=..., like=..., regex=..., axis=...) -> Self:
        """
        Subset the `BasePandasDataset` rows or columns according to the specified index labels.
        """
        ...
    
    def first(self, offset) -> Self | None:
        """
        Select initial periods of time series data based on a date offset.
        """
        ...
    
    def first_valid_index(self) -> int:
        """
        Return index for first non-NA value or None, if no non-NA value is found.
        """
        ...
    
    def floordiv(self, other, axis=..., level=..., fill_value=...) -> Self:
        """
        Get integer division of `BasePandasDataset` and `other`, element-wise (binary operator `floordiv`).
        """
        ...
    
    def ge(self, other, axis=..., level=...) -> Self:
        """
        Get greater than or equal comparison of `BasePandasDataset` and `other`, element-wise (binary operator `ge`).
        """
        ...
    
    def get(self, key, default=...) -> DataFrame | Series | Scalar:
        """
        Get item from object for given key.
        """
        ...
    
    def gt(self, other, axis=..., level=...) -> Self:
        """
        Get greater than comparison of `BasePandasDataset` and `other`, element-wise (binary operator `gt`).
        """
        ...
    
    def head(self, n=...) -> Self:
        """
        Return the first `n` rows.
        """
        ...
    
    @property
    def iat(self, axis=...) -> _iLocIndexer:
        """
        Get a single value for a row/column pair by integer position.
        """
        ...
    
    def idxmax(self, axis=..., skipna=..., numeric_only=...) -> Self:
        """
        Return index of first occurrence of maximum over requested axis.
        """
        ...
    
    def idxmin(self, axis=..., skipna=..., numeric_only=...) -> Self:
        """
        Return index of first occurrence of minimum over requested axis.
        """
        ...
    
    def infer_objects(self, copy=...) -> Self:
        """
        Attempt to infer better dtypes for object columns.
        """
        ...
    
    def convert_dtypes(self, infer_objects: bool = ..., convert_string: bool = ..., convert_integer: bool = ..., convert_boolean: bool = ..., convert_floating: bool = ..., dtype_backend: DtypeBackend = ...) -> Self:
        """
        Convert columns to best possible dtypes using dtypes supporting ``pd.NA``.
        """
        ...
    
    def isin(self, values) -> Self:
        """
        Whether elements in `BasePandasDataset` are contained in `values`.
        """
        ...
    
    def isna(self) -> Self:
        """
        Detect missing values.
        """
        ...
    
    isnull: Self = ...
    @property
    def iloc(self) -> _iLocIndexer:
        """
        Purely integer-location based indexing for selection by position.
        """
        ...
    
    @_inherit_docstrings(pandas.DataFrame.kurt, apilink="pandas.DataFrame.kurt")
    def kurt(self, axis=..., skipna=..., numeric_only=..., **kwargs) -> Series | float:
        ...
    
    kurtosis: Series | float = ...
    def last(self, offset) -> Self:
        """
        Select final periods of time series data based on a date offset.
        """
        ...
    
    def last_valid_index(self) -> int:
        """
        Return index for last non-NA value or None, if no non-NA value is found.
        """
        ...
    
    def le(self, other, axis=..., level=...) -> Self:
        """
        Get less than or equal comparison of `BasePandasDataset` and `other`, element-wise (binary operator `le`).
        """
        ...
    
    def lt(self, other, axis=..., level=...) -> Self:
        """
        Get less than comparison of `BasePandasDataset` and `other`, element-wise (binary operator `lt`).
        """
        ...
    
    @property
    def loc(self) -> _LocIndexer:
        """
        Get a group of rows and columns by label(s) or a boolean array.
        """
        ...
    
    def mask(self, cond, other=..., *, inplace: bool = ..., axis: Optional[Axis] = ..., level: Optional[Level] = ...) -> Self | None:
        """
        Replace values where the condition is True.
        """
        ...
    
    def max(self, axis: Axis = ..., skipna=..., numeric_only=..., **kwargs) -> Series | None:
        """
        Return the maximum of the values over the requested axis.
        """
        ...
    
    def min(self, axis: Axis = ..., skipna: bool = ..., numeric_only=..., **kwargs) -> Series | None:
        """
        Return the minimum of the values over the requested axis.
        """
        ...
    
    def memory_usage(self, index=..., deep=...) -> Series | None:
        """
        Return the memory usage of the `BasePandasDataset`.
        """
        ...
    
    def mod(self, other, axis=..., level=..., fill_value=...) -> Self:
        """
        Get modulo of `BasePandasDataset` and `other`, element-wise (binary operator `mod`).
        """
        ...
    
    def mode(self, axis=..., numeric_only=..., dropna=...) -> Self:
        """
        Get the mode(s) of each element along the selected axis.
        """
        ...
    
    def mul(self, other, axis=..., level=..., fill_value=...) -> Self:
        """
        Get multiplication of `BasePandasDataset` and `other`, element-wise (binary operator `mul`).
        """
        ...
    
    multiply: Self = ...
    def ne(self, other, axis=..., level=...) -> Self:
        """
        Get Not equal comparison of `BasePandasDataset` and `other`, element-wise (binary operator `ne`).
        """
        ...
    
    def notna(self) -> Self:
        """
        Detect existing (non-missing) values.
        """
        ...
    
    notnull: Self = ...
    def nunique(self, axis=..., dropna=...) -> Series | int:
        """
        Return number of unique elements in the `BasePandasDataset`.
        """
        ...
    
    def pct_change(self, periods=..., fill_method=..., limit=..., freq=..., **kwargs) -> Self:
        """
        Percentage change between the current and a prior element.
        """
        ...
    
    def pipe(self, func: Callable[..., T] | tuple[Callable[..., T], str], *args, **kwargs) -> T:
        """
        Apply chainable functions that expect `BasePandasDataset`.
        """
        ...
    
    def pop(self, item) -> Series | Scalar:
        """
        Return item and drop from frame. Raise KeyError if not found.
        """
        ...
    
    def pow(self, other, axis=..., level=..., fill_value=...) -> Self:
        """
        Get exponential power of `BasePandasDataset` and `other`, element-wise (binary operator `pow`).
        """
        ...
    
    def quantile(self, q, axis, numeric_only, interpolation, method) -> DataFrame | Series | Scalar:
        """
        Return values at the given quantile over requested axis.
        """
        ...
    
    @_inherit_docstrings(pandas.DataFrame.rank, apilink="pandas.DataFrame.rank")
    def rank(self, axis=..., method: str = ..., numeric_only=..., na_option: str = ..., ascending: bool = ..., pct: bool = ...) -> Self:
        ...
    
    def reindex(self, index=..., columns=..., copy=..., **kwargs) -> Self:
        """
        Conform `BasePandasDataset` to new index with optional filling logic.
        """
        ...
    
    def rename_axis(self, mapper=..., *, index=..., columns=..., axis=..., copy=..., inplace=...) -> DataFrame | Series | None:
        """
        Set the name of the axis for the index or columns.
        """
        ...
    
    def reorder_levels(self, order, axis=...) -> Self:
        """
        Rearrange index levels using input order.
        """
        ...
    
    def resample(self, rule, axis: Axis = ..., closed: Optional[str] = ..., label: Optional[str] = ..., convention: str = ..., kind: Optional[str] = ..., on: Level = ..., level: Level = ..., origin: str | TimestampConvertibleTypes = ..., offset: Optional[TimedeltaConvertibleTypes] = ..., group_keys=...) -> Resampler:
        """
        Resample time-series data.
        """
        ...
    
    def reset_index(self, level: IndexLabel = ..., *, drop: bool = ..., inplace: bool = ..., col_level: Hashable = ..., col_fill: Hashable = ..., allow_duplicates=..., names: Hashable | Sequence[Hashable] = ...) -> DataFrame | Series | None:
        """
        Reset the index, or a level of it.
        """
        ...
    
    def radd(self, other, axis=..., level=..., fill_value=...) -> Self:
        """
        Return addition of `BasePandasDataset` and `other`, element-wise (binary operator `radd`).
        """
        ...
    
    def rfloordiv(self, other, axis=..., level=..., fill_value=...) -> Self:
        """
        Get integer division of `BasePandasDataset` and `other`, element-wise (binary operator `rfloordiv`).
        """
        ...
    
    def rmod(self, other, axis=..., level=..., fill_value=...) -> Self:
        """
        Get modulo of `BasePandasDataset` and `other`, element-wise (binary operator `rmod`).
        """
        ...
    
    def rmul(self, other, axis=..., level=..., fill_value=...) -> Self:
        """
        Get Multiplication of dataframe and other, element-wise (binary operator `rmul`).
        """
        ...
    
    def rolling(self, window, min_periods: int | None = ..., center: bool = ..., win_type: str | None = ..., on: str | None = ..., axis: Axis = ..., closed: str | None = ..., step: int | None = ..., method: str = ...) -> Rolling | Window:
        """
        Provide rolling window calculations.
        """
        ...
    
    def round(self, decimals=..., *args, **kwargs) -> Self:
        """
        Round a `BasePandasDataset` to a variable number of decimal places.
        """
        ...
    
    def rpow(self, other, axis=..., level=..., fill_value=...) -> Self:
        """
        Get exponential power of `BasePandasDataset` and `other`, element-wise (binary operator `rpow`).
        """
        ...
    
    def rsub(self, other, axis=..., level=..., fill_value=...) -> Self:
        """
        Get subtraction of `BasePandasDataset` and `other`, element-wise (binary operator `rsub`).
        """
        ...
    
    def rtruediv(self, other, axis=..., level=..., fill_value=...) -> Self:
        """
        Get floating division of `BasePandasDataset` and `other`, element-wise (binary operator `rtruediv`).
        """
        ...
    
    rdiv: Self = ...
    def sample(self, n: int | None = ..., frac: float | None = ..., replace: bool = ..., weights=..., random_state: RandomState | None = ..., axis: Axis | None = ..., ignore_index: bool = ...) -> Self:
        """
        Return a random sample of items from an axis of object.
        """
        ...
    
    def sem(self, axis: Axis = ..., skipna: bool = ..., ddof: int = ..., numeric_only=..., **kwargs) -> Series | float:
        """
        Return unbiased standard error of the mean over requested axis.
        """
        ...
    
    def mean(self, axis: Axis = ..., skipna=..., numeric_only=..., **kwargs) -> Series | float:
        """
        Return the mean of the values over the requested axis.
        """
        ...
    
    def median(self, axis: Axis = ..., skipna=..., numeric_only=..., **kwargs) -> Series | float:
        """
        Return the mean of the values over the requested axis.
        """
        ...
    
    def set_axis(self, labels, *, axis: Axis = ..., copy=...) -> Self:
        """
        Assign desired index to given axis.
        """
        ...
    
    def set_flags(self, *, copy: bool = ..., allows_duplicate_labels: Optional[bool] = ...) -> Self:
        """
        Return a new `BasePandasDataset` with updated flags.
        """
        ...
    
    @property
    def flags(self):
        ...
    
    def shift(self, periods: int = ..., freq=..., axis: Axis = ..., fill_value: Hashable = ..., suffix=...) -> Self | DataFrame:
        """
        Shift index by desired number of periods with an optional time `freq`.
        """
        ...
    
    def skew(self, axis: Axis = ..., skipna: bool = ..., numeric_only=..., **kwargs) -> Series | float:
        """
        Return unbiased skew over requested axis.
        """
        ...
    
    def sort_index(self, *, axis=..., level=..., ascending=..., inplace=..., kind=..., na_position=..., sort_remaining=..., ignore_index: bool = ..., key: Optional[IndexKeyFunc] = ...) -> Self | None:
        """
        Sort object by labels (along an axis).
        """
        ...
    
    def sort_values(self, by, *, axis=..., ascending=..., inplace: bool = ..., kind=..., na_position=..., ignore_index: bool = ..., key: Optional[IndexKeyFunc] = ...) -> Self | None:
        """
        Sort by the values along either axis.
        """
        ...
    
    def std(self, axis: Axis = ..., skipna: bool = ..., ddof: int = ..., numeric_only=..., **kwargs) -> Series | float:
        """
        Return sample standard deviation over requested axis.
        """
        ...
    
    def sub(self, other, axis=..., level=..., fill_value=...) -> Self:
        """
        Get subtraction of `BasePandasDataset` and `other`, element-wise (binary operator `sub`).
        """
        ...
    
    subtract: Self = ...
    def swapaxes(self, axis1, axis2, copy=...) -> Self:
        """
        Interchange axes and swap values axes appropriately.
        """
        ...
    
    def swaplevel(self, i=..., j=..., axis=...) -> Self:
        """
        Swap levels `i` and `j` in a `MultiIndex`.
        """
        ...
    
    def tail(self, n=...) -> Self:
        """
        Return the last `n` rows.
        """
        ...
    
    def take(self, indices, axis=..., **kwargs) -> Self:
        """
        Return the elements in the given *positional* indices along an axis.
        """
        ...
    
    def to_clipboard(self, excel=..., sep=..., **kwargs):
        """
        Copy object to the system clipboard.
        """
        ...
    
    @expanduser_path_arg("path_or_buf")
    def to_csv(self, path_or_buf=..., sep=..., na_rep=..., float_format=..., columns=..., header=..., index=..., index_label=..., mode=..., encoding=..., compression=..., quoting=..., quotechar=..., lineterminator=..., chunksize=..., date_format=..., doublequote=..., escapechar=..., decimal=..., errors: str = ..., storage_options: StorageOptions = ...) -> str | None:
        ...
    
    @expanduser_path_arg("excel_writer")
    def to_excel(self, excel_writer, sheet_name=..., na_rep=..., float_format=..., columns=..., header=..., index=..., index_label=..., startrow=..., startcol=..., engine=..., merge_cells=..., inf_rep=..., freeze_panes=..., storage_options: StorageOptions = ..., engine_kwargs=...) -> None:
        """
        Write object to an Excel sheet.
        """
        ...
    
    def to_dict(self, orient=..., into=..., index=...) -> dict:
        ...
    
    @expanduser_path_arg("path_or_buf")
    def to_hdf(self, path_or_buf, key: str, mode: Literal["a", "w", "r+"] = ..., complevel: int | None = ..., complib: Literal["zlib", "lzo", "bzip2", "blosc"] | None = ..., append: bool = ..., format: Literal["fixed", "table"] | None = ..., index: bool = ..., min_itemsize: int | dict[str, int] | None = ..., nan_rep=..., dropna: bool | None = ..., data_columns: Literal[True] | list[str] | None = ..., errors: str = ..., encoding: str = ...) -> None:
        """
        Write the contained data to an HDF5 file using HDFStore.
        """
        ...
    
    @expanduser_path_arg("path_or_buf")
    def to_json(self, path_or_buf=..., orient=..., date_format=..., double_precision=..., force_ascii=..., date_unit=..., default_handler=..., lines=..., compression=..., index=..., indent=..., storage_options: StorageOptions = ..., mode=...) -> str | None:
        """
        Convert the object to a JSON string.
        """
        ...
    
    @expanduser_path_arg("buf")
    def to_latex(self, buf=..., columns=..., header=..., index=..., na_rep=..., formatters=..., float_format=..., sparsify=..., index_names=..., bold_rows=..., column_format=..., longtable=..., escape=..., encoding=..., decimal=..., multicolumn=..., multicolumn_format=..., multirow=..., caption=..., label=..., position=...) -> str | None:
        """
        Render object to a LaTeX tabular, longtable, or nested table.
        """
        ...
    
    @expanduser_path_arg("buf")
    def to_markdown(self, buf=..., mode: str = ..., index: bool = ..., storage_options: StorageOptions = ..., **kwargs) -> str:
        """
        Print `BasePandasDataset` in Markdown-friendly format.
        """
        ...
    
    @expanduser_path_arg("path")
    def to_pickle(self, path, compression: CompressionOptions = ..., protocol: int = ..., storage_options: StorageOptions = ...) -> None:
        """
        Pickle (serialize) object to file.
        """
        ...
    
    def to_numpy(self, dtype=..., copy=..., na_value=...) -> np.ndarray:
        """
        Convert the `BasePandasDataset` to a NumPy array or a Modin wrapper for NumPy array.
        """
        ...
    
    def to_period(self, freq=..., axis=..., copy=...) -> Self:
        """
        Convert `BasePandasDataset` from DatetimeIndex to PeriodIndex.
        """
        ...
    
    @expanduser_path_arg("buf")
    def to_string(self, buf=..., columns=..., col_space=..., header=..., index=..., na_rep=..., formatters=..., float_format=..., sparsify=..., index_names=..., justify=..., max_rows=..., min_rows=..., max_cols=..., show_dimensions=..., decimal=..., line_width=..., max_colwidth=..., encoding=...) -> str | None:
        """
        Render a `BasePandasDataset` to a console-friendly tabular output.
        """
        ...
    
    def to_sql(self, name, con, schema=..., if_exists=..., index=..., index_label=..., chunksize=..., dtype=..., method=...) -> int | None:
        """
        Write records stored in a `BasePandasDataset` to a SQL database.
        """
        ...
    
    def to_timestamp(self, freq=..., how=..., axis=..., copy=...) -> Self:
        """
        Cast to DatetimeIndex of timestamps, at *beginning* of period.
        """
        ...
    
    def to_xarray(self):
        """
        Return an xarray object from the `BasePandasDataset`.
        """
        ...
    
    def truediv(self, other, axis=..., level=..., fill_value=...) -> Self:
        """
        Get floating division of `BasePandasDataset` and `other`, element-wise (binary operator `truediv`).
        """
        ...
    
    div: Self = ...
    divide: Self = ...
    def truncate(self, before=..., after=..., axis=..., copy=...) -> Self:
        """
        Truncate a `BasePandasDataset` before and after some index value.
        """
        ...
    
    def transform(self, func, axis=..., *args, **kwargs) -> Self:
        """
        Call ``func`` on self producing a `BasePandasDataset` with the same axis shape as self.
        """
        ...
    
    def tz_convert(self, tz, axis=..., level=..., copy=...) -> Self:
        """
        Convert tz-aware axis to target time zone.
        """
        ...
    
    def tz_localize(self, tz, axis=..., level=..., copy=..., ambiguous=..., nonexistent=...) -> Self:
        """
        Localize tz-naive index of a `BasePandasDataset` to target time zone.
        """
        ...
    
    def interpolate(self, method=..., *, axis=..., limit=..., inplace=..., limit_direction: Optional[str] = ..., limit_area=..., downcast=..., **kwargs) -> Self:
        ...
    
    @_inherit_docstrings(pandas.DataFrame.value_counts, apilink="pandas.DataFrame.value_counts")
    def value_counts(self, subset: Sequence[Hashable] | None = ..., normalize: bool = ..., sort: bool = ..., ascending: bool = ..., dropna: bool = ...) -> Series:
        ...
    
    def var(self, axis: Axis = ..., skipna: bool = ..., ddof: int = ..., numeric_only=..., **kwargs) -> Series | float:
        """
        Return unbiased variance over requested axis.
        """
        ...
    
    def __abs__(self) -> Self:
        """
        Return a `BasePandasDataset` with absolute numeric value of each element.

        Returns
        -------
        BasePandasDataset
            Object containing the absolute value of each element.
        """
        ...
    
    @_doc_binary_op(operation="union", bin_op="and", right="other", **_doc_binary_op_kwargs)
    def __and__(self, other) -> Self:
        ...
    
    @_doc_binary_op(operation="union", bin_op="rand", right="other", **_doc_binary_op_kwargs)
    def __rand__(self, other) -> Self:
        ...
    
    def __array__(self, dtype: npt.DTypeLike | None = ..., copy: bool | None = ...) -> np.ndarray:
        """
        Return the values as a NumPy array.

        Parameters
        ----------
        dtype : str or np.dtype, optional
            The dtype of returned array.
        copy : bool, default: None
            This parameter has no effect; the method always returns a copy of
            the data.

        Returns
        -------
        arr : np.ndarray
            NumPy representation of Modin object.
        """
        ...
    
    def __copy__(self, deep=...) -> Self:
        """
        Return the copy of the `BasePandasDataset`.

        Parameters
        ----------
        deep : bool, default: True
            Whether the copy should be deep or not.

        Returns
        -------
        BasePandasDataset
        """
        ...
    
    def __deepcopy__(self, memo=...) -> Self:
        """
        Return the deep copy of the `BasePandasDataset`.

        Parameters
        ----------
        memo : Any, optional
           Deprecated parameter.

        Returns
        -------
        BasePandasDataset
        """
        ...
    
    @_doc_binary_op(operation="equality comparison", bin_op="eq", right="other", **_doc_binary_op_kwargs)
    def __eq__(self, other) -> Self:
        ...
    
    def __finalize__(self, other, method=..., **kwargs) -> Self:
        """
        Propagate metadata from `other` to `self`.

        Parameters
        ----------
        other : BasePandasDataset
            The object from which to get the attributes that we are going
            to propagate.
        method : str, optional
            A passed method name providing context on where `__finalize__`
            was called.
        **kwargs : dict
            Additional keywords arguments to be passed to `__finalize__`.

        Returns
        -------
        BasePandasDataset
        """
        ...
    
    @_doc_binary_op(operation="greater than or equal comparison", bin_op="ge", right="right", **_doc_binary_op_kwargs)
    def __ge__(self, right) -> Self:
        ...
    
    def __getitem__(self, key) -> Self:
        """
        Retrieve dataset according to `key`.

        Parameters
        ----------
        key : callable, scalar, slice, str or tuple
            The global row index to retrieve data from.

        Returns
        -------
        BasePandasDataset
            Located dataset.
        """
        ...
    
    def xs(self, key, axis=..., level=..., drop_level: bool = ...) -> Self:
        """
        Return cross-section from the Series/DataFrame.
        """
        ...
    
    __hash__ = ...
    @_doc_binary_op(operation="greater than comparison", bin_op="gt", right="right", **_doc_binary_op_kwargs)
    def __gt__(self, right) -> Self:
        ...
    
    def __invert__(self) -> Self:
        """
        Apply bitwise inverse to each element of the `BasePandasDataset`.

        Returns
        -------
        BasePandasDataset
            New BasePandasDataset containing bitwise inverse to each value.
        """
        ...
    
    @_doc_binary_op(operation="less than or equal comparison", bin_op="le", right="right", **_doc_binary_op_kwargs)
    def __le__(self, right) -> Self:
        ...
    
    def __len__(self) -> int:
        """
        Return length of info axis.

        Returns
        -------
        int
        """
        ...
    
    @_doc_binary_op(operation="less than comparison", bin_op="lt", right="right", **_doc_binary_op_kwargs)
    def __lt__(self, right) -> Self:
        ...
    
    def __matmul__(self, other) -> Self | np.ndarray | Scalar:
        """
        Compute the matrix multiplication between the `BasePandasDataset` and `other`.

        Parameters
        ----------
        other : BasePandasDataset or array-like
            The other object to compute the matrix product with.

        Returns
        -------
        BasePandasDataset, np.ndarray or scalar
        """
        ...
    
    @_doc_binary_op(operation="not equal comparison", bin_op="ne", right="other", **_doc_binary_op_kwargs)
    def __ne__(self, other) -> Self:
        ...
    
    def __neg__(self) -> Self:
        """
        Change the sign for every value of self.

        Returns
        -------
        BasePandasDataset
        """
        ...
    
    def __nonzero__(self):
        """
        Evaluate `BasePandasDataset` as boolean object.

        Raises
        ------
        ValueError
            Always since truth value for self is ambiguous.
        """
        ...
    
    __bool__ = ...
    @_doc_binary_op(operation="disjunction", bin_op="or", right="other", **_doc_binary_op_kwargs)
    def __or__(self, other) -> Self:
        ...
    
    @_doc_binary_op(operation="disjunction", bin_op="ror", right="other", **_doc_binary_op_kwargs)
    def __ror__(self, other) -> Self:
        ...
    
    def __sizeof__(self) -> int:
        """
        Generate the total memory usage for an `BasePandasDataset`.

        Returns
        -------
        int
        """
        ...
    
    def __str__(self) -> str:
        """
        Return str(self).

        Returns
        -------
        str
        """
        ...
    
    @_doc_binary_op(operation="exclusive disjunction", bin_op="xor", right="other", **_doc_binary_op_kwargs)
    def __xor__(self, other) -> Self:
        ...
    
    @_doc_binary_op(operation="exclusive disjunction", bin_op="rxor", right="other", **_doc_binary_op_kwargs)
    def __rxor__(self, other) -> Self:
        ...
    
    @property
    def size(self) -> int:
        """
        Return an int representing the number of elements in this `BasePandasDataset` object.
        """
        ...
    
    @property
    def values(self) -> np.ndarray:
        """
        Return a NumPy representation of the `BasePandasDataset`.
        """
        ...
    
    @disable_logging
    def __getattribute__(self, item) -> Any:
        """
        Return item from the `BasePandasDataset`.

        Parameters
        ----------
        item : hashable
            Item to get.

        Returns
        -------
        Any
        """
        ...
    
    def __array_ufunc__(self, ufunc: np.ufunc, method: str, *inputs: Any, **kwargs: Any) -> DataFrame | Series | Any:
        """
        Apply the `ufunc` to the `BasePandasDataset`.

        Parameters
        ----------
        ufunc : np.ufunc
            The NumPy ufunc to apply.
        method : str
            The method to apply.
        *inputs : tuple
            The inputs to the ufunc.
        **kwargs : dict
            Additional keyword arguments.

        Returns
        -------
        BasePandasDataset
            The result of the ufunc applied to the `BasePandasDataset`.
        """
        ...
    
    def __array_function__(self, func: np.func, types: tuple, args: tuple, kwargs: dict) -> DataFrame | Series | Any:
        """
        Apply `func` to the `BasePandasDataset`.

        This function implements NEP18-style dispatch for certain NumPy functions:
        https://numpy.org/neps/nep-0018-array-function-protocol.html#nep18

        By default, this function will transparently call __array__, followed by __array_function__
        on the returned NumPy array. We implement this function to prevent bugs with the extension
        system when another backend overrides this method.

        Parameters
        ----------
        func : np.func
            The NumPy func to apply.
        types : tuple
            The types of the args.
        args : tuple
            The args to the func.
        kwargs : dict
            Additional keyword arguments.

        Returns
        -------
        DataFrame | Series | Any
            The result of applying the function to this dataset. By default, it will return
            a NumPy array.
        """
        ...
    
    modin: ModinAPI = ...
    @disable_logging
    def is_backend_pinned(self) -> bool:
        """
        Get whether this object's data is pinned to a particular backend.

        Returns
        -------
        bool
            True if the data is pinned.
        """
        ...
    
    @doc(SET_BACKEND_DOC, class_name=__qualname__)
    def set_backend(self, backend: str, inplace: bool = ..., *, switch_operation: str = ...) -> Optional[Self]:
        ...
    
    move_to = ...
    @doc(GET_BACKEND_DOC, class_name=__qualname__)
    @disable_logging
    def get_backend(self) -> str:
        ...
    
    @disable_logging
    def __setattr__(self, key: str, value: Any) -> None:
        """
        Set attribute on this `BasePandasDataset`.

        Parameters
        ----------
        key : str
            The attribute name.
        value : Any
            The attribute value.

        Returns
        -------
        None
        """
        ...
    
    @disable_logging
    def __delattr__(self, name) -> None:
        """
        Delete attribute on this `BasePandasDataset`.

        Parameters
        ----------
        name : str
            The attribute name.

        Returns
        -------
        None
        """
        ...
    


