def noneish_string(string: str | None) -> str | None: ...
def snakify(string: str) -> str: ...
def unsnakify(string: str) -> str: ...
def kebabify(string: str) -> str: ...
def camel(string: str) -> str: ...
