def hllines(code, style): ...
def htlines(code, style): ...
def get_ansi_template():  # -> Any:
    ...
def get_html_template():  # -> Any:
    ...
def reform_code(annotation):  # -> Literal['']:

    ...

class Annotate:
    def __init__(self, function, signature=..., **kwargs) -> None: ...
