"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional
from . import xmlwriter

"""
This type stub file was generated by pyright.
"""
class Chart(xmlwriter.XMLwriter):
    """
    A class for writing the Excel XLSX Chart file.


    """
    def __init__(self) -> None:
        """
        Constructor.

        """
        ...
    
    def add_series(self, options: Optional[Dict[str, Any]] = ...) -> None:
        """
        Add a data series to a chart.

        Args:
            options:  A dictionary of chart series options.

        Returns:
            Nothing.

        """
        ...
    
    def set_x_axis(self, options: Dict[str, Any]) -> None:
        """
        Set the chart X axis options.

        Args:
            options:  A dictionary of axis options.

        Returns:
            Nothing.

        """
        ...
    
    def set_y_axis(self, options: Dict[str, Any]) -> None:
        """
        Set the chart Y axis options.

        Args:
            options: A dictionary of axis options.

        Returns:
            Nothing.

        """
        ...
    
    def set_x2_axis(self, options: Dict[str, Any]) -> None:
        """
        Set the chart secondary X axis options.

        Args:
            options: A dictionary of axis options.

        Returns:
            Nothing.

        """
        ...
    
    def set_y2_axis(self, options: Dict[str, Any]) -> None:
        """
        Set the chart secondary Y axis options.

        Args:
            options: A dictionary of axis options.

        Returns:
            Nothing.

        """
        ...
    
    def set_title(self, options: Optional[Dict[str, Any]] = ...) -> None:
        """
        Set the chart title options.

        Args:
            options: A dictionary of chart title options.

        Returns:
            Nothing.

        """
        ...
    
    def set_legend(self, options: Dict[str, Any]) -> None:
        """
        Set the chart legend options.

        Args:
            options: A dictionary of chart legend options.

        Returns:
            Nothing.
        """
        ...
    
    def set_plotarea(self, options: Dict[str, Any]) -> None:
        """
        Set the chart plot area options.

        Args:
            options: A dictionary of chart plot area options.

        Returns:
            Nothing.
        """
        ...
    
    def set_chartarea(self, options: Dict[str, Any]) -> None:
        """
        Set the chart area options.

        Args:
            options: A dictionary of chart area options.

        Returns:
            Nothing.
        """
        ...
    
    def set_style(self, style_id: int = ...) -> None:
        """
        Set the chart style type.

        Args:
            style_id: An int representing the chart style.

        Returns:
            Nothing.
        """
        ...
    
    def show_blanks_as(self, option: str) -> None:
        """
        Set the option for displaying blank data in a chart.

        Args:
            option: A string representing the display option.

        Returns:
            Nothing.
        """
        ...
    
    def show_na_as_empty_cell(self) -> None:
        """
        Display ``#N/A`` on charts as blank/empty cells.

        Args:
            None.

        Returns:
            Nothing.
        """
        ...
    
    def show_hidden_data(self) -> None:
        """
        Display data on charts from hidden rows or columns.

        Args:
            None.

        Returns:
            Nothing.
        """
        ...
    
    def set_size(self, options: Optional[Dict[str, Any]] = ...) -> None:
        """
        Set size or scale of the chart.

        Args:
            options: A dictionary of chart size options.

        Returns:
            Nothing.
        """
        ...
    
    def set_table(self, options: Optional[Dict[str, Any]] = ...) -> None:
        """
        Set properties for an axis data table.

        Args:
            options: A dictionary of axis table options.

        Returns:
            Nothing.

        """
        ...
    
    def set_up_down_bars(self, options: Optional[Dict[str, Any]] = ...) -> None:
        """
        Set properties for the chart up-down bars.

        Args:
            options: A dictionary of options.

        Returns:
            Nothing.

        """
        ...
    
    def set_drop_lines(self, options: Optional[Dict[str, Any]] = ...) -> None:
        """
        Set properties for the chart drop lines.

        Args:
            options: A dictionary of options.

        Returns:
            Nothing.

        """
        ...
    
    def set_high_low_lines(self, options: Optional[Dict[str, Any]] = ...) -> None:
        """
        Set properties for the chart high-low lines.

        Args:
            options: A dictionary of options.

        Returns:
            Nothing.

        """
        ...
    
    def combine(self, chart: Optional[Chart] = ...) -> None:
        """
        Create a combination chart with a secondary chart.

        Args:
            chart: The secondary chart to combine with the primary chart.

        Returns:
            Nothing.

        """
        ...
    


