"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional
from . import chart

"""
This type stub file was generated by pyright.
"""
class ChartArea(chart.Chart):
    """
    A class for writing the Excel XLSX Area charts.


    """
    def __init__(self, options: Optional[Dict[str, Any]] = ...) -> None:
        """
        Constructor.

        """
        ...
    


