"""
This type stub file was generated by pyright.
"""

from . import chart_pie

"""
This type stub file was generated by pyright.
"""
class ChartDoughnut(chart_pie.ChartPie):
    """
    A class for writing the Excel XLSX Doughnut charts.


    """
    def __init__(self) -> None:
        """
        Constructor.

        """
        ...
    
    def set_hole_size(self, size: int) -> None:
        """
        Set the Doughnut chart hole size.

        Args:
            size: 10 <= size <= 90.

        Returns:
            Nothing.

        """
        ...
    


