"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional
from xlsxwriter.chart import Chart
from . import worksheet

"""
This type stub file was generated by pyright.
"""
class Chartsheet(worksheet.Worksheet):
    """
    A class for writing the Excel XLSX Chartsheet file.


    """
    def __init__(self) -> None:
        """
        Constructor.

        """
        ...
    
    def set_chart(self, chart: Chart) -> Chart:
        """
        Set the chart object for the chartsheet.
        Args:
            chart:  Chart object.
        Returns:
            chart:  A reference to the chart object.
        """
        ...
    
    def protect(self, password: str = ..., options: Optional[Dict[str, Any]] = ...) -> None:
        """
        Set the password and protection options of the worksheet.

        Args:
            password: An optional password string.
            options:  A dictionary of worksheet objects to protect.

        Returns:
            Nothing.

        """
        ...
    


