"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict

"""
This type stub file was generated by pyright.
"""
class ChartTitle:
    """
    A class to represent an Excel chart title.

    This class encapsulates all title related properties and methods for the
    chart title and axis titles.
    """
    def __init__(self) -> None:
        """
        Initialize a ChartTitle instance.
        """
        ...
    
    def has_name(self) -> bool:
        """
        Check if the title has a text name set.

        Returns:
            True if name has been set.
        """
        ...
    
    def has_formula(self) -> bool:
        """
        Check if the title has a formula set.

        Returns:
            True if formula has been set.
        """
        ...
    
    def has_formatting(self) -> bool:
        """
        Check if the title has any formatting properties set.

        Returns:
            True if the title has line, fill, pattern, or gradient formatting.
        """
        ...
    
    def get_formatting(self) -> Dict[str, Any]:
        """
        Get a dictionary containing the formatting properties.

        Returns:
            A dictionary with line, fill, pattern, and gradient properties.
        """
        ...
    
    def is_hidden(self) -> bool:
        """
        Check if the title is explicitly hidden.

        Returns:
            True if title is hidden.
        """
        ...
    
    def __repr__(self) -> str:
        """
        Return a string representation of the ChartTitle.
        """
        ...
    


