"""
This type stub file was generated by pyright.
"""

from . import chart

"""
This type stub file was generated by pyright.
"""
class ChartPie(chart.Chart):
    """
    A class for writing the Excel XLSX Pie charts.


    """
    def __init__(self) -> None:
        """
        Constructor.

        """
        ...
    
    def set_rotation(self, rotation: int) -> None:
        """
        Set the Pie/Doughnut chart rotation: the angle of the first slice.

        Args:
            rotation: First segment angle: 0 <= rotation <= 360.

        Returns:
            Nothing.

        """
        ...
    


