"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict, Optional
from . import chart

"""
This type stub file was generated by pyright.
"""
class ChartScatter(chart.Chart):
    """
    A class for writing the Excel XLSX Scatter charts.


    """
    def __init__(self, options: Optional[Dict[str, Any]] = ...) -> None:
        """
        Constructor.

        """
        ...
    
    def combine(self, chart: Optional[chart.Chart] = ...) -> None:
        """
        Create a combination chart with a secondary chart.

        Note: Override parent method to add a warning.

        Args:
            chart: The secondary chart to combine with the primary chart.

        Returns:
            Nothing.

        """
        ...
    


