"""
This type stub file was generated by pyright.
"""

from typing import Dict, Optional, Union
from . import xmlwriter

"""
This type stub file was generated by pyright.
"""
class CommentType:
    """
    A class to represent a comment in an Excel worksheet.

    """
    def __init__(self, row: int, col: int, text: str, options: Optional[Dict[str, Union[str, int, float]]] = ...) -> None:
        """
        Initialize a Comment instance.

        Args:
            row (int): The row number of the comment.
            col (int): The column number of the comment.
            text (str): The text of the comment.
            options (dict): Additional options for the comment.
        """
        ...
    
    def set_offsets(self, row: int, col: int) -> None:
        """
        Set the default start cell and offsets for the comment. These are
        generally a fixed offset relative to the parent cell. However there are
        some edge cases for cells at the, well, edges.
        """
        ...
    


class Comments(xmlwriter.XMLwriter):
    """
    A class for writing the Excel XLSX Comments file.


    """
    def __init__(self) -> None:
        """
        Constructor.

        """
        ...
    


