"""
This type stub file was generated by pyright.
"""

from . import xmlwriter

"""
This type stub file was generated by pyright.
"""
APP_PACKAGE = ...
APP_DOCUMENT = ...
defaults = ...
overrides = ...
class ContentTypes(xmlwriter.XMLwriter):
    """
    A class for writing the Excel XLSX ContentTypes file.


    """
    def __init__(self) -> None:
        """
        Constructor.

        """
        ...
    


