"""
This type stub file was generated by pyright.
"""

from typing import Literal, Union
from xlsxwriter.color import Color
from . import xmlwriter

"""
This type stub file was generated by pyright.
"""
class Format(xmlwriter.XMLwriter):
    """
    A class for writing the Excel XLSX Format file.


    """
    def __init__(self, properties=..., xf_indices=..., dxf_indices=...) -> None:
        """
        Constructor.

        """
        ...
    
    def __repr__(self) -> str:
        """
        Return a string representation of the Format instance.
        """
        ...
    
    def set_font_name(self, font_name) -> None:
        """
        Set the Format font_name property such as 'Time New Roman'. The
        default Excel font is 'Calibri'.

        Args:
            font_name: String with the font name. No default.

        Returns:
            Nothing.

        """
        ...
    
    def set_font_size(self, font_size: int = ...) -> None:
        """
        Set the Format font_size property. The default Excel font size is 11.

        Args:
            font_size: Int with font size. No default.

        Returns:
            Nothing.

        """
        ...
    
    def set_font_color(self, font_color: Union[str, Color]) -> None:
        """
        Set the Format font_color property. The Excel default is black.

        Args:
            font_color: String with the font color. No default.

        Returns:
            Nothing.

        """
        ...
    
    def set_bold(self, bold: bool = ...) -> None:
        """
        Set the Format bold property.

        Args:
            bold: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_italic(self, italic: bool = ...) -> None:
        """
        Set the Format italic property.

        Args:
            italic: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_underline(self, underline: Literal[1, 2, 33, 34] = ...) -> None:
        """
        Set the Format underline property.

        Args:
            underline: Default is 1, single underline.

        Returns:
            Nothing.

        """
        ...
    
    def set_font_strikeout(self, font_strikeout: bool = ...) -> None:
        """
        Set the Format font_strikeout property.

        Args:
            font_strikeout: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_font_script(self, font_script: Literal[1, 2] = ...) -> None:
        """
        Set the Format font_script property.

        Args:
            font_script: Default is 1, superscript.

        Returns:
            Nothing.

        """
        ...
    
    def set_font_outline(self, font_outline: bool = ...) -> None:
        """
        Set the Format font_outline property.

        Args:
            font_outline: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_font_shadow(self, font_shadow: bool = ...) -> None:
        """
        Set the Format font_shadow property.

        Args:
            font_shadow: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_num_format(self, num_format: str) -> None:
        """
        Set the Format num_format property such as '#,##0'.

        Args:
            num_format: String representing the number format. No default.

        Returns:
            Nothing.

        """
        ...
    
    def set_locked(self, locked: bool = ...) -> None:
        """
        Set the Format locked property.

        Args:
            locked: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_hidden(self, hidden: bool = ...) -> None:
        """
        Set the Format hidden property.

        Args:
            hidden: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_align(self, alignment: Literal["left", "centre", "center", "right", "fill", "justify", "center_across", "centre_across", "distributed", "justify_distributed", "justify_distributed", "top", "vcentre", "vcenter", "bottom", "vjustify", "vdistributed",]) -> None:
        """
        Set the Format cell alignment.

        Args:
            alignment: String representing alignment. No default.

        Returns:
            Nothing.
        """
        ...
    
    def set_center_across(self, align_type: None = ...) -> None:
        """
        Set the Format center_across property.

        Returns:
            Nothing.

        """
        ...
    
    def set_text_wrap(self, text_wrap: bool = ...) -> None:
        """
        Set the Format text_wrap property.

        Args:
            text_wrap: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_rotation(self, rotation: int) -> None:
        """
        Set the Format rotation property.

        Args:
            rotation: Rotation angle. No default.

        Returns:
            Nothing.

        """
        ...
    
    def set_indent(self, indent: int = ...) -> None:
        """
        Set the Format indent property.

        Args:
            indent: Default is 1, first indentation level.

        Returns:
            Nothing.

        """
        ...
    
    def set_shrink(self, shrink: bool = ...) -> None:
        """
        Set the Format shrink property.

        Args:
            shrink: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_text_justlast(self, text_justlast: bool = ...) -> None:
        """
        Set the Format text_justlast property.

        Args:
            text_justlast: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_pattern(self, pattern: int = ...) -> None:
        """
        Set the Format pattern property.

        Args:
            pattern: Default is 1, solid fill.

        Returns:
            Nothing.

        """
        ...
    
    def set_bg_color(self, bg_color: Union[str, Color]) -> None:
        """
        Set the Format bg_color property.

        Args:
            bg_color: Background color. No default.

        Returns:
            Nothing.

        """
        ...
    
    def set_fg_color(self, fg_color: Union[str, Color]) -> None:
        """
        Set the Format fg_color property.

        Args:
            fg_color: Foreground color. No default.

        Returns:
            Nothing.

        """
        ...
    
    def set_border(self, style: int = ...) -> None:
        """
        Set the Format bottom property.

        Args:
            bottom: Default is 1, border type 1.

        Returns:
            Nothing.

        """
        ...
    
    def set_border_color(self, color: Union[str, Color]) -> None:
        """
        Set the Format bottom property.

        Args:
            color: Color string. No default.

        Returns:
            Nothing.

        """
        ...
    
    def set_bottom(self, bottom: int = ...) -> None:
        """
        Set the Format bottom property.

        Args:
            bottom: Default is 1, border type 1.

        Returns:
            Nothing.

        """
        ...
    
    def set_bottom_color(self, bottom_color: Union[str, Color]) -> None:
        """
        Set the Format bottom_color property.

        Args:
            bottom_color: Color string. No default.

        Returns:
            Nothing.

        """
        ...
    
    def set_diag_type(self, diag_type: Literal[1, 2, 3] = ...) -> None:
        """
        Set the Format diag_type property.

        Args:
            diag_type: Default is 1, border type 1.

        Returns:
            Nothing.

        """
        ...
    
    def set_left(self, left: int = ...) -> None:
        """
        Set the Format left property.

        Args:
            left: Default is 1, border type 1.

        Returns:
            Nothing.

        """
        ...
    
    def set_left_color(self, left_color: Union[str, Color]) -> None:
        """
        Set the Format left_color property.

        Args:
            left_color: Color string. No default.

        Returns:
            Nothing.

        """
        ...
    
    def set_right(self, right: int = ...) -> None:
        """
        Set the Format right property.

        Args:
            right: Default is 1, border type 1.

        Returns:
            Nothing.

        """
        ...
    
    def set_right_color(self, right_color: Union[str, Color]) -> None:
        """
        Set the Format right_color property.

        Args:
            right_color: Color string. No default.

        Returns:
            Nothing.

        """
        ...
    
    def set_top(self, top: int = ...) -> None:
        """
        Set the Format top property.

        Args:
            top: Default is 1, border type 1.

        Returns:
            Nothing.

        """
        ...
    
    def set_top_color(self, top_color: Union[str, Color]) -> None:
        """
        Set the Format top_color property.

        Args:
            top_color: Color string. No default.

        Returns:
            Nothing.

        """
        ...
    
    def set_diag_color(self, diag_color: Union[str, Color]) -> None:
        """
        Set the Format diag_color property.

        Args:
            diag_color: Color string. No default.

        Returns:
            Nothing.

        """
        ...
    
    def set_diag_border(self, diag_border: int = ...) -> None:
        """
        Set the Format diag_border property.

        Args:
            diag_border: Default is 1, border type 1.

        Returns:
            Nothing.

        """
        ...
    
    def set_quote_prefix(self, quote_prefix: bool = ...) -> None:
        """
        Set the Format quote prefix property.

        Args:
            quote_prefix: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_checkbox(self, checkbox: bool = ...) -> None:
        """
        Set the Format property to show a checkbox in a cell.

        This format property can be used with a cell that contains a boolean
        value to display it as a checkbox. This property isn't required very
        often and it is generally easier to create a checkbox using the
        ``worksheet.insert_checkbox()`` method.

        Args:
            checkbox: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_has_font(self, has_font: bool = ...) -> None:
        """
        Set the property to indicate the format has a font.

        Args:
            has_font: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_has_fill(self, has_fill: bool = ...) -> None:
        """
        Set the property to indicate the format has a fill.

        Args:
            has_fill: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_font_index(self, font_index: int) -> None:
        """
        Set the unique font index property.

        Args:
            font_index: The unique font index.

        Returns:
            Nothing.

        """
        ...
    
    def set_xf_index(self, xf_index: int) -> None:
        """
        Set the unique format index property.

        Args:
            xf_index: The unique Excel format index.

        Returns:
            Nothing.

        """
        ...
    
    def set_dxf_index(self, dxf_index: int) -> None:
        """
        Set the unique conditional format index property.

        Args:
            dxf_index: The unique Excel conditional format index.

        Returns:
            Nothing.

        """
        ...
    
    def set_num_format_index(self, num_format_index: int) -> None:
        """
        Set the number format_index property.

        Args:
            num_format_index: The unique number format index.

        Returns:
            Nothing.

        """
        ...
    
    def set_text_h_align(self, text_h_align: int) -> None:
        """
        Set the horizontal text alignment property.

        Args:
            text_h_align: Horizontal text alignment.

        Returns:
            Nothing.

        """
        ...
    
    def set_text_v_align(self, text_v_align: int) -> None:
        """
        Set the vertical text alignment property.

        Args:
            text_h_align: Vertical text alignment.

        Returns:
            Nothing.

        """
        ...
    
    def set_reading_order(self, direction: int = ...) -> None:
        """
        Set the reading order property.

        Args:
            direction: Default is 0, left to right.

        Returns:
            Nothing.

        """
        ...
    
    def set_valign(self, align: Literal["left", "centre", "center", "right", "fill", "justify", "center_across", "centre_across", "distributed", "justify_distributed", "justify_distributed", "top", "vcentre", "vcenter", "bottom", "vjustify", "vdistributed",]) -> None:
        """
        Set vertical cell alignment property.

        This is required by the constructor properties dict to differentiate
        between the vertical and horizontal properties.

        Args:
            align: Alignment property.

        Returns:
            Nothing.

        """
        ...
    
    def set_font_family(self, font_family: int) -> None:
        """
        Set the font family property.

        Args:
            font_family: Font family number.

        Returns:
            Nothing.

        """
        ...
    
    def set_font_charset(self, font_charset: int) -> None:
        """
        Set the font character set property.

        Args:
            font_charset: The font character set number.

        Returns:
            Nothing.

        """
        ...
    
    def set_font_scheme(self, font_scheme: int) -> None:
        """
        Set the font scheme property.

        Args:
            font_scheme: The font scheme.

        Returns:
            Nothing.

        """
        ...
    
    def set_font_condense(self, font_condense: int) -> None:
        """
        Set the font condense property.

        Args:
            font_condense: The font condense property.

        Returns:
            Nothing.

        """
        ...
    
    def set_font_extend(self, font_extend: int) -> None:
        """
        Set the font extend property.

        Args:
            font_extend: The font extend property.

        Returns:
            Nothing.

        """
        ...
    
    def set_theme(self, theme: int) -> None:
        """
        Set the theme property.

        Args:
            theme: Format theme.

        Returns:
            Nothing.

        """
        ...
    
    def set_hyperlink(self, hyperlink: bool = ...) -> None:
        """
        Set the properties for the hyperlink style.

        Args:
            hyperlink: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_color_indexed(self, color_index: Literal[0, 1]) -> None:
        """
        Set the color index property. Some fundamental format properties use an
        indexed color instead of a rbg or theme color.

        Args:
            color_index: Generally 0 or 1.

        Returns:
            Nothing.

        """
        ...
    
    def set_font_only(self, font_only: bool = ...) -> None:
        """
        Set property to indicate that the format is used for fonts only.

        Args:
            font_only: Default is True, turns property on.

        Returns:
            Nothing.

        """
        ...
    
    def set_font(self, font_name: str) -> None:
        """Deprecated: Use set_font_name() instead."""
        ...
    
    def set_size(self, font_size: int) -> None:
        """Deprecated: Use set_font_size() instead."""
        ...
    
    def set_color(self, font_color: Union[Color, str]) -> None:
        """Deprecated: Use set_font_color() instead."""
        ...
    


