"""
This type stub file was generated by pyright.
"""

from . import xmlwriter

"""
This type stub file was generated by pyright.
"""
SCHEMA_ROOT = ...
PACKAGE_SCHEMA = ...
DOCUMENT_SCHEMA = ...
class Relationships(xmlwriter.XMLwriter):
    """
    A class for writing the Excel XLSX Relationships file.


    """
    def __init__(self) -> None:
        """
        Constructor.

        """
        ...
    


