"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class Shape:
    """
    A class for to represent Excel XLSX shape objects.


    """
    def __init__(self, shape_type, name: str, options) -> None:
        """
        Constructor.

        """
        ...
    


