"""
This type stub file was generated by pyright.
"""

from . import xmlwriter

"""
This type stub file was generated by pyright.
"""
class Table(xmlwriter.XMLwriter):
    """
    A class for writing the Excel XLSX Table file.


    """
    def __init__(self) -> None:
        """
        Constructor.

        """
        ...
    


