"""
This type stub file was generated by pyright.
"""

from enum import Enum
from typing import Any, Dict, Optional

"""
This type stub file was generated by pyright.
"""
class UrlTypes(Enum):
    """
    Enum to represent different types of URLS.
    """
    UNKNOWN = ...
    URL = ...
    INTERNAL = ...
    EXTERNAL = ...


class Url:
    """
    A class to represent URLs in Excel.

    """
    MAX_URL_LEN = ...
    MAX_PARAMETER_LEN = ...
    def __init__(self, link: str) -> None:
        ...
    
    def __repr__(self) -> str:
        """
        Return a string representation of the Url instance.

        """
        ...
    
    @classmethod
    def from_options(cls, options: Dict[str, Any]) -> Optional[Url]:
        """
        For backward compatibility, convert the 'url' key and 'tip' keys in an
        options dictionary to a Url object, or return the Url object if already
        an instance.

        Args:
            options (dict): A dictionary that may contain a 'url' key.

        Returns:
            url: A Url object or None.

        """
        ...
    
    @property
    def text(self) -> str:
        """Get the alternative, user-friendly, text for the URL."""
        ...
    
    @text.setter
    def text(self, value: str) -> None:
        """Set the alternative, user-friendly, text for the URL."""
        ...
    
    @property
    def tip(self) -> str:
        """Get the screen tip for the URL."""
        ...
    
    @tip.setter
    def tip(self, value: str) -> None:
        """Set the screen tip for the URL."""
        ...
    


