"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
re_control_chars_1 = ...
re_control_chars_2 = ...
xml_escapes = ...
class XMLwriter:
    """
    Simple XML writer class.

    """
    def __init__(self) -> None:
        ...
    


