"""
This type stub file was generated by pyright.
"""

import pandas
from enum import Enum
from typing import Callable, TYPE_CHECKING
from .query_compiler import PandasQueryCompiler

"""Contains implementations for aggregation functions."""
if TYPE_CHECKING:
    ...
class CorrCovBuilder:
    """Responsible for building pandas query compiler's methods computing correlation and covariance matrices."""
    class Method(Enum):
        """Enum specifying what method to use (either CORR for correlation or COV for covariance)."""
        CORR = ...
        COV = ...
    
    
    @classmethod
    def build_corr_method(cls) -> Callable[[PandasQueryCompiler, str, int, bool], PandasQueryCompiler]:
        """
        Build a query compiler method computing the correlation matrix.

        Returns
        -------
        callable(qc: PandasQueryCompiler, method: str, min_periods: int, numeric_only: bool) -> PandasQueryCompiler
            A callable matching the ``BaseQueryCompiler.corr`` signature and computing the correlation matrix.
        """
        ...
    
    @classmethod
    def build_cov_method(cls) -> Callable[[PandasQueryCompiler, int, int], PandasQueryCompiler]:
        """
        Build a query compiler method computing the covariance matrix.

        Returns
        -------
        callable(qc: PandasQueryCompiler, min_periods: int, ddof: int) -> PandasQueryCompiler
            A callable matching the ``BaseQueryCompiler.cov`` signature and computing the covariance matrix.
        """
        ...
    


class _CorrCovKernels:
    """Holds kernel functions computing correlation/covariance matrices in a MapReduce manner."""
    @classmethod
    def map(cls, df: pandas.DataFrame, numeric_only: bool) -> pandas.DataFrame:
        """
        Perform the Map phase to compute the corr/cov matrix.

        In this kernel we compute all the required components to compute
        the correlation matrix at the reduce phase, the required components are:
            1. Matrix holding sums of pairwise multiplications between all columns
               defined as ``M[col1, col2] = sum(col1[i] * col2[i] for i in range(col_len))``
            2. Sum for each column (special case if there are NaN values)
            3. Sum of squares for each column (special case if there are NaN values)
            4. Number of values in each column (special case if there are NaN values)

        Parameters
        ----------
        df : pandas.DataFrame
            Partition to compute the aggregations for.
        numeric_only : bool
            Whether to only include numeric types.

        Returns
        -------
        pandas.DataFrame
            A MultiIndex columned DataFrame holding the described aggregation results for this
            specifix partition under the following keys: ``["mul", "sum", "pow2_sum", "count"]``
        """
        ...
    
    @classmethod
    def reduce(cls, df: pandas.DataFrame, min_periods: int, method: CorrCovBuilder.Method) -> pandas.DataFrame:
        """
        Perform the Reduce phase to compute the corr/cov matrix.

        Parameters
        ----------
        df : pandas.DataFrame
            A dataframe holding aggregations computed for each partition
            concatenated along the rows axis.
        min_periods : int
            Minimum number of observations required per pair of columns to have a valid result.
        method : CorrCovBuilder.Method
            Whether to build a correlation or a covariance matrix.

        Returns
        -------
        pandas.DataFrame
            Either correlation or covariance matrix.
        """
        ...
    


