"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from modin.core.storage_formats.pandas.query_compiler import PandasQueryCompiler

"""Contains implementations for Merge/Join."""
if TYPE_CHECKING:
    ...
class MergeImpl:
    """Provide implementations for merge/join."""
    @classmethod
    def range_partitioning_merge(cls, left, right, kwargs):
        """
        Execute merge using range-partitioning implementation.

        Parameters
        ----------
        left : PandasQueryCompiler
        right : PandasQueryCompiler
        kwargs : dict
            Keyword arguments for ``pandas.merge()`` function.

        Returns
        -------
        PandasQueryCompiler
        """
        ...
    
    @classmethod
    def row_axis_merge(cls, left: PandasQueryCompiler, right: PandasQueryCompiler, kwargs: dict) -> PandasQueryCompiler:
        """
        Execute merge using row-axis implementation.

        Parameters
        ----------
        left : PandasQueryCompiler
        right : PandasQueryCompiler
        kwargs : dict
            Keyword arguments for ``pandas.merge()`` function.

        Returns
        -------
        PandasQueryCompiler
        """
        ...
    


