import numpy as np
from numba import _devicearray
from numba.cuda.cudadrv import devices

"""
A CUDA ND Array is recognized by checking the __cuda_memory__ attribute
on the object.  If it exists and evaluate to True, it must define shape,
strides, dtype and size attributes similar to a NumPy ndarray.
"""
lru_cache = ...

def is_cuda_ndarray(obj):  # -> Any | bool:

    ...
def verify_cuda_ndarray_interface(obj):  # -> None:

    ...
def require_cuda_ndarray(obj):  # -> None:

    ...

class DeviceNDArrayBase(_devicearray.DeviceArray):
    __cuda_memory__ = ...
    __cuda_ndarray__ = ...
    def __init__(self, shape, strides, dtype, stream=..., gpu_data=...) -> None: ...
    @property
    def __cuda_array_interface__(self):  # -> dict[str, Any]:
        ...
    def bind(self, stream=...):  # -> Self:

        ...
    @property
    def T(self):  # -> Self:
        ...
    def transpose(self, axes=...):  # -> Self:
        ...
    @property
    def device_ctypes_pointer(self):  # -> c_void_p | Any:

        ...
    @devices.require_context
    def copy_to_device(self, ary, stream=...):  # -> None:

        ...
    @devices.require_context
    def copy_to_host(self, ary=..., stream=...):  # -> ndarray[_AnyShape, dtype[Any]] | _Array1D[signedinteger[_NBitByte]]:

        ...
    def split(self, section, stream=...):  # -> Generator[DeviceNDArray, Any, None]:

        ...
    def as_cuda_arg(self):  # -> Any | MemoryPointer:

        ...
    def get_ipc_handle(self):  # -> IpcArrayHandle:

        ...
    def squeeze(self, axis=..., stream=...):  # -> DeviceNDArray:

        ...
    def view(self, dtype):  # -> DeviceNDArray:

        ...
    @property
    def nbytes(self):  # -> int:
        ...

class DeviceRecord(DeviceNDArrayBase):
    def __init__(self, dtype, stream=..., gpu_data=...) -> None: ...
    @property
    def flags(self):  # -> dict[str, bool]:

        ...
    @devices.require_context
    def __getitem__(self, item):  # -> DeviceRecord | Any | DeviceNDArray:
        ...
    @devices.require_context
    def getitem(self, item, stream=...):  # -> DeviceRecord | Any | DeviceNDArray:

        ...
    @devices.require_context
    def __setitem__(self, key, value) -> None:  # -> None:
        ...
    @devices.require_context
    def setitem(self, key, value, stream=...):  # -> None:

        ...

class DeviceNDArray(DeviceNDArrayBase):
    def is_f_contiguous(self):  # -> bool:

        ...
    @property
    def flags(self):  # -> dict[str, bool]:

        ...
    def is_c_contiguous(self):  # -> bool:

        ...
    def __array__(self, dtype=...):  # -> ndarray[_AnyShape, dtype[Any]] | ndarray[tuple[int], dtype[signedinteger[_NBitByte]]]:

        ...
    def __len__(self) -> int:  # -> int:
        ...
    def reshape(self, *newshape, **kws):  # -> Self:

        ...
    def ravel(self, order=..., stream=...):  # -> Self:

        ...
    @devices.require_context
    def __getitem__(self, item):  # -> DeviceRecord | Any | Self:
        ...
    @devices.require_context
    def getitem(self, item, stream=...):  # -> DeviceRecord | Any | Self:

        ...
    @devices.require_context
    def __setitem__(self, key, value) -> None:  # -> None:
        ...
    @devices.require_context
    def setitem(self, key, value, stream=...):  # -> None:

        ...

class IpcArrayHandle:
    def __init__(self, ipc_handle, array_desc) -> None: ...
    def open(self):  # -> DeviceNDArray:

        ...
    def close(self):  # -> None:

        ...
    def __enter__(self):  # -> DeviceNDArray:
        ...
    def __exit__(self, type, value, traceback):  # -> None:
        ...

class MappedNDArray(DeviceNDArrayBase, np.ndarray):
    def device_setup(self, gpu_data, stream=...):  # -> None:
        ...

class ManagedNDArray(DeviceNDArrayBase, np.ndarray):
    def device_setup(self, gpu_data, stream=...):  # -> None:
        ...

def from_array_like(ary, stream=..., gpu_data=...):  # -> DeviceNDArray:

    ...
def from_record_like(rec, stream=..., gpu_data=...):  # -> DeviceRecord:

    ...
def array_core(ary): ...
def is_contiguous(ary):  # -> bool:

    ...

errmsg_contiguous_buffer = ...

def sentry_contiguous(ary):  # -> None:
    ...
def auto_device(
    obj, stream=..., copy=..., user_explicit=...
):  # -> tuple[Any, Literal[False]] | tuple[DeviceRecord | DeviceNDArray, Literal[True]]:

    ...
def check_array_compatibility(ary1, ary2):  # -> None:
    ...
