import asyncio
import contextlib
from abc import ABCMeta, abstractmethod

from numba import mviewbuf

from .error import CudaDriverError

"""
CUDA driver bridge implementation

NOTE:
The new driver implementation uses a *_PendingDeallocs* that help prevents a
crashing the system (particularly OSX) when the CUDA context is corrupted at
resource deallocation.  The old approach ties resource management directly
into the object destructor; thus, at corruption of the CUDA context,
subsequent deallocation could further corrupt the CUDA context and causes the
system to freeze in some cases.

"""
USE_NV_BINDING = ...
if USE_NV_BINDING:
    CU_STREAM_DEFAULT = ...
MIN_REQUIRED_CC = ...
SUPPORTS_IPC = ...
_py_decref = ...
_py_incref = ...

def make_logger():  # -> Logger:
    ...

class DeadMemoryError(RuntimeError): ...
class LinkerError(RuntimeError): ...

class CudaAPIError(CudaDriverError):
    def __init__(self, code, msg) -> None: ...

def locate_driver_and_loader():  # -> tuple[type[CDLL], list[Any | str] | list[str]]:
    ...
def load_driver(dlloader, candidates):  # -> tuple[Any, Any] | None:
    ...
def find_driver():  # -> CDLL:
    ...

DRIVER_NOT_FOUND_MSG = ...
DRIVER_LOAD_ERROR_MSG = ...
ERROR_MAP = ...

class Driver:
    _singleton = ...
    def __new__(cls):  # -> Self:
        ...
    def __init__(self) -> None: ...
    def ensure_initialized(self):  # -> None:
        ...
    @property
    def is_available(self):  # -> bool:
        ...
    def __getattr__(
        self, fname
    ):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any] | _Wrapped[Callable[..., Any], NoReturn, Callable[..., Any], None]:
        ...
    def get_device(self, devnum=...):  # -> Any:
        ...
    def get_device_count(self):  # -> Any | int | None:
        ...
    def list_devices(self):  # -> list[Any]:

        ...
    def reset(self):  # -> None:

        ...
    def pop_active_context(self):  # -> Any | cu_context | None:

        ...
    def get_active_context(self):  # -> _ActiveContext:

        ...
    def get_version(self):  # -> tuple[Any | int, Any | int]:

        ...

class _ActiveContext:
    _tls_cache = ...
    def __enter__(self):  # -> Self:
        ...
    def __exit__(self, exc_type, exc_val, exc_tb):  # -> None:
        ...
    def __bool__(self) -> bool:  # -> bool:

        ...

    __nonzero__ = ...

driver = ...
DEVICE_ATTRIBUTES = ...

class Device:
    @classmethod
    def from_identity(cls, identity):  # -> Any:

        ...
    def __init__(self, devnum) -> None: ...
    def get_device_identity(self):  # -> dict[str, Any | int | None]:
        ...
    def __getattr__(self, attr):  # -> Any | int | None:

        ...
    def __hash__(self) -> int: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def get_primary_context(self):  # -> Context:

        ...
    def release_primary_context(self):  # -> None:

        ...
    def reset(self):  # -> None:
        ...
    @property
    def supports_float16(self):  # -> bool:
        ...

def met_requirement_for_device(device):  # -> None:
    ...

class BaseCUDAMemoryManager(metaclass=ABCMeta):
    def __init__(self, *args, **kwargs) -> None: ...
    @abstractmethod
    def memalloc(self, size):  # -> None:

        ...
    @abstractmethod
    def memhostalloc(self, size, mapped, portable, wc):  # -> None:

        ...
    @abstractmethod
    def mempin(self, owner, pointer, size, mapped):  # -> None:

        ...
    @abstractmethod
    def initialize(self):  # -> None:

        ...
    @abstractmethod
    def get_ipc_handle(self, memory):  # -> None:

        ...
    @abstractmethod
    def get_memory_info(self):  # -> None:

        ...
    @abstractmethod
    def reset(self):  # -> None:

        ...
    @abstractmethod
    def defer_cleanup(self):  # -> None:

        ...
    @property
    @abstractmethod
    def interface_version(self):  # -> None:

        ...

class HostOnlyCUDAMemoryManager(BaseCUDAMemoryManager):
    def __init__(self, *args, **kwargs) -> None: ...
    def memhostalloc(self, size, mapped=..., portable=..., wc=...):  # -> MappedOwnedPointer | PinnedMemory:

        ...
    def mempin(self, owner, pointer, size, mapped=...):  # -> MappedOwnedPointer | PinnedMemory:

        ...
    def memallocmanaged(self, size, attach_global):  # -> ManagedOwnedPointer:
        ...
    def reset(self):  # -> None:

        ...
    @contextlib.contextmanager
    def defer_cleanup(self):  # -> Generator[None, Any, None]:

        ...

class GetIpcHandleMixin:
    def get_ipc_handle(self, memory):  # -> IpcHandle:

        ...

class NumbaCUDAMemoryManager(GetIpcHandleMixin, HostOnlyCUDAMemoryManager):
    def initialize(self):  # -> None:
        ...
    def memalloc(self, size):  # -> OwnedPointer:
        ...
    def get_memory_info(self):  # -> MemoryInfo:
        ...
    @property
    def interface_version(self):  # -> Literal[1]:
        ...

_SUPPORTED_EMM_INTERFACE_VERSION = ...
_memory_manager = ...

def set_memory_manager(mm_plugin):  # -> None:

    ...

class _SizeNotSet(int):
    def __new__(cls, *args, **kwargs):  # -> Self:
        ...

_SizeNotSet = ...

class _PendingDeallocs:
    def __init__(self, capacity=...) -> None: ...
    def add_item(self, dtor, handle, size=...):  # -> None:

        ...
    def clear(self):  # -> None:

        ...
    @contextlib.contextmanager
    def disable(self):  # -> Generator[None, Any, None]:

        ...
    @property
    def is_disabled(self):  # -> bool:
        ...
    def __len__(self) -> int:  # -> int:

        ...

MemoryInfo = ...

class Context:
    def __init__(self, device, handle) -> None: ...
    def reset(self):  # -> None:

        ...
    def get_memory_info(self):  # -> MemoryInfo:

        ...
    def get_active_blocks_per_multiprocessor(self, func, blocksize, memsize, flags=...):  # -> Any | int | None:

        ...
    def get_max_potential_block_size(self, func, b2d_func, memsize, blocksizelimit, flags=...):  # -> Any | tuple[int, int] | None:

        ...
    def prepare_for_use(self):  # -> None:

        ...
    def push(self):  # -> None:

        ...
    def pop(self):  # -> None:

        ...
    def memalloc(self, bytesize):  # -> OwnedPointer:
        ...
    def memallocmanaged(self, bytesize, attach_global=...):  # -> ManagedOwnedPointer:
        ...
    def memhostalloc(self, bytesize, mapped=..., portable=..., wc=...):  # -> MappedOwnedPointer | PinnedMemory:
        ...
    def mempin(self, owner, pointer, size, mapped=...):  # -> MappedOwnedPointer | PinnedMemory:
        ...
    def get_ipc_handle(self, memory):  # -> IpcHandle:

        ...
    def open_ipc_handle(self, handle, size):  # -> MemoryPointer:
        ...
    def enable_peer_access(self, peer_context, flags=...):  # -> None:

        ...
    def can_access_peer(self, peer_device):  # -> bool:

        ...
    def create_module_ptx(self, ptx):  # -> Any:
        ...
    def create_module_image(self, image):  # -> Any:
        ...
    def unload_module(self, module):  # -> None:
        ...
    def get_default_stream(self):  # -> Stream:
        ...
    def get_legacy_default_stream(self):  # -> Stream:
        ...
    def get_per_thread_default_stream(self):  # -> Stream:
        ...
    def create_stream(self):  # -> Stream:
        ...
    def create_external_stream(self, ptr):  # -> Stream:
        ...
    def create_event(self, timing=...):  # -> Event:
        ...
    def synchronize(self):  # -> None:
        ...
    @contextlib.contextmanager
    def defer_cleanup(self):  # -> Generator[None, Any, None]:
        ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...

def load_module_image(context, image):  # -> CudaPythonModule | CtypesModule:

    ...
def load_module_image_ctypes(context, image):  # -> CtypesModule:
    ...
def load_module_image_cuda_python(context, image):  # -> CudaPythonModule:

    ...

class _CudaIpcImpl:
    def __init__(self, parent) -> None: ...
    def open(self, context): ...
    def close(self):  # -> None:
        ...

class _StagedIpcImpl:
    def __init__(self, parent, source_info) -> None: ...
    def open(self, context): ...
    def close(self):  # -> None:
        ...

class IpcHandle:
    def __init__(self, base, handle, size, source_info=..., offset=...) -> None: ...
    def can_access_peer(self, context):  # -> Literal[True]:

        ...
    def open_staged(self, context): ...
    def open_direct(self, context): ...
    def open(self, context): ...
    def open_array(self, context, shape, dtype, strides=...):  # -> DeviceNDArray:

        ...
    def close(self):  # -> None:
        ...
    def __reduce__(self):  # -> tuple[Callable[..., Any], tuple[type[Self], Any | tuple[Any, ...], Any, Any | None, int]]:
        ...

class MemoryPointer:
    __cuda_memory__ = ...
    def __init__(self, context, pointer, size, owner=..., finalizer=...) -> None: ...
    @property
    def owner(self):  # -> Self:
        ...
    def own(self):  # -> OwnedPointer:
        ...
    def free(self):  # -> None:

        ...
    def memset(self, byte, count=..., stream=...):  # -> None:
        ...
    def view(self, start, stop=...):  # -> OwnedPointer | Self | MemoryPointer:
        ...
    @property
    def device_ctypes_pointer(self):  # -> Any:
        ...
    @property
    def device_pointer_value(self):  # -> int | None:
        ...

class AutoFreePointer(MemoryPointer):
    def __init__(self, *args, **kwargs) -> None: ...

class MappedMemory(AutoFreePointer):
    __cuda_memory__ = ...
    def __init__(self, context, pointer, size, owner=..., finalizer=...) -> None: ...
    def own(self):  # -> MappedOwnedPointer:
        ...

class PinnedMemory(mviewbuf.MemAlloc):
    def __init__(self, context, pointer, size, owner=..., finalizer=...) -> None: ...
    def own(self):  # -> Self:
        ...

class ManagedMemory(AutoFreePointer):
    __cuda_memory__ = ...
    def __init__(self, context, pointer, size, owner=..., finalizer=...) -> None: ...
    def own(self):  # -> ManagedOwnedPointer:
        ...

class OwnedPointer:
    def __init__(self, memptr, view=...) -> None: ...
    def __getattr__(self, fname):  # -> Any:

        ...

class MappedOwnedPointer(OwnedPointer, mviewbuf.MemAlloc): ...
class ManagedOwnedPointer(OwnedPointer, mviewbuf.MemAlloc): ...

class Stream:
    def __init__(self, context, handle, finalizer, external=...) -> None: ...
    def __int__(self) -> int: ...
    def synchronize(self):  # -> None:

        ...
    @contextlib.contextmanager
    def auto_synchronize(self):  # -> Generator[Self, Any, None]:

        ...
    def add_callback(self, callback, arg=...):  # -> None:

        ...
    def async_done(self) -> asyncio.futures.Future: ...

class Event:
    def __init__(self, context, handle, finalizer=...) -> None: ...
    def query(self):  # -> bool:

        ...
    def record(self, stream=...):  # -> None:

        ...
    def synchronize(self):  # -> None:

        ...
    def wait(self, stream=...):  # -> None:

        ...
    def elapsed_time(self, evtend):  # -> Any | float | None:
        ...

def event_elapsed_time(evtstart, evtend):  # -> Any | float | None:

    ...

class Module(metaclass=ABCMeta):
    def __init__(self, context, handle, info_log, finalizer=...) -> None: ...
    def unload(self):  # -> None:

        ...
    @abstractmethod
    def get_function(self, name):  # -> None:

        ...
    @abstractmethod
    def get_global_symbol(self, name):  # -> None:

        ...

class CtypesModule(Module):
    def get_function(self, name):  # -> CtypesFunction:
        ...
    def get_global_symbol(self, name):  # -> tuple[MemoryPointer, int]:
        ...

class CudaPythonModule(Module):
    def get_function(self, name):  # -> CudaPythonFunction:
        ...
    def get_global_symbol(self, name):  # -> tuple[MemoryPointer, Any]:
        ...

FuncAttr = ...

class Function(metaclass=ABCMeta):
    griddim = ...
    blockdim = ...
    stream = ...
    sharedmem = ...
    def __init__(self, module, handle, name) -> None: ...
    @property
    def device(self): ...
    @abstractmethod
    def cache_config(self, prefer_equal=..., prefer_cache=..., prefer_shared=...):  # -> None:

        ...
    @abstractmethod
    def read_func_attr(self, attrid):  # -> None:

        ...
    @abstractmethod
    def read_func_attr_all(self):  # -> None:

        ...

class CtypesFunction(Function):
    def cache_config(self, prefer_equal=..., prefer_cache=..., prefer_shared=...):  # -> None:
        ...
    def read_func_attr(self, attrid):  # -> int:
        ...
    def read_func_attr_all(self):  # -> FuncAttr:
        ...

class CudaPythonFunction(Function):
    def cache_config(self, prefer_equal=..., prefer_cache=..., prefer_shared=...):  # -> None:
        ...
    def read_func_attr(self, attrid):  # -> Any | None:
        ...
    def read_func_attr_all(self):  # -> FuncAttr:
        ...

def launch_kernel(cufunc_handle, gx, gy, gz, bx, by, bz, sharedmem, hstream, args, cooperative=...):  # -> None:
    ...

if USE_NV_BINDING:
    jitty = ...
    FILE_EXTENSION_MAP = ...
else:
    FILE_EXTENSION_MAP = ...

class Linker(metaclass=ABCMeta):
    @classmethod
    def new(cls, max_registers=..., lineinfo=..., cc=...):  # -> MVCLinker | CudaPythonLinker | CtypesLinker:
        ...
    @abstractmethod
    def __init__(self, max_registers, lineinfo, cc) -> None: ...
    @property
    @abstractmethod
    def info_log(self):  # -> None:

        ...
    @property
    @abstractmethod
    def error_log(self):  # -> None:

        ...
    @abstractmethod
    def add_ptx(self, ptx, name):  # -> None:

        ...
    def add_cu(self, cu, name):  # -> None:

        ...
    @abstractmethod
    def add_file(self, path, kind):  # -> None:

        ...
    def add_cu_file(self, path):  # -> None:
        ...
    def add_file_guess_ext(self, path):  # -> None:

        ...
    @abstractmethod
    def complete(self):  # -> None:

        ...

_MVC_ERROR_MESSAGE = ...

class MVCLinker(Linker):
    def __init__(self, max_registers=..., lineinfo=..., cc=...) -> None: ...
    @property
    def info_log(self): ...
    @property
    def error_log(self): ...
    def add_ptx(self, ptx, name=...):  # -> None:
        ...
    def add_file(self, path, kind):  # -> None:
        ...
    def complete(self): ...

class CtypesLinker(Linker):
    def __init__(self, max_registers=..., lineinfo=..., cc=...) -> None: ...
    @property
    def info_log(self): ...
    @property
    def error_log(self): ...
    def add_ptx(self, ptx, name=...):  # -> None:
        ...
    def add_file(self, path, kind):  # -> None:
        ...
    def complete(self):  # -> bytes:
        ...

class CudaPythonLinker(Linker):
    def __init__(self, max_registers=..., lineinfo=..., cc=...) -> None: ...
    @property
    def info_log(self):  # -> str:
        ...
    @property
    def error_log(self):  # -> str:
        ...
    def add_ptx(self, ptx, name=...):  # -> None:
        ...
    def add_file(self, path, kind):  # -> None:
        ...
    def complete(self):  # -> bytes:
        ...

def get_devptr_for_active_ctx(ptr):  # -> Any | cu_device_ptr | None:

    ...
def device_extents(devmem):  # -> tuple[Any, Any] | tuple[int, int]:

    ...
def device_memory_size(devmem):  # -> int | Any:

    ...
def host_pointer(obj, readonly=...):  # -> int:

    ...
def host_memory_extents(obj): ...
def memory_size_from_info(shape, strides, itemsize): ...
def host_memory_size(obj): ...
def device_pointer(obj):  # -> int | None:

    ...
def device_ctypes_pointer(obj):  # -> c_void_p:

    ...
def is_device_memory(obj):  # -> Any | bool:

    ...
def require_device_memory(obj):  # -> None:

    ...
def device_memory_depends(devmem, *objs):  # -> None:

    ...
def host_to_device(dst, src, size, stream=...):  # -> None:

    ...
def device_to_host(dst, src, size, stream=...):  # -> None:

    ...
def device_to_device(dst, src, size, stream=...):  # -> None:

    ...
def device_memset(dst, val, size, stream=...):  # -> None:

    ...
def profile_start():  # -> None:

    ...
def profile_stop():  # -> None:

    ...
@contextlib.contextmanager
def profiling():  # -> Generator[None, Any, None]:

    ...
def get_version():  # -> tuple[Any | int, Any | int]:

    ...
