Extent = ...
attempt_nocopy_reshape = ...

class Dim:
    __slots__ = ...
    def __init__(self, start, stop, size, stride, single) -> None: ...
    def __getitem__(self, item):  # -> Dim:
        ...
    def get_offset(self, idx): ...
    def normalize(self, base):  # -> Dim:
        ...
    def copy(self, start=..., stop=..., size=..., stride=..., single=...):  # -> Dim:
        ...
    def is_contiguous(self, itemsize): ...

def compute_index(indices, dims):  # -> int:
    ...

class Element:
    is_array = ...
    def __init__(self, extent) -> None: ...
    def iter_contiguous_extent(self):  # -> Generator[Any, Any, None]:
        ...

class Array:
    is_array = ...
    @classmethod
    def from_desc(cls, offset, shape, strides, itemsize):  # -> Self:
        ...
    def __init__(self, dims, itemsize) -> None: ...
    def __getitem__(self, item):  # -> Array | Element:
        ...
    @property
    def is_c_contig(self):  # -> bool:
        ...
    @property
    def is_f_contig(self):  # -> bool:
        ...
    def iter_contiguous_extent(self):  # -> Generator[Extent | tuple[Any, Any] | tuple[int, int], Any, None]:

        ...
    def reshape(self, *newdims, **kws):  # -> tuple[Self, None] | tuple[Self, list[Extent | tuple[Any, Any] | tuple[int, int]]]:
        ...
    def squeeze(self, axis=...):  # -> tuple[Self, list[Extent | tuple[Any, Any] | tuple[int, int]]]:
        ...
    def ravel(self, order=...):  # -> tuple[Self, list[Extent | tuple[Any, Any] | tuple[int, int]]]:
        ...

def iter_strides_f_contig(arr, shape=...):  # -> Generator[Any, Any, None]:

    ...
def iter_strides_c_contig(arr, shape=...):  # -> Generator[Any, Any, None]:

    ...
def is_element_indexing(item, ndim):  # -> bool:
    ...
