from ctypes import c_int, c_void_p
from enum import IntEnum

nvrtc_program = c_void_p
nvrtc_result = c_int

class NvrtcResult(IntEnum):
    NVRTC_SUCCESS = ...
    NVRTC_ERROR_OUT_OF_MEMORY = ...
    NVRTC_ERROR_PROGRAM_CREATION_FAILURE = ...
    NVRTC_ERROR_INVALID_INPUT = ...
    NVRTC_ERROR_INVALID_PROGRAM = ...
    NVRTC_ERROR_INVALID_OPTION = ...
    NVRTC_ERROR_COMPILATION = ...
    NVRTC_ERROR_BUILTIN_OPERATION_FAILURE = ...
    NVRTC_ERROR_NO_NAME_EXPRESSIONS_AFTER_COMPILATION = ...
    NVRTC_ERROR_NO_LOWERED_NAMES_BEFORE_COMPILATION = ...
    NVRTC_ERROR_NAME_EXPRESSION_NOT_VALID = ...
    NVRTC_ERROR_INTERNAL_ERROR = ...

_nvrtc_lock = ...

class NvrtcProgram:
    def __init__(self, nvrtc, handle) -> None: ...
    @property
    def handle(self):  # -> Any:
        ...
    def __del__(self) -> None:  # -> None:
        ...

class NVRTC:
    _PROTOTYPES = ...
    __INSTANCE = ...
    def __new__(cls):  # -> Self:
        ...
    def get_version(self):  # -> tuple[int, int]:

        ...
    def create_program(self, src, name):  # -> NvrtcProgram:

        ...
    def compile_program(self, program, options):  # -> bool:

        ...
    def destroy_program(self, program):  # -> None:

        ...
    def get_compile_log(self, program):  # -> Any:

        ...
    def get_ptx(self, program):  # -> Any:

        ...

def compile(src, name, cc):  # -> tuple[Any, Any]:

    ...
