from ctypes import c_int, c_void_p

"""
This is a direct translation of nvvm.h
"""
logger = ...
ADDRSPACE_GENERIC = ...
ADDRSPACE_GLOBAL = ...
ADDRSPACE_SHARED = ...
ADDRSPACE_CONSTANT = ...
ADDRSPACE_LOCAL = ...
nvvm_program = c_void_p
nvvm_result = c_int
RESULT_CODE_NAMES = ...
_datalayout_original = ...
_datalayout_i128 = ...

def is_available():  # -> bool:

    ...

_nvvm_lock = ...

class NVVM:
    _PROTOTYPES = ...
    __INSTANCE = ...
    def __new__(cls):  # -> Self:
        ...
    def __init__(self) -> None: ...
    @property
    def data_layout(self):  # -> str:
        ...
    @property
    def supported_ccs(self):  # -> tuple[()] | tuple[tuple[int, int], ...]:
        ...
    def get_version(self):  # -> tuple[int, int]:
        ...
    def get_ir_version(self):  # -> tuple[int, int, int, int]:
        ...
    def check_error(self, error, msg, exit=...):  # -> None:
        ...

class CompilationUnit:
    def __init__(self) -> None: ...
    def __del__(self) -> None:  # -> None:
        ...
    def add_module(self, buffer):  # -> None:

        ...
    def lazy_add_module(self, buffer):  # -> None:

        ...
    def compile(self, **options):  # -> list[Any]:

        ...
    def get_log(self):  # -> Any | Literal['']:
        ...

COMPUTE_CAPABILITIES = ...
CTK_SUPPORTED = ...

def ccs_supported_by_ctk(ctk_version):  # -> tuple[tuple[int, int], ...]:
    ...
def get_supported_ccs():  # -> tuple[()] | tuple[tuple[int, int], ...]:
    ...
def find_closest_arch(mycc):  # -> tuple[int, int]:

    ...
def get_arch_option(major, minor):  # -> str:

    ...

MISSING_LIBDEVICE_FILE_MSG = ...

class LibDevice:
    _cache_ = ...
    def __init__(self) -> None: ...
    def get(self):  # -> bytes:
        ...

cas_nvvm = ...
ir_numba_atomic_binary_template = ...
ir_numba_atomic_inc_template = ...
ir_numba_atomic_dec_template = ...
ir_numba_atomic_minmax_template = ...

def ir_cas(Ti):  # -> str:
    ...
def ir_numba_atomic_binary(T, Ti, OP, FUNC):  # -> str:
    ...
def ir_numba_atomic_minmax(T, Ti, NAN, OP, PTR_OR_VAL, FUNC):  # -> str:
    ...
def ir_numba_atomic_inc(T, Tu):  # -> str:
    ...
def ir_numba_atomic_dec(T, Tu):  # -> str:
    ...
def llvm_replace(llvmir):  # -> LiteralString:
    ...
def compile_ir(llvmir, **opts):  # -> list[Any]:
    ...

re_attributes_def = ...

def llvm140_to_70_ir(ir):  # -> LiteralString:

    ...
def set_cuda_kernel(function):  # -> None:

    ...
def add_ir_version(mod):  # -> None:

    ...
