"""
This type stub file was generated by pyright.
"""

from plotly.basedatatypes import BaseTraceHierarchyType as _BaseTraceHierarchyType

"""
This type stub file was generated by pyright.
"""
class Unselected(_BaseTraceHierarchyType):
    _parent_path_str = ...
    _path_str = ...
    _valid_props = ...
    @property
    def line(self):
        """
        The 'line' property is an instance of Line
        that may be specified as:
          - An instance of :class:`plotly.graph_objs.parcoords.unselected.Line`
          - A dict of string/value properties that will be passed
            to the Line constructor

        Returns
        -------
        plotly.graph_objs.parcoords.unselected.Line
        """
        ...
    
    @line.setter
    def line(self, val):
        ...
    
    def __init__(self, arg=..., line=..., **kwargs) -> None:
        """
        Construct a new Unselected object

        Parameters
        ----------
        arg
            dict of properties compatible with this constructor or
            an instance of
            :class:`plotly.graph_objs.parcoords.Unselected`
        line
            :class:`plotly.graph_objects.parcoords.unselected.Line`
            instance or dict with compatible properties

        Returns
        -------
        Unselected
        """
        ...
    


