"""
This type stub file was generated by pyright.
"""

"""The module holds utility and initialization routines for Modin on Ray."""
_OBJECT_STORE_TO_SYSTEM_MEMORY_RATIO = ...
_MAC_OBJECT_STORE_LIMIT_BYTES = ...
_RAY_IGNORE_UNHANDLED_ERRORS_VAR = ...
ObjectIDType = ...
def initialize_ray(override_is_cluster=..., override_redis_address: str = ..., override_redis_password: str = ...): # -> None:
    """
    Initialize Ray based on parameters, ``modin.config`` variables and internal defaults.

    Parameters
    ----------
    override_is_cluster : bool, default: False
        Whether to override the detection of Modin being run in a cluster
        and always assume this runs on cluster head node.
        This also overrides Ray worker detection and always runs the initialization
        function (runs from main thread only by default).
        If not specified, ``modin.config.IsRayCluster`` variable is used.
    override_redis_address : str, optional
        What Redis address to connect to when running in Ray cluster.
        If not specified, ``modin.config.RayRedisAddress`` is used.
    override_redis_password : str, optional
        What password to use when connecting to Redis.
        If not specified, ``modin.config.RayRedisPassword`` is used.
    """
    ...

def deserialize(obj): # -> List[Any] | dict[Any, Any]:
    """
    Deserialize a Ray object.

    Parameters
    ----------
    obj : ObjectIDType, iterable of ObjectIDType, or mapping of keys to ObjectIDTypes
        Object(s) to deserialize.

    Returns
    -------
    obj
        The deserialized object.
    """
    ...

