import enum

class Conversion(enum.IntEnum):
    exact = ...
    promote = ...
    safe = ...
    unsafe = ...
    nil = ...

class CastSet:
    def __init__(self) -> None: ...
    def insert(self, to, rel): ...
    def items(self):  # -> dict_items[Any, Any]:
        ...
    def get(self, item): ...
    def __len__(self) -> int:  # -> int:
        ...
    def __contains__(self, item) -> bool:  # -> bool:
        ...
    def __iter__(self):  # -> Iterator[Any]:
        ...
    def __getitem__(self, item): ...

class TypeGraph:
    def __init__(self, callback=...) -> None: ...
    def get(self, ty):  # -> CastSet:
        ...
    def propagate(self, a, b, baserel):  # -> None:
        ...
    def insert_rule(self, a, b, rel):  # -> None:
        ...
    def promote(self, a, b):  # -> None:
        ...
    def safe(self, a, b):  # -> None:
        ...
    def unsafe(self, a, b):  # -> None:
        ...
