class MatplotlibTableConverter:
    def __init__(self, fontsize=..., encode_base64=..., crop_top=..., for_document=..., savefig_dpi=..., format=...) -> None: ...
    def parse_html(self, tree):  # -> tuple[list[Any], int]:
        ...
    def get_text_align(self, element):  # -> Literal['left', 'right', 'center'] | None:
        ...
    def parse_into_rows(self, tree):  # -> tuple[list[Any], int]:
        ...
    def get_text_width(self, text, weight=...):  # -> float:
        ...
    def get_all_text_widths(self, rows):  # -> ndarray[_AnyShape, dtype[Any]]:
        ...
    def calculate_col_widths(self):  # -> list[Any]:
        ...
    def wrap_col(self, idx, col_widths, mult):  # -> list[Any]:
        ...
    def get_row_heights(self):  # -> list[Any]:
        ...
    def print_table(self):  # -> str | bytes:
        ...
    def run(self, html):  # -> str | bytes:
        ...
