import contextlib
import os
import unittest
from functools import cached_property

from numba.core.compiler import CompilerBase

"""
Assorted utilities for use in tests.
"""
enable_pyobj_flags = ...
force_pyobj_flags = ...
no_pyobj_flags = ...
nrt_flags = ...
tag = ...
always_test = ...
_32bit = ...
is_parfors_unsupported = ...
skip_parfors_unsupported = ...
skip_unless_py10_or_later = ...
skip_unless_py10 = ...
skip_unless_py312 = ...
skip_if_py313plus_on_windows = ...
skip_if_py314 = ...
skip_if_linux_aarch64 = ...
skip_if_32bit = ...
IS_NUMPY_2 = ...
skip_if_numpy_2 = ...
REDUCED_TESTING = ...
skip_if_reduced_testing = ...
_free_threading = ...
skip_if_freethreading = ...

def expected_failure_py311(fn): ...
def expected_failure_py312(fn): ...
def expected_failure_py313(fn): ...
def expected_failure_py314(fn): ...
def expected_failure_np2(fn): ...

_msg = ...
skip_unless_scipy = ...
skip_unless_cffi = ...
_lnx_reason = ...
linux_only = ...
_win_reason = ...
windows_only = ...
_is_armv7l = ...
disabled_test = ...
skip_ppc64le_issue4563 = ...
has_typeguard = ...
skip_unless_typeguard = ...
skip_if_typeguard = ...
skip_ppc64le_issue6465 = ...
skip_ppc64le_invalid_ctr_loop = ...
_uname = ...
IS_MACOS = ...
skip_macos_fenv_errors = ...
IS_MACOS_ARM64 = ...
has_lapack = ...
needs_lapack = ...
has_blas = ...
needs_blas = ...
_exec_cond = ...
needs_subprocess = ...
has_setuptools = ...
needs_setuptools = ...

def ignore_internal_warnings():  # -> None:

    ...

class TestCase(unittest.TestCase):
    longMessage = ...
    @cached_property
    def random(self):  # -> RandomState:
        ...
    def reset_module_warnings(self, module):  # -> None:

        ...
    @contextlib.contextmanager
    def assertTypingError(
        self,
    ):  # -> Generator[_AssertRaisesContext[LoweringError | TypingError | TypeError | NotImplementedError], Any, None]:

        ...
    @contextlib.contextmanager
    def assertRefCount(self, *objects):  # -> Generator[None, Any, None]:

        ...
    def assertRefCountEqual(self, *objects):  # -> None:
        ...
    @contextlib.contextmanager
    def assertNoNRTLeak(self):  # -> Generator[None, Any, None]:

        ...

    _bool_types = ...
    _exact_typesets = ...
    _approx_typesets = ...
    _sequence_typesets = ...
    _float_types = ...
    _complex_types = ...
    def assertStridesEqual(self, first, second):  # -> None:

        ...
    def assertPreciseEqual(self, first, second, prec=..., ulps=..., msg=..., ignore_sign_on_zero=..., abs_tol=...):  # -> None:

        ...
    def subprocess_test_runner(
        self, test_module, test_class=..., test_name=..., envvars=..., timeout=..., flags=..., _subproc_test_env=...
    ):  # -> CompletedProcess[str]:

        ...
    def run_test_in_subprocess(self=..., timeout=..., envvars=...):  # -> Callable[..., None] | Callable[..., Callable[..., None]]:

        ...
    def make_dummy_type(self) -> None:  # -> tuple[type[Dummy], type[_]]:

        ...
    def skip_if_no_external_compiler(self):  # -> None:

        ...

class SerialMixin:
    _numba_parallel_test_ = ...

@contextlib.contextmanager
def override_config(name, value):  # -> Generator[None, Any, None]:

    ...
@contextlib.contextmanager
def override_env_config(name, value):  # -> Generator[None, Any, None]:

    ...
def compile_function(name, code, globs): ...

_trashcan_dir = ...
if os.name == "nt": ...
else:
    _trashcan_dir = ...
_trashcan_timeout = ...

def temp_directory(prefix):  # -> str:

    ...
def import_dynamic(modname):  # -> ModuleType:

    ...
@contextlib.contextmanager
def captured_output(stream_name):  # -> Generator[Any, Any, None]:

    ...
def captured_stdout():  # -> _GeneratorContextManager[Any, None, None]:

    ...
def captured_stderr():  # -> _GeneratorContextManager[Any, None, None]:

    ...
@contextlib.contextmanager
def capture_cache_log():  # -> Generator[Any, Any, None]:
    ...

class EnableNRTStatsMixin:
    def setUp(self):  # -> None:
        ...
    def tearDown(self):  # -> None:
        ...

class MemoryLeak:
    __enable_leak_check = ...
    def memory_leak_setup(self):  # -> None:
        ...
    def memory_leak_teardown(self):  # -> None:
        ...
    def assert_no_memory_leak(self):  # -> None:
        ...
    def disable_leak_check(self):  # -> None:
        ...

class MemoryLeakMixin(EnableNRTStatsMixin, MemoryLeak):
    def setUp(self):  # -> None:
        ...
    def tearDown(self):  # -> None:
        ...

@contextlib.contextmanager
def forbid_codegen():  # -> Generator[None, Any, None]:

    ...
@contextlib.contextmanager
def redirect_fd(fd):  # -> Generator[TextIOWrapper[_WrappedBuffer], Any, None]:

    ...
def redirect_c_stdout():  # -> _GeneratorContextManager[TextIOWrapper[_WrappedBuffer], None, None]:

    ...
def redirect_c_stderr():  # -> _GeneratorContextManager[TextIOWrapper[_WrappedBuffer], None, None]:

    ...
def run_in_new_process_caching(func, cache_dir_prefix=..., verbose=...):  # -> dict[str, Any]:

    ...
def run_in_new_process_in_cache_dir(func, cache_dir, verbose=...):  # -> dict[str, Any]:

    ...

class CheckWarningsMixin:
    @contextlib.contextmanager
    def check_warnings(self, messages, category=...):  # -> Generator[None, Any, None]:
        ...

@contextlib.contextmanager
def create_temp_module(source_lines, **jit_options):  # -> Generator[ModuleType, Any, None]:

    ...
def run_in_subprocess(code, flags=..., env=..., timeout=...):  # -> tuple[bytes, bytes]:

    ...
def strace(work, syscalls, timeout=...):  # -> list[str]:

    ...
def strace_supported():  # -> bool:

    ...

class IRPreservingTestPipeline(CompilerBase):
    def define_pipelines(self):  # -> list[PassManager]:
        ...

def print_azure_matrix():  # -> None:

    ...
