_NRT_Meminfo_Functions = ...
_NRT_MEMINFO_SAFE_API = ...
_NRT_MEMINFO_DEFAULT_API = ...

class NRTContext:
    def __init__(self, context, enabled) -> None: ...
    @_check_null_result
    def allocate(self, builder, size): ...
    def allocate_unchecked(self, builder, size): ...
    def free(self, builder, ptr): ...
    @_check_null_result
    def meminfo_alloc(self, builder, size): ...
    def meminfo_alloc_unchecked(self, builder, size): ...
    @_check_null_result
    def meminfo_alloc_dtor(self, builder, size, dtor): ...
    def meminfo_alloc_dtor_unchecked(self, builder, size, dtor): ...
    @_check_null_result
    def meminfo_alloc_aligned(self, builder, size, align): ...
    def meminfo_alloc_aligned_unchecked(self, builder, size, align): ...
    @_check_null_result
    def meminfo_new_varsize(self, builder, size): ...
    def meminfo_new_varsize_unchecked(self, builder, size): ...
    @_check_null_result
    def meminfo_new_varsize_dtor(self, builder, size, dtor): ...
    def meminfo_new_varsize_dtor_unchecked(self, builder, size, dtor): ...
    @_check_null_result
    def meminfo_varsize_alloc(self, builder, meminfo, size): ...
    def meminfo_varsize_alloc_unchecked(self, builder, meminfo, size): ...
    @_check_null_result
    def meminfo_varsize_realloc(self, builder, meminfo, size): ...
    def meminfo_varsize_realloc_unchecked(self, builder, meminfo, size): ...
    def meminfo_varsize_free(self, builder, meminfo, ptr): ...
    def meminfo_data(self, builder, meminfo): ...
    def get_meminfos(self, builder, ty, val):  # -> list[Any]:

        ...
    def incref(self, builder, typ, value):  # -> None:

        ...
    def decref(self, builder, typ, value):  # -> None:

        ...
    def get_nrt_api(self, builder): ...
    def eh_check(self, builder): ...
    def eh_try(self, builder):  # -> None:

        ...
    def eh_end_try(self, builder):  # -> None:

        ...
