from numba.core.compiler_lock import global_compiler_lock
from numba.core.typing.typeof import typeof_impl

_nrt_mstats = ...

class _Runtime:
    def __init__(self) -> None: ...
    @global_compiler_lock
    def initialize(self, ctx):  # -> None:

        ...
    @staticmethod
    def shutdown():  # -> None:

        ...
    @property
    def library(self): ...
    def meminfo_new(self, data, pyobj): ...
    def meminfo_alloc(self, size, safe=...): ...
    def get_allocation_stats(self):  # -> nrt_mstats:

        ...

MemInfo = ...

@typeof_impl.register(MemInfo)
def typeof_meminfo(val, c):  # -> MemInfoPointer:
    ...

rtsys = ...
