_word_type = ...
_pointer_type = ...
_meminfo_struct_type = ...
incref_decref_ty = ...
meminfo_data_ty = ...
_disable_atomicity = ...

def create_nrt_module(ctx):  # -> tuple[Any, Any]:

    ...
def compile_nrt_functions(ctx): ...
