"""
This type stub file was generated by pyright.
"""

from types import MappingProxyType
from typing import Any, Optional
from modin.core.storage_formats.base.query_compiler import BaseQueryCompiler

"""
Module contains ``BackendCostCalculator`` class.

``BackendCostCalculator`` is used to determine the casting cost
between a set of different backends. It aggregates the cost across
all query compilers to determine the best query compiler to use.
"""
def all_switchable_backends() -> list[str]:
    """
    Return a list of all currently active backends that are candidates for switching.

    Returns
    -------
    list
        A list of valid backends.
    """
    ...

class AggregatedBackendData:
    """
    Contains information on Backends considered for computation.

    Parameters
    ----------
    backend : str
        String representing the backend name.
    qc_cls : type[QueryCompiler]
        The query compiler sub-class for this backend.
    """
    def __init__(self, backend: str, qc_cls: type[BaseQueryCompiler]) -> None:
        ...
    


class BackendCostCalculator:
    """
    Calculate which Backend should be used for an operation.

    Given a set of QueryCompilers containing various data, determine
    which query compiler's backend would minimize the cost of casting
    or coercion. Use the aggregate sum of coercion to determine overall
    cost.

    Parameters
    ----------
    operation_arguments : MappingProxyType[str, Any]
        Mapping from operation argument names to their values.
    api_cls_name : str or None
        Representing the class name of the function being called.
    operation : str representing the operation being performed
    query_compilers : list of query compiler arguments
    preop_switch : bool
        True if the operation is a pre-operation switch point.
    """
    def __init__(self, *, operation_arguments: MappingProxyType[str, Any], api_cls_name: Optional[str], operation: str, query_compilers: list[BaseQueryCompiler], preop_switch: bool) -> None:
        ...
    
    def calculate(self) -> str:
        """
        Calculate which query compiler we should cast to.

        Switching calculation is performed as follows:
        - For every registered query compiler in qc_list, with backend `backend_from`, compute
          `self_cost = qc_from.stay_cost(...)` and add it to the total cost for `backend_from`.
          - For every valid target `backend_to`, compute `qc_from.move_to_cost(qc_cls_to, ...)`. If it
            returns None, instead compute `qc_cls_to.move_to_me_cost(qc_from, ...)`. Add the result
            to the cost for `backend_to`.
        At a high level, the cost for choosing a particular backend is the sum of
            (all stay costs for data already on that backend)
            + (cost of moving all other query compilers to this backend)

        If the operation is a registered pre-operation switch point, then the list of target backends
        is ALL active backends. Otherwise, only backends found among the arguments are considered.
        Post-operation switch points are not yet supported.

        If the arguments contain no query compilers for a particular backend, then there are no stay
        costs. In this scenario, we expect the move_to cost for this backend to outweigh the corresponding
        stay costs for each query compiler's original backend.

        If no argument QCs have cost information for each other (that is, move_to_cost and move_to_me_cost
        returns None), then we attempt to move all data to the backend of the first QC.

        We considered a few alternative algorithms for switching calculation:

        1. Instead of considering all active backends, consider only backends found among input QCs.
        This was used in the calculator's original implementation, as we figured transfer cost to
        unrelated backends would outweigh any possible gains in computation speed. However, certain
        pathological cases that significantly changed the size of input or output data (e.g. cross join)
        would create situations where transferring data after the computation became prohibitively
        expensive, so we chose to allow switching to unrelated backends.
        Additionally, the original implementation had a bug where stay_cost was only computed for the
        _first_ query compiler of each backend, thus under-reporting the cost of computation for any
        backend with multiple QCs present. In practice this very rarely affected the chosen result.
        2. Compute stay/move costs only once for each backend pair, but force QCs to consider other
        arguments when calculating.
        This approach is the most robust and accurate for cases like cross join, where a product of
        transfer costs between backends is more reflective of cost than size. This approach requires
        more work in the query compiler, as each QC must be aware of when multiple QC arguments are
        passed and adjust the cost computation accordingly. It is also unclear how often this would
        make a meaningful difference compared to the summation approach.

        Returns
        -------
        str
            A string representing a backend.

        Raises
        ------
        ValueError
            Raises ValueError when the reported transfer cost for every backend exceeds its maximum cost.
        """
        ...
    


