import contextlib
import operator

import numpy as np
from numba.core import config
from numba.core.extending import overload, register_jitable

"""
Implementation of linear algebra operations.
"""
ll_char = ...
ll_char_p = ...
ll_void_p = ...
ll_intc = ...
ll_intc_p = ...
intp_t = ...
ll_intp_p = ...
F_INT_nptype = np.int32
if config.USE_LEGACY_TYPE_SYSTEM:
    F_INT_nbtype = ...
    _blas_kinds = ...
else:
    F_INT_nbtype = ...
    _blas_kinds = ...

def get_blas_kind(dtype, func_name=...):  # -> str:
    ...
def ensure_blas():  # -> None:
    ...
def ensure_lapack():  # -> None:
    ...
def make_constant_slot(context, builder, ty, val): ...

class _BLAS:
    def __init__(self) -> None: ...
    @classmethod
    def numba_xxnrm2(cls, dtype):  # -> ExternalFunction:
        ...
    @classmethod
    def numba_xxgemm(cls, dtype):  # -> ExternalFunction:
        ...

class _LAPACK:
    def __init__(self) -> None: ...
    @classmethod
    def numba_xxgetrf(cls, dtype):  # -> ExternalFunction:
        ...
    @classmethod
    def numba_ez_xxgetri(cls, dtype):  # -> ExternalFunction:
        ...
    @classmethod
    def numba_ez_rgeev(cls, dtype):  # -> ExternalFunction:
        ...
    @classmethod
    def numba_ez_cgeev(cls, dtype):  # -> ExternalFunction:
        ...
    @classmethod
    def numba_ez_xxxevd(cls, dtype):  # -> ExternalFunction:
        ...
    @classmethod
    def numba_xxpotrf(cls, dtype):  # -> ExternalFunction:
        ...
    @classmethod
    def numba_ez_gesdd(cls, dtype):  # -> ExternalFunction:
        ...
    @classmethod
    def numba_ez_geqrf(cls, dtype):  # -> ExternalFunction:
        ...
    @classmethod
    def numba_ez_xxgqr(cls, dtype):  # -> ExternalFunction:
        ...
    @classmethod
    def numba_ez_gelsd(cls, dtype):  # -> ExternalFunction:
        ...
    @classmethod
    def numba_xgesv(cls, dtype):  # -> ExternalFunction:
        ...

@contextlib.contextmanager
def make_contiguous(context, builder, sig, args):  # -> Generator[tuple[Signature, tuple[Any, ...]], Any, None]:

    ...
def check_c_int(context, builder, n):  # -> None:

    ...
def check_blas_return(context, builder, res):  # -> None:

    ...
def check_lapack_return(context, builder, res):  # -> None:

    ...
def call_xxdot(context, builder, conjugate, dtype, n, a_data, b_data, out_data):  # -> None:

    ...
def call_xxgemv(context, builder, do_trans, m_type, m_shapes, m_data, v_data, out_data):  # -> None:

    ...
def call_xxgemm(context, builder, x_type, x_shapes, x_data, y_type, y_shapes, y_data, out_type, out_shapes, out_data):  # -> None:

    ...
def dot_2_mm(context, builder, sig, args): ...
def dot_2_vm(context, builder, sig, args): ...
def dot_2_mv(context, builder, sig, args): ...
def dot_2_vv(context, builder, sig, args, conjugate=...): ...
@overload(np.dot)
def dot_2(a, b):  # -> Callable[..., Any] | None:

    ...
@overload(operator.matmul)
def matmul_2(a, b):  # -> Callable[..., Any] | None:

    ...
def dot_2_impl(name, a, b):  # -> Callable[..., Any] | None:
    ...
@overload(np.vdot)
def vdot(left, right):  # -> Callable[..., Any] | None:

    ...
def dot_3_vm_check_args(a, b, out):  # -> None:
    ...
def dot_3_mv_check_args(a, b, out):  # -> None:
    ...
def dot_3_vm(context, builder, sig, args):  # -> Any:

    ...
def dot_3_mm(context, builder, sig, args):  # -> Any:

    ...
@overload(np.dot)
def dot_3(a, b, out):  # -> Callable[..., Any] | None:

    ...

fatal_error_func = ...

@overload(_copy_to_fortran_order)
def ol_copy_to_fortran_order(a):  # -> Callable[..., NDArray[Any]]:
    ...
@overload(np.linalg.inv)
def inv_impl(a):  # -> Callable[..., Any]:
    ...
@overload(np.linalg.cholesky)
def cho_impl(a):  # -> Callable[..., Any]:
    ...
@overload(np.linalg.eig)
def eig_impl(a):  # -> Callable[..., tuple[_Array1D[float64], _Array[tuple[int, int], float64]]]:
    ...
@overload(np.linalg.eigvals)
def eigvals_impl(a):  # -> Callable[..., _Array1D[float64]]:
    ...
@overload(np.linalg.eigh)
def eigh_impl(a):  # -> Callable[..., tuple[ndarray[tuple[int], dtype[object_ | Any]], Any]]:
    ...
@overload(np.linalg.eigvalsh)
def eigvalsh_impl(a):  # -> Callable[..., ndarray[tuple[int], dtype[object_ | Any]]]:
    ...
@overload(np.linalg.svd)
def svd_impl(
    a, full_matrices=...
):  # -> Callable[..., tuple[_Array[tuple[int, int], float64], ndarray[tuple[int], dtype[object_ | Any]], _Array[tuple[int, int], float64]]]:
    ...
@overload(np.linalg.qr)
def qr_impl(a):  # -> Callable[..., tuple[Any, _Array[tuple[int, int], float64]]]:
    ...
@overload(np.linalg.lstsq)
def lstsq_impl(
    a, b, rcond=...
):  # -> Callable[..., tuple[NoReturn, ndarray[tuple[int], dtype[object_ | Any]], Any, ndarray[_AnyShape, dtype[object_ | Any]]]]:
    ...
@overload(np.linalg.solve)
def solve_impl(a, b):  # -> Callable[..., NoReturn]:
    ...
@overload(np.linalg.pinv)
def pinv_impl(a, rcond=...):  # -> Callable[..., Any]:
    ...
@overload(np.linalg.slogdet)
def slogdet_impl(a):  # -> Callable[..., tuple[Any, Any] | tuple[float, float] | tuple[Any, float | Any]]:
    ...
@overload(np.linalg.det)
def det_impl(a):  # -> Callable[..., Any]:
    ...
@overload(np.linalg.norm)
def norm_impl(x, ord=...):  # -> Callable[..., NoReturn] | Callable[..., float] | None:
    ...
@overload(np.linalg.cond)
def cond_impl(x, p=...):  # -> Callable[..., float | Incomplete | floating[Any]]:
    ...
@overload(np.linalg.matrix_rank)
def matrix_rank_impl(A, tol=...):  # -> Callable[..., Literal[1, 0]] | Callable[..., int] | None:

    ...
@overload(np.linalg.matrix_power)
def matrix_power_impl(a, n):  # -> Callable[..., ndarray[tuple[int], dtype[object_ | Any]] | Any | Incomplete | None]:

    ...
@overload(np.trace)
def matrix_trace_impl(a, offset=...):  # -> Callable[..., Any | Literal[0]]:

    ...
@register_jitable
def outer_impl_none(a, b, out):  # -> NDArray[Incomplete]:
    ...
@register_jitable
def outer_impl_arr(a, b, out): ...
@overload(np.outer)
def outer_impl(a, b, out=...):  # -> Callable[..., NDArray[Incomplete] | Any]:
    ...
@overload(np.kron)
def kron_impl(a, b):  # -> Callable[..., Any]:
    ...
