DATETIME_UNITS = ...
NAT = ...

def same_kind(src, dest):  # -> bool:

    ...
def can_cast_timedelta_units(src, dest):  # -> bool:
    ...

_factors = ...

def get_timedelta_conversion_factor(src_unit, dest_unit):  # -> int | None:

    ...
def get_datetime_timedelta_conversion(
    datetime_unit, timedelta_unit
):  # -> tuple[Any, Literal[1], Literal[1]] | tuple[Any, int, Literal[400, 2800, 1, 4800, 33600]] | tuple[Any, Literal[146097, 1], int]:

    ...
def combine_datetime_timedelta_units(datetime_unit, timedelta_unit):  # -> None:

    ...
def get_best_unit(unit_a, unit_b): ...
def datetime_minimum(a, b):  # -> None:
    ...
def datetime_maximum(a, b):  # -> None:
    ...
