import operator
from collections import namedtuple

import numpy as np
from numba.core import types
from numba.core.extending import overload

"""
Implementation of functions in the Numpy package.
"""
registry = ...

class _ScalarIndexingHelper:
    def update_indices(self, loop_indices, name):  # -> None:
        ...
    def as_values(self):  # -> None:
        ...

class _ScalarHelper:
    def __init__(self, ctxt, bld, val, ty) -> None: ...
    def create_iter_indices(self):  # -> _ScalarIndexingHelper:
        ...
    def load_data(self, indices):  # -> Any:
        ...
    def store_data(self, indices, val):  # -> None:
        ...
    @property
    def return_val(self): ...

class _ArrayIndexingHelper(namedtuple("_ArrayIndexingHelper", ("array", "indices"))):
    def update_indices(self, loop_indices, name):  # -> None:
        ...
    def as_values(self):  # -> list[Any]:

        ...

class _ArrayHelper(
    namedtuple("_ArrayHelper", ("context", "builder", "shape", "strides", "data", "layout", "base_type", "ndim", "return_val"))
):
    def create_iter_indices(self):  # -> _ArrayIndexingHelper:
        ...
    def load_data(self, indices): ...
    def store_data(self, indices, value):  # -> None:
        ...

class _ArrayGUHelper(
    namedtuple(
        "_ArrayHelper", ("context", "builder", "shape", "strides", "data", "layout", "base_type", "ndim", "inner_arr_ty", "is_input_arg")
    )
):
    def create_iter_indices(self):  # -> _ArrayIndexingHelper:
        ...
    def load_data(self, indices):  # -> Any:
        ...
    def guard_shape(self, loopshape):  # -> None:
        ...
    def guard_match_core_dims(self, other: _ArrayGUHelper, ndims: int):  # -> None:
        ...

_broadcast_onto_sig = ...

def numpy_ufunc_kernel(context, builder, sig, args, ufunc, kernel_class): ...
def numpy_gufunc_kernel(context, builder, sig, args, ufunc, kernel_class):  # -> None:
    ...

class _Kernel:
    def __init__(self, context, builder, outer_sig) -> None: ...
    def cast(self, val, fromty, toty): ...
    def generate(self, *args): ...

def register_ufunc_kernel(ufunc, kernel, lower): ...
def register_unary_operator_kernel(operator, ufunc, kernel, lower, inplace=...):  # -> None:
    ...
def register_binary_operator_kernel(op, ufunc, kernel, lower, inplace=...):  # -> None:
    ...
@registry.lower(operator.pos, types.Array)
def array_positive_impl(context, builder, sig, args) -> None: ...
def register_ufuncs(ufuncs, lower):  # -> None:
    ...
@overload(np.dtype)
def numpy_dtype(dtype):  # -> Callable[..., Callable[..., Any]]:

    ...
