import collections

numpy_version = ...
FROM_DTYPE = ...
re_typestr = ...
re_datetimestr = ...
sizeof_unicode_char = ...

def from_dtype(dtype):  # -> Record | UnicodeCharSeq | CharSeq | NPTimedelta | NPDatetime | NestedArray:

    ...

_as_dtype_letters = ...

def as_dtype(nbtype):  # -> dtype[Any] | dtype[numpy.bool[builtins.bool]] | dtype[void] | dtype[object_ | Any]:

    ...
def as_struct_dtype(rec):  # -> dtype[Any]:

    ...
def map_arrayscalar_type(val):  # -> Record | UnicodeCharSeq | CharSeq | NPTimedelta | NPDatetime | NestedArray:
    ...
def is_array(val):  # -> bool:
    ...
def map_layout(val):  # -> Literal['C', 'F', 'A']:
    ...
def select_array_wrapper(inputs):  # -> int:

    ...
def resolve_output_type(context, inputs, formal_output): ...
def supported_ufunc_loop(ufunc, loop):  # -> bool:

    ...

class UFuncLoopSpec(collections.namedtuple("_UFuncLoopSpec", ("inputs", "outputs", "ufunc_sig"))):
    __slots__ = ...
    @property
    def numpy_inputs(self):  # -> list[dtype[Any] | dtype[numpy.bool[builtins.bool]] | Any | dtype[void] | dtype[object_ | Any]]:
        ...
    @property
    def numpy_outputs(self):  # -> list[dtype[Any] | dtype[numpy.bool[builtins.bool]] | Any | dtype[void] | dtype[object_ | Any]]:
        ...

def ufunc_can_cast(from_, to, has_mixed_inputs, casting=...):  # -> bool:

    ...
def ufunc_find_matching_loop(ufunc, arg_types):  # -> UFuncLoopSpec | None:

    ...
def from_struct_dtype(dtype):  # -> Record:

    ...
def carray(ptr, shape, dtype=...):  # -> NDArray[float64]:

    ...
def farray(ptr, shape, dtype=...):  # -> NDArray[float64]:

    ...
def is_contiguous(dims, strides, itemsize):  # -> bool:

    ...
def is_fortran(dims, strides, itemsize):  # -> bool:

    ...
def type_can_asarray(arr):  # -> bool:

    ...
def type_is_scalar(typ):  # -> bool:

    ...
def check_is_integer(v, name):  # -> None:

    ...
def lt_floats(a, b):  # -> Any | bool:
    ...
def lt_complex(a, b):  # -> bool:
    ...
