"""
This type stub file was generated by pyright.
"""

import numpy as np
import pandas
from typing import Any, Callable, Optional, TYPE_CHECKING, Union
from .operator import Operator
from pandas._typing import DtypeObj
from modin.core.storage_formats.pandas.query_compiler import PandasQueryCompiler

"""Module houses builder class for Binary operator."""
if TYPE_CHECKING:
    ...
def maybe_compute_dtypes_common_cast(first: PandasQueryCompiler, second: Union[PandasQueryCompiler, dict, list, tuple, np.ndarray, str, DtypeObj], trigger_computations: bool = ..., axis: int = ..., func: Optional[Callable[[pandas.DataFrame, pandas.DataFrame], pandas.DataFrame]] = ...) -> Optional[pandas.Series]:
    """
    Precompute data types for binary operations by finding common type between operands.

    Parameters
    ----------
    first : PandasQueryCompiler
        First operand for which the binary operation would be performed later.
    second : PandasQueryCompiler, dict, list, tuple, np.ndarray, str or DtypeObj
        Second operand for which the binary operation would be performed later.
    trigger_computations : bool, default: False
        Whether to trigger computation of the lazy metadata for `first` and `second`.
        If False is specified this method will return None if any of the operands doesn't
        have materialized dtypes.
    axis : int, default: 0
        Axis to perform the binary operation along.
    func : callable(pandas.DataFrame, pandas.DataFrame) -> pandas.DataFrame, optional
        If specified, will use this function to perform the "try_sample" method
        (see ``Binary.register()`` docs for more details).

    Returns
    -------
    pandas.Series
        The pandas series with precomputed dtypes or None if there's not enough metadata to compute it.

    Notes
    -----
    The dtypes of the operands are supposed to be known.
    """
    ...

def maybe_build_dtypes_series(first: PandasQueryCompiler, second: Union[PandasQueryCompiler, Any], dtype: DtypeObj, trigger_computations: bool = ...) -> Optional[pandas.Series]:
    """
    Build a ``pandas.Series`` describing dtypes of the result of a binary operation.

    Parameters
    ----------
    first : PandasQueryCompiler
        First operand for which the binary operation would be performed later.
    second : PandasQueryCompiler, list-like or scalar
        Second operand for which the binary operation would be performed later.
    dtype : DtypeObj
        Dtype of the result.
    trigger_computations : bool, default: False
        Whether to trigger computation of the lazy metadata for `first` and `second`.
        If False is specified this method will return None if any of the operands doesn't
        have materialized columns.

    Returns
    -------
    pandas.Series or None
        The pandas series with precomputed dtypes or None if there's not enough metadata to compute it.

    Notes
    -----
    Finds a union of columns and finds dtypes for all these columns.
    """
    ...

def try_compute_new_dtypes(first: PandasQueryCompiler, second: Union[PandasQueryCompiler, Any], infer_dtypes: Optional[str] = ..., result_dtype: Optional[Union[DtypeObj, str]] = ..., axis: int = ..., func: Optional[Callable[[pandas.DataFrame, pandas.DataFrame], pandas.DataFrame]] = ...) -> Optional[pandas.Series]:
    """
    Precompute resulting dtypes of the binary operation if possible.

    The dtypes won't be precomputed if any of the operands doesn't have their dtypes materialized
    or if the second operand type is not supported. Supported types: PandasQueryCompiler, list,
    dict, tuple, np.ndarray.

    Parameters
    ----------
    first : PandasQueryCompiler
        First operand of the binary operation.
    second : PandasQueryCompiler, list-like or scalar
        Second operand of the binary operation.
    infer_dtypes : {"common_cast", "try_sample", "bool", None}, default: None
        How dtypes should be infered (see ``Binary.register`` doc for more info).
    result_dtype : np.dtype, optional
        NumPy dtype of the result. If not specified it will be inferred from the `infer_dtypes` parameter.
    axis : int, default: 0
        Axis to perform the binary operation along.
    func : callable(pandas.DataFrame, pandas.DataFrame) -> pandas.DataFrame, optional
        A callable to be used for the "try_sample" method.

    Returns
    -------
    pandas.Series or None
    """
    ...

class Binary(Operator):
    """Builder class for Binary operator."""
    @classmethod
    def register(cls, func: Callable[..., pandas.DataFrame], join_type: str = ..., sort: bool = ..., labels: str = ..., infer_dtypes: Optional[str] = ...) -> Callable[..., PandasQueryCompiler]:
        """
        Build template binary operator.

        Parameters
        ----------
        func : callable(pandas.DataFrame, [pandas.DataFrame, list-like, scalar]) -> pandas.DataFrame
            Binary function to execute. Have to be able to accept at least two arguments.
        join_type : {'left', 'right', 'outer', 'inner', None}, default: 'outer'
            Type of join that will be used if indices of operands are not aligned.
        sort : bool, default: None
            Whether to sort index and columns or not.
        labels : {"keep", "replace", "drop"}, default: "replace"
            Whether keep labels from left Modin DataFrame, replace them with labels
            from joined DataFrame or drop altogether to make them be computed lazily later.
        infer_dtypes : {"common_cast", "try_sample", "bool", None}, default: None
            How dtypes should be inferred.
                * If "common_cast", casts to common dtype of operand columns.
                * If "try_sample", creates small pandas DataFrames with dtypes of operands and
                  runs the `func` on them to determine output dtypes. If a ``TypeError`` is raised
                  during this process, fallback to "common_cast" method.
                * If "bool", dtypes would be a boolean series with same size as that of operands.
                * If ``None``, do not infer new dtypes (they will be computed manually once accessed).

        Returns
        -------
        callable
            Function that takes query compiler and executes binary operation.
        """
        ...
    


