"""
This type stub file was generated by pyright.
"""

import pandas
from typing import Callable, TYPE_CHECKING
from .operator import Operator
from modin.core.storage_formats.pandas.query_compiler import PandasQueryCompiler

"""Module houses builder class for Map operator."""
if TYPE_CHECKING:
    ...
class Map(Operator):
    """Builder class for Map operator."""
    @classmethod
    def register(cls, function: Callable[..., pandas.DataFrame], *call_args: tuple, **call_kwds: dict) -> Callable[..., PandasQueryCompiler]:
        """
        Build Map operator that will be performed across each partition.

        Parameters
        ----------
        function : callable(pandas.DataFrame, *args, **kwargs) -> pandas.DataFrame
            Function that will be applied to the each partition.
            Function takes `pandas.DataFrame` and returns `pandas.DataFrame`
            of the same shape.
        *call_args : tuple
            Args that will be passed to the returned function.
        **call_kwds : dict
            Kwargs that will be passed to the returned function.

        Returns
        -------
        callable
            Function that takes query compiler and executes map function.
        """
        ...
    


