"""
This type stub file was generated by pyright.
"""

import pandas
from typing import Callable, Optional, TYPE_CHECKING
from .operator import Operator
from modin.core.storage_formats.pandas.query_compiler import PandasQueryCompiler

"""Module houses builder class for Reduce operator."""
if TYPE_CHECKING:
    ...
class Reduce(Operator):
    """Builder class for Reduce operator."""
    @classmethod
    def register(cls, reduce_function: Callable[..., pandas.Series], axis: Optional[int] = ..., shape_hint: Optional[str] = ...) -> Callable[..., PandasQueryCompiler]:
        """
        Build Reduce operator that will be performed across rows/columns.

        It's used if `func` reduces the dimension of partitions in contrast to `Fold`.

        Parameters
        ----------
        reduce_function : callable(pandas.DataFrame, *args, **kwargs) -> pandas.Series
            Source function.
        axis : int, optional
            Axis to apply function along.
        shape_hint : {"row", "column", None}, default: None
            Shape hint for the results known to be a column or a row, otherwise None.

        Returns
        -------
        callable
            Function that takes query compiler and executes Reduce function.
        """
        ...
    


