def is_nan(builder, z): ...
def is_inf(builder, z): ...
def is_finite(builder, z): ...
def isnan_float_impl(context, builder, sig, args): ...
def isinf_float_impl(context, builder, sig, args): ...
def isfinite_float_impl(context, builder, sig, args): ...
def impl_cmath_rect(r, phi):  # -> Callable[..., Any | complex] | None:
    ...
def intrinsic_complex_unary(inner_func):  # -> Callable[..., Any]:
    ...

NAN = ...
INF = ...

@intrinsic_complex_unary
def exp_impl(x, y, x_is_finite, y_is_finite):  # -> complex:

    ...
@intrinsic_complex_unary
def log_impl(x, y, x_is_finite, y_is_finite):  # -> complex:

    ...
def log_base_impl(context, builder, sig, args): ...
def impl_cmath_log10(z):  # -> Callable[..., complex] | None:
    ...
def phase_impl(x):  # -> Callable[..., float] | None:

    ...
def polar_impl(x):  # -> Callable[..., tuple[float, float]] | None:
    ...
def sqrt_impl(context, builder, sig, args): ...
def cos_impl(context, builder, sig, args): ...
def impl_cmath_cosh(z):  # -> Callable[..., complex] | None:
    ...
def sin_impl(context, builder, sig, args): ...
def impl_cmath_sinh(z):  # -> Callable[..., complex] | None:
    ...
def tan_impl(context, builder, sig, args): ...
def impl_cmath_tanh(z):  # -> Callable[..., complex] | None:
    ...
def acos_impl(context, builder, sig, args): ...
def impl_cmath_acosh(z):  # -> Callable[..., complex] | None:
    ...
def asinh_impl(context, builder, sig, args): ...
def asin_impl(context, builder, sig, args): ...
def atan_impl(context, builder, sig, args): ...
def atanh_impl(context, builder, sig, args): ...
