_NP_FLT_FINFO = ...
FLT_MAX = _NP_FLT_FINFO.max
FLT_MIN = _NP_FLT_FINFO.tiny
_NP_DBL_FINFO = ...
DBL_MAX = ...
DBL_MIN = ...
FLOAT_ABS_MASK = ...
FLOAT_SIGN_MASK = ...
DOUBLE_ABS_MASK = ...
DOUBLE_SIGN_MASK = ...

def is_nan(builder, val): ...
def is_inf(builder, val): ...
def is_finite(builder, val): ...
def f64_as_int64(builder, val): ...
def int64_as_f64(builder, val): ...
def f32_as_int32(builder, val): ...
def int32_as_f32(builder, val): ...
def negate_real(builder, val): ...
def call_fp_intrinsic(builder, name, args): ...
def unary_math_int_impl(fn, float_impl):  # -> None:
    ...
def unary_math_intr(fn, intrcode):  # -> Callable[..., Any]:

    ...
def unary_math_extern(fn, f32extern, f64extern, int_restype=...):  # -> Callable[..., Any]:

    ...

exp_impl = ...
exp2_impl = ...
log_impl = ...
log10_impl = ...
sin_impl = ...
cos_impl = ...
log1p_impl = ...
expm1_impl = ...
erf_impl = ...
erfc_impl = ...
tan_impl = ...
asin_impl = ...
acos_impl = ...
atan_impl = ...
asinh_impl = ...
acosh_impl = ...
atanh_impl = ...
sinh_impl = ...
cosh_impl = ...
tanh_impl = ...
log2_impl = ...
ceil_impl = ...
floor_impl = ...
gamma_impl = ...
sqrt_impl = ...
trunc_impl = ...
lgamma_impl = ...

def isnan_float_impl(context, builder, sig, args): ...
def isnan_int_impl(context, builder, sig, args):  # -> Constant:
    ...
def isinf_float_impl(context, builder, sig, args): ...
def isinf_int_impl(context, builder, sig, args):  # -> Constant:
    ...
def isfinite_float_impl(context, builder, sig, args): ...
def isfinite_int_impl(context, builder, sig, args):  # -> Constant:
    ...
def copysign_float_impl(context, builder, sig, args): ...
def frexp_impl(context, builder, sig, args):  # -> Constant:
    ...
def ldexp_impl(context, builder, sig, args): ...
def atan2_s64_impl(context, builder, sig, args): ...
def atan2_u64_impl(context, builder, sig, args): ...
def atan2_float_impl(context, builder, sig, args): ...
def hypot_s64_impl(context, builder, sig, args): ...
def hypot_u64_impl(context, builder, sig, args): ...
def hypot_float_impl(context, builder, sig, args): ...
def radians_float_impl(context, builder, sig, args): ...
def degrees_float_impl(context, builder, sig, args): ...
def pow_impl(context, builder, sig, args): ...
def gcd_impl(context, builder, sig, args): ...
