def int_add_impl(context, builder, sig, args): ...
def int_sub_impl(context, builder, sig, args): ...
def int_mul_impl(context, builder, sig, args): ...
def int_divmod_signed(context, builder, ty, x, y):  # -> tuple[Any, Any]:

    ...
def int_divmod(context, builder, ty, x, y):  # -> tuple[Any, Any]:

    ...
def int_divmod_impl(context, builder, sig, args):  # -> Constant:
    ...
def int_floordiv_impl(context, builder, sig, args): ...
def int_truediv_impl(context, builder, sig, args): ...
def int_rem_impl(context, builder, sig, args): ...
def int_power_impl(context, builder, sig, args): ...
def static_power_impl(context, builder, sig, args): ...
def int_slt_impl(context, builder, sig, args): ...
def int_sle_impl(context, builder, sig, args): ...
def int_sgt_impl(context, builder, sig, args): ...
def int_sge_impl(context, builder, sig, args): ...
def int_ult_impl(context, builder, sig, args): ...
def int_ule_impl(context, builder, sig, args): ...
def int_ugt_impl(context, builder, sig, args): ...
def int_uge_impl(context, builder, sig, args): ...
def int_eq_impl(context, builder, sig, args): ...
def int_ne_impl(context, builder, sig, args): ...
def int_signed_unsigned_cmp(op):  # -> Callable[..., Any]:
    ...
def int_unsigned_signed_cmp(op):  # -> Callable[..., Any]:
    ...
def int_abs_impl(context, builder, sig, args): ...
def identity_impl(context, builder, sig, args): ...
def uint_abs_impl(context, builder, sig, args): ...
def int_shl_impl(context, builder, sig, args): ...
def int_shr_impl(context, builder, sig, args): ...
def int_and_impl(context, builder, sig, args): ...
def int_or_impl(context, builder, sig, args): ...
def int_xor_impl(context, builder, sig, args): ...
def int_negate_impl(context, builder, sig, args): ...
def int_positive_impl(context, builder, sig, args): ...
def int_invert_impl(context, builder, sig, args): ...
def int_sign_impl(context, builder, sig, args): ...
def bool_negate_impl(context, builder, sig, args): ...
def bool_unary_positive_impl(context, builder, sig, args): ...
def real_add_impl(context, builder, sig, args): ...
def real_sub_impl(context, builder, sig, args): ...
def real_mul_impl(context, builder, sig, args): ...
def real_div_impl(context, builder, sig, args): ...
def real_divmod(context, builder, x, y):  # -> tuple[Any, Any]:
    ...
def real_divmod_func_body(context, builder, vx, wx):  # -> tuple[Any, Any]:
    ...
def real_divmod_impl(context, builder, sig, args, loc=...):  # -> Constant:
    ...
def real_mod_impl(context, builder, sig, args, loc=...): ...
def real_floordiv_impl(context, builder, sig, args, loc=...): ...
def real_power_impl(context, builder, sig, args): ...
def real_lt_impl(context, builder, sig, args): ...
def real_le_impl(context, builder, sig, args): ...
def real_gt_impl(context, builder, sig, args): ...
def real_ge_impl(context, builder, sig, args): ...
def real_eq_impl(context, builder, sig, args): ...
def real_ne_impl(context, builder, sig, args): ...
def real_abs_impl(context, builder, sig, args): ...
def real_negate_impl(context, builder, sig, args): ...
def real_positive_impl(context, builder, sig, args): ...
def real_sign_impl(context, builder, sig, args): ...
def complex_real_impl(context, builder, typ, value): ...
def complex_imag_impl(context, builder, typ, value): ...
def complex_conjugate_impl(context, builder, sig, args): ...
def real_real_impl(context, builder, typ, value): ...
def real_imag_impl(context, builder, typ, value): ...
def real_conjugate_impl(context, builder, sig, args): ...
def complex_power_impl(context, builder, sig, args): ...
def complex_add_impl(context, builder, sig, args): ...
def complex_sub_impl(context, builder, sig, args): ...
def complex_mul_impl(context, builder, sig, args): ...

NAN = ...

def complex_div_impl(context, builder, sig, args): ...
def complex_negate_impl(context, builder, sig, args): ...
def complex_positive_impl(context, builder, sig, args): ...
def complex_eq_impl(context, builder, sig, args): ...
def complex_ne_impl(context, builder, sig, args): ...
def complex_abs_impl(context, builder, sig, args): ...
def number_item_impl(context, builder, sig, args): ...
def number_not_impl(context, builder, sig, args): ...
def bool_as_bool(context, builder, sig, args): ...
def int_as_bool(context, builder, sig, args): ...
def float_as_bool(context, builder, sig, args): ...
def complex_as_bool(context, builder, sig, args): ...
def literal_int_to_number(context, builder, fromty, toty, val): ...
def integer_to_integer(context, builder, fromty, toty, val): ...
def integer_to_voidptr(context, builder, fromty, toty, val): ...
def float_to_float(context, builder, fromty, toty, val): ...
def integer_to_float(context, builder, fromty, toty, val): ...
def float_to_integer(context, builder, fromty, toty, val): ...
def non_complex_to_complex(context, builder, fromty, toty, val): ...
def complex_to_complex(context, builder, fromty, toty, val): ...
def any_to_boolean(context, builder, fromty, toty, val): ...
def boolean_to_any(context, builder, fromty, toty, val): ...
def literal_int_to_boolean(context, builder, fromty, toty, val): ...
def constant_complex(context, builder, ty, pyval):  # -> Constant:
    ...
def constant_integer(context, builder, ty, pyval): ...
def scalar_view(scalar, viewty):  # -> Callable[..., Any] | None:

    ...
