from . import base

"""App Engine memcache based cache for the discovery document."""
LOGGER = ...
NAMESPACE = ...

class Cache(base.Cache):
    def __init__(self, max_age) -> None: ...
    def get(self, url):  # -> None:
        ...
    def set(self, url, content):  # -> None:
        ...

cache = ...
