from . import base

"""File based cache for the discovery document.

The cache is stored in a single file so that multiple processes can
share the same cache. It locks the file whenever accessing to the
file. When the cache content is corrupted, it will be initialized with
an empty cache.
"""
LOGGER = ...
FILENAME = ...
EPOCH = ...

class Cache(base.Cache):
    def __init__(self, max_age) -> None: ...
    def get(self, url):  # -> Any | None:
        ...
    def set(self, url, content):  # -> None:
        ...

cache = ...
