"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._x import X
from ._y import Y
from ._z import Z

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
else:
    ...
