from functools import total_ordering
from typing import Any

logger = ...

@total_ordering
class QueryContextElement:
    def __init__(self, id: int, read_timestamp: int, priority: int, context: str) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: Any) -> bool: ...
    def __hash__(self) -> int: ...

class QueryContextCache:
    def __init__(self, capacity: int) -> None: ...
    def insert(self, id: int, read_timestamp: int, priority: int, context: str) -> None: ...
    def trim_cache(self) -> None: ...
    def clear_cache(self) -> None: ...
    def serialize_to_dict(self) -> dict: ...
    def deserialize_json_dict(self, data: dict) -> None: ...
    def log_cache_entries(self) -> None: ...
    def __len__(self) -> int: ...
