from .constants import FileTransferType

COMMENT_START_SQL_RE = ...
PUT_SQL_RE = ...
GET_SQL_RE = ...

def remove_starting_comments(sql: str) -> str: ...
def get_file_transfer_type(sql: str) -> FileTransferType | None: ...
def is_put_statement(sql: str) -> bool: ...
def is_get_statement(sql: str) -> bool: ...
