from enum import Enum
from threading import Timer
from uuid import UUID

logger = ...

class TempObjectType(Enum):
    TABLE = ...
    VIEW = ...
    STAGE = ...
    FUNCTION = ...
    FILE_FORMAT = ...
    QUERY_TAG = ...
    COLUMN = ...
    PROCEDURE = ...
    TABLE_FUNCTION = ...
    DYNAMIC_TABLE = ...
    AGGREGATE_FUNCTION = ...
    CTE = ...

TEMP_OBJECT_NAME_PREFIX = ...
ALPHANUMERIC = ...
TEMPORARY_STRING = ...
SCOPED_TEMPORARY_STRING = ...
_PYTHON_SNOWPARK_USE_SCOPED_TEMP_OBJECTS_STRING = ...
REQUEST_ID_STATEMENT_PARAM_NAME = ...
_DEFAULT_VALUE_SERVER_DOP_CAP_FOR_FILE_TRANSFER = ...
_VARIABLE_NAME_SERVER_DOP_CAP_FOR_FILE_TRANSFER = ...

def generate_random_alphanumeric(length: int = ...) -> str: ...
def random_name_for_temp_object(object_type: TempObjectType) -> str: ...
def get_temp_type_for_object(use_scoped_temp_objects: bool) -> str: ...
def is_uuid4(str_or_uuid: str | UUID) -> bool: ...

class _TrackedQueryCancellationTimer(Timer):
    def __init__(self, interval, function, args=..., kwargs=...) -> None: ...
    def run(self): ...

def get_application_path() -> str: ...

_SPCS_TOKEN_ENV_VAR_NAME = ...
_SPCS_TOKEN_DEFAULT_PATH = ...

def get_spcs_token() -> str | None: ...

class _NanoarrowLoader:
    def __init__(self) -> None: ...
    def set_load_error(self, err: Exception): ...
    def get_load_error(self) -> str: ...

class _CoreLoader:
    def __init__(self) -> None: ...
    def get_present_binaries(self) -> str: ...
    def load(self): ...
    def get_load_error(self) -> str: ...
    def get_core_version(self) -> str | None: ...
    def get_file_name(self) -> str: ...
    def get_load_time(self) -> float | None: ...

_core_loader = ...
_nanoarrow_loader = ...

def build_minicore_usage_for_session() -> dict[str, str | None]: ...
def build_minicore_usage_for_telemetry() -> dict[str, str | None]: ...
def build_nanoarrow_usage_for_telemetry() -> dict[str, str | None]: ...
