import decimal
from datetime import datetime, timedelta
from typing import TYPE_CHECKING

from numpy import datetime64, float64, int64, timedelta64

if TYPE_CHECKING: ...
ZERO_EPOCH = ...
logger = ...

class ArrowConverterContext:
    def __init__(self, session_parameters: dict[str, str | int | bool] | None = ...) -> None: ...
    @property
    def timezone(self) -> str: ...
    @timezone.setter
    def timezone(self, tz) -> None: ...
    def TIMESTAMP_TZ_to_python(self, epoch: int, microseconds: int, tz: int) -> datetime: ...
    def TIMESTAMP_TZ_to_python_windows(self, epoch: int, microseconds: int, tz: int) -> datetime: ...
    def TIMESTAMP_NTZ_to_python(self, epoch: int, microseconds: int) -> datetime: ...
    def TIMESTAMP_NTZ_to_python_windows(self, epoch: int, microseconds: int) -> datetime: ...
    def TIMESTAMP_LTZ_to_python(self, epoch: int, microseconds: int) -> datetime: ...
    def TIMESTAMP_LTZ_to_python_windows(self, epoch: int, microseconds: int) -> datetime: ...
    def REAL_to_numpy_float64(self, py_double: float) -> float64: ...
    def FIXED_to_numpy_int64(self, py_long: int) -> int64: ...
    def FIXED_to_numpy_float64(self, py_long: int, scale: int) -> float64: ...
    def DATE_to_numpy_datetime64(self, py_days: int) -> datetime64: ...
    def TIMESTAMP_NTZ_ONE_FIELD_to_numpy_datetime64(self, value: int, scale: int) -> datetime64: ...
    def TIMESTAMP_NTZ_TWO_FIELD_to_numpy_datetime64(self, epoch: int, fraction: int) -> datetime64: ...
    def DECIMAL128_to_decimal(self, int128_bytes: bytes, scale: int) -> decimal.Decimal: ...
    def DECFLOAT_to_decimal(self, exponent: int, significand: bytes) -> decimal.Decimal: ...
    def DECFLOAT_to_numpy_float64(self, exponent: int, significand: bytes) -> float64: ...
    def INTERVAL_YEAR_MONTH_to_str(self, months: int, scale: int) -> str: ...
    def INTERVAL_YEAR_MONTH_to_numpy_timedelta(self, months: int, scale: int) -> timedelta64: ...
    def INTERVAL_DAY_TIME_int_to_numpy_timedelta(self, nanos: int) -> timedelta64: ...
    def INTERVAL_DAY_TIME_int_to_timedelta(self, nanos: int) -> timedelta: ...
    def INTERVAL_DAY_TIME_decimal_to_numpy_timedelta(self, value: bytes) -> timedelta64: ...
    def INTERVAL_DAY_TIME_decimal_to_timedelta(self, value: bytes) -> timedelta: ...
