from typing import TYPE_CHECKING, Any, NamedTuple

from .constants import FileHeader
from .file_transfer_agent import SnowflakeFileMeta, StorageCredential
from .storage_client import SnowflakeStorageClient

if TYPE_CHECKING: ...
logger = ...

class AzureLocation(NamedTuple):
    container_name: str
    path: str

TOKEN_EXPIRATION_ERR_MESSAGE = ...
SFCDIGEST = ...
ENCRYPTION_DATA = ...
MATDESC = ...

class SnowflakeAzureRestClient(SnowflakeStorageClient):
    def __init__(
        self,
        meta: SnowflakeFileMeta,
        credentials: StorageCredential | None,
        chunk_size: int,
        stage_info: dict[str, Any],
        unsafe_file_write: bool = ...,
    ) -> None: ...
    @staticmethod
    def extract_container_name_and_path(stage_location: str) -> AzureLocation: ...
    def get_file_header(self, filename: str) -> FileHeader | None: ...
    def download_chunk(self, chunk_id: int) -> None: ...
