from collections.abc import Callable, Iterator

DEFAULT_BACKOFF_FACTOR = ...
DEFAULT_BACKOFF_BASE = ...
DEFAULT_BACKOFF_CAP = ...
DEFAULT_ENABLE_JITTER = ...

def mixed_backoff(factor: int = ..., base: int = ..., cap: int = ..., enable_jitter: bool = ...) -> Callable[..., Iterator[int]]: ...
def linear_backoff(factor: int = ..., base: int = ..., cap: int = ..., enable_jitter: bool = ...) -> Callable[..., Iterator[int]]: ...
def exponential_backoff(factor: int = ..., base: int = ..., cap: int = ..., enable_jitter: bool = ...) -> Callable[..., Iterator[int]]: ...
