from typing import TYPE_CHECKING

from .cursor import SnowflakeCursor

if TYPE_CHECKING: ...
logger = ...

class BindUploadAgent:
    def __init__(self, cursor: SnowflakeCursor, rows: list[bytes], stream_buffer_size: int = ...) -> None: ...
    def upload(self) -> None: ...
