"""
This type stub file was generated by pyright.
"""

from typing import TYPE_CHECKING
from .cursor import SnowflakeCursor

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
logger = ...
class BindUploadAgent:
    def __init__(self, cursor: SnowflakeCursor, rows: list[bytes], stream_buffer_size: int = ...) -> None:
        ...
    
    def upload(self) -> None:
        ...
    


