import datetime
from collections.abc import Iterator
from typing import NamedTuple, Self, TypeVar

now = ...
getmtime = ...
T = TypeVar("T")
logger = ...
test_mode = ...

class CacheEntry[T](NamedTuple):
    expiry: datetime.datetime
    entry: T

K = TypeVar("K")
V = TypeVar("V")

def is_expired(d: datetime.datetime) -> bool: ...

class SFDictCache[K, V]:
    def __init__(self, entry_lifetime: int = ...) -> None: ...
    def __len__(self) -> int: ...
    @classmethod
    def from_dict(cls, _dict: dict[K, V], **kw) -> Self: ...

    _getitem_non_locking = ...
    def __getitem__(self, k: K) -> V: ...
    def __setitem__(self, k: K, v: V) -> None: ...
    def __iter__(self) -> Iterator[K]: ...
    def keys(self) -> list[K]: ...
    def items(self) -> list[tuple[K, V]]: ...
    def values(self) -> list[V]: ...
    def get(self, k: K, default: V | None = ...) -> V | None: ...
    def clear(self) -> None: ...
    def __delitem__(self, key: K) -> None: ...
    def __contains__(self, key: K) -> bool: ...
    def update(self, other: dict[K, V] | list[tuple[K, V]] | SFDictCache[K, V], update_newer_only: bool = ...) -> bool: ...
    def update_newer(self, other: dict[K, V] | list[tuple[K, V]] | SFDictCache[K, V]) -> bool: ...
    def clear_expired_entries(self) -> None: ...

class SFDictFileCache(SFDictCache):
    MAX_RAND_INT = ...
    _ATTRIBUTES_TO_PICKLE = ...
    def __init__(
        self, file_path: str | dict[str, str], entry_lifetime: int = ..., file_timeout: int = ..., load_if_file_exists: bool = ...
    ) -> None: ...
    def __getitem__(self, k: K) -> V: ...
    def load(self) -> bool: ...
    def save(self, load_first: bool = ...) -> bool: ...
    def clear(self) -> None: ...
    def __getstate__(self) -> dict: ...
    def __setstate__(self, state: dict) -> None: ...
