import collections.abc
import http.client
import queue
from typing import Any

IS_LINUX = ...
IS_WINDOWS = ...
IS_MACOS = ...
NUM_DATA_TYPES: tuple[type, ...] = ...
NUM_DATA_TYPES = ...
GET_CWD = ...
BASE_EXCEPTION_CLASS = Exception
TO_UNICODE = str
ITERATOR = collections.abc.Iterator
MAPPING = collections.abc.Mapping
urlsplit = ...
urlunsplit = ...
parse_qs = ...
urlparse = ...
urlunparse = ...

def PKCS5_UNPAD(v: bytes) -> bytes: ...
def PKCS5_OFFSET(v: bytes) -> int: ...
def IS_BINARY(v: bytearray | bytes | str) -> bool: ...

METHOD_NOT_ALLOWED = ...
BAD_GATEWAY = ...
BAD_REQUEST = ...
REQUEST_TIMEOUT = ...
TOO_MANY_REQUESTS = ...
SERVICE_UNAVAILABLE = ...
GATEWAY_TIMEOUT = ...
FORBIDDEN = ...
UNAUTHORIZED = ...
INTERNAL_SERVER_ERROR = ...
IncompleteRead = http.client.IncompleteRead
OK = ...
BadStatusLine = http.client.BadStatusLine
urlencode = ...
unquote = ...
quote = ...
unescape = ...
EmptyQueue = queue.Empty
Queue = queue.Queue

def IS_BYTES(v: Any) -> bool: ...
def IS_UNICODE(v: Any) -> bool: ...
def IS_NUMERIC(v: Any) -> bool: ...

IS_STR = ...

def PKCS5_PAD(value: bytes, block_size: int) -> bytes: ...
def PRINT(msg: str) -> None: ...
def INPUT(prompt: str) -> str: ...
def quote_url_piece(piece: str) -> str: ...
