from collections.abc import Callable, Iterable
from pathlib import Path
from typing import Any, Literal, NamedTuple, TypeVar

_T = TypeVar("_T")
LOGGER = ...
READABLE_BY_OTHERS = ...
WRITABLE_BY_OTHERS = ...
SKIP_WARNING_ENV_VAR = ...

class ConfigSliceOptions(NamedTuple):
    check_permissions: bool = ...
    only_in_slice: bool = ...

class ConfigSlice(NamedTuple):
    path: Path
    options: ConfigSliceOptions
    section: str

class ConfigOption:
    def __init__(
        self,
        *,
        name: str,
        parse_str: Callable[[str], _T] | None = ...,
        choices: Iterable[Any] | None = ...,
        env_name: str | None | Literal[False] = ...,
        default: Any | None = ...,
        _root_manager: ConfigManager | None = ...,
        _nest_path: list[str] | None,
    ) -> None: ...
    def value(self) -> Any: ...
    @property
    def option_name(self) -> str: ...
    @property
    def default_env_name(self) -> str: ...

class ConfigManager:
    def __init__(self, *, name: str, file_path: Path | None = ..., _slices: list[ConfigSlice] | None = ...) -> None: ...
    def read_config(self, skip_file_permissions_check: bool = ...) -> None: ...
    def add_option(self, *, option_cls: type[ConfigOption] = ..., **kwargs) -> None: ...
    def add_submanager(self, new_child: ConfigManager) -> None: ...
    def add_subparser(self, *args, **kwargs) -> None: ...
    def __getitem__(self, name: str) -> ConfigOption | ConfigManager: ...

CONFIG_MANAGER = ...

def __getattr__(name): ...

__all__ = ["CONFIG_MANAGER", "CONFIG_PARSER", "ConfigManager", "ConfigOption"]
