import pathlib
import sys
import uuid
from collections.abc import Callable, Generator, Iterable
from functools import cached_property
from io import StringIO
from types import TracebackType
from typing import Any, NamedTuple, Self, TypeVar

from .auth import AuthByPlugin
from .constants import QueryStatus
from .converter import SnowflakeConverter
from .cursor import SnowflakeCursor, SnowflakeCursorBase
from .network import SnowflakeRestful

if sys.version_info >= (3, 13) or typing.TYPE_CHECKING:
    CursorCls = TypeVar("CursorCls", bound=SnowflakeCursorBase, default=SnowflakeCursor)
else: ...
DEFAULT_CLIENT_PREFETCH_THREADS = ...
MAX_CLIENT_PREFETCH_THREADS = ...
MAX_CLIENT_FETCH_THREADS = ...
DEFAULT_BACKOFF_POLICY = ...

def DefaultConverterClass() -> type: ...

SUPPORTED_PARAMSTYLES = ...
DEFAULT_CONFIGURATION: dict[str, tuple[Any, type | tuple[type, ...]]] = ...
APPLICATION_RE = ...
logger = ...

class TypeAndBinding(NamedTuple):
    type: str
    binding: str | None

class SnowflakeConnection:
    OCSP_ENV_LOCK = ...
    def __init__(self, connection_name: str | None = ..., connections_file_path: pathlib.Path | None = ..., **kwargs) -> None: ...
    @property
    def insecure_mode(self) -> bool: ...
    @property
    def disable_ocsp_checks(self) -> bool: ...
    @property
    def ocsp_fail_open(self) -> bool: ...
    @property
    def cert_revocation_check_mode(self) -> str | None: ...
    @property
    def allow_certificates_without_crl_url(self) -> bool | None: ...
    @property
    def crl_connection_timeout_ms(self) -> int | None: ...
    @property
    def crl_read_timeout_ms(self) -> int | None: ...
    @property
    def crl_cache_validity_hours(self) -> float | None: ...
    @property
    def enable_crl_cache(self) -> bool | None: ...
    @property
    def enable_crl_file_cache(self) -> bool | None: ...
    @property
    def crl_cache_dir(self) -> str | None: ...
    @property
    def crl_cache_removal_delay_days(self) -> int | None: ...
    @property
    def crl_cache_cleanup_interval_hours(self) -> int | None: ...
    @property
    def crl_cache_start_cleanup(self) -> bool | None: ...
    @property
    def crl_download_max_size(self) -> int | None: ...
    @property
    def skip_file_permissions_check(self) -> bool | None: ...
    @property
    def session_id(self) -> int: ...
    @property
    def user(self) -> str: ...
    @property
    def host(self) -> str: ...
    @property
    def port(self) -> int: ...
    @property
    def region(self) -> str | None: ...
    @property
    def proxy_host(self) -> str | None: ...
    @property
    def proxy_port(self) -> str | None: ...
    @property
    def proxy_user(self) -> str | None: ...
    @property
    def proxy_password(self) -> str | None: ...
    @property
    def no_proxy(self) -> str | Iterable | None: ...
    @property
    def account(self) -> str: ...
    @property
    def database(self) -> str | None: ...
    @property
    def schema(self) -> str | None: ...
    @property
    def warehouse(self) -> str | None: ...
    @property
    def role(self) -> str | None: ...
    @property
    def login_timeout(self) -> int | None: ...
    @property
    def network_timeout(self) -> int | None: ...
    @property
    def socket_timeout(self) -> int | None: ...
    @property
    def client_session_keep_alive(self) -> bool | None: ...
    @client_session_keep_alive.setter
    def client_session_keep_alive(self, value) -> None: ...
    @property
    def client_session_keep_alive_heartbeat_frequency(self) -> int | None: ...
    @client_session_keep_alive_heartbeat_frequency.setter
    def client_session_keep_alive_heartbeat_frequency(self, value) -> None: ...
    @property
    def platform_detection_timeout_seconds(self) -> float | None: ...
    @platform_detection_timeout_seconds.setter
    def platform_detection_timeout_seconds(self, value) -> None: ...
    @property
    def client_prefetch_threads(self) -> int: ...
    @client_prefetch_threads.setter
    def client_prefetch_threads(self, value) -> None: ...
    @property
    def client_fetch_threads(self) -> int | None: ...
    @client_fetch_threads.setter
    def client_fetch_threads(self, value: None | int) -> None: ...
    @property
    def client_fetch_use_mp(self) -> bool: ...
    @property
    def rest(self) -> SnowflakeRestful | None: ...
    @property
    def application(self) -> str: ...
    @property
    def errorhandler(self) -> Callable: ...
    @errorhandler.setter
    def errorhandler(self, value: Callable | None) -> None: ...
    @property
    def converter_class(self) -> type[SnowflakeConverter]: ...
    @property
    def validate_default_parameters(self) -> bool: ...
    @property
    def is_pyformat(self) -> bool: ...
    @property
    def consent_cache_id_token(self): ...
    @property
    def telemetry_enabled(self) -> bool: ...
    @telemetry_enabled.setter
    def telemetry_enabled(self, value) -> None: ...
    @property
    def service_name(self) -> str | None: ...
    @service_name.setter
    def service_name(self, value) -> None: ...
    @property
    def log_max_query_length(self) -> int: ...
    @property
    def disable_request_pooling(self) -> bool: ...
    @disable_request_pooling.setter
    def disable_request_pooling(self, value) -> None: ...
    @property
    def use_openssl_only(self) -> bool: ...
    @property
    def arrow_number_to_decimal(self): ...
    @property
    def enable_stage_s3_privatelink_for_us_east_1(self) -> bool: ...
    @enable_stage_s3_privatelink_for_us_east_1.setter
    def enable_stage_s3_privatelink_for_us_east_1(self, value) -> None: ...
    @property
    def enable_connection_diag(self) -> bool: ...
    @property
    def connection_diag_log_path(self): ...
    @property
    def connection_diag_whitelist_path(self): ...
    @property
    def connection_diag_allowlist_path(self): ...
    @arrow_number_to_decimal.setter
    def arrow_number_to_decimal_setter(self, value: bool) -> None: ...
    @property
    def auth_class(self) -> AuthByPlugin | None: ...
    @auth_class.setter
    def auth_class(self, value: AuthByPlugin) -> None: ...
    @property
    def is_query_context_cache_disabled(self) -> bool: ...
    @property
    def iobound_tpe_limit(self) -> int | None: ...
    @property
    def unsafe_file_write(self) -> bool: ...
    @unsafe_file_write.setter
    def unsafe_file_write(self, value: bool) -> None: ...
    @property
    def check_arrow_conversion_error_on_every_column(self) -> bool: ...
    @cached_property
    def snowflake_version(self) -> str: ...
    @check_arrow_conversion_error_on_every_column.setter
    def check_arrow_conversion_error_on_every_column(self, value: bool) -> bool: ...
    def connect(self, **kwargs) -> None: ...
    def close(self, retry: bool = ...) -> None: ...
    def is_closed(self) -> bool: ...
    def autocommit(self, mode) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def cursor(self, cursor_class: type[CursorCls] = ...) -> CursorCls: ...
    def execute_string(
        self, sql_text: str, remove_comments: bool = ..., return_cursors: bool = ..., cursor_class: SnowflakeCursor = ..., **kwargs
    ) -> Iterable[SnowflakeCursor]: ...
    def execute_stream(
        self, stream: StringIO, remove_comments: bool = ..., cursor_class: SnowflakeCursor = ..., **kwargs
    ) -> Generator[SnowflakeCursor]: ...
    @staticmethod
    def setup_ocsp_privatelink(app, hostname) -> None: ...
    def cmd_query(
        self,
        sql: str,
        sequence_counter: int,
        request_id: uuid.UUID,
        binding_params: None | tuple | dict[str, dict[str, str]] = ...,
        binding_stage: str | None = ...,
        is_file_transfer: bool = ...,
        statement_params: dict[str, str] | None = ...,
        is_internal: bool = ...,
        describe_only: bool = ...,
        _no_results: bool = ...,
        _update_current_object: bool = ...,
        _no_retry: bool = ...,
        timeout: int | None = ...,
        dataframe_ast: str | None = ...,
    ) -> dict[str, Any]: ...
    def authenticate_with_retry(self, auth_instance) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None: ...
    def get_query_status(self, sf_qid: str) -> QueryStatus: ...
    def get_query_status_throw_if_error(self, sf_qid: str) -> QueryStatus: ...
    def initialize_query_context_cache(self) -> None: ...
    def get_query_context(self) -> dict | None: ...
    def set_query_context(self, data: dict) -> None: ...
    @staticmethod
    def is_still_running(status: QueryStatus) -> bool: ...
    @staticmethod
    def is_an_error(status: QueryStatus) -> bool: ...
    def is_valid(self) -> bool: ...

class _ConnectionsRegistry:
    def __init__(self) -> None: ...
    def add_connection(self, connection: SnowflakeConnection) -> None: ...
    def remove_connection(self, connection: SnowflakeConnection) -> None: ...
    def get_connection_count(self) -> int: ...

_connections_registry = ...
