from collections import defaultdict
from collections.abc import Callable
from enum import Enum, unique
from typing import TYPE_CHECKING, Any, NamedTuple

from pyarrow import DataType

from .cursor import ResultMetadataV2

if TYPE_CHECKING: ...
DIRS = ...
CONNECTIONS_FILE = ...
CONFIG_FILE = ...
DBAPI_TYPE_STRING = ...
DBAPI_TYPE_BINARY = ...
DBAPI_TYPE_NUMBER = ...
DBAPI_TYPE_TIMESTAMP = ...
_DEFAULT_HOSTNAME_TLD = ...
_CHINA_HOSTNAME_TLD = ...
_TOP_LEVEL_DOMAIN_REGEX = ...
_SNOWFLAKE_HOST_SUFFIX_REGEX = ...
_PARAM_USE_SCOPED_TEMP_FOR_PANDAS_TOOLS = ...

class FieldType(NamedTuple):
    name: str
    dbapi_type: list[int]
    pa_type: Callable[[ResultMetadataV2], DataType]

def vector_pa_type(metadata: ResultMetadataV2) -> DataType: ...
def array_pa_type(metadata: ResultMetadataV2) -> DataType: ...
def map_pa_type(metadata: ResultMetadataV2) -> DataType: ...
def struct_pa_type(metadata: ResultMetadataV2) -> DataType: ...

FIELD_TYPES: tuple[FieldType, ...] = ...
FIELD_NAME_TO_ID: defaultdict[Any, int] = ...
FIELD_ID_TO_NAME: defaultdict[int, str] = ...
__binary_types: list[int] = ...
__binary_type_names: list[str] = ...
__string_types: list[int] = ...
__string_type_names: list[str] = ...
__number_types: list[int] = ...
__number_type_names: list[str] = ...
__timestamp_types: list[int] = ...
__timestamp_type_names: list[str] = ...

def get_binary_types() -> list[int]: ...
def is_binary_type_name(type_name: str) -> bool: ...
def get_string_types() -> list[int]: ...
def is_string_type_name(type_name) -> bool: ...
def get_number_types() -> list[int]: ...
def is_number_type_name(type_name) -> bool: ...
def get_timestamp_types() -> list[int]: ...
def is_timestamp_type_name(type_name) -> bool: ...
def is_date_type_name(type_name) -> bool: ...

LOG_FORMAT = ...
UTF8 = ...
SHA256_DIGEST = ...
S3_FS = ...
AZURE_FS = ...
GCS_FS = ...
LOCAL_FS = ...
CMD_TYPE_UPLOAD = ...
CMD_TYPE_DOWNLOAD = ...
FILE_PROTOCOL = ...

@unique
class ResultStatus(Enum):
    ERROR = ...
    SUCCEEDED = ...
    UPLOADED = ...
    DOWNLOADED = ...
    COLLISION = ...
    SKIPPED = ...
    RENEW_TOKEN = ...
    RENEW_PRESIGNED_URL = ...
    NOT_FOUND_FILE = ...
    NEED_RETRY = ...
    NEED_RETRY_WITH_LOWER_CONCURRENCY = ...

class SnowflakeS3FileEncryptionMaterial(NamedTuple):
    query_id: str
    query_stage_master_key: str
    smk_id: int

class MaterialDescriptor(NamedTuple):
    smk_id: int
    query_id: str
    key_size: int

class EncryptionMetadata(NamedTuple):
    key: str
    iv: str
    matdesc: str

class FileHeader(NamedTuple):
    digest: str | None
    content_length: int | None
    encryption_metadata: EncryptionMetadata | None

PARAMETER_AUTOCOMMIT = ...
PARAMETER_CLIENT_SESSION_KEEP_ALIVE_HEARTBEAT_FREQUENCY = ...
PARAMETER_CLIENT_SESSION_KEEP_ALIVE = ...
PARAMETER_CLIENT_PREFETCH_THREADS = ...
PARAMETER_CLIENT_TELEMETRY_ENABLED = ...
PARAMETER_CLIENT_TELEMETRY_OOB_ENABLED = ...
PARAMETER_CLIENT_STORE_TEMPORARY_CREDENTIAL = ...
PARAMETER_CLIENT_REQUEST_MFA_TOKEN = ...
PARAMETER_CLIENT_USE_SECURE_STORAGE_FOR_TEMPORARY_CREDENTIAL = ...
PARAMETER_QUERY_CONTEXT_CACHE_SIZE = ...
PARAMETER_TIMEZONE = ...
PARAMETER_SERVICE_NAME = ...
PARAMETER_CLIENT_VALIDATE_DEFAULT_PARAMETERS = ...
PARAMETER_PYTHON_CONNECTOR_QUERY_RESULT_FORMAT = ...
PARAMETER_ENABLE_STAGE_S3_PRIVATELINK_FOR_US_EAST_1 = ...
PARAMETER_MULTI_STATEMENT_COUNT = ...
HTTP_HEADER_CONTENT_TYPE = ...
HTTP_HEADER_CONTENT_ENCODING = ...
HTTP_HEADER_ACCEPT_ENCODING = ...
HTTP_HEADER_ACCEPT = ...
HTTP_HEADER_USER_AGENT = ...
HTTP_HEADER_SERVICE_NAME = ...
HTTP_HEADER_VALUE_OCTET_STREAM = ...
OCSP_ROOT_CERTS_DICT_LOCK_TIMEOUT_DEFAULT_NO_TIMEOUT: int = ...

@unique
class OCSPMode(Enum):
    FAIL_CLOSED = ...
    FAIL_OPEN = ...
    INSECURE = ...
    DISABLE_OCSP_CHECKS = ...

@unique
class FileTransferType(Enum):
    PUT = ...
    GET = ...

@unique
class QueryStatus(Enum):
    RUNNING = ...
    ABORTING = ...
    SUCCESS = ...
    FAILED_WITH_ERROR = ...
    ABORTED = ...
    QUEUED = ...
    FAILED_WITH_INCIDENT = ...
    DISCONNECTED = ...
    RESUMING_WAREHOUSE = ...
    QUEUED_REPARING_WAREHOUSE = ...
    RESTARTED = ...
    BLOCKED = ...
    NO_DATA = ...

kilobyte = ...
megabyte = ...
gigabyte = ...

@unique
class IterUnit(Enum):
    ROW_UNIT = ...
    TABLE_UNIT = ...

S3_DEFAULT_CHUNK_SIZE = ...
S3_MAX_OBJECT_SIZE = ...
S3_MAX_PART_SIZE = ...
S3_MIN_PART_SIZE = ...
S3_MAX_PARTS = ...
S3_CHUNK_SIZE = ...
AZURE_CHUNK_SIZE = ...
REQUEST_CONNECTION_TIMEOUT = ...
REQUEST_READ_TIMEOUT = ...
DAY_IN_SECONDS = ...
ENV_VAR_PARTNER = ...
ENV_VAR_TEST_MODE = ...
ENV_VAR_DISABLE_PLATFORM_DETECTION = ...
ENV_VAR_ENABLE_CUSTOM_REVOCATION_ERRORS = ...
ENV_VAR_BOOL_POSITIVE_VALUES_LOWERCASED = ...
_DOMAIN_NAME_MAP = ...
_CONNECTIVITY_ERR_MSG = ...
_OAUTH_DEFAULT_SCOPE = ...
OAUTH_TYPE_AUTHORIZATION_CODE = ...
OAUTH_TYPE_CLIENT_CREDENTIALS = ...
