from collections.abc import Callable
from datetime import datetime, tzinfo
from typing import TYPE_CHECKING, Any, NoReturn

if TYPE_CHECKING: ...
BITS_FOR_TIMEZONE = ...
ZERO_TIMEDELTA = ...
ZERO_EPOCH_DATE = ...
ZERO_EPOCH = ...
ZERO_FILL = ...
logger = ...
PYTHON_TO_SNOWFLAKE_TYPE = ...
type SnowflakeConverterType = Callable[[Any], Any]

def convert_datetime_to_epoch(dt: datetime) -> float: ...

class SnowflakeConverter:
    def __init__(self, **kwargs) -> None: ...
    def set_parameters(self, new_parameters: dict) -> None: ...
    def set_parameter(self, param: Any, value: Any) -> None: ...
    def get_parameters(self) -> dict[str, str | int | bool]: ...
    def get_parameter(self, param: str) -> str | int | bool | None: ...
    def to_python_method(self, type_name, column) -> SnowflakeConverterType: ...

    _TIMESTAMP_to_python = ...
    _OBJECT_to_python = ...
    _ARRAY_to_python = ...
    def snowflake_type(self, value: Any) -> str | None: ...
    def to_snowflake_bindings(self, snowflake_type: str, value: Any) -> str: ...

    _int_to_snowflake_bindings = ...
    _long_to_snowflake_bindings = ...
    _float_to_snowflake_bindings = ...
    _unicode_to_snowflake_bindings = ...
    _decimal_to_snowflake_bindings = ...
    _bytearray_to_snowflake_bindings = ...
    def to_snowflake(self, value: Any) -> Any: ...

    _unicode_to_snowflake = ...
    _bytearray_to_snowflake = ...
    _tuple_to_snowflake = ...
    _int8_to_snowflake = ...
    _int16_to_snowflake = ...
    _int32_to_snowflake = ...
    _int64_to_snowflake = ...
    _uint8_to_snowflake = ...
    _uint16_to_snowflake = ...
    _uint32_to_snowflake = ...
    _uint64_to_snowflake = ...
    _float32_to_snowflake = ...
    _float64_to_snowflake = ...
    def __getattr__(self, item: str) -> NoReturn: ...
    def to_csv_bindings(self, value: tuple[str, Any] | Any) -> str | None: ...
    @staticmethod
    def escape(value: Any) -> Any: ...
    @staticmethod
    def quote(value) -> str: ...
    @staticmethod
    def escape_for_csv(value: str) -> str: ...
    @staticmethod
    def get_seconds_microseconds(value: str, scale: int) -> tuple[int, int]: ...
    @staticmethod
    def create_timestamp_from_string(value: str, scale: int, tz: tzinfo | None = ...) -> datetime: ...
