from dataclasses import dataclass
from datetime import timedelta
from enum import Enum, unique
from pathlib import Path
from typing import Any

from cryptography import x509
from OpenSSL.SSL import Connection as SSLConnection

from .crl_cache import CRLCacheManager
from .session_manager import SessionManager

logger = ...

@unique
class CertRevocationCheckMode(Enum):
    DISABLED = ...
    ENABLED = ...
    ADVISORY = ...

class CRLValidationResult(Enum):
    REVOKED = ...
    UNREVOKED = ...
    ERROR = ...

@dataclass
class CRLConfig:
    cert_revocation_check_mode: CertRevocationCheckMode = ...
    allow_certificates_without_crl_url: bool = ...
    connection_timeout_ms: int = ...
    read_timeout_ms: int = ...
    cache_validity_time: timedelta = ...
    enable_crl_cache: bool = ...
    enable_crl_file_cache: bool = ...
    crl_cache_dir: Path | str | None = ...
    crl_cache_removal_delay_days: int = ...
    crl_cache_cleanup_interval_hours: int = ...
    crl_cache_start_cleanup: bool = ...
    crl_download_max_size: int = ...
    unsafe_skip_file_permissions_check: bool = ...
    @classmethod
    def from_connection(cls, sf_connection) -> CRLConfig: ...

class CRLValidator:
    def __init__(
        self,
        session_manager: SessionManager | Any,
        trusted_certificates: list[x509.Certificate],
        cert_revocation_check_mode: CertRevocationCheckMode = ...,
        allow_certificates_without_crl_url: bool = ...,
        connection_timeout_ms: int = ...,
        read_timeout_ms: int = ...,
        cache_validity_time: timedelta = ...,
        cache_manager: CRLCacheManager | None = ...,
        crl_download_max_size: int = ...,
    ) -> None: ...
    @classmethod
    def from_config(
        cls, config: CRLConfig, session_manager: SessionManager, trusted_certificates: list[x509.Certificate]
    ) -> CRLValidator: ...
    def validate_certificate_chain(self, peer_cert: x509.Certificate, chain: list[x509.Certificate] | None) -> bool: ...
    def validate_connection(self, connection: SSLConnection) -> bool: ...
