import threading
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime, timedelta
from pathlib import Path

from cryptography import x509

logger = ...

@dataclass
class CRLCacheEntry:
    crl: x509.CertificateRevocationList
    download_time: datetime
    def is_crl_expired_by(self, ts: datetime) -> bool: ...
    def is_evicted_by(self, ts: datetime, cache_validity_time: timedelta) -> bool: ...

class CRLCache(ABC):
    @abstractmethod
    def get(self, crl_url: str) -> CRLCacheEntry | None: ...
    @abstractmethod
    def put(self, crl_url: str, entry: CRLCacheEntry) -> None: ...
    @abstractmethod
    def cleanup(self) -> None: ...

class NoopCRLCache(CRLCache):
    INSTANCE = ...
    def __new__(cls): ...
    def get(self, crl_url: str) -> CRLCacheEntry | None: ...
    def put(self, crl_url: str, entry: CRLCacheEntry) -> None: ...
    def cleanup(self) -> None: ...

class CRLInMemoryCache(CRLCache):
    def __init__(self, cache_validity_time: timedelta) -> None: ...
    def get(self, crl_url: str) -> CRLCacheEntry | None: ...
    def put(self, crl_url: str, entry: CRLCacheEntry) -> None: ...
    def cleanup(self) -> None: ...

class CRLFileCache(CRLCache):
    def __init__(
        self, cache_dir: Path | None = ..., removal_delay: timedelta | None = ..., unsafe_skip_file_permissions_check: bool = ...
    ) -> None: ...
    def get(self, crl_url: str) -> CRLCacheEntry | None: ...
    def put(self, crl_url: str, entry: CRLCacheEntry) -> None: ...
    def cleanup(self) -> None: ...

class CRLCacheManager:
    def __init__(self, memory_cache: CRLCache, file_cache: CRLCache) -> None: ...
    @classmethod
    def noop(cls) -> CRLCacheManager: ...
    def get(self, crl_url: str) -> CRLCacheEntry | None: ...
    def put(self, crl_url: str, crl: x509.CertificateRevocationList, download_time: datetime) -> None: ...

class CRLCacheFactory:
    _memory_cache_instance = ...
    _file_cache_instance = ...
    _instance_lock = ...
    _cleanup_thread: threading.Thread | None = ...
    _cleanup_shutdown: threading.Event = ...
    _cleanup_interval: timedelta | None = ...
    _atexit_registered: bool = ...
    @classmethod
    def get_memory_cache(cls, cache_validity_time: timedelta) -> CRLInMemoryCache: ...
    @classmethod
    def get_file_cache(
        cls, cache_dir: Path | None = ..., removal_delay: timedelta | None = ..., unsafe_skip_file_permissions_check: bool = ...
    ) -> CRLFileCache: ...
    @classmethod
    def start_periodic_cleanup(cls, cleanup_interval: timedelta) -> None: ...
    @classmethod
    def stop_periodic_cleanup(cls) -> None: ...
    @classmethod
    def is_periodic_cleanup_running(cls) -> bool: ...
    @classmethod
    def reset(cls) -> None: ...
