import abc
import collections
from collections.abc import Callable, Iterator, Sequence
from enum import Enum, StrEnum
from types import TracebackType
from typing import IO, TYPE_CHECKING, Any, Literal, NamedTuple, NoReturn, Self, TypeVar, overload

from pandas import DataFrame
from pyarrow import Table

from .connection import SnowflakeConnection
from .constants import FileTransferType
from .file_transfer_agent import SnowflakeProgressPercentage
from .options import installed_pandas
from .result_batch import ResultBatch

if TYPE_CHECKING: ...
T = TypeVar("T", bound=collections.abc.Sequence)
FetchRow = TypeVar("FetchRow", bound=tuple[Any, ...] | dict[str, Any])
logger = ...
if not installed_pandas: ...
CAN_USE_ARROW_RESULT_FORMAT = ...
STATEMENT_TYPE_ID_DML = ...
STATEMENT_TYPE_ID_INSERT = ...
STATEMENT_TYPE_ID_UPDATE = ...
STATEMENT_TYPE_ID_DELETE = ...
STATEMENT_TYPE_ID_MERGE = ...
STATEMENT_TYPE_ID_MULTI_TABLE_INSERT = ...
STATEMENT_TYPE_ID_DML_SET = ...
DESC_TABLE_RE = ...
LOG_MAX_QUERY_LENGTH = ...
ASYNC_NO_DATA_MAX_RETRY = ...
ASYNC_RETRY_PATTERN = ...

class _NanoarrowUsage(StrEnum):
    FOLLOW_SESSION_PARAMETER = ...
    ENABLE_NANOARROW = ...
    DISABLE_NANOARROW = ...

class ResultMetadata(NamedTuple):
    name: str
    type_code: int
    display_size: int | None
    internal_size: int | None
    precision: int | None
    scale: int | None
    is_nullable: bool
    @classmethod
    def from_column(cls, col: dict[str, Any]): ...

class ResultMetadataV2:
    def __init__(
        self,
        name: str,
        type_code: int,
        is_nullable: bool,
        display_size: int | None = ...,
        internal_size: int | None = ...,
        precision: int | None = ...,
        scale: int | None = ...,
        vector_dimension: int | None = ...,
        fields: list[ResultMetadataV2] | None = ...,
    ) -> None: ...
    @classmethod
    def from_column(cls, col: dict[str, Any]) -> ResultMetadataV2: ...
    def __eq__(self, other) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def type_code(self) -> int: ...
    @property
    def is_nullable(self) -> bool: ...
    @property
    def internal_size(self) -> int | None: ...
    @property
    def display_size(self) -> int | None: ...
    @property
    def precision(self) -> int | None: ...
    @property
    def scale(self) -> int | None: ...
    @property
    def vector_dimension(self) -> int | None: ...
    @property
    def fields(self) -> list[ResultMetadataV2] | None: ...

def exit_handler(*_) -> NoReturn: ...

class ResultState(Enum):
    DEFAULT = ...
    VALID = ...
    RESET = ...

class SnowflakeCursorBase[FetchRow: tuple[Any, ...] | dict[str, Any]](abc.ABC):
    INSERT_SQL_RE = ...
    COMMENT_SQL_RE = ...
    INSERT_SQL_VALUES_RE = ...
    ALTER_SESSION_RE = ...
    @staticmethod
    def get_file_transfer_type(sql: str) -> FileTransferType | None: ...
    def __init__(self, connection: SnowflakeConnection) -> None: ...
    def __del__(self) -> None: ...
    @property
    def description(self) -> list[ResultMetadata]: ...
    @property
    def rowcount(self) -> int | None: ...
    @property
    def stats(self) -> QueryResultStats | None: ...
    @property
    def rownumber(self) -> int | None: ...
    @property
    def sfqid(self) -> str | None: ...
    @property
    def sqlstate(self): ...
    @property
    def timestamp_output_format(self) -> str | None: ...
    @property
    def timestamp_ltz_output_format(self) -> str | None: ...
    @property
    def timestamp_tz_output_format(self) -> str | None: ...
    @property
    def timestamp_ntz_output_format(self) -> str | None: ...
    @property
    def date_output_format(self) -> str | None: ...
    @property
    def time_output_format(self) -> str | None: ...
    @property
    def timezone(self) -> str | None: ...
    @property
    def binary_output_format(self) -> str | None: ...
    @property
    def arraysize(self) -> int: ...
    @arraysize.setter
    def arraysize(self, value) -> None: ...
    @property
    def connection(self) -> SnowflakeConnection: ...
    @property
    def errorhandler(self) -> Callable: ...
    @errorhandler.setter
    def errorhandler(self, value: Callable | None) -> None: ...
    @property
    def is_file_transfer(self) -> bool: ...
    @property
    def lastrowid(self) -> None: ...
    @overload
    def callproc(self, procname: str) -> tuple: ...
    @overload
    def callproc(self, procname: str, args: T) -> T: ...
    def callproc(self, procname: str, args=...): ...
    def close(self) -> bool | None: ...
    def is_closed(self) -> bool: ...
    @overload
    def execute(
        self,
        command: str,
        params: Sequence[Any] | dict[Any, Any] | None = ...,
        _bind_stage: str | None = ...,
        timeout: int | None = ...,
        _exec_async: bool = ...,
        _no_retry: bool = ...,
        _do_reset: bool = ...,
        _put_callback: SnowflakeProgressPercentage = ...,
        _put_azure_callback: SnowflakeProgressPercentage = ...,
        _put_callback_output_stream: IO[str] = ...,
        _get_callback: SnowflakeProgressPercentage = ...,
        _get_azure_callback: SnowflakeProgressPercentage = ...,
        _get_callback_output_stream: IO[str] = ...,
        _show_progress_bar: bool = ...,
        _statement_params: dict[str, str] | None = ...,
        _is_internal: bool = ...,
        _describe_only: bool = ...,
        _no_results: Literal[False] = ...,
        _is_put_get: bool | None = ...,
        _raise_put_get_error: bool = ...,
        _force_put_overwrite: bool = ...,
        _skip_upload_on_content_match: bool = ...,
        file_stream: IO[bytes] | None = ...,
        num_statements: int | None = ...,
        _dataframe_ast: str | None = ...,
    ) -> Self | None: ...
    @overload
    def execute(
        self,
        command: str,
        params: Sequence[Any] | dict[Any, Any] | None = ...,
        _bind_stage: str | None = ...,
        timeout: int | None = ...,
        _exec_async: bool = ...,
        _no_retry: bool = ...,
        _do_reset: bool = ...,
        _put_callback: SnowflakeProgressPercentage = ...,
        _put_azure_callback: SnowflakeProgressPercentage = ...,
        _put_callback_output_stream: IO[str] = ...,
        _get_callback: SnowflakeProgressPercentage = ...,
        _get_azure_callback: SnowflakeProgressPercentage = ...,
        _get_callback_output_stream: IO[str] = ...,
        _show_progress_bar: bool = ...,
        _statement_params: dict[str, str] | None = ...,
        _is_internal: bool = ...,
        _describe_only: bool = ...,
        _no_results: Literal[True] = ...,
        _is_put_get: bool | None = ...,
        _raise_put_get_error: bool = ...,
        _force_put_overwrite: bool = ...,
        _skip_upload_on_content_match: bool = ...,
        file_stream: IO[bytes] | None = ...,
        num_statements: int | None = ...,
        _dataframe_ast: str | None = ...,
    ) -> dict[str, Any] | None: ...
    def execute(
        self,
        command: str,
        params: Sequence[Any] | dict[Any, Any] | None = ...,
        _bind_stage: str | None = ...,
        timeout: int | None = ...,
        _exec_async: bool = ...,
        _no_retry: bool = ...,
        _do_reset: bool = ...,
        _put_callback: SnowflakeProgressPercentage = ...,
        _put_azure_callback: SnowflakeProgressPercentage = ...,
        _put_callback_output_stream: IO[str] = ...,
        _get_callback: SnowflakeProgressPercentage = ...,
        _get_azure_callback: SnowflakeProgressPercentage = ...,
        _get_callback_output_stream: IO[str] = ...,
        _show_progress_bar: bool = ...,
        _statement_params: dict[str, str] | None = ...,
        _is_internal: bool = ...,
        _describe_only: bool = ...,
        _no_results: bool = ...,
        _is_put_get: bool | None = ...,
        _raise_put_get_error: bool = ...,
        _force_put_overwrite: bool = ...,
        _skip_upload_on_content_match: bool = ...,
        file_stream: IO[bytes] | None = ...,
        num_statements: int | None = ...,
        _force_qmark_paramstyle: bool = ...,
        _dataframe_ast: str | None = ...,
    ) -> Self | dict[str, Any] | None: ...
    def execute_async(self, *args: Any, **kwargs: Any) -> dict[str, Any]: ...
    def describe(self, *args: Any, **kwargs: Any) -> list[ResultMetadata]: ...
    def check_can_use_arrow_resultset(self) -> None: ...
    def check_can_use_pandas(self) -> None: ...
    def query_result(self, qid: str) -> SnowflakeCursor: ...
    def fetch_arrow_batches(self, force_microsecond_precision: bool = ...) -> Iterator[Table]: ...
    @overload
    def fetch_arrow_all(self, force_return_table: Literal[False] = ..., force_microsecond_precision: bool = ...) -> Table | None: ...
    @overload
    def fetch_arrow_all(self, force_return_table: Literal[True], force_microsecond_precision: bool = ...) -> Table: ...
    def fetch_arrow_all(self, force_return_table: bool = ..., force_microsecond_precision: bool = ...) -> Table | None: ...
    def fetch_pandas_batches(self, **kwargs: Any) -> Iterator[DataFrame]: ...
    def fetch_pandas_all(self, **kwargs: Any) -> DataFrame: ...
    def abort_query(self, qid: str) -> bool: ...
    def executemany(self, command: str, seqparams: Sequence[Any] | dict[str, Any], **kwargs: Any) -> SnowflakeCursor: ...
    @abc.abstractmethod
    def fetchone(self) -> FetchRow: ...
    def fetchmany(self, size: int | None = ...) -> list[FetchRow]: ...
    def fetchall(self) -> list[FetchRow]: ...
    def nextset(self) -> SnowflakeCursor | None: ...
    def setinputsizes(self, _) -> None: ...
    def setoutputsize(self, _, column=...) -> None: ...
    def scroll(self, value, mode: str = ...) -> None: ...
    def reset(self, closing: bool = ...) -> None: ...
    def __iter__(self) -> Iterator[dict] | Iterator[tuple]: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None: ...
    def get_results_from_sfqid(self, sfqid: str) -> None: ...
    def get_result_batches(self) -> list[ResultBatch] | None: ...

class SnowflakeCursor(SnowflakeCursorBase[tuple[Any, ...]]):
    def fetchone(self) -> tuple[Any, ...] | None: ...

class DictCursor(SnowflakeCursorBase[dict[str, Any]]):
    def fetchone(self) -> dict[str, Any] | None: ...

def __getattr__(name): ...

class QueryResultStats(NamedTuple):
    num_rows_inserted: int | None = ...
    num_rows_deleted: int | None = ...
    num_rows_updated: int | None = ...
    num_dml_duplicates: int | None = ...
    @classmethod
    def from_dict(cls, stats_dict: dict[str, int]) -> QueryResultStats: ...
