import datetime

class _DBAPITypeObject:
    def __init__(self, *values) -> None: ...
    def __cmp__(self, other): ...

Date = datetime.date
Time = datetime.time
Timestamp = datetime.datetime

def DateFromTicks(ticks: float) -> datetime.date: ...
def TimeFromTicks(ticks: float) -> datetime.time: ...
def TimestampFromTicks(ticks: float) -> datetime.datetime: ...

Binary = bytes
STRING = ...
BINARY = ...
NUMBER = ...
DATETIME = ...
ROWID = ...
