from abc import ABC, abstractmethod
from typing import TYPE_CHECKING

from .connection import SnowflakeConnection

if TYPE_CHECKING: ...

class FileOperationParserBase(ABC):
    @abstractmethod
    def __init__(self, connection) -> None: ...
    @abstractmethod
    def parse_file_operation(
        self, stage_location, local_file_name, target_directory, command_type, options, has_source_from_stream=...
    ): ...

class StreamDownloaderBase(ABC):
    @abstractmethod
    def __init__(self, connection) -> None: ...
    @abstractmethod
    def download_as_stream(self, ret, decompress=...): ...

class FileOperationParser(FileOperationParserBase):
    def __init__(self, connection: SnowflakeConnection) -> None: ...
    def parse_file_operation(
        self, stage_location, local_file_name, target_directory, command_type, options, has_source_from_stream=...
    ): ...

class StreamDownloader(StreamDownloaderBase):
    def __init__(self, connection) -> None: ...
    def download_as_stream(self, ret, decompress=...): ...
