from typing import TYPE_CHECKING, Any

from .aio._connection import SnowflakeConnection as AsyncSnowflakeConnection
from .aio._cursor import SnowflakeCursor as AsyncSnowflakeCursor
from .connection import SnowflakeConnection
from .cursor import SnowflakeCursor
from .telemetry import TelemetryField

if TYPE_CHECKING: ...
logger = ...
connector_base_path = ...
RE_FORMATTED_ERROR = ...

class Error(Exception):
    def __init__(
        self,
        msg: str | None = ...,
        errno: int | None = ...,
        sqlstate: str | None = ...,
        sfqid: str | None = ...,
        query: str | None = ...,
        done_format_msg: bool | None = ...,
        connection: SnowflakeConnection | AsyncSnowflakeConnection | None = ...,
        cursor: SnowflakeCursor | AsyncSnowflakeCursor | None = ...,
        errtype: TelemetryField = ...,
        send_telemetry: bool = ...,
    ) -> None: ...
    @staticmethod
    def generate_telemetry_stacktrace() -> str: ...
    def telemetry_msg(self) -> str | None: ...
    def generate_telemetry_exception_data(self) -> dict[str, tuple[bool, str, str] | str]: ...
    def send_exception_telemetry(
        self, connection: SnowflakeConnection | AsyncSnowflakeConnection | None, telemetry_data: dict[str, Any]
    ) -> None: ...
    def exception_telemetry(
        self,
        msg: str,
        cursor: SnowflakeCursor | AsyncSnowflakeCursor | None,
        connection: SnowflakeConnection | AsyncSnowflakeConnection | None,
    ) -> None: ...
    @staticmethod
    def default_errorhandler(
        connection: SnowflakeConnection, cursor: SnowflakeCursor, error_class: type[Error], error_value: dict[str, str]
    ) -> None: ...
    @staticmethod
    def errorhandler_wrapper_from_cause(
        connection: SnowflakeConnection, cause: Error | Exception, cursor: SnowflakeCursor | None = ...
    ) -> None: ...
    @staticmethod
    def errorhandler_wrapper(
        connection: SnowflakeConnection | None,
        cursor: SnowflakeCursor | None,
        error_class: type[Error | Exception],
        error_value: dict[str, Any],
    ) -> None: ...
    @staticmethod
    def errorhandler_wrapper_from_ready_exception(
        connection: SnowflakeConnection | None, cursor: SnowflakeCursor | None, error_exc: Error | Exception
    ) -> None: ...
    @staticmethod
    def hand_to_other_handler(
        connection: SnowflakeConnection | None,
        cursor: SnowflakeCursor | None,
        error_class: type[Error | Exception],
        error_value: dict[str, str | bool],
    ) -> bool: ...
    @staticmethod
    def errorhandler_make_exception(error_class: type[Error | Exception], error_value: dict[str, str | bool]) -> Error | Exception: ...

class _Warning(Exception): ...
class InterfaceError(Error): ...

class HttpError(Error):
    def __init__(self, **kwargs) -> None: ...

class DatabaseError(Error): ...
class InternalError(DatabaseError): ...
class OperationalError(DatabaseError): ...
class ProgrammingError(DatabaseError): ...
class IntegrityError(DatabaseError): ...
class DataError(DatabaseError): ...

class NotSupportedError(DatabaseError):
    def telemetry_msg(self) -> str: ...

class RevocationCheckError(OperationalError):
    def __init__(self, **kwargs) -> None: ...

class InternalServerError(Error):
    def __init__(self, **kwargs) -> None: ...

class ServiceUnavailableError(Error):
    def __init__(self, **kwargs) -> None: ...

class GatewayTimeoutError(Error):
    def __init__(self, **kwargs) -> None: ...

class ForbiddenError(Error):
    def __init__(self, **kwargs) -> None: ...

class RequestTimeoutError(Error):
    def __init__(self, **kwargs) -> None: ...

class BadRequest(Error):
    def __init__(self, **kwargs) -> None: ...

class BadGatewayError(Error):
    def __init__(self, **kwargs) -> None: ...

class MethodNotAllowed(Error):
    def __init__(self, **kwargs) -> None: ...

class TooManyRequests(Error):
    def __init__(self, **kwargs) -> None: ...

class RefreshTokenError(Error):
    def __init__(self, **kwargs) -> None: ...

class OtherHTTPRetryableError(Error):
    def __init__(self, **kwargs) -> None: ...

class MissingDependencyError(Error):
    def __init__(self, dependency: str) -> None: ...

class BindUploadError(Error): ...
class RequestExceedMaxRetryError(Error): ...
class TokenExpiredError(Error): ...
class PresignedUrlExpiredError(Error): ...
class ConfigSourceError(Error): ...
class MissingConfigOptionError(ConfigSourceError): ...
class ConfigManagerError(Error): ...
