from typing import IO

logger = ...

def owner_rw_opener(path, flags) -> int: ...

class SnowflakeFileUtil:
    @staticmethod
    def get_digest_and_size(src: IO[bytes]) -> tuple[str, int]: ...
    @staticmethod
    def compress_with_gzip_from_stream(src_stream: IO[bytes]) -> tuple[IO[bytes], int]: ...
    @staticmethod
    def compress_file_with_gzip(file_name: str, tmp_dir: str) -> tuple[str, int]: ...
    @staticmethod
    def normalize_gzip_header(gzip_file_name: str) -> None: ...
    @staticmethod
    def get_digest_and_size_for_stream(src_stream: IO[bytes]) -> tuple[str, int]: ...
    @staticmethod
    def get_digest_and_size_for_file(file_name: str) -> tuple[str, int]: ...
