from pathlib import Path

MAX_RETRIES = ...
INITIAL_BACKOFF_SECONDS = ...
STALE_LOCK_AGE_SECONDS = ...

class FileLockError(Exception): ...

class FileLock:
    def __init__(self, path: Path) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type, exc_val, exc_tbc): ...
