from dataclasses import dataclass
from typing import IO, TYPE_CHECKING, Any

from .connection import SnowflakeConnection
from .constants import ResultStatus
from .cursor import SnowflakeCursor
from .file_compression_type import CompressionType
from .storage_client import SnowflakeFileEncryptionMaterial

if TYPE_CHECKING: ...
VALID_STORAGE = ...
INJECT_WAIT_IN_PUT = ...
logger = ...

def result_text_column_desc(name: str) -> dict[str, Any]: ...
def result_fixed_column_desc(name: str) -> dict[str, Any]: ...

@dataclass
class SnowflakeFileMeta:
    name: str
    src_file_name: str
    stage_location_type: str
    result_status: ResultStatus | None = ...
    sfagent: SnowflakeFileTransferAgent | None = ...
    put_callback: type[SnowflakeProgressPercentage] | None = ...
    put_azure_callback: type[SnowflakeProgressPercentage] | None = ...
    put_callback_output_stream: IO[str] | None = ...
    get_callback: type[SnowflakeProgressPercentage] | None = ...
    get_azure_callback: type[SnowflakeProgressPercentage] | None = ...
    get_callback_output_stream: IO[str] | None = ...
    show_progress_bar: bool = ...
    multipart_threshold: int = ...
    presigned_url: str | None = ...
    overwrite: bool = ...
    sha256_digest: str | None = ...
    upload_size: int | None = ...
    real_src_file_name: str | None = ...
    error_details: Exception | None = ...
    last_error: Exception | None = ...
    no_sleeping_time: bool = ...
    gcs_file_header_digest: str | None = ...
    gcs_file_header_content_length: int | None = ...
    gcs_file_header_encryption_metadata: dict[str, Any] | None = ...
    encryption_material: SnowflakeFileEncryptionMaterial | None = ...
    src_file_size: int = ...
    src_compression_type: CompressionType | None = ...
    dst_compression_type: CompressionType = ...
    require_compress: bool = ...
    dst_file_name: str | None = ...
    dst_file_size: int = ...
    intermediate_stream: IO[bytes] | None = ...
    src_stream: IO[bytes] | None = ...
    skip_upload_on_content_match: bool = ...
    local_location: str | None = ...

def percent(seen_so_far: int, size: float) -> float: ...

class SnowflakeProgressPercentage:
    def __init__(self, filename: str, filesize: float, output_stream: IO | None = ..., show_progress_bar: bool | None = ...) -> None: ...
    def __call__(self, bytes_amount: int): ...

class SnowflakeS3ProgressPercentage(SnowflakeProgressPercentage):
    def __init__(self, filename: str, filesize: float, output_stream: IO | None = ..., show_progress_bar: bool | None = ...) -> None: ...
    def __call__(self, bytes_amount: int) -> None: ...

class SnowflakeAzureProgressPercentage(SnowflakeProgressPercentage):
    def __init__(self, filename: str, filesize: float, output_stream: IO | None = ..., show_progress_bar: bool | None = ...) -> None: ...
    def __call__(self, current: int) -> None: ...

class StorageCredential:
    def __init__(self, credentials: dict[str, Any], connection: SnowflakeConnection, command: str) -> None: ...
    def update(self, cur_timestamp) -> None: ...

@dataclass
class TransferMetadata:
    num_files_started: int = ...
    num_files_completed: int = ...
    chunks_in_queue: int = ...

class SnowflakeFileTransferAgent:
    def __init__(
        self,
        cursor: SnowflakeCursor,
        command: str,
        ret: dict[str, Any],
        put_callback: type[SnowflakeProgressPercentage] | None = ...,
        put_azure_callback: type[SnowflakeProgressPercentage] | None = ...,
        put_callback_output_stream: IO[str] = ...,
        get_callback: type[SnowflakeProgressPercentage] | None = ...,
        get_azure_callback: type[SnowflakeProgressPercentage] | None = ...,
        get_callback_output_stream: IO[str] = ...,
        show_progress_bar: bool = ...,
        raise_put_get_error: bool = ...,
        force_put_overwrite: bool = ...,
        skip_upload_on_content_match: bool = ...,
        multipart_threshold: int | None = ...,
        source_from_stream: IO[bytes] | None = ...,
        use_s3_regional_url: bool = ...,
        iobound_tpe_limit: int | None = ...,
        unsafe_file_write: bool = ...,
        snowflake_server_dop_cap_for_file_transfer=...,
        reraise_error_in_file_transfer_work_function: bool = ...,
    ) -> None: ...
    def execute(self) -> None: ...
    def transfer(self, metas: list[SnowflakeFileMeta]) -> None: ...
    def result(self) -> dict[str, Any]: ...
