from typing import TYPE_CHECKING, Any, NamedTuple

from .connection import SnowflakeConnection
from .constants import FileHeader
from .file_transfer_agent import SnowflakeFileMeta, StorageCredential
from .storage_client import SnowflakeStorageClient

if TYPE_CHECKING: ...
logger = ...
GCS_METADATA_PREFIX = ...
GCS_METADATA_SFC_DIGEST = ...
GCS_METADATA_MATDESC_KEY = ...
GCS_METADATA_ENCRYPTIONDATAPROP = ...
GCS_FILE_HEADER_DIGEST = ...
GCS_FILE_HEADER_CONTENT_LENGTH = ...
GCS_FILE_HEADER_ENCRYPTION_METADATA = ...
GCS_REGION_ME_CENTRAL_2 = ...
CONTENT_CHUNK_SIZE = ...
ACCESS_TOKEN = ...

class GcsLocation(NamedTuple):
    bucket_name: str
    path: str
    endpoint: str = ...

class SnowflakeGCSRestClient(SnowflakeStorageClient):
    def __init__(
        self,
        meta: SnowflakeFileMeta,
        credentials: StorageCredential,
        stage_info: dict[str, Any],
        cnx: SnowflakeConnection,
        command: str,
        unsafe_file_write: bool = ...,
    ) -> None: ...
    def download_chunk(self, chunk_id: int) -> None: ...
    def finish_download(self) -> None: ...
    def get_file_header(self, filename: str) -> FileHeader | None: ...
    @staticmethod
    def get_location(
        stage_location: str, use_regional_url: str = ..., region: str = ..., endpoint: str = ..., use_virtual_url: bool = ...
    ) -> GcsLocation: ...
    @staticmethod
    def generate_file_url(
        stage_location: str, filename: str, use_regional_url: str = ..., region: str = ..., endpoint: str = ..., use_virtual_url: bool = ...
    ) -> str: ...
