from typing import TYPE_CHECKING, Any

from .constants import FileHeader
from .file_transfer_agent import SnowflakeFileMeta
from .storage_client import SnowflakeStorageClient

if TYPE_CHECKING: ...
logger = ...

class SnowflakeLocalStorageClient(SnowflakeStorageClient):
    def __init__(self, meta: SnowflakeFileMeta, stage_info: dict[str, Any], chunk_size: int, unsafe_file_write: bool = ...) -> None: ...
    def get_file_header(self, filename: str) -> FileHeader | None: ...
    def download_chunk(self, chunk_id: int) -> None: ...
    def finish_download(self) -> None: ...
    def prepare_upload(self) -> None: ...
    def finish_upload(self) -> None: ...
