LOG_FILE_NAME = ...

class EasyLoggingConfigPython:
    def __init__(self, skip_config_file_permissions_check: bool = ...) -> None: ...
    def parse_config_file(self, skip_config_file_permissions_check: bool = ...): ...
    def create_log(self): ...
