import json
from collections.abc import Generator
from typing import TYPE_CHECKING, Any

from snowflake.connector.vendored.requests.models import PreparedRequest

from .connection import SnowflakeConnection
from .description import (
    CLIENT_NAME,
    CLIENT_VERSION,
    COMPILER,
    IMPLEMENTATION,
    OPERATING_SYSTEM,
    PLATFORM,
    PYTHON_VERSION,
    SNOWFLAKE_CONNECTOR_VERSION,
)
from .errors import Error
from .session_manager import SessionManager, SessionPool
from .vendored.requests import Response, Session
from .vendored.requests.auth import AuthBase

if TYPE_CHECKING: ...
logger = ...
APPLICATION_SNOWSQL = ...
DEFAULT_SOCKET_CONNECT_TIMEOUT = ...
QUERY_IN_PROGRESS_CODE = ...
QUERY_IN_PROGRESS_ASYNC_CODE = ...
ID_TOKEN_EXPIRED_GS_CODE = ...
SESSION_EXPIRED_GS_CODE = ...
MASTER_TOKEN_NOTFOUND_GS_CODE = ...
MASTER_TOKEN_EXPIRED_GS_CODE = ...
MASTER_TOKEN_INVALD_GS_CODE = ...
ID_TOKEN_INVALID_LOGIN_REQUEST_GS_CODE = ...
BAD_REQUEST_GS_CODE = ...
OAUTH_ACCESS_TOKEN_EXPIRED_GS_CODE = ...
CONTENT_TYPE_APPLICATION_JSON = ...
ACCEPT_TYPE_APPLICATION_SNOWFLAKE = ...
REQUEST_TYPE_RENEW = ...
HEADER_AUTHORIZATION_KEY = ...
HEADER_SNOWFLAKE_TOKEN = ...
HEADER_EXTERNAL_SESSION_KEY = ...
REQUEST_ID = ...
REQUEST_GUID = ...
SNOWFLAKE_HOST_SUFFIX = ...
SNOWFLAKE_CONNECTOR_VERSION = ...
PYTHON_VERSION = ...
OPERATING_SYSTEM = ...
PLATFORM = ...
IMPLEMENTATION = ...
COMPILER = ...
CLIENT_NAME = ...
CLIENT_VERSION = ...
PYTHON_CONNECTOR_USER_AGENT = ...
NO_TOKEN = ...
STATUS_TO_EXCEPTION: dict[int, type[Error]] = ...
DEFAULT_AUTHENTICATOR = ...
EXTERNAL_BROWSER_AUTHENTICATOR = ...
KEY_PAIR_AUTHENTICATOR = ...
OAUTH_AUTHENTICATOR = ...
OAUTH_AUTHORIZATION_CODE = ...
OAUTH_CLIENT_CREDENTIALS = ...
ID_TOKEN_AUTHENTICATOR = ...
USR_PWD_MFA_AUTHENTICATOR = ...
PROGRAMMATIC_ACCESS_TOKEN = ...
NO_AUTH_AUTHENTICATOR = ...
WORKLOAD_IDENTITY_AUTHENTICATOR = ...
PAT_WITH_EXTERNAL_SESSION = ...

def is_retryable_http_code(code: int) -> bool: ...
def get_http_retryable_error(status_code: int) -> Error: ...
def raise_okta_unauthorized_error(connection: SnowflakeConnection | None, response: Response) -> None: ...
def raise_failed_request_error(connection: SnowflakeConnection | None, url: str, method: str, response: Response) -> None: ...
def is_login_request(url: str) -> bool: ...
def is_econnreset_exception(e: Exception) -> bool: ...

class RetryRequest(Exception): ...

class ReauthenticationRequest(Exception):
    def __init__(self, cause) -> None: ...

class SnowflakeAuth(AuthBase):
    def __init__(self, token) -> None: ...
    def __call__(self, r: PreparedRequest) -> PreparedRequest: ...

class PATWithExternalSessionAuth(AuthBase):
    def __init__(self, token, external_session_id) -> None: ...
    def __call__(self, r: PreparedRequest) -> PreparedRequest: ...

class SnowflakeRestfulJsonEncoder(json.JSONEncoder):
    def default(self, o): ...

class SnowflakeRestful:
    def __init__(
        self,
        host: str = ...,
        port: int = ...,
        protocol: str = ...,
        inject_client_pause: int = ...,
        connection: SnowflakeConnection | None = ...,
        session_manager: SessionManager | None = ...,
    ) -> None: ...
    @property
    def token(self) -> str | None: ...
    @property
    def external_session_id(self) -> str | None: ...
    @property
    def master_token(self) -> str | None: ...
    @property
    def master_validity_in_seconds(self) -> int: ...
    @master_validity_in_seconds.setter
    def master_validity_in_seconds(self, value) -> None: ...
    @property
    def id_token(self): ...
    @id_token.setter
    def id_token(self, value) -> None: ...
    @property
    def mfa_token(self) -> str | None: ...
    @mfa_token.setter
    def mfa_token(self, value: str) -> None: ...
    @property
    def server_url(self) -> str: ...
    @property
    def session_manager(self) -> SessionManager: ...
    @property
    def sessions_map(self) -> dict[str, SessionPool]: ...
    def close(self) -> None: ...
    def request(
        self,
        url,
        body=...,
        method: str = ...,
        client: str = ...,
        timeout: int | None = ...,
        _no_results: bool = ...,
        _include_retry_params: bool = ...,
        _no_retry: bool = ...,
    ): ...
    def update_tokens(self, session_token, master_token, master_validity_in_seconds=..., id_token=..., mfa_token=...) -> None: ...
    def set_pat_and_external_session(self, personal_access_token, external_session_id) -> None: ...
    def delete_session(self, retry: bool = ...) -> None: ...
    def fetch(
        self, method: str, full_url: str, headers: dict[str, Any], data: dict[str, Any] | None = ..., timeout: int | None = ..., **kwargs
    ) -> dict[Any, Any]: ...
    @staticmethod
    def add_request_guid(full_url: str) -> str: ...
    def log_and_handle_http_error_with_cause(
        self,
        e: Exception,
        full_url: str,
        method: str,
        retry_timeout: int,
        retry_count: int,
        conn: SnowflakeConnection,
        timed_out: bool = ...,
    ) -> None: ...
    def handle_invalid_certificate_error(self, conn, full_url, cause) -> None: ...
    def use_session(self, url: str | bytes) -> Generator[Session, Any]: ...
    def use_requests_session(self, url: str | bytes) -> Generator[Session, Any]: ...
