from typing import Any, NamedTuple

from asn1crypto.ocsp import CertId, OCSPRequest
from asn1crypto.x509 import Certificate
from OpenSSL.SSL import Connection

from .cache import SFDictFileCache

class OCSPResponseValidationResult(NamedTuple):
    exception: Exception | None = ...
    issuer: Certificate | None = ...
    subject: Certificate | None = ...
    cert_id: CertId | None = ...
    ocsp_response: bytes | None = ...
    ts: int | None = ...
    validated: bool = ...

class _OCSPResponseValidationResultCache(SFDictFileCache): ...

OCSP_RESPONSE_VALIDATION_CACHE: SFDictFileCache[tuple[bytes, bytes, bytes], OCSPResponseValidationResult] = ...
logger = ...

def generate_cache_key(cert_id: CertId) -> tuple[bytes, bytes, bytes]: ...

class OCSPTelemetryData:
    CERTIFICATE_EXTRACTION_FAILED = ...
    OCSP_URL_MISSING = ...
    OCSP_RESPONSE_UNAVAILABLE = ...
    OCSP_RESPONSE_FETCH_EXCEPTION = ...
    OCSP_RESPONSE_FAILED_TO_CONNECT_CACHE_SERVER = ...
    OCSP_RESPONSE_CERT_STATUS_INVALID = ...
    OCSP_RESPONSE_CERT_STATUS_REVOKED = ...
    OCSP_RESPONSE_CERT_STATUS_UNKNOWN = ...
    OCSP_RESPONSE_STATUS_UNSUCCESSFUL = ...
    OCSP_RESPONSE_ATTACHED_CERT_INVALID = ...
    OCSP_RESPONSE_ATTACHED_CERT_EXPIRED = ...
    OCSP_RESPONSE_INVALID_SIGNATURE = ...
    OCSP_RESPONSE_EXPIRY_INFO_MISSING = ...
    OCSP_RESPONSE_EXPIRED = ...
    OCSP_RESPONSE_FETCH_FAILURE = ...
    OCSP_RESPONSE_CACHE_DOWNLOAD_FAILED = ...
    OCSP_RESPONSE_CACHE_DECODE_FAILED = ...
    OCSP_RESPONSE_LOAD_FAILURE = ...
    OCSP_RESPONSE_INVALID_SSD = ...
    ERROR_CODE_MAP = ...
    def __init__(self) -> None: ...
    def set_event_sub_type(self, event_sub_type: str) -> None: ...
    def set_ocsp_connection_method(self, ocsp_conn_method: str) -> None: ...
    def set_cert_id(self, cert_id) -> None: ...
    def set_sfc_peer_host(self, sfc_peer_host) -> None: ...
    def set_ocsp_url(self, ocsp_url) -> None: ...
    def set_ocsp_req(self, ocsp_req) -> None: ...
    def set_error_msg(self, error_msg) -> None: ...
    def set_cache_enabled(self, cache_enabled) -> None: ...
    def set_cache_hit(self, cache_hit) -> None: ...
    def set_fail_open(self, fail_open) -> None: ...
    def set_insecure_mode(self, insecure_mode) -> None: ...
    def set_disable_ocsp_checks(self, disable_ocsp_checks) -> None: ...
    def generate_telemetry_data(self, event_type: str, urgent: bool = ...) -> dict[str, Any]: ...

class OCSPServer:
    MAX_RETRY = ...
    def __init__(self, **kwargs) -> None: ...
    @staticmethod
    def is_enabled_new_ocsp_endpoint() -> bool: ...
    def reset_ocsp_endpoint(self, hname) -> None: ...
    def reset_ocsp_dynamic_cache_server_url(self, use_ocsp_cache_server) -> None: ...
    def download_cache_from_server(self, ocsp): ...
    def generate_get_url(self, ocsp_url, b64data): ...

class OCSPCache:
    CACHE_LOCK = ...
    CACHE_UPDATED = ...
    CACHE_EXPIRATION = ...
    OCSP_RESPONSE_CACHE_URI = ...
    OCSP_RESPONSE_CACHE_FILE_NAME = ...
    CACHE_DIR = ...
    @staticmethod
    def reset_cache_dir() -> None: ...
    @staticmethod
    def del_cache_file() -> None: ...
    @staticmethod
    def reset_ocsp_response_cache_uri(ocsp_response_cache_uri) -> None: ...
    @staticmethod
    def read_file(ocsp): ...
    @staticmethod
    def read_ocsp_response_cache_file(ocsp, filename): ...
    @staticmethod
    def update_file(ocsp) -> None: ...
    @staticmethod
    def update_ocsp_response_cache_file(ocsp, ocsp_response_cache_uri) -> None: ...
    @staticmethod
    def write_ocsp_response_cache_file(ocsp, filename) -> None: ...
    @staticmethod
    def check_ocsp_response_cache_lock_dir(filename) -> bool: ...
    @staticmethod
    def is_cache_fresh(current_time: int, ts: int) -> bool: ...
    @staticmethod
    def find_cache(ocsp: SnowflakeOCSP, cert_id: CertId, subject: Certificate | None, **kwargs: Any) -> tuple[bool, bytes | None]: ...
    @staticmethod
    def delete_cache(ocsp: SnowflakeOCSP, cert_id: CertId, **kwargs: Any) -> None: ...
    @staticmethod
    def lock_cache_file(fname) -> bool: ...
    @staticmethod
    def unlock_cache_file(fname) -> bool: ...
    @staticmethod
    def delete_cache_file() -> None: ...
    @staticmethod
    def clear_cache() -> None: ...
    @staticmethod
    def cache_size(): ...

class SnowflakeOCSP:
    ROOT_CERTIFICATES_DICT = ...
    ROOT_CERTIFICATES_DICT_LOCK = ...
    OCSP_CACHE = ...
    OCSP_WHITELIST = ...
    TOLERABLE_VALIDITY_RANGE_RATIO = ...
    MAX_CLOCK_SKEW = ...
    ZERO_EPOCH = ...
    OUTPUT_TIMESTAMP_FORMAT = ...
    CA_OCSP_RESPONDER_CONNECTION_TIMEOUT = ...
    OCSP_CACHE_SERVER_CONNECTION_TIMEOUT = ...
    CA_OCSP_RESPONDER_MAX_RETRY_FO = ...
    CA_OCSP_RESPONDER_MAX_RETRY_FC = ...
    OCSP_CACHE_SERVER_MAX_RETRY = ...
    def __init__(
        self,
        ocsp_response_cache_uri=...,
        use_ocsp_cache_server=...,
        use_post_method: bool = ...,
        use_fail_open: bool = ...,
        root_certs_dict_lock_timeout: int = ...,
        **kwargs,
    ) -> None: ...
    def validate_certfile(self, cert_filename, no_exception: bool = ...): ...
    def validate(
        self, hostname: str | None, connection: Connection, no_exception: bool = ...
    ) -> list[tuple[Exception | None, Certificate, Certificate, CertId, str | bytes]] | None: ...
    @staticmethod
    def get_ocsp_retry_choice() -> bool: ...
    def is_cert_id_in_cache(self, cert_id: CertId, subject: Certificate | None, **kwargs: Any): ...
    def get_account_from_hostname(self, hostname: str) -> str: ...
    def is_enabled_fail_open(self) -> bool: ...
    @staticmethod
    def print_fail_open_debug(ocsp_log) -> None: ...
    def validate_by_direct_connection(
        self,
        issuer: Certificate,
        subject: Certificate,
        telemetry_data: OCSPTelemetryData,
        hostname: str = ...,
        do_retry: bool = ...,
        **kwargs: Any,
    ) -> tuple[Exception | None, Certificate, Certificate, CertId, bytes]: ...
    def verify_fail_open(self, ex_obj, telemetry_data): ...
    @staticmethod
    def clear_cache() -> None: ...
    @staticmethod
    def cache_size(): ...
    @staticmethod
    def delete_cache_file() -> None: ...
    @staticmethod
    def create_ocsp_debug_info(ocsp, ocsp_request, ocsp_url): ...
    def decode_ocsp_response_cache(self, ocsp_response_cache_json): ...
    def encode_ocsp_response_cache(self, ocsp_response_cache_json) -> None: ...
    def read_cert_bundle(self, ca_bundle_file, storage=...): ...
    def encode_cert_id_key(self, _): ...
    def decode_cert_id_key(self, _): ...
    def encode_cert_id_base64(self, hkey): ...
    def decode_cert_id_base64(self, cert_id_base64): ...
    def create_ocsp_request(self, issuer: Certificate, subject: Certificate) -> tuple[CertId, OCSPRequest]: ...
    def extract_ocsp_url(self, cert): ...
    def decode_ocsp_request(self, ocsp_request): ...
    def decode_ocsp_request_b64(self, ocsp_request): ...
    def extract_good_status(self, single_response): ...
    def extract_revoked_status(self, single_response): ...
    def process_ocsp_response(self, issuer, cert_id, ocsp_response): ...
    def verify_signature(self, signature_algorithm, signature, cert, data): ...
    def extract_certificate_chain(self, connection): ...
    def create_pair_issuer_subject(self, cert_map): ...
    def subject_name(self, subject): ...
    def is_valid_time(self, cert_id, ocsp_response): ...
