from collections import OrderedDict
from datetime import datetime

from asn1crypto.ocsp import CertId, OCSPRequest, SingleResponse
from asn1crypto.x509 import Certificate
from OpenSSL.SSL import Connection
from snowflake.connector.ocsp_snowflake import SnowflakeOCSP

logger = ...

class SnowflakeOCSPAsn1Crypto(SnowflakeOCSP):
    SIGNATURE_ALGORITHM_TO_DIGEST_CLASS = ...
    def encode_cert_id_key(self, hkey): ...
    def decode_cert_id_key(self, cert_id: CertId) -> tuple[bytes, bytes, bytes]: ...
    def decode_cert_id_base64(self, cert_id_base64): ...
    def encode_cert_id_base64(self, hkey): ...
    def read_cert_bundle(self, ca_bundle_file, storage=...) -> None: ...
    def create_ocsp_request(self, issuer: Certificate, subject: Certificate) -> tuple[CertId, OCSPRequest]: ...
    def extract_ocsp_url(self, cert): ...
    def decode_ocsp_request(self, ocsp_request): ...
    def decode_ocsp_request_b64(self, ocsp_request): ...
    def extract_good_status(self, single_response: SingleResponse) -> tuple[datetime, datetime]: ...
    def extract_revoked_status(self, single_response): ...
    def check_cert_time_validity(self, cur_time: datetime, ocsp_cert: Certificate) -> tuple[bool, str | None]: ...
    def is_valid_time(self, cert_id, ocsp_response) -> bool: ...
    def process_ocsp_response(self, issuer, cert_id, ocsp_response): ...
    def verify_signature(self, signature_algorithm, signature, cert, data): ...
    def extract_certificate_chain(self, connection: Connection) -> list[tuple[Certificate, Certificate]]: ...
    def create_pair_issuer_subject(self, cert_map: OrderedDict) -> list[tuple[Certificate, Certificate]]: ...
    def subject_name(self, subject: Certificate) -> OrderedDict: ...
