from types import ModuleType

from packaging.requirements import Requirement

logger = ...

class MissingOptionalDependency:
    _dep_name = ...
    def __getattr__(self, item): ...

class MissingPandas(MissingOptionalDependency):
    _dep_name = ...

class MissingKeyring(MissingOptionalDependency):
    _dep_name = ...

class MissingBotocore(MissingOptionalDependency):
    _dep_name = ...

class MissingBoto3(MissingOptionalDependency):
    _dep_name = ...

class MissingAioBotocore(MissingOptionalDependency):
    _dep_name = ...

class MissingAioBoto3(MissingOptionalDependency):
    _dep_name = ...

type ModuleLikeObject = ModuleType | MissingOptionalDependency

def warn_incompatible_dep(dep_name: str, installed_ver: str, expected_ver: Requirement) -> None: ...
