logger = ...
ALLOWED_KEYS = ...
OS_RELEASE_KEY_VALUE_REGEX = ...
_cached_os_details: dict[str, str] | None = ...
_cache_initialized = ...

def extract_linux_os_release() -> dict[str, str]: ...
def get_os_details() -> dict[str, str] | None: ...
