from enum import Enum
from functools import cache

from .options import installed_boto
from .session_manager import SessionManager

if installed_boto:
    Config = ...
    IMDSFetcher = ...
logger = ...
_LOGGERS_TO_SUPPRESS = ...

class _DetectionState(Enum):
    DETECTED = ...
    NOT_DETECTED = ...
    HTTP_TIMEOUT = ...
    WORKER_TIMEOUT = ...

_PLATFORM_DETECTION_DISABLED_RESULT = ...

def is_ec2_instance(platform_detection_timeout_seconds: float): ...
def is_aws_lambda(): ...
def is_valid_arn_for_wif(arn: str) -> bool: ...
def has_aws_identity(platform_detection_timeout_seconds: float): ...
def is_azure_vm(platform_detection_timeout_seconds: float, session_manager: SessionManager): ...
def is_azure_function(): ...
def is_managed_identity_available_on_azure_vm(platform_detection_timeout_seconds, session_manager: SessionManager, resource=...): ...
def is_managed_identity_available_on_azure_function(): ...
def has_azure_managed_identity(platform_detection_timeout_seconds: float, session_manager: SessionManager): ...
def is_gce_vm(platform_detection_timeout_seconds: float, session_manager: SessionManager): ...
def is_gcp_cloud_run_service(): ...
def is_gcp_cloud_run_job(): ...
def has_gcp_identity(platform_detection_timeout_seconds: float, session_manager: SessionManager): ...
def is_github_action(): ...
@cache
def detect_platforms(platform_detection_timeout_seconds: float | None, session_manager: SessionManager | None = ...) -> list[str]: ...
