from typing import TYPE_CHECKING, Any, NamedTuple

from .constants import FileHeader
from .file_transfer_agent import SnowflakeFileMeta, StorageCredential
from .storage_client import SnowflakeStorageClient

if TYPE_CHECKING: ...
logger = ...
META_PREFIX = ...
SFC_DIGEST = ...
AMZ_MATDESC = ...
AMZ_KEY = ...
AMZ_IV = ...
ERRORNO_WSAECONNABORTED = ...
EXPIRED_TOKEN = ...
ADDRESSING_STYLE = ...
UNSIGNED_PAYLOAD = ...
RE_MULTIPLE_SPACES = ...

class S3Location(NamedTuple):
    bucket_name: str
    path: str

class SnowflakeS3RestClient(SnowflakeStorageClient):
    def __init__(
        self,
        meta: SnowflakeFileMeta,
        credentials: StorageCredential,
        stage_info: dict[str, Any],
        chunk_size: int,
        use_accelerate_endpoint: bool | None = ...,
        use_s3_regional_url: bool = ...,
        unsafe_file_write: bool = ...,
    ) -> None: ...
    def transfer_accelerate_config(self, use_accelerate_endpoint: bool | None = ...) -> bool: ...
    def get_file_header(self, filename: str) -> FileHeader | None: ...
    def download_chunk(self, chunk_id: int) -> None: ...
