import logging
from typing import NamedTuple

MIN_TOKEN_LEN = ...
MIN_PWD_LEN = ...

class MaskedMessageData(NamedTuple):
    is_masked: bool = ...
    masked_text: str | None = ...
    error_str: str | None = ...

class SecretDetector(logging.Formatter):
    AWS_KEY_PATTERN = ...
    AWS_TOKEN_PATTERN = ...
    SAS_TOKEN_PATTERN = ...
    PRIVATE_KEY_PATTERN = ...
    PRIVATE_KEY_DATA_PATTERN = ...
    CONNECTION_TOKEN_PATTERN = ...
    PASSWORD_PATTERN = ...
    SECRET_STARRED_MASK_STR = ...
    @staticmethod
    def mask_connection_token(text: str) -> str: ...
    @staticmethod
    def mask_password(text: str) -> str: ...
    @staticmethod
    def mask_aws_keys(text: str) -> str: ...
    @staticmethod
    def mask_sas_tokens(text: str) -> str: ...
    @staticmethod
    def mask_aws_tokens(text: str) -> str: ...
    @staticmethod
    def mask_private_key(text: str) -> str: ...
    @staticmethod
    def mask_private_key_data(text: str) -> str: ...
    @staticmethod
    def mask_secrets(text: str) -> MaskedMessageData: ...
    @staticmethod
    def create_formatting_error_log(original_record: logging.LogRecord, error_message: str) -> str: ...
    def format(self, record: logging.LogRecord) -> str: ...
