import abc
import contextlib
from collections.abc import Callable, Generator, Mapping
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any, TypeVar

from .vendored.requests import Response, Session
from .vendored.requests.adapters import BaseAdapter, HTTPAdapter
from .vendored.urllib3 import PoolManager, Retry
from .vendored.urllib3.connectionpool import HTTPConnectionPool, HTTPSConnectionPool

if TYPE_CHECKING: ...
logger = ...
REQUESTS_RETRY = ...
SessionT = TypeVar("SessionT")

class ProxySupportAdapter(HTTPAdapter):
    def get_connection_with_tls_context(self, request, verify, proxies=..., cert=...) -> HTTPConnectionPool | HTTPSConnectionPool: ...

class AdapterFactory(abc.ABC):
    @abc.abstractmethod
    def __call__(self, *args, **kwargs) -> BaseAdapter: ...

class ProxySupportAdapterFactory(AdapterFactory):
    def __call__(self, *args, **kwargs) -> ProxySupportAdapter: ...

@dataclass(frozen=True)
class BaseHttpConfig:
    use_pooling: bool = ...
    max_retries: int | Retry | None = ...
    proxy_host: str | None = ...
    proxy_port: str | None = ...
    proxy_user: str | None = ...
    proxy_password: str | None = ...
    no_proxy: str | None = ...
    def copy_with(self, **overrides: Any) -> BaseHttpConfig: ...
    def to_base_dict(self) -> dict[str, Any]: ...

@dataclass(frozen=True)
class HttpConfig(BaseHttpConfig):
    adapter_factory: Callable[..., HTTPAdapter] = ...
    def get_adapter(self, **override_adapter_factory_kwargs) -> HTTPAdapter: ...

class SessionPool[SessionT]:
    def __init__(self, manager: SessionManager) -> None: ...
    def get_session(self, *, url: str | None = ...) -> SessionT: ...
    def return_session(self, session: SessionT) -> None: ...
    def close(self) -> None: ...

class _BaseConfigDirectAccessMixin(abc.ABC):
    @property
    @abc.abstractmethod
    def config(self) -> HttpConfig: ...
    @config.setter
    @abc.abstractmethod
    def config(self, value) -> HttpConfig: ...
    @property
    def use_pooling(self) -> bool: ...
    @use_pooling.setter
    def use_pooling(self, value: bool) -> None: ...
    @property
    def max_retries(self) -> Retry | int: ...
    @max_retries.setter
    def max_retries(self, value: Retry | int) -> None: ...

class _HttpConfigDirectAccessMixin(_BaseConfigDirectAccessMixin, abc.ABC):
    @property
    def adapter_factory(self) -> Callable[..., HTTPAdapter]: ...
    @adapter_factory.setter
    def adapter_factory(self, value: Callable[..., HTTPAdapter]) -> None: ...

class _RequestVerbsUsingSessionMixin(abc.ABC):
    @abc.abstractmethod
    def use_session(self, url: str, use_pooling: bool) -> Session: ...
    def get(
        self,
        url: str,
        *,
        headers: Mapping[str, str] | None = ...,
        timeout: int | tuple[int, int] | None = ...,
        use_pooling: bool | None = ...,
        **kwargs,
    ): ...
    def options(
        self, url: str, *, headers: Mapping[str, str] | None = ..., timeout: int | None = ..., use_pooling: bool | None = ..., **kwargs
    ): ...
    def head(
        self, url: str, *, headers: Mapping[str, str] | None = ..., timeout: int | None = ..., use_pooling: bool | None = ..., **kwargs
    ): ...
    def post(
        self,
        url: str,
        *,
        headers: Mapping[str, str] | None = ...,
        timeout: int | None = ...,
        use_pooling: bool | None = ...,
        data=...,
        json=...,
        **kwargs,
    ): ...
    def put(
        self,
        url: str,
        *,
        headers: Mapping[str, str] | None = ...,
        timeout: int | None = ...,
        use_pooling: bool | None = ...,
        data=...,
        **kwargs,
    ): ...
    def patch(
        self,
        url: str,
        *,
        headers: Mapping[str, str] | None = ...,
        timeout: int | None = ...,
        use_pooling: bool | None = ...,
        data=...,
        **kwargs,
    ): ...
    def delete(
        self, url: str, *, headers: Mapping[str, str] | None = ..., timeout: int | None = ..., use_pooling: bool | None = ..., **kwargs
    ): ...

class SessionManager(_RequestVerbsUsingSessionMixin, _HttpConfigDirectAccessMixin):
    def __init__(self, config: HttpConfig | None = ..., **http_config_kwargs) -> None: ...
    @classmethod
    def from_config(cls, cfg: HttpConfig, **overrides: Any) -> SessionManager: ...
    @property
    def config(self) -> HttpConfig: ...
    @config.setter
    def config(self, cfg: HttpConfig) -> None: ...
    @property
    def proxy_url(self) -> str: ...
    @property
    def sessions_map(self) -> dict[str, SessionPool]: ...
    @staticmethod
    def get_session_pool_manager(session: Session, url: str) -> PoolManager | None: ...
    def make_session(self, *, url: str | None = ...) -> Session: ...
    @contextlib.contextmanager
    @_propagate_session_manager_to_ocsp
    def use_session(self, url: str | bytes | None, use_pooling: bool | None = ...) -> Generator[Session, Any]: ...
    def request(
        self,
        method: str,
        url: str,
        *,
        headers: Mapping[str, str] | None = ...,
        timeout: int | None = ...,
        use_pooling: bool | None = ...,
        **kwargs: Any,
    ) -> Response: ...
    def close(self): ...
    def clone(self, **http_config_overrides) -> SessionManager: ...
    def __getstate__(self): ...
    def __setstate__(self, state): ...

def request(
    method: str,
    url: str,
    *,
    headers: Mapping[str, str] | None = ...,
    timeout: int | None = ...,
    session_manager: SessionManager | None = ...,
    use_pooling: bool | None = ...,
    **kwargs: Any,
) -> Response: ...

class ProxySessionManager(SessionManager):
    def make_session(self, *, url: str | None = ...) -> Session: ...

class SessionManagerFactory:
    @staticmethod
    def get_manager(config: HttpConfig | None = ..., **http_config_kwargs) -> SessionManager: ...
