binary_to_python = ...

def binary_to_snowflake(binary_value) -> bytes | bytearray: ...

class SnowflakeBinaryFormat:
    def __init__(self, name) -> None: ...
    def format(self, binary_value): ...
