from datetime import timedelta

ZERO_TIMEDELTA = ...
ElementType = ...

def sfdatetime_total_seconds_from_timedelta(td: timedelta) -> int: ...

SnowflakeDateTime = ...
NOT_OTHER_FORMAT = ...

class SnowflakeDateTimeFormat:
    def __init__(
        self, sql_format, data_type: str = ..., datetime_class=..., support_negative_year: bool = ..., inject_fraction: bool = ...
    ) -> None: ...

class SnowflakeDateFormat(SnowflakeDateTimeFormat):
    def __init__(self, sql_format, **kwargs) -> None: ...
