import weakref
from contextvars import ContextVar
from functools import wraps
from typing import TYPE_CHECKING, Any

from .constants import OCSPMode
from .crl import CRLConfig
from .session_manager import SessionManager
from .vendored.urllib3.contrib.pyopenssl import WrappedSocket
from .vendored.urllib3.util import ssl_ as ssl_

if TYPE_CHECKING: ...
DEFAULT_OCSP_MODE: OCSPMode = ...
FEATURE_OCSP_MODE: OCSPMode = ...
FEATURE_ROOT_CERTS_DICT_LOCK_TIMEOUT: int = ...
DEFAULT_CRL_CONFIG: CRLConfig = ...
FEATURE_CRL_CONFIG: CRLConfig = ...
FEATURE_OCSP_RESPONSE_CACHE_FILE_NAME: str | None = ...
log = ...
_CURRENT_SESSION_MANAGER: ContextVar[weakref.ref[SessionManager] | None] = ...

def get_current_session_manager(create_default_if_missing: bool = ..., **clone_kwargs) -> SessionManager | None: ...
def set_current_session_manager(sm: SessionManager | None) -> Any: ...
def reset_current_session_manager(token) -> None: ...
def inject_into_urllib3() -> None: ...
@wraps(ssl_.ssl_wrap_socket)
def ssl_wrap_socket_with_cert_revocation_checks(*args: Any, **kwargs: Any) -> WrappedSocket: ...
