from abc import ABC, abstractmethod
from typing import TYPE_CHECKING, Any, NamedTuple

from .constants import FileHeader
from .file_transfer_agent import SnowflakeFileMeta, StorageCredential
from .vendored import requests

if TYPE_CHECKING: ...
logger = ...

class SnowflakeFileEncryptionMaterial(NamedTuple):
    query_stage_master_key: str
    query_id: str
    smk_id: int

METHODS = ...

def remove_content_encoding(resp: requests.Response, **kwargs) -> None: ...

class SnowflakeStorageClient(ABC):
    TRANSIENT_HTTP_ERR = ...
    TRANSIENT_ERRORS = ...
    SLEEP_MAX = ...
    SLEEP_UNIT = ...
    def __init__(
        self,
        meta: SnowflakeFileMeta,
        stage_info: dict[str, Any],
        chunk_size: int,
        chunked_transfer: bool | None = ...,
        credentials: StorageCredential | None = ...,
        max_retry: int = ...,
        unsafe_file_write: bool = ...,
    ) -> None: ...
    def compress(self) -> None: ...
    def get_digest(self) -> None: ...
    def encrypt(self) -> None: ...
    @abstractmethod
    def get_file_header(self, filename: str) -> FileHeader | None: ...
    def preprocess(self) -> None: ...
    def prepare_upload(self) -> None: ...
    def finish_upload(self) -> None: ...
    def prepare_download(self) -> None: ...
    def write_downloaded_chunk(self, chunk_id: int, data: bytes) -> None: ...
    def finish_download(self) -> None: ...
    def upload_chunk(self, chunk_id: int) -> None: ...
    @abstractmethod
    def download_chunk(self, chunk_id: int) -> None: ...
    def delete_client_data(self) -> None: ...
    def __del__(self) -> None: ...
