from enum import Enum, unique
from typing import TYPE_CHECKING, Any

from .connection import SnowflakeConnection
from .network import SnowflakeRestful

if TYPE_CHECKING: ...
logger = ...

@unique
class TelemetryField(Enum):
    TIME_CONSUME_FIRST_RESULT = ...
    TIME_CONSUME_LAST_RESULT = ...
    TIME_DOWNLOADING_CHUNKS = ...
    TIME_PARSING_CHUNKS = ...
    SQL_EXCEPTION = ...
    OCSP_EXCEPTION = ...
    HTTP_EXCEPTION = ...
    GET_PARTITIONS_USED = ...
    EMPTY_SEQ_INTERPOLATION = ...
    PANDAS_FETCH_ALL = ...
    PANDAS_FETCH_BATCHES = ...
    ARROW_FETCH_ALL = ...
    ARROW_FETCH_BATCHES = ...
    PANDAS_WRITE = ...
    IMPORTED_PACKAGES = ...
    CORE_IMPORT = ...
    NANOARROW_IMPORT = ...
    MULTI_STATEMENT = ...
    KEY_TYPE = ...
    KEY_SOURCE = ...
    KEY_SFQID = ...
    KEY_SQLSTATE = ...
    KEY_DRIVER_TYPE = ...
    KEY_DRIVER_VERSION = ...
    KEY_REASON = ...
    KEY_VALUE = ...
    KEY_EXCEPTION = ...
    KEY_ERROR_NUMBER = ...
    KEY_ERROR_MESSAGE = ...
    KEY_STACKTRACE = ...
    KEY_OOB_DRIVER = ...
    KEY_OOB_VERSION = ...
    KEY_OOB_TELEMETRY_SERVER_DEPLOYMENT = ...
    KEY_OOB_CONNECTION_STRING = ...
    KEY_OOB_EXCEPTION_MESSAGE = ...
    KEY_OOB_ERROR_MESSAGE = ...
    KEY_OOB_EXCEPTION_STACK_TRACE = ...
    KEY_OOB_EVENT_TYPE = ...
    KEY_OOB_ERROR_CODE = ...
    KEY_OOB_SQL_STATE = ...
    KEY_OOB_REQUEST = ...
    KEY_OOB_RESPONSE = ...
    KEY_OOB_RESPONSE_STATUS_LINE = ...
    KEY_OOB_RESPONSE_STATUS_CODE = ...
    KEY_OOB_RETRY_TIMEOUT = ...
    KEY_OOB_RETRY_COUNT = ...
    KEY_OOB_EVENT_SUB_TYPE = ...
    KEY_OOB_SFC_PEER_HOST = ...
    KEY_OOB_CERT_ID = ...
    KEY_OOB_OCSP_REQUEST_BASE64 = ...
    KEY_OOB_OCSP_RESPONDER_URL = ...
    KEY_OOB_INSECURE_MODE = ...
    KEY_OOB_FAIL_OPEN = ...
    KEY_OOB_CACHE_ENABLED = ...
    KEY_OOB_CACHE_HIT = ...

class TelemetryData:
    TRUE = ...
    FALSE = ...
    def __init__(self, message, timestamp) -> None: ...
    @classmethod
    def from_telemetry_data_dict(
        cls, from_dict: dict, timestamp: int, connection: SnowflakeConnection | None = ..., is_oob_telemetry: bool = ...
    ): ...
    def to_dict(self) -> dict[str, Any]: ...

class TelemetryClient:
    SF_PATH_TELEMETRY = ...
    DEFAULT_FORCE_FLUSH_SIZE = ...
    def __init__(self, rest: SnowflakeRestful, flush_size=...) -> None: ...
    def add_log_to_batch(self, telemetry_data: TelemetryData) -> None: ...
    def try_add_log_to_batch(self, telemetry_data: TelemetryData) -> None: ...
    def send_batch(self, retry: bool = ...) -> None: ...
    @property
    def is_closed(self) -> bool: ...
    def close(self, retry: bool = ...) -> None: ...
    def disable(self) -> None: ...
    def is_enabled(self): ...
    def buffer_size(self): ...

def generate_telemetry_data_dict(
    from_dict: dict | None = ..., connection: SnowflakeConnection | None = ..., is_oob_telemetry: bool = ...
) -> dict[str, Any]: ...
