from collections.abc import Callable, Iterator
from threading import _Timer as Timer
from types import TracebackType
from typing import Self

logger = ...
DEFAULT_MASTER_VALIDITY_IN_SECONDS = ...

class HeartBeatTimer(Timer):
    def __init__(self, client_session_keep_alive_heartbeat_frequency: int, f: Callable) -> None: ...
    def run(self) -> None: ...

def get_time_millis() -> int: ...

class TimerContextManager:
    def __init__(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None) -> None: ...
    def get_timing_millis(self) -> int: ...

class TimeoutBackoffCtx:
    def __init__(
        self, max_retry_attempts: int | None = ..., timeout: int | None = ..., backoff_generator: Iterator | None = ...
    ) -> None: ...
    @property
    def timeout(self) -> int | None: ...
    @property
    def current_retry_count(self) -> int: ...
    @property
    def current_sleep_time(self) -> int: ...
    @property
    def remaining_time_millis(self) -> int: ...
    @property
    def should_retry(self) -> bool: ...
    def set_start_time(self) -> None: ...
    def increment(self) -> None: ...
