from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import TypeVar

logger = ...
T = TypeVar("T")

class TokenType(Enum):
    ID_TOKEN = ...
    MFA_TOKEN = ...
    OAUTH_ACCESS_TOKEN = ...
    OAUTH_REFRESH_TOKEN = ...

class _InvalidTokenKeyError(Exception): ...

@dataclass
class TokenKey:
    user: str
    host: str
    tokenType: TokenType
    def string_key(self) -> str: ...
    def hash_key(self) -> str: ...

class TokenCache(ABC):
    @staticmethod
    def make(skip_file_permissions_check: bool = ...) -> TokenCache: ...
    @abstractmethod
    def store(self, key: TokenKey, token: str) -> None: ...
    @abstractmethod
    def retrieve(self, key: TokenKey) -> str | None: ...
    @abstractmethod
    def remove(self, key: TokenKey) -> None: ...

class _FileTokenCacheError(Exception): ...
class _OwnershipError(_FileTokenCacheError): ...
class _PermissionsTooWideError(_FileTokenCacheError): ...
class _CacheDirNotFoundError(_FileTokenCacheError): ...
class _InvalidCacheDirError(_FileTokenCacheError): ...
class _MalformedCacheFileError(_FileTokenCacheError): ...
class _CacheFileReadError(_FileTokenCacheError): ...
class _CacheFileWriteError(_FileTokenCacheError): ...

class FileTokenCache(TokenCache):
    @staticmethod
    def make(skip_file_permissions_check: bool = ...) -> FileTokenCache | None: ...
    def __init__(self, cache_dir: Path, skip_file_permissions_check: bool = ...) -> None: ...
    def store(self, key: TokenKey, token: str) -> None: ...
    def retrieve(self, key: TokenKey) -> str | None: ...
    def remove(self, key: TokenKey) -> None: ...
    def cache_file(self) -> Path: ...
    def lock_file(self) -> Path: ...
    @staticmethod
    def find_cache_dir(skip_file_permissions_check: bool = ...) -> Path | None: ...
    @staticmethod
    def validate_cache_dir(cache_dir: Path | None, skip_file_permissions_check: bool = ...) -> None: ...

class KeyringTokenCache(TokenCache):
    def __init__(self) -> None: ...
    def store(self, key: TokenKey, token: str) -> None: ...
    def retrieve(self, key: TokenKey) -> str | None: ...
    def remove(self, key: TokenKey) -> None: ...

class NoopTokenCache(TokenCache):
    def store(self, key: TokenKey, token: str) -> None: ...
    def retrieve(self, key: TokenKey) -> str | None: ...
    def remove(self, key: TokenKey) -> None: ...
