from collections.abc import Iterable

logger = ...
URL_VALIDATOR = ...

def is_valid_url(url: str) -> bool: ...
def url_encode_str(target: str | None) -> str: ...
def extract_top_level_domain_from_hostname(hostname: str | None = ...) -> str: ...
def should_bypass_proxies(url: str | bytes, no_proxy: Iterable[str] | None) -> bool: ...
