from collections.abc import Sequence
from io import StringIO

COMMENT_PATTERN_RE = ...
EMPTY_LINE_RE = ...
_logger = ...

class SQLDelimiter:
    def __init__(self, sql_delimiter: str = ...) -> None: ...

def split_statements(buf: StringIO, remove_comments: bool = ..., delimiter: SQLDelimiter | None = ...): ...
def construct_hostname(region: str | None, account: str) -> str: ...
def parse_account(account): ...
def random_string(length: int = ..., prefix: str = ..., suffix: str = ..., choices: Sequence[str] = ...) -> str: ...
def get_md5_for_integrity(text: str | bytes) -> bytes: ...
