from dataclasses import dataclass
from enum import Enum, unique

from .options import installed_boto
from .session_manager import SessionManager

if installed_boto:
    SigV4Auth = ...
    AWSRequest = ...
    InstanceMetadataRegionFetcher = ...
logger = ...
SNOWFLAKE_AUDIENCE = ...
DEFAULT_ENTRA_SNOWFLAKE_RESOURCE = ...
GCP_METADATA_SERVICE_ACCOUNT_BASE_URL = ...

@unique
class AttestationProvider(Enum):
    AWS = ...
    AZURE = ...
    GCP = ...
    OIDC = ...
    @staticmethod
    def from_string(provider: str) -> AttestationProvider: ...
    @staticmethod
    def all_string_values() -> list[str]: ...

@dataclass
class WorkloadIdentityAttestation:
    provider: AttestationProvider
    credential: str
    user_identifier_components: dict

def extract_iss_and_sub_without_signature_verification(jwt_str: str) -> tuple[str, str]: ...
def get_aws_region() -> str: ...
def get_aws_sts_hostname(region: str, partition: str) -> str: ...
def get_aws_session(impersonation_path: list[str] | None = ...): ...
def create_aws_attestation(impersonation_path: list[str] | None = ...) -> WorkloadIdentityAttestation: ...
def get_gcp_access_token(session_manager: SessionManager) -> str: ...
def get_gcp_identity_token_via_impersonation(impersonation_path: list[str], session_manager: SessionManager) -> str: ...
def get_gcp_identity_token(session_manager: SessionManager) -> str: ...
def create_gcp_attestation(session_manager: SessionManager, impersonation_path: list[str] | None = ...) -> WorkloadIdentityAttestation: ...
def create_azure_attestation(
    snowflake_entra_resource: str, session_manager: SessionManager | None = ...
) -> WorkloadIdentityAttestation: ...
def create_oidc_attestation(token: str | None) -> WorkloadIdentityAttestation: ...
def create_attestation(
    provider: AttestationProvider,
    entra_resource: str | None = ...,
    token: str | None = ...,
    impersonation_path: list[str] | None = ...,
    session_manager: SessionManager | None = ...,
) -> WorkloadIdentityAttestation: ...
