"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._currentvalue import Currentvalue
from ._font import Font
from ._pad import Pad
from ._step import Step
from ._transition import Transition
from . import currentvalue

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
else:
    ...
