"""
This type stub file was generated by pyright.
"""

from modin.core.io.column_stores.column_store_dispatcher import ColumnStoreDispatcher

"""Module houses `HDFDispatcher` class, that is used for reading hdf data."""
class HDFDispatcher(ColumnStoreDispatcher):
    """
    Class handles utils for reading hdf data.

    Inherits some common for columnar store files util functions from
    `ColumnStoreDispatcher` class.
    """
    ...


