"""
This type stub file was generated by pyright.
"""

import functools
from typing import TYPE_CHECKING
from modin.core.io.column_stores.column_store_dispatcher import ColumnStoreDispatcher
from modin.utils import _inherit_docstrings
from modin.core.storage_formats.pandas.parsers import ParquetFileToRead

"""Module houses `ParquetDispatcher` class, that is used for reading `.parquet` files."""
if TYPE_CHECKING:
    ...
class ColumnStoreDataset:
    """
    Base class that encapsulates Parquet engine-specific details.

    This class exposes a set of functions that are commonly used in the
    `read_parquet` implementation.

    Attributes
    ----------
    path : str, path object or file-like object
        The filepath of the parquet file in local filesystem or hdfs.
    storage_options : dict
        Parameters for specific storage engine.
    _fs_path : str, path object or file-like object
        The filepath or handle of the parquet dataset specific to the
        filesystem implementation. E.g. for `s3://test/example`, _fs
        would be set to S3FileSystem and _fs_path would be `test/example`.
    _fs : Filesystem
        Filesystem object specific to the given parquet file/dataset.
    dataset : ParquetDataset or ParquetFile
        Underlying dataset implementation for PyArrow and fastparquet
        respectively.
    """
    def __init__(self, path, storage_options) -> None:
        ...
    
    @property
    def pandas_metadata(self):
        """Return the pandas metadata of the dataset."""
        ...
    
    @property
    def columns(self):
        """Return the list of columns in the dataset."""
        ...
    
    @property
    def engine(self):
        """Return string representing what engine is being used."""
        ...
    
    @functools.cached_property
    def files(self):
        """Return the list of formatted file paths of the dataset."""
        ...
    
    @functools.cached_property
    def row_groups_per_file(self):
        """Return a list with the number of row groups per file."""
        ...
    
    @property
    def fs(self): # -> Any:
        """
        Return the filesystem object associated with the dataset path.

        Returns
        -------
        filesystem
            Filesystem object.
        """
        ...
    
    @property
    def fs_path(self): # -> AbstractBufferedFile:
        """
        Return the filesystem-specific path or file handle.

        Returns
        -------
        fs_path : str, path object or file-like object
            String path specific to filesystem or a file handle.
        """
        ...
    
    def to_pandas_dataframe(self, columns):
        """
        Read the given columns as a pandas dataframe.

        Parameters
        ----------
        columns : list
            List of columns that should be read from file.
        """
        ...
    


@_inherit_docstrings(ColumnStoreDataset)
class PyArrowDataset(ColumnStoreDataset):
    @property
    def pandas_metadata(self):
        ...
    
    @property
    def columns(self):
        ...
    
    @property
    def engine(self): # -> Literal['pyarrow']:
        ...
    
    @functools.cached_property
    def row_groups_per_file(self): # -> list[Any]:
        ...
    
    @functools.cached_property
    def files(self): # -> list[AbstractBufferedFile] | list[Any | str] | list[Any]:
        ...
    
    def to_pandas_dataframe(self, columns): # -> DataFrame:
        ...
    


@_inherit_docstrings(ColumnStoreDataset)
class FastParquetDataset(ColumnStoreDataset):
    @property
    def pandas_metadata(self): # -> dict[Any, Any] | Any:
        ...
    
    @property
    def columns(self):
        ...
    
    @property
    def engine(self): # -> Literal['fastparquet']:
        ...
    
    @functools.cached_property
    def row_groups_per_file(self): # -> list[Any]:
        ...
    
    @functools.cached_property
    def files(self): # -> list[AbstractBufferedFile] | list[Any | str] | list[Any]:
        ...
    
    def to_pandas_dataframe(self, columns):
        ...
    


class ParquetDispatcher(ColumnStoreDispatcher):
    """Class handles utils for reading `.parquet` files."""
    index_regex = ...
    @classmethod
    def get_dataset(cls, path, engine, storage_options): # -> FastParquetDataset | PyArrowDataset:
        """
        Retrieve Parquet engine specific Dataset implementation.

        Parameters
        ----------
        path : str, path object or file-like object
            The filepath of the parquet file in local filesystem or hdfs.
        engine : str
            Parquet library to use (only 'PyArrow' is supported for now).
        storage_options : dict
            Parameters for specific storage engine.

        Returns
        -------
        Dataset
            Either a PyArrowDataset or FastParquetDataset object.
        """
        ...
    
    @classmethod
    def call_deploy(cls, partition_files: list[list[ParquetFileToRead]], col_partitions: list[list[str]], storage_options: dict, engine: str, **kwargs): # -> list[Any]:
        """
        Deploy remote tasks to the workers with passed parameters.

        Parameters
        ----------
        partition_files : list[list[ParquetFileToRead]]
            List of arrays with files that should be read by each partition.
        col_partitions : list[list[str]]
            List of arrays with columns names that should be read
            by each partition.
        storage_options : dict
            Parameters for specific storage engine.
        engine : {"auto", "pyarrow", "fastparquet"}
            Parquet library to use for reading.
        **kwargs : dict
            Parameters of deploying read_* function.

        Returns
        -------
        List
            Array with references to the task deploy result for each partition.
        """
        ...
    
    @classmethod
    def build_partition(cls, partition_ids, column_widths): # -> NDArray[Any]:
        """
        Build array with partitions of `cls.frame_partition_cls` class.

        Parameters
        ----------
        partition_ids : list
            Array with references to the partitions data.
        column_widths : list
            Number of columns in each partition.

        Returns
        -------
        np.ndarray
            array with shape equals to the shape of `partition_ids` and
            filed with partition objects.

        Notes
        -----
        The second level of partitions_ids contains a list of object references
        for each read call:
        partition_ids[i][j] -> [ObjectRef(df), ObjectRef(df.index), ObjectRef(len(df))].
        """
        ...
    
    @classmethod
    def build_index(cls, dataset, partition_ids, index_columns, filters): # -> tuple[list[Any], Literal[False]] | tuple[Any | RangeIndex, bool]:
        """
        Compute index and its split sizes of resulting Modin DataFrame.

        Parameters
        ----------
        dataset : Dataset
            Dataset object of Parquet file/files.
        partition_ids : list
            Array with references to the partitions data.
        index_columns : list
            List of index columns specified by pandas metadata.
        filters : list
            List of filters to be used in reading the Parquet file/files.

        Returns
        -------
        index : pandas.Index
            Index of resulting Modin DataFrame.
        needs_index_sync : bool
            Whether the partition indices need to be synced with frame
            index because there's no index column, or at least one
            index column is a RangeIndex.

        Notes
        -----
        See `build_partition` for more detail on the contents of partitions_ids.
        """
        ...
    
    @classmethod
    def build_query_compiler(cls, dataset, columns, index_columns, **kwargs):
        """
        Build query compiler from deployed tasks outputs.

        Parameters
        ----------
        dataset : Dataset
            Dataset object of Parquet file/files.
        columns : list
            List of columns that should be read from file.
        index_columns : list
            List of index columns specified by pandas metadata.
        **kwargs : dict
            Parameters of deploying read_* function.

        Returns
        -------
        new_query_compiler : BaseQueryCompiler
            Query compiler with imported data for further processing.
        """
        ...
    
    @classmethod
    def write(cls, qc, **kwargs): # -> None:
        """
        Write a ``DataFrame`` to the binary parquet format.

        Parameters
        ----------
        qc : BaseQueryCompiler
            The query compiler of the Modin dataframe that we want to run `to_parquet` on.
        **kwargs : dict
            Parameters for `pandas.to_parquet(**kwargs)`.
        """
        ...
    


