from mayutils.visualisation.console import setup_printing as setup_printing

def apply_css(*css) -> None: ...
def not_nbconvert() -> bool: ...
def export(
    slides: bool = True, file_name: str = "report.ipynb", title: str | None = None
) -> None: ...
def write_markdown(*args) -> None: ...
def write_latex(*args) -> None: ...
def add_default_css(*args, **kwargs) -> None: ...
def setup_notebooks() -> None: ...
