class AsNumbaTypeRegistry:
    def __init__(self) -> None: ...
    def register(self, func_or_py_type, numba_type=...):  # -> None:

        ...
    def try_infer(self, py_type):  # -> Buffer | Type | ExternalFunctionPointer | Opaque | None:

        ...
    def infer(self, py_type):  # -> Buffer | Type | ExternalFunctionPointer | Opaque:
        ...
    def __call__(self, py_type):  # -> Buffer | Type | ExternalFunctionPointer | Opaque:
        ...

as_numba_type = ...
