_pep3118_int_types = ...
_pep3118_scalar_map = ...
_type_map = ...

def decode_pep3118_format(fmt, itemsize):  # -> Integer:

    ...
def get_type_class(typ):  # -> type[Buffer]:

    ...
def infer_layout(val):  # -> Literal['C', 'F', 'A']:

    ...
