from numba.core.typing import templates

"""
Support for CFFI. Allows checking whether objects are CFFI functions and
obtaining the pointer and numba signature.
"""
ffi = ...
SUPPORTED = ...
_ool_func_types = ...
_ool_func_ptr = ...
_ffi_instances = ...

def is_ffi_instance(obj):  # -> bool:
    ...
def is_cffi_func(obj):  # -> Any | bool:

    ...
def get_pointer(cffi_func):  # -> int:

    ...

_cached_type_map = ...

def map_type(
    cffi_type, use_record_dtype=...
):  # -> Signature | RawPointer | CPointer | NestedArray | Record | UnicodeCharSeq | CharSeq | NPTimedelta | NPDatetime:

    ...
def map_struct_to_record_dtype(cffi_type):  # -> Record | UnicodeCharSeq | CharSeq | NPTimedelta | NPDatetime | NestedArray:

    ...
def make_function_type(cffi_func, use_record_dtype=...):  # -> ExternalFunctionPointer:

    ...

registry = ...

@registry.register
class FFI_from_buffer(templates.AbstractTemplate):
    key = ...
    def generic(self, args, kws):  # -> Signature | None:
        ...

@registry.register_attr
class FFIAttribute(templates.AttributeTemplate):
    key = ...
    def resolve_from_buffer(self, ffi):  # -> BoundFunction:
        ...

def register_module(mod):  # -> None:

    ...
def register_type(cffi_type, numba_type):  # -> None:

    ...
