import contextlib
from collections.abc import Sequence

class Rating:
    __slots__ = ...
    def __init__(self) -> None: ...
    def astuple(self):  # -> tuple[int, int, int]:

        ...
    def __add__(self, other):  # -> NotImplementedType | Rating:
        ...

class CallStack(Sequence):
    def __init__(self) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int:  # -> int:
        ...
    @contextlib.contextmanager
    def register(self, target, typeinfer, func_id, args):  # -> Generator[None, Any, None]:
        ...
    def finditer(self, py_func):  # -> Generator[Any, Any, None]:

        ...
    def findfirst(self, py_func):  # -> None:

        ...
    def match(self, py_func, args):  # -> None:

        ...
    def lookup_resolve_cache(self, func, args, kws) -> _ResolveCache: ...

class _ResolveCache:
    _status: str
    _exc: BaseException | None
    def __init__(self) -> None: ...
    def mark_error(self, exc) -> None: ...
    def mark_failed(self) -> None: ...
    def replay_failure(self) -> None: ...
    def has_failed_previously(self) -> bool: ...

class CallFrame:
    def __init__(self, target, typeinfer, func_id, args) -> None: ...
    def add_return_type(self, return_type):  # -> None:

        ...

class BaseContext:
    def __init__(self) -> None: ...
    def init(self):  # -> None:

        ...
    def refresh(self):  # -> None:

        ...
    def explain_function_type(self, func):  # -> str:

        ...
    def resolve_function_type(self, func, args, kws):  # -> None:

        ...
    def resolve_getattr(self, typ, attr):  # -> Buffer | Any | ExternalFunctionPointer | Opaque | ExternalFunction | Module | None:

        ...
    def find_matching_getattr_template(self, typ, attr):  # -> dict[str, Any] | None:
        ...
    def resolve_setattr(self, target, attr, value):  # -> Signature | None:

        ...
    def resolve_static_getitem(self, value, index):  # -> None:
        ...
    def resolve_static_setitem(self, target, index, value):  # -> None:
        ...
    def resolve_setitem(self, target, index, value):  # -> Any:
        ...
    def resolve_delitem(self, target, index):  # -> Any:
        ...
    def resolve_module_constants(self, typ, attr):  # -> Buffer | Any | ExternalFunctionPointer | Opaque | ExternalFunction | Module | None:

        ...
    def resolve_value_type(self, val):  # -> Buffer | Any | ExternalFunctionPointer | Opaque | ExternalFunction | Module:

        ...
    def resolve_value_type_prefer_literal(
        self, value
    ):  # -> Buffer | Any | ExternalFunctionPointer | Opaque | ExternalFunction | Module | Literal:

        ...
    def load_additional_registries(self):  # -> None:

        ...
    def install_registry(self, registry):  # -> None:

        ...
    def insert_global(self, gv, gty):  # -> None:
        ...
    def insert_attributes(self, at):  # -> None:
        ...
    def insert_function(self, ft):  # -> None:
        ...
    def insert_user_function(self, fn, ft):  # -> None:

        ...
    def can_convert(self, fromty, toty):  # -> Literal[Conversion.exact, Conversion.promote, Conversion.safe, Conversion.unsafe]:

        ...
    def install_possible_conversions(self, actualargs, formalargs):  # -> bool:

        ...
    def resolve_overload(self, key, cases, args, kws, allow_ambiguous=..., unsafe_casting=..., exact_match_required=...):  # -> None:

        ...
    def unify_types(self, *typelist):  # -> None:
        ...
    def unify_pairs(self, first, second):  # -> None:

        ...

class Context(BaseContext):
    def load_additional_registries(self):  # -> None:
        ...
