_FROM_CTYPES = ...
_TO_CTYPES = ...

def from_ctypes(ctypeobj):  # -> NoneType | CPointer:

    ...
def to_ctypes(ty):  # -> type[_Pointer[_Pointer[c_void_p]]] | type[_Pointer[c_void_p]] | type[c_void_p] | None:

    ...
def is_ctypes_funcptr(obj):  # -> bool:
    ...
def get_pointer(ctypes_func):  # -> int | None:

    ...
def make_function_type(cfnptr):  # -> ExternalFunctionPointer:

    ...
