import operator

import numpy as np
from numba import pndindex
from numba.core import config
from numba.core.typing.templates import AbstractTemplate

registry = ...
infer = ...
infer_global = ...
infer_getattr = ...

class Numpy_rules_ufunc(AbstractTemplate):
    @property
    def ufunc(self): ...
    def generic(self, args, kws):  # -> Signature:
        ...

class NumpyRulesArrayOperator(Numpy_rules_ufunc):
    _op_map = ...
    @property
    def ufunc(self):  # -> Any:
        ...
    @classmethod
    def install_operations(cls):  # -> None:
        ...
    def generic(self, args, kws):  # -> Signature | None:

        ...

_binop_map = ...

class NumpyRulesInplaceArrayOperator(NumpyRulesArrayOperator):
    _op_map = ...
    def generic(self, args, kws):  # -> Signature | None:
        ...

class NumpyRulesUnaryArrayOperator(NumpyRulesArrayOperator):
    _op_map = ...
    def generic(self, args, kws):  # -> Signature | None:
        ...

math_operations = ...
trigonometric_functions = ...
bit_twiddling_functions = ...
comparison_functions = ...
floating_functions = ...
logic_functions = ...
_unsupported = ...

def register_numpy_ufunc(name, register_global=...) -> None:  # -> None:
    ...

all_ufuncs = ...
supported_ufuncs = ...
all_ufuncs = ...
supported_ufuncs = ...
supported_array_operators = ...

class Numpy_method_redirection(AbstractTemplate):
    prefer_literal = ...
    def generic(self, args, kws):  # -> None:
        ...

if config.USE_LEGACY_TYPE_SYSTEM:
    np_types = ...
    def register_number_classes(register_global):  # -> None:
        ...

else:
    np_types = ...
    def register_number_classes(register_global):  # -> None:
        ...

def parse_shape(shape):  # -> int | None:

    ...
def parse_dtype(dtype):  # -> Record | UnicodeCharSeq | CharSeq | NPTimedelta | NPDatetime | NestedArray | None:

    ...

class MatMulTyperMixin:
    def matmul_typer(self, a, b, out=...):  # -> Array | Float | Complex | None:

        ...

@infer_global(np.ndenumerate)
class NdEnumerate(AbstractTemplate):
    def generic(self, args, kws):  # -> Signature | None:
        ...

@infer_global(np.nditer)
class NdIter(AbstractTemplate):
    def generic(self, args, kws):  # -> Signature | None:
        ...

@infer_global(pndindex)
@infer_global(np.ndindex)
class NdIndex(AbstractTemplate):
    def generic(self, args, kws):  # -> Signature | None:
        ...

@infer_global(operator.eq)
class DtypeEq(AbstractTemplate):
    def generic(self, args, kws):  # -> Signature | None:
        ...
