from abc import ABC, abstractmethod

from numba.core.errors import InternalError

"""
Define typing templates
"""
_inline_info = ...

class Signature:
    __slots__ = ...
    def __init__(self, return_type, args, recvr, pysig=...) -> None: ...
    @property
    def return_type(self):  # -> Any:
        ...
    @property
    def args(self):  # -> tuple[Any, ...] | Any:
        ...
    @property
    def recvr(self):  # -> Any:
        ...
    @property
    def pysig(self):  # -> None:
        ...
    def replace(self, **kwargs):  # -> Signature:

        ...
    def __getstate__(self):  # -> tuple[Any, tuple[Any, ...] | Any, Any, Any | None]:

        ...
    def __setstate__(self, state):  # -> None:

        ...
    def __hash__(self) -> int: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    @property
    def is_method(self):  # -> bool:

        ...
    def as_method(self):  # -> Self | Signature:

        ...
    def as_function(self):  # -> Self | Signature:

        ...
    def as_type(self):  # -> FunctionType:

        ...
    def __unliteral__(self):  # -> Signature:
        ...
    def dump(self, tab=...):  # -> None:
        ...
    def is_precise(self):  # -> Literal[False]:
        ...

def make_concrete_template(name, key, signatures):  # -> Any:
    ...
def make_callable_template(key, typer, recvr=...):  # -> Any:

    ...
def signature(return_type, *args, **kws):  # -> Signature:
    ...
def fold_arguments(pysig, args, kws, normal_handler, default_handler, stararg_handler):  # -> tuple[Any, ...]:

    ...

class FunctionTemplate(ABC):
    unsafe_casting = ...
    exact_match_required = ...
    prefer_literal = ...
    metadata = ...
    def __init__(self, context) -> None: ...
    def get_impl_key(self, sig): ...
    @classmethod
    def get_source_code_info(cls, impl):  # -> tuple[list[str] | Literal['None available (built from string?)'], int, str]:

        ...
    @abstractmethod
    def get_template_info(self):  # -> None:

        ...

    __repr__ = ...

class AbstractTemplate(FunctionTemplate):
    def apply(self, args, kws):  # -> Any | Signature:
        ...
    def get_template_info(self):  # -> dict[str, Any]:
        ...

class CallableTemplate(FunctionTemplate):
    recvr = ...
    def apply(self, args, kws):  # -> None:
        ...
    def get_template_info(self):  # -> dict[str, Any]:
        ...

class ConcreteTemplate(FunctionTemplate):
    def apply(self, args, kws): ...
    def get_template_info(self):  # -> dict[str, Any]:
        ...

class _EmptyImplementationEntry(InternalError):
    def __init__(self, reason) -> None: ...

class _OverloadFunctionTemplate(AbstractTemplate):
    def generic(self, args, kws):  # -> Signature | None:

        ...
    def get_impl_key(self, sig): ...
    @classmethod
    def get_source_info(cls):  # -> dict[str, Any]:

        ...
    def get_template_info(self):  # -> dict[str, Any]:
        ...

def make_overload_template(
    func, overload_func, jit_options, strict, inline, prefer_literal=..., **kwargs
):  # -> type[_OverloadFunctionTemplate]:

    ...

class _TemplateTargetHelperMixin: ...

class _IntrinsicTemplate(_TemplateTargetHelperMixin, AbstractTemplate):
    def generic(self, args, kws):  # -> None:

        ...
    def get_impl_key(self, sig): ...
    def get_template_info(self):  # -> dict[str, Any]:
        ...

def make_intrinsic_template(handle, defn, name, *, prefer_literal=..., kwargs=...):  # -> type[_IntrinsicTemplate]:

    ...

class AttributeTemplate:
    def __init__(self, context) -> None: ...
    def resolve(self, value, attr):  # -> Any | None:
        ...

    generic_resolve = ...

class _OverloadAttributeTemplate(_TemplateTargetHelperMixin, AttributeTemplate):
    is_method = ...
    def __init__(self, context) -> None: ...

class _OverloadMethodTemplate(_OverloadAttributeTemplate):
    is_method = ...

def make_overload_attribute_template(
    typ, attr, overload_func, inline=..., prefer_literal=..., base=..., **kwargs
):  # -> type[_OverloadAttributeTemplate]:

    ...
def make_overload_method_template(typ, attr, overload_func, inline, prefer_literal=..., **kwargs):  # -> type[_OverloadAttributeTemplate]:

    ...
def bound_function(template_key):  # -> Callable[..., _Wrapped[Callable[..., Any], Any, Callable[..., Any], BoundFunction]]:

    ...

class Registry:
    def __init__(self) -> None: ...
    def register(self, item):  # -> type[FunctionTemplate]:
        ...
    def register_attr(self, item):  # -> type[AttributeTemplate]:
        ...
    def register_global(self, val=..., typ=..., **kwargs):  # -> Callable[..., Any] | None:

        ...

class BaseRegistryLoader:
    def __init__(self, registry) -> None: ...
    def new_registrations(self, name):  # -> Generator[Any, Any, None]:
        ...

class RegistryLoader(BaseRegistryLoader):
    registry_items = ...

builtin_registry = ...
infer = ...
infer_getattr = ...
infer_global = ...
