import enum
from functools import singledispatch

import numpy as np
from numba.core import config
from numpy.random.bit_generator import BitGenerator

_termcolor = ...

class Purpose(enum.Enum):
    argument = ...
    constant = ...

_TypeofContext = ...

def typeof(val, purpose=...):  # -> Buffer | Any | ExternalFunctionPointer | Opaque:

    ...
@singledispatch
def typeof_impl(val, c):  # -> Buffer | Any | ExternalFunctionPointer | Opaque | None:

    ...

if config.USE_LEGACY_TYPE_SYSTEM: ...
else: ...

@typeof_impl.register(BitGenerator)
def typeof_numpy_random_bitgen(val, c):  # -> NumPyRandomBitGeneratorType:
    ...
@typeof_impl.register(np.random.Generator)
def typeof_random_generator(val, c):  # -> NumPyRandomGeneratorType:
    ...
@typeof_impl.register(np.polynomial.polynomial.Polynomial)
def typeof_numpy_polynomial(val, c):  # -> PolynomialType:
    ...
