def main(*argv, **kwds):  # -> bool:

    ...

class _FailedFirstRunner:
    cache_filename = ...
    def __init__(self, last_failed=...) -> None: ...
    def main(self, argv, kwds):  # -> bool:
        ...
    def save_failed_tests(self, result, all_tests):  # -> None:
        ...
    def find_last_failed(self, argv):  # -> tuple[list[Any], Any | list[Any]]:
        ...
