import collections
import contextlib
import unittest
from unittest import runner

def make_tag_decorator(known_tags):  # -> Callable[..., Callable[..., Callable[..., object]]]:

    ...
def cuda_sensitive_mtime(x):  # -> str:

    ...
def parse_slice(useslice):  # -> Callable[..., object] | Callable[..., Literal[True]] | Callable[..., bool]:

    ...

class TestLister:
    def __init__(self, useslice) -> None: ...
    def run(self, test):  # -> TextTestResult[_WritelnDecorator]:
        ...

class SerialSuite(unittest.TestSuite):
    def __init__(self, tests=...) -> None: ...
    def addTest(self, test):  # -> None:
        ...
    def run(self, result): ...

class BasicTestRunner(runner.TextTestRunner):
    def __init__(self, useslice, **kwargs) -> None: ...
    def run(self, test):  # -> TextTestResult[_WritelnDecorator]:
        ...

class NumbaTestProgram(unittest.main):
    refleak = ...
    profile = ...
    multiprocess = ...
    useslice = ...
    list = ...
    tags = ...
    exclude_tags = ...
    random_select = ...
    random_seed = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def parseArgs(self, argv):  # -> None:
        ...
    def runTests(self):  # -> None:
        ...

_GENERATED = ...

class ReferenceLeakError(RuntimeError): ...

class IntPool(collections.defaultdict):
    def __missing__(self, key): ...

class RefleakTestResult(runner.TextTestResult):
    warmup = ...
    repetitions = ...
    def addSuccess(self, test):  # -> None:
        ...

class RefleakTestRunner(runner.TextTestRunner):
    resultclass = RefleakTestResult

class ParallelTestResult(runner.TextTestResult):
    def add_results(self, result):  # -> None:

        ...

class _MinimalResult:
    __slots__ = ...
    def fixup_case(self, case):  # -> None:

        ...
    def __init__(self, original_result, test_id=..., resource_info=...) -> None: ...

class _FakeStringIO:
    def __init__(self, value) -> None: ...
    def getvalue(self):  # -> Any:
        ...

class _MinimalRunner:
    def __init__(self, runner_cls, runner_args) -> None: ...
    def __call__(self, test):  # -> _MinimalResult:
        ...
    @contextlib.contextmanager
    def cleanup_object(self, test):  # -> Generator[Any, Any, None]:

        ...

_TIMEOUT = ...

class ParallelTestRunner(runner.TextTestRunner):
    resultclass = ParallelTestResult
    timeout = ...
    def __init__(self, runner_cls, nprocs, useslice, **kwargs) -> None: ...
    def run(self, test):  # -> TextTestResult[_WritelnDecorator]:
        ...
