from typing import Any

from sqlalchemy import sql
from sqlalchemy import util as sa_util
from sqlalchemy.engine import default
from sqlalchemy.orm import context
from sqlalchemy.sql import compiler, sqltypes
from sqlalchemy.sql.base import CompileState
from sqlalchemy.sql.selectable import SelectState

RESERVED_WORDS = ...
AUTOCOMMIT_REGEXP = ...
ILLEGAL_INITIAL_CHARACTERS = ...
ILLEGAL_IDENTIFIERS = ...

@CompileState.plugin_for("default", "select")
class SnowflakeSelectState(SelectState): ...

@sql.base.CompileState.plugin_for("orm", "select")
class SnowflakeORMSelectCompileState(context.ORMSelectCompileState): ...

class SnowflakeIdentifierPreparer(compiler.IdentifierPreparer):
    reserved_words = ...
    illegal_initial_characters = ...
    illegal_identifiers = ...
    def __init__(self, dialect, **kw) -> None: ...
    def quote_schema(self, schema, force=...): ...
    def format_label(self, label, name=...): ...

class SnowflakeCompiler(compiler.SQLCompiler):
    def visit_sequence(self, sequence, **kw): ...
    def visit_now_func(self, now, **kw): ...
    def visit_sysdate_func(self, sysdate, **kw): ...
    def visit_merge_into(self, merge_into, **kw): ...
    def visit_merge_into_clause(self, merge_into_clause, **kw): ...
    def visit_copy_into(self, copy_into, **kw): ...
    def visit_copy_formatter(self, formatter, **kw): ...
    def visit_aws_bucket(self, aws_bucket, **kw): ...
    def visit_azure_container(self, azure_container, **kw): ...
    def visit_external_stage(self, external_stage, **kw): ...
    def delete_extra_from_clause(self, delete_stmt, from_table, extra_froms, from_hints, **kw): ...
    def update_from_clause(self, update_stmt, from_table, extra_froms, from_hints, **kw): ...
    def visit_regexp_match_op_binary(self, binary, operator, **kw): ...
    def visit_regexp_replace_op_binary(self, binary, operator, **kw): ...
    def visit_not_regexp_match_op_binary(self, binary, operator, **kw): ...
    def visit_ilike_op_binary(self, binary, operator, **kw): ...
    def visit_not_ilike_op_binary(self, binary, operator, **kw): ...
    def visit_join(self, join, asfrom=..., from_linter=..., **kwargs): ...
    def visit_truediv_binary(self, binary, operator, **kw): ...
    def visit_floordiv_binary(self, binary, operator, **kw): ...
    def render_literal_value(self, value, type_): ...

class SnowflakeExecutionContext(default.DefaultExecutionContext):
    INSERT_SQL_RE = ...
    def fire_sequence(self, seq, type_): ...
    def should_autocommit_text(self, statement): ...
    @sa_util.memoized_property
    def should_autocommit(self): ...
    def pre_exec(self): ...
    def post_exec(self): ...
    @property
    def rowcount(self): ...

class SnowflakeDDLCompiler(compiler.DDLCompiler):
    def denormalize_column_name(self, name): ...
    def get_column_specification(self, column, **kwargs): ...
    def handle_cluster_by(self, table): ...
    def post_create_table(self, table): ...
    def visit_create_stage(self, create_stage, **kw): ...
    def visit_create_file_format(self, file_format, **kw): ...
    def visit_drop_table_comment(self, drop, **kw): ...
    def visit_drop_column_comment(self, drop, **kw): ...
    def visit_identity_column(self, identity, **kw): ...
    def get_identity_options(self, identity_options): ...

class SnowflakeTypeCompiler(compiler.GenericTypeCompiler):
    def visit_BYTEINT(self, type_, **kw): ...
    def visit_CHARACTER(self, type_, **kw): ...
    def visit_DEC(self, type_, **kw): ...
    def visit_DOUBLE(self, type_, **kw): ...
    def visit_FIXED(self, type_, **kw): ...
    def visit_INT(self, type_, **kw): ...
    def visit_NUMBER(self, type_, **kw): ...
    def visit_STRING(self, type_, **kw): ...
    def visit_TINYINT(self, type_, **kw): ...
    def visit_VARIANT(self, type_, **kw): ...
    def visit_MAP(self, type_, **kw): ...
    def visit_ARRAY(self, type_, **kw): ...
    def visit_SNOWFLAKE_ARRAY(self, type_, **kw): ...
    def visit_OBJECT(self, type_, **kw): ...
    def visit_BLOB(self, type_, **kw): ...
    def visit_datetime(self, type_: sqltypes.DateTime, **kw: Any) -> str: ...
    def visit_DATETIME(self, type_: sqltypes.DateTime, **kw: Any) -> str: ...
    def visit_TIMESTAMP_NTZ(self, type_, **kw): ...
    def visit_TIMESTAMP_TZ(self, type_, **kw): ...
    def visit_TIMESTAMP_LTZ(self, type_, **kw): ...
    def visit_TIMESTAMP(self, type_: sqltypes.TIMESTAMP, **kw: Any) -> str: ...
    def visit_GEOGRAPHY(self, type_, **kw): ...
    def visit_GEOMETRY(self, type_, **kw): ...
    def visit_DECFLOAT(self, type_, **kw): ...
    def visit_VECTOR(self, type_, **kw): ...

construct_arguments = ...
