import sqlalchemy.types as sqltypes
from sqlalchemy.types import TypeEngine

DECFLOAT_PRECISION = ...
TEXT = sqltypes.VARCHAR
CHARACTER = sqltypes.CHAR
DEC = sqltypes.DECIMAL
DOUBLE = sqltypes.FLOAT
FIXED = sqltypes.DECIMAL
NUMBER = sqltypes.DECIMAL
BYTEINT = sqltypes.SMALLINT
STRING = sqltypes.VARCHAR
TINYINT = sqltypes.SMALLINT
VARBINARY = sqltypes.BINARY

class SnowflakeType(sqltypes.TypeEngine): ...

class VARIANT(SnowflakeType):
    __visit_name__ = ...

class VECTOR(SnowflakeType):
    __visit_name__ = ...
    _VALID_ELEMENT_TYPES = ...
    def __init__(self, element_type: str | sqltypes.Integer | sqltypes.Float, dimension: int) -> None: ...

class StructuredType(SnowflakeType):
    def __init__(self, is_semi_structured: bool = ...) -> None: ...

class MAP(StructuredType):
    __visit_name__ = ...
    def __init__(self, key_type: sqltypes.TypeEngine, value_type: sqltypes.TypeEngine, not_null: bool = ...) -> None: ...

class OBJECT(StructuredType):
    __visit_name__ = ...
    def __init__(self, **items_types: TypeEngine | tuple[TypeEngine, bool]) -> None: ...

class ARRAY(StructuredType):
    __visit_name__ = ...
    def __init__(self, value_type: sqltypes.TypeEngine | None = ..., not_null: bool = ...) -> None: ...

class TIMESTAMP_TZ(SnowflakeType):
    __visit_name__ = ...

class TIMESTAMP_LTZ(SnowflakeType):
    __visit_name__ = ...

class TIMESTAMP_NTZ(SnowflakeType):
    __visit_name__ = ...

class GEOGRAPHY(SnowflakeType):
    __visit_name__ = ...

class GEOMETRY(SnowflakeType):
    __visit_name__ = ...

class DECFLOAT(SnowflakeType):
    __visit_name__ = ...
    _warned_precision = ...
    def result_processor(self, dialect, coltype): ...

class _CUSTOM_Date(SnowflakeType, sqltypes.Date):
    def literal_processor(self, dialect): ...

class _CUSTOM_DateTime(SnowflakeType, sqltypes.DateTime):
    def __init__(self, timezone=...) -> None: ...
    def literal_processor(self, dialect): ...

class _CUSTOM_Time(SnowflakeType, sqltypes.Time):
    def literal_processor(self, dialect): ...

class _CUSTOM_Float(SnowflakeType, sqltypes.Float):
    def bind_processor(self, dialect): ...

class _CUSTOM_DECIMAL(SnowflakeType, sqltypes.DECIMAL): ...
