from sqlalchemy.sql.ddl import DDLElement
from sqlalchemy.sql.dml import UpdateBase
from sqlalchemy.sql.elements import ClauseElement
from sqlalchemy.sql.roles import FromClauseRole

NoneType = ...

def translate_bool(bln): ...

class MergeInto(UpdateBase):
    __visit_name__ = ...
    _bind = ...
    def __init__(self, target, source, on) -> None: ...

    class clause(ClauseElement):
        __visit_name__ = ...
        def __init__(self, command) -> None: ...
        def values(self, **kwargs): ...
        def where(self, expr): ...

    def when_matched_then_update(self): ...
    def when_matched_then_delete(self): ...
    def when_not_matched_then_insert(self): ...

class FilesOption:
    def __init__(self, file_names: list[str]) -> None: ...

class CopyInto(UpdateBase):
    __visit_name__ = ...
    _bind = ...
    def __init__(self, from_, into, partition_by=..., formatter=...) -> None: ...
    def bind(self): ...
    def force(self, force): ...
    def single(self, single_file): ...
    def maxfilesize(self, max_size): ...
    def files(self, file_names): ...
    def pattern(self, pattern): ...

class CopyFormatter(ClauseElement):
    __visit_name__ = ...
    def __init__(self, format_name=...) -> None: ...
    @staticmethod
    def value_repr(name, value): ...

class CSVFormatter(CopyFormatter):
    file_format = ...
    def compression(self, comp_type): ...
    def record_delimiter(self, deli_type): ...
    def field_delimiter(self, deli_type): ...
    def file_extension(self, ext): ...
    def date_format(self, dt_frmt): ...
    def time_format(self, tm_frmt): ...
    def timestamp_format(self, tmstmp_frmt): ...
    def binary_format(self, bin_fmt): ...
    def escape(self, esc): ...
    def escape_unenclosed_field(self, esc): ...
    def field_optionally_enclosed_by(self, enc): ...
    def null_if(self, null_value): ...
    def skip_header(self, skip_header): ...
    def trim_space(self, trim_space): ...
    def error_on_column_count_mismatch(self, error_on_col_count_mismatch): ...

class JSONFormatter(CopyFormatter):
    file_format = ...
    def compression(self, comp_type): ...
    def file_extension(self, ext): ...

class PARQUETFormatter(CopyFormatter):
    file_format = ...
    def snappy_compression(self, comp): ...
    def compression(self, comp): ...
    def binary_as_text(self, value): ...

class ExternalStage(ClauseElement, FromClauseRole):
    __visit_name__ = ...
    _hide_froms = ...
    @staticmethod
    def prepare_namespace(namespace): ...
    @staticmethod
    def prepare_path(path): ...
    def __init__(self, name, path=..., namespace=..., file_format=...) -> None: ...
    @classmethod
    def from_parent_stage(cls, parent_stage, path, file_format=...): ...

class CreateFileFormat(DDLElement):
    __visit_name__ = ...
    def __init__(self, format_name, formatter, replace_if_exists=...) -> None: ...

class CreateStage(DDLElement):
    __visit_name__ = ...
    def __init__(self, container, stage, replace_if_exists=..., *, temporary=...) -> None: ...

class AWSBucket(ClauseElement):
    __visit_name__ = ...
    def __init__(self, bucket, path=...) -> None: ...
    @classmethod
    def from_uri(cls, uri): ...
    def credentials(self, aws_role=..., aws_key_id=..., aws_secret_key=..., aws_token=...): ...
    def encryption_aws_cse(self, master_key): ...
    def encryption_aws_sse_s3(self): ...
    def encryption_aws_sse_kms(self, kms_key_id=...): ...

class AzureContainer(ClauseElement):
    __visit_name__ = ...
    def __init__(self, account, container, path=...) -> None: ...
    @classmethod
    def from_uri(cls, uri): ...
    def credentials(self, azure_sas_token): ...
    def encryption_azure_cse(self, master_key): ...

CopyIntoStorage = CopyInto
