from sqlalchemy.exc import ArgumentError

class NoPrimaryKeyError(ArgumentError):
    def __init__(self, target: str) -> None: ...

class UnsupportedPrimaryKeysAndForeignKeysError(ArgumentError):
    def __init__(self, target: str) -> None: ...

class RequiredParametersNotProvidedError(ArgumentError):
    def __init__(self, target: str, parameters: list[str]) -> None: ...

class UnexpectedTableOptionKeyError(ArgumentError):
    def __init__(self, expected: str, actual: str) -> None: ...

class OptionKeyNotProvidedError(ArgumentError):
    def __init__(self, target: str) -> None: ...

class UnexpectedOptionParameterTypeError(ArgumentError):
    def __init__(self, parameter_name: str, target: str, types: list[str]) -> None: ...

class CustomOptionsAreOnlySupportedOnSnowflakeTables(ArgumentError):
    def __init__(self) -> None: ...

class UnexpectedOptionTypeError(ArgumentError):
    def __init__(self, options: list[str]) -> None: ...

class InvalidTableParameterTypeError(ArgumentError):
    def __init__(self, name: str, input_type: str, expected_types: list[str]) -> None: ...

class MultipleErrors(ArgumentError):
    def __init__(self, errors) -> None: ...

class StructuredTypeNotSupportedInTableColumnsError(ArgumentError):
    def __init__(self, table_type: str, table_name: str, column_name: str) -> None: ...
