from sqlalchemy.sql.compiler import IdentifierPreparer

class _NameUtils:
    def __init__(self, identifier_preparer: IdentifierPreparer) -> None: ...
    def normalize_name(self, name): ...
    def denormalize_name(self, name): ...
