from sqlalchemy.testing.requirements import SuiteRequirements

class Requirements(SuiteRequirements):
    @property
    def table_ddl_if_exists(self): ...
    @property
    def table_value_constructor(self): ...
    @property
    def deferrable_fks(self): ...
    @property
    def boolean_col_expressions(self): ...
    @property
    def nullsordering(self): ...
    @property
    def standalone_binds(self): ...
    @property
    def intersect(self): ...
    @property
    def except_(self): ...
    @property
    def window_functions(self): ...
    @property
    def ctes(self): ...
    @property
    def ctes_on_dml(self): ...
    @property
    def tuple_in(self): ...
    @property
    def emulated_lastrowid(self): ...
    @property
    def emulated_lastrowid_even_with_sequences(self): ...
    @property
    def views(self): ...
    @property
    def cross_schema_fk_reflection(self): ...
    @property
    def foreign_key_constraint_name_reflection(self): ...
    @property
    def implicit_default_schema(self): ...
    @property
    def default_schema_name_switch(self): ...
    @property
    def reflects_pk_names(self): ...
    @property
    def comment_reflection(self): ...
    @property
    def fk_constraint_option_reflection_ondelete_noaction(self): ...
    @property
    def temp_table_names(self): ...
    @property
    def temporary_views(self): ...
    @property
    def unicode_ddl(self): ...
    @property
    def datetime_literals(self): ...
    @property
    def timestamp_microseconds(self): ...
    @property
    def datetime_historic(self): ...
    @property
    def date_historic(self): ...
    @property
    def legacy_unconditional_json_extract(self): ...
    @property
    def precision_numerics_enotation_small(self): ...
    @property
    def precision_numerics_enotation_large(self): ...
    @property
    def precision_numerics_many_significant_digits(self): ...
    @property
    def precision_numerics_retains_significant_digits(self): ...
    @property
    def infinity_floats(self): ...
    @property
    def update_from(self): ...
    @property
    def delete_from(self): ...
    @property
    def mod_operator_as_percent_sign(self): ...
    @property
    def percent_schema_names(self): ...
    @property
    def order_by_label_with_expression(self): ...
    @property
    def regexp_match(self): ...
    @property
    def regexp_replace(self): ...
    @property
    def fetch_first(self): ...
    @property
    def fetch_no_order_by(self): ...
    @property
    def fetch_offset_with_options(self): ...
    @property
    def identity_columns(self): ...
    @property
    def duplicate_key_raises_integrity_error(self): ...
    @property
    def ctes_with_update_delete(self): ...
    @property
    def sql_expression_limit_offset(self): ...
    @property
    def json_type(self): ...
    @property
    def implements_get_lastrowid(self): ...
    @property
    def implicit_decimal_binds(self): ...
    @property
    def datetime_implicit_bound(self): ...
    @property
    def date_implicit_bound(self): ...
    @property
    def time_implicit_bound(self): ...
    @property
    def timestamp_microseconds_implicit_bound(self): ...
    @property
    def array_type(self): ...
