from collections.abc import Collection
from enum import Enum
from typing import Any

from sqlalchemy import event as sa_vnt
from sqlalchemy.engine import URL, default, reflection
from sqlalchemy.schema import Table

from .base import SnowflakeCompiler, SnowflakeDDLCompiler, SnowflakeExecutionContext, SnowflakeIdentifierPreparer, SnowflakeTypeCompiler
from .parser.custom_type_parser import *

colspecs = ...
_ENABLE_SQLALCHEMY_AS_APPLICATION_NAME = ...
logger = ...

class TelemetryEvents(Enum):
    NEW_CONNECTION = ...

class SnowflakeIsolationLevel(Enum):
    READ_COMMITTED = ...
    AUTOCOMMIT = ...

class SnowflakeDialect(default.DefaultDialect):
    name = ...
    driver = ...
    max_identifier_length = ...
    cte_follows_insert = ...
    supports_statement_cache = ...
    encoding = ...
    default_paramstyle = ...
    colspecs = ...
    ischema_names = ...
    div_is_floordiv = ...
    convert_unicode = ...
    supports_unicode_statements = ...
    supports_unicode_binds = ...
    returns_unicode_strings = ...
    description_encoding = ...
    postfetch_lastrowid = ...
    supports_sane_rowcount = ...
    supports_sane_multi_rowcount = ...
    supports_native_decimal = ...
    supports_native_boolean = ...
    supports_alter = ...
    supports_sequences = ...
    supports_native_enum = ...
    supports_multivalues_insert = ...
    supports_comments = ...
    preparer = SnowflakeIdentifierPreparer
    ddl_compiler = SnowflakeDDLCompiler
    type_compiler = SnowflakeTypeCompiler
    statement_compiler = SnowflakeCompiler
    execution_ctx_cls = SnowflakeExecutionContext
    requires_name_normalize = ...
    multivalues_inserts = ...
    supports_schemas = ...
    sequences_optional = ...
    supports_is_distinct_from = ...
    supports_identity_columns = ...
    def __init__(
        self, force_div_is_floordiv: bool = ..., isolation_level: str | None = ..., enable_decfloat: bool = ..., **kwargs: Any
    ) -> None: ...
    def initialize(self, connection): ...
    @classmethod
    def dbapi(cls): ...
    @classmethod
    def import_dbapi(cls): ...
    @staticmethod
    def parse_query_param_type(name: str, value: Any) -> Any: ...
    def create_connect_args(self, url: URL): ...
    @reflection.cache
    def has_table(self, connection, table_name, schema=..., **kw): ...
    def get_isolation_level_values(self, dbapi_connection): ...
    def do_rollback(self, dbapi_connection): ...
    def do_commit(self, dbapi_connection): ...
    def get_default_isolation_level(self, dbapi_conn): ...
    def set_isolation_level(self, dbapi_connection, level): ...
    @reflection.cache
    def has_sequence(self, connection, sequence_name, schema=..., **kw): ...
    def normalize_name(self, name): ...
    def denormalize_name(self, name): ...
    @reflection.cache
    def get_check_constraints(self, connection, table_name, schema, **kw): ...
    def get_pk_constraint(self, connection, table_name, schema=..., **kw): ...
    def get_unique_constraints(self, connection, table_name, schema, **kw): ...
    def get_foreign_keys(self, connection, table_name, schema=..., **kw): ...
    def get_columns(self, connection, table_name, schema=..., **kw): ...
    def get_prefixes_from_data(self, name_to_index_map, row, **kw): ...
    def get_table_names(self, connection, schema=..., **kw): ...
    @reflection.cache
    def get_view_names(self, connection, schema=..., **kw): ...
    @reflection.cache
    def get_view_definition(self, connection, view_name, schema=..., **kw): ...
    def get_temp_table_names(self, connection, schema=..., **kw): ...
    def get_schema_names(self, connection, **kw): ...
    @reflection.cache
    def get_sequence_names(self, connection, schema=..., **kw): ...
    def get_table_comment(self, connection, table_name, schema=..., **kw): ...
    def get_table_names_with_prefix(self, connection, *, schema, prefix, **kw): ...
    def get_multi_indexes(self, connection, *, schema: str | None = ..., filter_names: Collection[str] | None = ..., **kw): ...
    @reflection.cache
    def get_indexes(self, connection, tablename, schema, **kw): ...
    def connect(self, *cargs, **cparams): ...

@sa_vnt.listens_for(Table, "before_create")
def check_table(table, connection, _ddl_runner, **kw): ...

dialect = SnowflakeDialect
