from snowflake.sqlalchemy.name_utils import _NameUtils

class _StructuredTypeInfoManager:
    def __init__(self, connection, name_utils: _NameUtils, default_schema: str) -> None: ...
    def get_column_info(self, schema_name: str, table_name: str, column_name: str, **kwargs): ...
    def get_table_columns(self, table_name: str, schema: str = ...): ...
