from sqlalchemy.orm.util import _ORMJoin as sa_orm_util_ORMJoin
from sqlalchemy.sql.selectable import Join

def parse_url_boolean(value: str) -> bool: ...
def parse_url_integer(value: str) -> int: ...

class _Snowflake_ORMJoin(sa_orm_util_ORMJoin):
    def __init__(self, left, right, onclause=..., isouter=..., full=..., _left_memo=..., _right_memo=..., _extra_criteria=...) -> None: ...

class _Snowflake_Selectable_Join(Join):
    def __init__(self, left, right, onclause=..., isouter=..., full=...) -> None: ...
