xpath_tokenizer_re = ...

def xpath_tokenizer(pattern, namespaces=..., with_prefixes=...): ...
def prepare_child(next, token): ...
def prepare_star(next, token): ...
def prepare_self(next, token): ...
def prepare_descendant(next, token): ...
def prepare_parent(next, token): ...
def prepare_predicate(next, token): ...

ops = ...
_cache = ...

def iterfind(elem, path, namespaces=..., with_prefixes=...): ...
def find(elem, path, namespaces=..., with_prefixes=...): ...
def findall(elem, path, namespaces=..., with_prefixes=...): ...
def findtext(elem, path, default=..., namespaces=..., with_prefixes=...): ...
