_QName = ...

class ElementMaker:
    def __init__(self, typemap=..., namespace=..., nsmap=..., makeelement=...) -> None: ...
    def __call__(self, tag, *children, **attrib): ...
    def __getattr__(self, tag): ...
    def __class_getitem__(cls, item): ...

E = ...
