import doctest

__all__ = ["NOPARSE_MARKUP", "PARSE_HTML", "PARSE_XML", "LHTMLOutputChecker", "LXMLOutputChecker", "install", "temp_install"]
PARSE_HTML = ...
PARSE_XML = ...
NOPARSE_MARKUP = ...
OutputChecker = doctest.OutputChecker

def strip(v): ...
def norm_whitespace(v): ...

_html_parser = ...

def html_fromstring(html): ...

_repr_re = ...
_norm_whitespace_re = ...

class LXMLOutputChecker(OutputChecker):
    empty_tags = ...
    def get_default_parser(self): ...
    def check_output(self, want, got, optionflags): ...
    def get_parser(self, want, got, optionflags): ...
    def compare_docs(self, want, got): ...
    def text_compare(self, want, got, strip): ...
    def tag_compare(self, want, got): ...
    def output_difference(self, example, got, optionflags): ...
    def html_empty_tag(self, el, html=...): ...
    def format_doc(self, doc, html, indent, prefix=...): ...
    def format_text(self, text, strip=...): ...
    def format_tag(self, el): ...
    def format_end_tag(self, el): ...
    def collect_diff(self, want, got, html, indent): ...
    def collect_diff_tag(self, want, got): ...
    def collect_diff_end_tag(self, want, got): ...
    def collect_diff_text(self, want, got, strip=...): ...

class LHTMLOutputChecker(LXMLOutputChecker):
    def get_default_parser(self): ...

def install(html=...): ...
def temp_install(html=..., del_module=...): ...

class _RestoreChecker:
    def __init__(self, dt_self, old_checker, new_checker, check_func, clone_func, del_module) -> None: ...
    def install_clone(self): ...
    def uninstall_clone(self): ...
    def install_dt_self(self): ...
    def uninstall_dt_self(self): ...
    def uninstall_module(self): ...
    def __call__(self, *args, **kw): ...
    def call_super(self, *args, **kw): ...

__test__ = ...
if __name__ == "__main__": ...
