from lxml import etree

XINCLUDE = ...
XINCLUDE_INCLUDE = ...
XINCLUDE_FALLBACK = ...
XINCLUDE_ITER_TAG = ...
DEFAULT_MAX_INCLUSION_DEPTH = ...

class FatalIncludeError(etree.LxmlSyntaxError): ...
class LimitedRecursiveIncludeError(FatalIncludeError): ...

def default_loader(href, parse, encoding=...): ...
def include(elem, loader=..., base_url=..., max_depth=...): ...
