from xml.sax.handler import ContentHandler

from lxml import etree

class SaxError(etree.LxmlError): ...

class ElementTreeContentHandler(ContentHandler):
    def __init__(self, makeelement=...) -> None: ...

    etree = ...
    def setDocumentLocator(self, locator): ...
    def startDocument(self): ...
    def endDocument(self): ...
    def startPrefixMapping(self, prefix, uri): ...
    def endPrefixMapping(self, prefix): ...
    def startElementNS(self, ns_name, qname, attributes=...): ...
    def processingInstruction(self, target, data): ...
    def endElementNS(self, ns_name, qname): ...
    def startElement(self, name, attributes=...): ...
    def endElement(self, name): ...
    def characters(self, data): ...

    ignorableWhitespace = ...
    def __class_getitem__(cls, item): ...

class ElementTreeProducer:
    def __init__(self, element_or_tree, content_handler) -> None: ...
    def saxify(self): ...

def saxify(element_or_tree, content_handler): ...
