"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._domain import Domain
from ._imaginaryaxis import Imaginaryaxis
from ._realaxis import Realaxis
from . import imaginaryaxis, realaxis

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
else:
    ...
