from numba.core.extending import register_jitable
from numba.core.imputils import lower_builtin

class StencilFuncLowerer:
    def __init__(self, sf) -> None: ...
    def __call__(self, context, builder, sig, args): ...

@register_jitable
def raise_if_incompatible_array_sizes(a, *args):  # -> None:
    ...
def slice_addition(the_slice, addend):  # -> slice[Any, Any, Any]:

    ...

class StencilFunc:
    id_counter = ...
    def __init__(self, kernel_ir, mode, options) -> None: ...
    def replace_return_with_setitem(self, blocks, index_vars, out_name):  # -> list[Any]:

        ...
    def add_indices_to_kernel(self, kernel, index_names, ndim, neighborhood, standard_indexed, typemap, calltypes): ...
    def get_return_type(self, argtys):  # -> tuple[Array, Any, Any]:
        ...
    def compile_for_argtys(self, argtys, kwtys, return_type, sigret): ...
    def copy_ir_with_calltypes(self, ir, calltypes):  # -> tuple[Any, dict[Any, Any]]:

        ...
    def __call__(self, *args, **kwargs): ...

def stencil(func_or_mode=..., **options):  # -> StencilFunc | Callable[..., StencilFunc]:
    ...
@lower_builtin(stencil)
def stencil_dummy_lower(context, builder, sig, args):  # -> Constant:

    ...
