class StencilPass:
    def __init__(self, func_ir, typemap, calltypes, array_analysis, typingctx, targetctx, flags) -> None: ...
    def run(self):  # -> None:

        ...
    def replace_return_with_setitem(self, blocks, exit_value_var, parfor_body_exit_label):  # -> None:

        ...

def get_stencil_ir(sf, typingctx, args, scope, loc, input_dict, typemap, calltypes):  # -> tuple[Any, Any, dict[Any, Any]]:

    ...

class DummyPipeline:
    def __init__(self, typingctx, targetctx, args, f_ir) -> None: ...
