"""
This type stub file was generated by pyright.
"""

"""Collection of utility functions for the PandasDataFrame."""
def concatenate(dfs, copy=...):
    """
    Concatenate pandas DataFrames with saving 'category' dtype.

    All dataframes' columns must be equal to each other.

    Parameters
    ----------
    dfs : list
        List of pandas DataFrames to concatenate.
    copy : bool, default: True
        Make explicit copy when creating dataframe.

    Returns
    -------
    pandas.DataFrame
        A pandas DataFrame.
    """
    ...

def create_pandas_df_from_partitions(partition_data, partition_shape, called_from_remote=..., new_index=..., new_columns=...): # -> DataFrame:
    """
    Convert partition data of multiple dataframes to a single dataframe.

    Parameters
    ----------
    partition_data : list
        List of pandas DataFrames or list of Object references holding pandas DataFrames.
    partition_shape : int or tuple
        Shape of the partitions NumPy array.
    called_from_remote : bool, default: False
        Flag used to check if explicit copy should be done in concat.
    new_index : pandas.Index, optional
        Index for propagation into internal partitions.
        Optimization allowing to do this in one remote kernel.
    new_columns : pandas.Index, optional
        Columns for propagation into internal partitions.
        Optimization allowing to do this in one remote kernel.

    Returns
    -------
    pandas.DataFrame
        A pandas DataFrame.
    """
    ...

