"""
This type stub file was generated by pyright.
"""

from modin.core.io.text.text_file_dispatcher import TextFileDispatcher

"""Module houses `JSONDispatcher` class, that is used for reading `.json` files."""
class JSONDispatcher(TextFileDispatcher):
    """Class handles utils for reading `.json` files."""
    ...


