"""
This type stub file was generated by pyright.
"""

"""Contains utility functions for dispatchers."""
class CustomNewlineIterator:
    r"""
    Used to iterate through files in binary mode line by line where newline != b'\n'.

    Parameters
    ----------
    _file : file-like object
        File-like object to iterate over.
    newline : bytes
        Byte or sequence of bytes indicating line endings.
    """
    def __init__(self, _file, newline) -> None:
        ...
    
    def __iter__(self): # -> Generator[Any, Any, None]:
        """
        Iterate over lines.

        Yields
        ------
        bytes
            Data from file.
        """
        ...
    
    def seek(self): # -> None:
        """Change the stream positition to where the last returned line ends."""
        ...
    


