from lxml import etree as _etree

__all__ = [
    "Schematron",
    "extract_rng",
    "extract_xsd",
    "iso_abstract_expand",
    "iso_dsdl_include",
    "iso_svrl_for_xslt1",
    "schematron_schema_valid",
    "stylesheet_params",
    "svrl_validation_errors",
]
XML_SCHEMA_NS = ...
RELAXNG_NS = ...
SCHEMATRON_NS = ...
SVRL_NS = ...
_schematron_root = ...
_xml_schema_root = ...
_resources_dir = ...
extract_xsd = ...
extract_rng = ...
iso_dsdl_include = ...
iso_abstract_expand = ...
iso_svrl_for_xslt1 = ...
svrl_validation_errors = ...
schematron_schema_valid_supported = ...
schematron_schema_valid = ...
schematron_schema_valid_supported = ...

def stylesheet_params(**kwargs): ...

class Schematron(_etree._Validator):
    _domain = ...
    _level = ...
    _error_type = ...
    ASSERTS_ONLY = ...
    ASSERTS_AND_REPORTS = ...
    _extract_xsd = ...
    _extract_rng = ...
    _include = ...
    _expand = ...
    _compile = ...
    _validation_errors = ...
    def __init__(
        self,
        etree=...,
        file=...,
        include=...,
        expand=...,
        include_params=...,
        expand_params=...,
        compile_params=...,
        store_schematron=...,
        store_xslt=...,
        store_report=...,
        phase=...,
        error_finder=...,
        validate_schema=...,
    ) -> None: ...
    def __call__(self, etree): ...
    @property
    def schematron(self): ...
    @property
    def validator_xslt(self): ...
    @property
    def validation_report(self): ...
