from collections.abc import MutableMapping

from numba.core import types
from numba.core.extending import box, overload, overload_classmethod, type_callable, unbox
from numba.core.imputils import numba_typeref_ctor
from numba.core.types import DictType

"""
Python wrapper that connects CPython interpreter to the numba dictobject.
"""

class Dict(MutableMapping):
    def __new__(cls, dcttype=..., meminfo=..., n_keys=...):  # -> dict[Any, Any] | Self:
        ...
    @classmethod
    def empty(cls, key_type, value_type, n_keys=...):  # -> dict[Any, Any] | Self:

        ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None:  # -> None:
        ...
    def __delitem__(self, key) -> None:  # -> None:
        ...
    def __iter__(self):  # -> Iterator[Never] | Iterator[Any]:
        ...
    def __len__(self) -> int:  # -> int:
        ...
    def __contains__(self, key) -> bool:  # -> bool:
        ...
    def get(self, key, default=...):  # -> None:
        ...
    def setdefault(self, key, default=...): ...
    def popitem(self): ...
    def copy(self): ...

@overload_classmethod(types.DictType, "empty")
def typeddict_empty(cls, key_type, value_type, n_keys=...):  # -> Callable[..., dict[Any, Any]] | None:
    ...
@box(types.DictType)
def box_dicttype(typ, val, c): ...
@unbox(types.DictType)
def unbox_dicttype(typ, val, c): ...
@type_callable(DictType)
def typeddict_call(context):  # -> Callable[..., DictType | None]:

    ...
@overload(numba_typeref_ctor)
def impl_numba_typeref_ctor(cls, *args):  # -> Callable[..., dict[Any, Any] | Dict] | None:

    ...
