import typing as pt
from collections.abc import MutableSequence

from numba.core import types
from numba.core.extending import box, overload, overload_classmethod, type_callable, unbox
from numba.core.imputils import numba_typeref_ctor
from numba.core.types import ListType

"""
Python wrapper that connects CPython interpreter to the Numba typed-list.

This is the code that is used when creating typed lists outside of a `@jit`
context and when returning a typed-list from a `@jit` decorated function. It
basically a Python class that has a Numba allocated typed-list under the hood
and uses `@jit` functions to access it. Since it inherits from MutableSequence
it should really quack like the CPython `list`.

"""
type Int_or_Slice = pt.SupportsIndex | slice
T_co = pt.TypeVar("T_co", covariant=True)

class _Sequence(pt.Protocol[T_co]):
    def __getitem__(self, i: int) -> T_co: ...
    def __len__(self) -> int: ...

DEFAULT_ALLOCATED = ...
T = pt.TypeVar("T")
type T_or_ListT[T] = T | List[T]

class List[T](MutableSequence):
    _legal_kwargs = ...
    def __new__(cls, *args, lsttype=..., meminfo=..., allocated=..., **kwargs):  # -> list[Any] | Self:
        ...
    @classmethod
    def empty_list(cls, item_type, allocated=...):  # -> list[Any] | Self:

        ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __len__(self) -> int: ...
    def __eq__(self, other) -> bool: ...
    def __ne__(self, other) -> bool: ...
    def __lt__(self, other) -> bool: ...
    def __le__(self, other) -> bool: ...
    def __gt__(self, other) -> bool: ...
    def __ge__(self, other) -> bool: ...
    def append(self, item: T) -> None: ...
    @pt.overload
    def __setitem__(self, i: int, o: T) -> None: ...
    @pt.overload
    def __setitem__(self, s: slice, o: List[T]) -> None: ...
    def __setitem__(self, i: Int_or_Slice, item: T_or_ListT) -> None: ...
    @pt.overload
    def __getitem__(self, i: int) -> T: ...
    @pt.overload
    def __getitem__(self, i: slice) -> List[T]: ...
    def __getitem__(self, i: Int_or_Slice) -> T_or_ListT: ...
    def __iter__(self) -> pt.Iterator[T]: ...
    def __contains__(self, item: T) -> bool: ...
    def __delitem__(self, i: Int_or_Slice) -> None: ...
    def insert(self, i: int, item: T) -> None: ...
    def count(self, item: T) -> int: ...
    def pop(self, i: pt.SupportsIndex = ...) -> T: ...
    def extend(self, iterable: _Sequence[T]) -> None: ...
    def remove(self, item: T) -> None: ...
    def clear(self):  # -> None:
        ...
    def reverse(self):  # -> None:
        ...
    def copy(self): ...
    def index(self, item: T, start: int | None = ..., stop: int | None = ...) -> int: ...
    def sort(self, key=..., reverse=...): ...

@overload_classmethod(ListType, "empty_list")
def typedlist_empty(cls, item_type, allocated=...):  # -> Callable[..., list[Any]] | None:
    ...
@box(types.ListType)
def box_lsttype(typ, val, c): ...
@unbox(types.ListType)
def unbox_listtype(typ, val, c): ...
@type_callable(ListType)
def typedlist_call(context) -> None:  # -> Typer:

    ...
@overload(numba_typeref_ctor)
def impl_numba_typeref_ctor(cls, *args):  # -> Callable[..., list[Any] | List[Any]] | None:

    ...
