from abc import ABC

from PIL import Image

_logger = ...

class BrowserConverter(ABC):
    MAX_IMAGE_SIZE = ...
    def __init__(
        self,
        center_df: bool = ...,
        max_rows: int = ...,
        max_cols: int = ...,
        chrome_path: str = ...,
        fontsize: int = ...,
        encode_base64: bool = ...,
        crop_top: bool = ...,
        device_scale_factor: int = ...,
        use_mathjax: bool = ...,
    ) -> None: ...
    def build_valid_html(self, html: str) -> str: ...
    def get_css(self) -> str: ...
    def should_enlarge(self, img: Image, ss_width: int, ss_height: int) -> tuple: ...
    def screenshot(self, html: str, ss_width: int = ..., ss_height: int = ...) -> Image: ...
    def crop(self, im: Image) -> Image: ...
    def run(self, html: str) -> bytes: ...
    def finalize_image(self, img: Image) -> bytes: ...
    def repr_png_wrapper(self): ...
