import sys

"""Utilities for determining application-specific dirs.

See <http://github.com/ActiveState/appdirs> for details and usage.
"""
__version_info__ = ...
__version__ = ...
unicode = str
if sys.platform.startswith("java"):
    os_name = ...
else:
    system = ...

def user_data_dir(appname=..., appauthor=..., version=..., roaming=...):  # -> str | Any:

    ...
def site_data_dir(appname=..., appauthor=..., version=..., multipath=...):  # -> str | Any:

    ...
def user_config_dir(appname=..., appauthor=..., version=..., roaming=...):  # -> str | Any:

    ...
def site_config_dir(appname=..., appauthor=..., version=..., multipath=...):  # -> str | Any:

    ...
def user_cache_dir(appname=..., appauthor=..., version=..., opinion=...):  # -> str | Any:

    ...
def user_log_dir(appname=..., appauthor=..., version=..., opinion=...):  # -> str | Any:

    ...

class AppDirs:
    def __init__(self, appname, appauthor=..., version=..., roaming=..., multipath=...) -> None: ...
    @property
    def user_data_dir(self):  # -> str | Any:
        ...
    @property
    def site_data_dir(self):  # -> str | Any:
        ...
    @property
    def user_config_dir(self):  # -> str | Any:
        ...
    @property
    def site_config_dir(self):  # -> str | Any:
        ...
    @property
    def user_cache_dir(self):  # -> str | Any:
        ...
    @property
    def user_log_dir(self):  # -> str | Any:
        ...

if system == "win32":
    _get_win_folder = ...
if __name__ == "__main__":
    appname = ...
    appauthor = ...
    props = ...
    dirs = ...
    dirs = ...
    dirs = ...
    dirs = ...
