def get_lib_dirs():  # -> list[str]:

    ...

DLLNAMEMAP = ...
RE_VER = ...

def find_lib(libname, libdir=..., platform=..., static=...):  # -> list[Any]:
    ...
def find_file(pat, libdir=...):  # -> list[Any]:
    ...
