from numba import gdb, gdb_breakpoint, gdb_init
from numba.core.extending import overload

_path = ...
_platform = ...
_unix_like = ...

@overload(gdb)
def hook_gdb(*args):  # -> Callable[..., None]:
    ...
@overload(gdb_init)
def hook_gdb_init(*args):  # -> Callable[..., None]:
    ...
def init_gdb_codegen(cgctx, builder, signature, args, const_args, do_break=...):  # -> None:
    ...
def gen_gdb_impl(const_args, do_break):  # -> Callable[[Callable[Concatenate[object, P], R]], Callable[P, R]]:
    ...
@overload(gdb_breakpoint)
def hook_gdb_breakpoint():  # -> Callable[[], None]:

    ...
def gen_bp_impl():  # -> Callable[[Callable[Concatenate[object, P], R]], Callable[P, R]]:
    ...
