from collections.abc import Sequence
from contextlib import contextmanager

class RecordLLVMPassTimingsLegacy:
    __slots__ = ...
    def __enter__(self):  # -> Self:

        ...
    def __exit__(self, exc_val, exc_type, exc_tb):  # -> None:

        ...
    def get(self):  # -> ProcessedPassTimings:

        ...

class RecordLLVMPassTimings:
    __slots__ = ...
    def __init__(self, pb) -> None: ...
    def __enter__(self):  # -> Self:

        ...
    def __exit__(self, exc_val, exc_type, exc_tb):  # -> None:

        ...
    def get(self):  # -> ProcessedPassTimings:

        ...

PassTimingRecord = ...

class ProcessedPassTimings:
    def __init__(self, raw_data) -> None: ...
    def __bool__(self) -> bool:  # -> bool:
        ...
    def get_raw_data(self):  # -> Any:

        ...
    def get_total_time(self): ...
    def list_records(self):  # -> list[PassTimingRecord]:

        ...
    def list_top(self, n):  # -> list[PassTimingRecord]:

        ...
    def summary(self, topn=..., indent=...):  # -> LiteralString:

        ...

NamedTimings = ...

class PassTimingsCollection(Sequence):
    def __init__(self, name) -> None: ...
    @contextmanager
    def record_legacy(self, name):  # -> Generator[None, Any, None]:

        ...
    @contextmanager
    def record(self, name, pb):  # -> Generator[None, Any, None]:

        ...
    def get_total_time(self):  # -> int | None:

        ...
    def list_longest_first(self):  # -> list[Any]:

        ...
    @property
    def is_empty(self):  # -> bool:

        ...
    def summary(self, topn=...):  # -> LiteralString | Literal['No pass timings were recorded']:

        ...
    def __getitem__(self, i): ...
    def __len__(self) -> int:  # -> int:

        ...
