SMALL_MERGESORT = ...
MergesortImplementation = ...

def make_mergesort_impl(wrap, lt=..., is_argsort=...):  # -> MergesortImplementation:
    ...
def make_jit_mergesort(*args, **kwargs):  # -> MergesortImplementation:
    ...
