_fields = ...
_gdb_info = ...

class _GDBTestWrapper:
    def __init__(self) -> None: ...
    @property
    def gdb_binary(self): ...
    @classmethod
    def success(cls, status): ...
    def check_launch(self):  # -> CompletedProcess[str]:

        ...
    def check_python(self):  # -> CompletedProcess[str]:
        ...
    def check_numpy(self):  # -> CompletedProcess[str]:
        ...
    def check_numpy_version(self):  # -> CompletedProcess[str]:
        ...

def collect_gdbinfo():  # -> _gdb_info:

    ...
def display_gdbinfo(sep_pos=...):  # -> None:

    ...

if __name__ == "__main__": ...
