def pndindex(*args):  # -> ndindex:

    ...

class prange:
    def __new__(cls, *args):  # -> range:
        ...

def gdb(*args):  # -> None:

    ...
def gdb_breakpoint():  # -> None:

    ...
def gdb_init(*args):  # -> None:

    ...
def literally(obj): ...
def literal_unroll(container): ...

__all__ = ["as_numba_type", "gdb", "gdb_breakpoint", "gdb_init", "literal_unroll", "literally", "pndindex", "prange", "typeof"]
