"""
This type stub file was generated by pyright.
"""

from modin.core.dataframe.pandas.partitioning.partition_manager import PandasDataframePartitionManager

"""The module holds Modin partition manager implemented for unidist."""
class GenericUnidistDataframePartitionManager(PandasDataframePartitionManager):
    """The class implements the interface in `PandasDataframePartitionManager`."""
    @classmethod
    def to_numpy(cls, partitions, **kwargs): # -> NDArray[Any]:
        """
        Convert `partitions` into a NumPy array.

        Parameters
        ----------
        partitions : NumPy array
            A 2-D array of partitions to convert to local NumPy array.
        **kwargs : dict
            Keyword arguments to pass to each partition ``.to_numpy()`` call.

        Returns
        -------
        NumPy array
        """
        ...
    


