"""
This type stub file was generated by pyright.
"""

import sys
from typing import TYPE_CHECKING
from ._colorbar import ColorBar
from ._gradient import Gradient
from ._line import Line
from . import colorbar

"""
This type stub file was generated by pyright.
"""
if TYPE_CHECKING:
    ...
else:
    ...
