"""
This type stub file was generated by pyright.
"""

from modin.core.execution.ray.generic.io import RayIO
from ..dataframe import PandasOnRayDataframe
from ..partitioning import PandasOnRayDataframePartition

"""The module holds the factory which performs I/O using pandas on Ray."""
class PandasOnRayIO(RayIO):
    """Factory providing methods for performing I/O operations using pandas as storage format on Ray as engine."""
    frame_cls = PandasOnRayDataframe
    frame_partition_cls = PandasOnRayDataframePartition
    query_compiler_cls = ...
    build_args = ...
    read_csv = ...
    read_fwf = ...
    read_json = ...
    read_parquet = ...
    to_parquet = ...
    read_feather = ...
    read_sql = ...
    to_sql = ...
    read_excel = ...
    read_csv_glob = ...
    read_parquet_glob = ...
    to_parquet_glob = ...
    read_json_glob = ...
    to_json_glob = ...
    read_xml_glob = ...
    to_xml_glob = ...
    read_pickle_glob = ...
    to_pickle_glob = ...
    read_custom_text = ...
    read_sql_distributed = ...
    @classmethod
    def to_csv(cls, qc, **kwargs): # -> None:
        """
        Write records stored in the `qc` to a CSV file.

        Parameters
        ----------
        qc : BaseQueryCompiler
            The query compiler of the Modin dataframe that we want to run ``to_csv`` on.
        **kwargs : dict
            Parameters for ``pandas.to_csv(**kwargs)``.
        """
        ...
    
    @classmethod
    def from_ray(cls, ray_obj): # -> BaseQueryCompiler:
        """
        Create a Modin `query_compiler` from a Ray Dataset.

        Parameters
        ----------
        ray_obj : ray.data.Dataset
            The Ray Dataset to convert from.

        Returns
        -------
        BaseQueryCompiler
            QueryCompiler containing data from the Ray Dataset.
        """
        ...
    
    @classmethod
    def to_ray(cls, modin_obj): # -> MaterializedDataset[Any]:
        """
        Convert a Modin DataFrame/Series to a Ray Dataset.

        Parameters
        ----------
        modin_obj : modin.pandas.DataFrame, modin.pandas.Series
            The Modin DataFrame/Series to convert.

        Returns
        -------
        ray.data.Dataset
            Converted object with type depending on input.
        """
        ...
    
    @classmethod
    def from_map(cls, func, iterable, *args, **kwargs):
        """
        Create a Modin `query_compiler` from a map function.

        This method will construct a Modin `query_compiler` split by row partitions.
        The number of row partitions matches the number of elements in the iterable object.

        Parameters
        ----------
        func : callable
            Function to map across the iterable object.
        iterable : Iterable
            An iterable object.
        *args : tuple
            Positional arguments to pass in `func`.
        **kwargs : dict
            Keyword arguments to pass in `func`.

        Returns
        -------
        BaseQueryCompiler
            QueryCompiler containing data returned by map function.
        """
        ...
    


