browser_map = ...

class Html2Image:
    def __init__(
        self,
        browser=...,
        browser_executable=...,
        browser_cdp_port=...,
        output_path=...,
        size=...,
        temp_path=...,
        keep_temp_files=...,
        custom_flags=...,
        disable_logging=...,
    ) -> None: ...
    @property
    def temp_path(self): ...
    @temp_path.setter
    def temp_path(self, value): ...
    @property
    def output_path(self): ...
    @output_path.setter
    def output_path(self, value): ...
    def load_str(self, content, as_filename): ...
    def load_file(self, src, as_filename=...): ...
    def screenshot_loaded_file(self, file, output_file=..., size=...): ...
    def screenshot_url(self, url, output_file=..., size=...): ...
    def screenshot(self, html_str=..., html_file=..., css_str=..., css_file=..., other_file=..., url=..., save_as=..., size=...): ...
    def __enter__(self): ...
    def __exit__(self, *exc): ...

if __name__ == "__main__": ...
