name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      statuses: read
    steps:
      - name: Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@2c9e7a64481c1a5ab6aa1ac7aac77823b67c1ee4 # main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
