name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      statuses: read
    steps:
      - name: Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@1af00c73a346f8f9d40e2052bc6d4f0710748b0d # main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
