name: Merge Gatekeeper

on:
  pull_request:
    branches:
      - main

jobs:
  merge-gatekeeper:
    runs-on: ubuntu-latest
    permissions:
      checks: read
      statuses: read
    steps:
      - name: Run Merge Gatekeeper
        uses: upsidr/merge-gatekeeper@12e1af4ecc92572c30bda0afff86b78f4d6baac5 # main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
