"""
This type stub file was generated by pyright.
"""

from ._errors import JavascriptError, KaleidoError
from ._tab import _KaleidoTab

"""
This type stub file was generated by pyright.
"""
__all__ = ["JavascriptError", "KaleidoError", "_KaleidoTab"]
