"""
This type stub file was generated by pyright.
"""

import choreographer
from typing import Any, TYPE_CHECKING

"""Contains both DevTools protocol and kaleido_scopes.js helper fns."""
if TYPE_CHECKING:
    ...
_logger = ...
def get_js_id(result) -> int:
    """Grab javascript engine ID from a chrome executionContextStarted event."""
    ...

async def console_print(tab: choreographer.Tab, js_id: int, message: str) -> None:
    """
    Print something to the javascript console.

    Note: tab and js_id need to specified separately

    Args:
        tab: the choreographer tab to print on
        js_id: the javascript engine id to print on
        message: The thing to print.

    """
    ...

async def exec_js_fn(tab: choreographer.Tab, js_id: int, fn: str, *args: Any): # -> BrowserResponse:
    ...

def check_kaleido_js_response(response) -> dict:
    ...

async def print_pdf(tab: choreographer.Tab) -> str:
    ...

