"""
This type stub file was generated by pyright.
"""

import logging
from enum import IntEnum
from typing import Optional

"""
This type stub file was generated by pyright.
"""
DEFAULT_LOGGER_NAME = ...
__LOGGER_CONFIGURED__: bool = ...
class LogLevel(IntEnum):
    """Enumerator to specify the valid values of LogLevel accepted by Logger.setLevel()."""
    DEBUG = ...
    INFO = ...
    WARNING = ...
    ERROR = ...
    CRITICAL = ...


class ModinFormatter(logging.Formatter):
    """Implement custom formatter to log at microsecond granularity."""
    def formatTime(self, record: logging.LogRecord, datefmt: Optional[str] = ...) -> str:
        """
        Return the creation time of the specified LogRecord as formatted text.

        This custom logging formatter inherits from the logging module and
        records timestamps at the microsecond level of granularity.

        Parameters
        ----------
        record : LogRecord
            The specified LogRecord object.
        datefmt : str, default: None
            Used with time.ststrftime() to format time record.

        Returns
        -------
        str
            Datetime string containing microsecond timestamp.
        """
        ...
    


def bytes_int_to_str(num_bytes: int, suffix: str = ...) -> str:
    """
    Scale bytes to its human-readable format (e.g: 1253656678 => '1.17GB').

    Parameters
    ----------
    num_bytes : int
        Number of bytes.
    suffix : str, default: "B"
        Suffix to add to conversion of num_bytes.

    Returns
    -------
    str
        Human-readable string format.
    """
    ...

def configure_logging() -> None:
    """Configure Modin logging by setting up directory structure and formatting."""
    ...

def memory_thread(logger: logging.Logger, sleep_time: int) -> None:
    """
    Configure Modin logging system memory profiling thread.

    Parameters
    ----------
    logger : logging.Logger
        The logger object.
    sleep_time : int
        The interval at which to profile system memory.
    """
    ...

def get_logger(namespace: str = ...) -> logging.Logger:
    """
    Configure Modin logger based on Modin config and returns the logger.

    Parameters
    ----------
    namespace : str, default: "modin.logger.default"
        Which namespace to use for logging.

    Returns
    -------
    logging.Logger
        The Modin logger.
    """
    ...

